cloudify-cosmo/cloudify-manager

plugins/riemann-controller/riemann_controller/config_constants.py
plugins/riemann-controller/riemann_controller/resources/manager.config
resources/rest-service/cloudify/policies/ewma_stabilized.clj
resources/rest-service/cloudify/policies/host_failure.clj
resources/rest-service/cloudify/policies/threshold.clj
resources/rest-service/cloudify/types/types.yaml
tests/resources/dsl/auto_heal_grandchild.yaml
tests/resources/dsl/auto_heal_multiple_policies.yaml
tests/resources/dsl/auto_heal_nested_nodes.yaml
tests/resources/dsl/ewma_stabilized.yaml
tests/resources/dsl/isstarted_check_turned_off.yaml
tests/resources/dsl/simple_auto_heal_policy.yaml
tests/resources/dsl/simple_auto_heal_policy_two_nodes.yaml
tests/resources/dsl/stabilized_monitoring.yaml
tests/resources/dsl/threshold_compute_per_node.yaml
tests/resources/dsl/two_instances_auto_heal.yaml
tests/workflow_tests/test_policies.py

I have also updated one url in types.yaml

Failure healing policies tests fixes

---

resources/rest-service/cloudify/fs/mount.sh
resources/rest-service/cloudify/fs/unmount.sh

Cfy 2039 support volume mount on reboot

---

tests/workflow_tests/test_policies.py

Fix for tests' sporadic failures

Fixed tests

---

tests/resources/dsl/stabilized_monitoring2.yaml
tests/workflow_tests/test_policies.py

Stabilized tests + added debugging tests

Failure healing policies

---

rest-service/manager_rest/runitsupervise.py

Reverts cloudify-cosmo/cloudify-manager#249

Revert "CFY-2504 if service does not exist, no status will be returned"

---

resources/rest-service/cloudify/fs/mount.sh
resources/rest-service/cloudify/fs/unmount.sh

FS related bash scripts improvements

Cfy 2422 idempotent volume attachment

---

rest-service/manager_rest/resources.py
rest-service/manager_rest/systemddbus.py

use systemd's dbus binding to read daemon state

CFY-2977 fix status api call for centos

---

rest-service/manager_rest/blueprints_manager.py
rest-service/manager_rest/models.py
rest-service/manager_rest/resources.py
rest-service/manager_rest/responses_v2.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/security/test_secured_access.py
rest-service/manager_rest/test/test_blueprints.py
rest-service/manager_rest/test/test_blueprints_v1.py
rest-service/manager_rest/test/test_storage_manager.py

Added a metadata field to the Blueprint data model which
inclues the main blueprint file name.

CFY-3408 blueprint metadata

---

rest-service/dev-requirements.txt
rest-service/manager_rest/blueprints_manager.py
rest-service/manager_rest/config.py
rest-service/manager_rest/endpoint_mapper.py
rest-service/manager_rest/es_storage_manager.py
rest-service/manager_rest/file_storage_manager.py
rest-service/manager_rest/files.py
rest-service/manager_rest/manager_exceptions.py
rest-service/manager_rest/models.py
rest-service/manager_rest/resources.py
rest-service/manager_rest/resources_v2.py
rest-service/manager_rest/responses_v2.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/test_list_filters.py
rest-service/manager_rest/test/test_plugins.py
tests/dev-requirements.txt
tests/testenv/__init__.py
tests/workflow_tests/test_plugins.py
tests/workflow_tests/test_rest_service_list_filters.py

CFY-3465 more work on plugins upload impl
CFY-3465 more work on plugins upload impl
CFY-3462 added delete functionality
CFY-3462 test refactoring
CFY-3462 more work on unit-test
CFY-3462 fixed upload impl
CFY-3462 refactoring
CFY-3462 more tests
CFY-3462 flake8
CFY-3462 swagger and integration test framework
CFY-3462 added integration tests
CFY-3462 more work
CFY-3462 plugins upload/download support
CFY-3462 added test attr
CFY-3462 now reading plugin properties from module.json
CFY-3462 fixed integration tests
CFY-3462 temp change to travis dependencies
CFY-3462 changed plugin data representation
CFY-3462 fixup unit-tests and integration tests
CFY-3465 fixup unit and integration tests
CFY-3462 more work.
CFY-3462 minor fixes
CFY-3462 made delete more user friendly.
CFY-3462 minor changes …

CFY-3462 plugins upload/download support

---

rest-service/manager_rest/es_storage_manager.py
rest-service/manager_rest/file_storage_manager.py
rest-service/manager_rest/resources_v2.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/test_list_filters.py
rest-service/manager_rest/test/test_nodes.py
tests/workflow_tests/test_rest_service_list_filters.py

introduce multiple-value filters to REST service v2

CFY-3592 support multiple values in filters

---

rest-service/manager_rest/resources.py

remove a misplaced "self" parameter in @staticmethod

CFY-3449 encapsulate ES in Events API

---

resources/rest-service/cloudify/install_agent.py
resources/rest-service/cloudify/types/types.yaml
workflows/cloudify_system_workflows/snapshot.py

* CFY-4381 Certificates support in install_new_agents
* CFY-4382 Sanity checks for agents
This is the replacement pull request for https://github.com/cloudify-cosmo/cloudify-manager/pull/366

CFY-4381 and CFY-4382

---

resources/rest-service/cloudify/install_agent.py
resources/rest-service/cloudify/types/types.yaml
workflows/cloudify_system_workflows/snapshot.py

(direct copy of #375)
* CFY-4381 Certificates support in install_new_agents
* CFY-4382 Sanity checks for agents

CFY-4381 and CFY-4382 (master)

---

rest-service/dev-requirements.txt
rest-service/manager_rest/test/security/security_test_base.py
rest-service/manager_rest/test/security/test_userstore_reload.py
rest-service/setup.py

Conflicts:
rest-service/dev-requirements.txt

CFY-3717 added unit-test for reload of userstore

---

rest-service/manager_rest/manager_elasticsearch.py

Both "ES Storage Manager" and "Manager Elasticsearch" have a ES
connection. Share the connection between them, and store it on
the app.

Cfy 5218 manager elasticsearch

---

rest-service/manager_rest/deployment_update/constants.py
rest-service/manager_rest/deployment_update/entity_context.py
rest-service/manager_rest/deployment_update/handlers.py
rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/deployment_update/utils.py
rest-service/manager_rest/deployment_update/validator.py
rest-service/manager_rest/es_storage_manager.py
rest-service/manager_rest/models.py
rest-service/manager_rest/test/resources/deployment_update/dep_up_add_node.yaml
rest-service/manager_rest/test/test_deployment_updates.py
tests/resources/dsl/deployment_update/add_output_base.yaml
tests/resources/dsl/deployment_update/add_output_modification.yaml
tests/resources/dsl/deployment_update/add_workflow_base.yaml
tests/resources/dsl/deployment_update/add_workflow_modification.yaml
tests/resources/dsl/deployment_update/modify_output_base.yaml
tests/resources/dsl/deployment_update/modify_output_modification.yaml
tests/resources/dsl/deployment_update/modify_workflow_base.yaml
tests/resources/dsl/deployment_update/modify_workflow_modification.yaml
tests/resources/dsl/deployment_update/remove_output_base.yaml
tests/resources/dsl/deployment_update/remove_output_modification.yaml
tests/resources/dsl/deployment_update/remove_workflow_base.yaml
tests/resources/dsl/deployment_update/remove_workflow_modification.yaml
tests/resources/dsl/deployment_update/scripts/decrease.sh
tests/workflow_tests/test_deployment_update.py

Add-support-for-adding-or-modifying-a-workflow-to-the-deployment

CFY-5088-Add-support-for-adding-or-modifying-a-workflow-to-the-deployment

---

resources/rest-service/cloudify/types/types.yaml
rest-service/manager_rest/blueprints_manager.py
rest-service/manager_rest/test/test_executions.py

CFY-5711: try casting workflow parameters from string
code review fixups

CFY-5711: try casting workflow parameters from string

---

rest-service/manager_rest/constants.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/storage/management_models.py
rest-service/manager_rest/utils.py
workflows/cloudify_system_workflows/snapshots/postgres.py

And make its ID to always be 0

CFY-6145 Prevent deletion/modification of bootstrap admin

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3.py
rest-service/manager_rest/server.py
tests/integration_tests/tests/agentless_tests/test_snapshot.py
workflows/cloudify_system_workflows/snapshot.py
workflows/cloudify_system_workflows/snapshots/estopg.py
workflows/cloudify_system_workflows/snapshots/postgres.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

CFY-6239 Add ability to restore multiple v3.x snapshots

---

rest-service/manager_rest/storage/storage_manager.py

Revert some of the changes from e6004854318884cc9023c93a6130773949b13679 that have to do with filtering on tenants.

CFY-6259 Associate admin commands with a single tenant

---

README.md

In this PR, a code health badge from landscape.io is added to the README file.

Add landscape.io code health badge to README

---

rest-service/manager_rest/config.py
rest-service/manager_rest/flask_utils.py
rest-service/manager_rest/test/base_test.py
tests/integration_tests/framework/postgresql.py
tests/integration_tests/tests/agentless_tests/test_snapshot.py
workflows/cloudify_system_workflows/snapshots/estopg.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py
workflows/cloudify_system_workflows/snapshots/utils.py

- Keep them in the flask app config (taken from rest-security.conf)
- Update unittests/integration tests accordingly

CFY-6319 Generate random hash_salt and secret key during bootstrap

---

rest-service/manager_rest/storage/management_models.py
rest-service/manager_rest/storage/models_base.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/storage/resource_models_base.py
rest-service/manager_rest/storage/storage_manager.py
tests/integration_tests/framework/docl.py
tests/integration_tests/framework/flask_utils.py
tests/integration_tests/framework/postgresql.py
tests/integration_tests/tests/agentless_tests/security/security_base.py
tests/integration_tests/tests/test_cases.py
workflows/cloudify_system_workflows/snapshots/estopg.py

- Update the `__repr__` method of SQL models
- Fix/add many tests

CFY-6320 Make user groups names/LDAP DNs case insensitive

---

rest-service/tox.ini
run-tests.sh

In this PR, the tox configuration file for the rest service is refactored using [brace expansion](http://tox.readthedocs.io/en/latest/config.html#generative-envlist) and [factor conditional settings](http://tox.readthedocs.io/en/latest/config.html#factors-and-factor-conditional-settings) to make it more compact and maintainable.

More compact tox configuration

---

rest-service/manager_rest/rest/rest_decorators.py
rest-service/manager_rest/test/endpoints/test_rest_decorators.py

In this PR, the rangeable REST decorator is updated with improved validation through the voluptuous library. Aside from that, documentation and test cases have been added.

Rangeable decorator validation

---

rest-service/manager_rest/rest/resources_v3.py

- CFY-6424 Pass the config without the additional dict envelope
- CFY-6425 Use the same endpoint for starting and joining

CFY-6423 Cluster REST API changes

---

rest-service/manager_rest/resource_manager.py
workflows/cloudify_system_workflows/deployment_environment.py

* Optimize delete deployment environment workflow.
* Do not wait for workflows to terminate on delete deployment rest call.

CFY-6516 Fix parallel deployments issue

---

rest-service/manager_rest/rest/resources_v3.py
rest-service/manager_rest/rest/rest_utils.py

- The password can no longer be empty
- The password has a maximum (256) and minimum (5) length

CFY-6466 Add basic password validations

---

rest-service/manager_rest/blueprints_manager.py
rest-service/manager_rest/workflow_client.py
tests/dev-requirements.txt
tests/workflow_tests/test_deployment_logs.py
tests/workflow_tests/test_workflow.py
workflows/cloudify_system_workflows/deployment_environment.py

- Optimize delete deployment environment workflow.
- Do not wait for delete deployment environment wf to finish
on deployment deletion.

CFY-6516 Concurrent delete deployment fix

---

plugins/riemann-controller/riemann_controller/config.py
plugins/riemann-controller/riemann_controller/resources/deployment.config.template
plugins/riemann-controller/riemann_controller/resources/manager.config
plugins/riemann-controller/riemann_controller/tasks.py

Will not work without https://github.com/cloudify-cosmo/cloudify-manager-blueprints/pull/511

CFY-6482: Riemann CFY API security

---

resources/rest-service/cloudify/install_agent_template.py

As the `install_agent.py` script runs on the old mgmtworker env, it
might not have the new `local_rest_cert_path` function, so we pass it
directly in the script

CFY-6577 Fix `cfy agents install` for 3.4.2 snapshots

---

rest-service/manager_rest/deployment_update/handlers.py
rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/deployment_update/step_extractor.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v2_1.py
tests/integration_tests/tests/agentless_tests/test_rest_service_sort.py

CFY-6759 Fix a bug with deployment updates

---

workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

Required for https://github.com/cloudify-cosmo/cloudify-manager-blueprints/pull/556

Fix snapshot permissions

---

rest-service/manager_rest/amqp_manager.py

If a service is stopped and restarted later and between those two events
a tenant has been removed, then its related vhost and user should be
removed on restart. This is what the code in this change does.

CFY-6882 Delete vhosts and users from unknown tenants

---

workflows/cloudify_system_workflows/snapshots/restore_amqp.py

Remove vhosts and users for tenants that are no longer in the database
Related: cloudify-cosmo/cloudify-manager#885

CFY-6883. AMQP synchronize data

---

rest-service/manager_rest/amqp_manager.py

In this PR, a random password is generated for AMQP users instead of using a UUID.
Based on: https://stackoverflow.com/a/23728630/183066

CFY-6997. Generate random AMQP user password

---

rest-service/manager_rest/rest/resources_v1/status.py

pending https://github.com/cloudify-cosmo/cloudify-manager-blueprints/pull/611
once composer is part of the manager

add composer to status check

---

resources/rest-service/cloudify/types/types.yaml
tests/integration_tests/resources/dsl/install_agent_from_plugin.yaml

For a possible use case see the integration test
"test_agent_install_from_plugin.yaml"

CFY-7179 Introduce new agent installation method - "plugin"

---

rest-service/manager_rest/rest/resources_v3/tenants.py
rest-service/manager_rest/rest/rest_utils.py

In this PR, the add user to tenant endpoint is updated to make sure that the role name passed as argument is in the database.

CFY-7350. Role name validation

---

rest-service/manager_rest/rest/resources_v3/tenants.py

In this PR, a role parameter is added to the add group to tenant endpoint.

CFY-7373 Add role parameter to add group to tenant endpoint

---

rest-service/manager_rest/rest/resources_v3/tenants.py
rest-service/manager_rest/rest/rest_utils.py

In this PR, the role name is validated when adding a group to a tenant to make sure that it exists in the database.

CFY-7373. Validate role name

---

workflows/cloudify_system_workflows/snapshots/postgres.py

Aside from being horrible, hopefully this is reasonable.

Cfy 7383 fix riemann restores

---

rest-service/manager_rest/storage/management_models.py

After this PR, when the `get-data` flag is used when listing groups, the tenant and role names for each association will be displayed instead of just the tenant.
Before:
```
$ cfy user-group list --get-data
Listing all user groups...
User groups:
+----------+--------------------------+-------+
|   name   |         tenants          | users |
+----------+--------------------------+-------+
| my-group | default_tenant,my-tenant | admin |
+----------+--------------------------+-------+
```
After:
```
$ cfy user-group list --get-data
Listing all user groups...
User groups:
+----------+-----------------------------------------------------+-------+
|   name   |                       tenants                       | users |
+----------+-----------------------------------------------------+-------+ …
```

CFY-7373. Display role in group-tenant association with get-data flag

---

rest-service/manager_rest/rest/resources_v3/tenants.py

In this PR, an endpoint to update the user-tenant relationship is added.
Requires:
- cloudify-cosmo/cloudify-manager-blueprints#698
- cloudify-cosmo/cloudify-premium#293

CFY-7350. Add endpoint to update user-tenant relationship

---

workflows/cloudify_system_workflows/snapshots/postgres.py
workflows/cloudify_system_workflows/snapshots/snapshot_create.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

CFY-7506 Snapshot composer DB

---

rest-service/tox.ini

In this PR, the tox configuration file is updated to make it easier to run a single test case.

Tox use default value for posargs

---

packaging/restservice/build.spec

Generate the wheel from the master branch and install it explicitly in the RPM spec script.

CFY-7582 Add aria dependency

---

.gitignore
packaging/Vagrantfile
packaging/build_rpm.py
packaging/version_info

This script will be used to build the new style RPMs from spec files.

New build_rpm.py script

---

packaging/mgmtworker/build.spec

It is required by the restclient.

Add ARIA to the mgmtworker .spec installs

---

resources/rest-service/cloudify/types/types.yaml

Reverts cloudify-cosmo/cloudify-manager#1107

Revert "CFY-7726: add start, stop and restart workflows"

---

rest-service/manager_rest/app_context.py

"centos" is a distribution, not a platform

CFY-7700 Fix docstring to use 'distribution' instead of 'platform'

---

packaging/build_rpm.py

https://github.com/rpm-software-management/mock/pull/139

build_rpm.py work around mock PR 139

---

packaging/cloudify-logstash.spec

they just do the wrong things we stopped doing for the other components

Don't use copied logstash RPM scripts after all

---

packaging/cloudify-agents.spec

They need to change according to version_info

agents.spec: parametrize agents urls

---

tests/integration_tests/framework/flask_utils.py

Tests flask_utils: setup_flask_app

---

rest-service/manager_rest/config.py
rest-service/manager_rest/cryptography_utils.py
rest-service/manager_rest/rest/resources_v3/secrets.py
rest-service/manager_rest/rest/resources_v3_1/secrets.py
rest-service/manager_rest/test/base_test.py
rest-service/setup.py
tests/integration_tests/tests/agentless_tests/test_secrets.py

* Add the value encryption to secrets create
* Add the value decryption to secrets get
* Add secrets integration tests

CY-197 Encrypt the secret's value

---

rest-service/manager_rest/dsl_functions.py
rest-service/manager_rest/rest/resources_v3/secrets.py
rest-service/manager_rest/rest/resources_v3_1/secrets.py
tests/integration_tests/resources/dsl/basic_get_secret.yaml
tests/integration_tests/tests/agentless_tests/test_secrets.py

* Add the value decryption to get_secret intrinsic function
* Add the value encryption to secrets update
* Prevent the update of the DB with the decrypted value in get secret.
When updating a model in a session of sqlalchemy in the next commit the changes will be updated in the DB

CY-197 Fix get_secret intrinsic function

---

packaging/cloudify-mgmtworker.spec
packaging/cloudify-rest-service.spec
packaging/mgmtworker/requirements.txt

* CY-195 Add requirements.txt for mgmtworker
* CY-195 Use requirements.txt for the restservice build

CY-195 Use requirements.txt for restservice and mgmtworker (#1249)

---

resources/rest-service/cloudify/migrations/versions/c7652b2a97a4_4_3_to_4_4.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_executions.py
rest-service/manager_rest/test/mocks.py
tests/integration_tests/tests/agentless_tests/test_executions.py
tests/integration_tests/tests/test_cases.py

- Updated unit tests and integ tests
- Added ended_at property property for execution model

CY-381 - Adding execution end time

---

tests/integration_tests/tests/agentless_tests/test_events.py

* When restoring a snapshot we also restart the rest service and nginx,
which might lead to intermittent connection errors.
So, I added the error type "ConnectionError" to the except clause.

Fix the snapshots events integration test

---

packaging/cloudify-rest-service.spec

Don't add the libdbus .so files in the RPM's requires field

---

tests/integration_tests/tests/agent_tests/__init__.py
tests/integration_tests/tests/agentless_tests/__init__.py
tests/integration_tests/tests/test_cases.py

- pytest does not support setup_package action

CY-430 : Remove of use of setup_package

---

.circleci/config.yml
amqp-postgres/amqp_postgres/tests/test_amqp_postgres.py
amqp-postgres/tox.ini
tests/README.md
tests/integration_tests/tests/test_cases.py

- Fixing access to global env var
- Updating docs about running integration tests 
- Moving amqp_postgres to pytest

CY-430 : Completing the move from nosetests to pytest

---

plugins/riemann-controller/setup.py
tests/integration_tests/framework/amqp_events_printer.py
tests/integration_tests/framework/env.py

- Updating jinja2
- Fix the use of framework function

CY-471 : fixing broken integ test run

---

rest-service/manager_rest/flask_utils.py
rest-service/manager_rest/rest/resources_v1/deployments.py
rest-service/manager_rest/rest/resources_v1/executions.py
rest-service/manager_rest/rest/resources_v1/nodes.py
rest-service/manager_rest/rest/resources_v1/provider_context.py
rest-service/manager_rest/rest/resources_v3_1/agents.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/upload_manager.py

* Fixing the use of request argument parsing with flask-restful to standard.
* Setting flask settings to production mode.

CY-471 - Fixing performance issue in the rest service

---

amqp-postgres/amqp_postgres/postgres_publisher.py

It is possible that the IntegrityError is caused by the cache
being stale: in snapshot restore, the execution db-ID changes
after the db restore, even though cloudify-ID stays the same.
If that db-ID was already cached, we need to drop that item
from the cache.
To help this, let's just drop the whole cache on IntegrityErrors:
this happens rarely enough, that a more granular way isn't
required to keep overall performance high

amqp_postgres: when de-batching after IntegrityError, clear cache

---

rest-service/manager_rest/flask_utils.py

There is a performance issue with flask_secuirty package, so for changing it back.

CY-471 : Change hash scheme due to performance hit

---

rest-service/manager_rest/rest/resources_v3/nodes.py

NodeInstances get: use the node_instance_get permission

---

packaging/cloudify-mgmtworker.spec

Adding missing dependency for psycopg2-binary package

psycopg2 : Install needed postgresql libs

---

.circleci/config.yml
.codecov.yml
amqp-postgres/tox.ini
rest-service/tox.ini
workflows/tox.ini

Putting limits for the unit tests coverage level is:
- at the pull request's level will decrease from 80%
- at the projects level will not decrease at all

codecov: adding codecov support

---

rest-service/manager_rest/app_context.py
rest-service/manager_rest/resolver_with_catalog_support.py
rest-service/manager_rest/test/infrastructure/test_parse_with_resolver.py
rest-service/manager_rest/test/infrastructure/test_resolver_with_catalog_support.py
rest-service/manager_rest/test/mock_blueprint/blueprint_with_blueprint_import.yaml
rest-service/manager_rest/test/mock_blueprint/blueprint_with_plugin_import.yaml

Adding resolver to catalog uploaded blueprints.

CY-680: blueprint catalog import

---

rest-service/manager_rest/amqp_manager.py

* Gives only write permissions to the specific exchanges of events, logs and monitoring

CY-685 Change the permissions given to a tenant vhost user

---

rest-service/manager_rest/security/secured_resource.py

The view function from flask restful returns an ordered dict, so we can not treat it as a normal Response class and need to unpack it first for adding in the headers.

Dealing with tuple response

---

rest-service/manager_rest/rest/resources_v1/events.py

These should allow improved efficiency in Stage

Support operation,nodeid,instanceid events filters

---

rest-service/manager_rest/storage/models_base.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/storage/storage_manager.py

So that queries are ordered by something even if the user didn't
request any sorting (so that pagination makes sense).

CY-720 Add 'default sort column' to models

---

packaging/rest-service/files/opt/cloudify/encryption/update-encryption-key
rest-service/manager_rest/cryptography_utils.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

https://cloudifysource.atlassian.net/browse/CY-731
https://cloudifysource.atlassian.net/browse/CYBL-622

Make not-fernet-anymore use AES256 instead of 128

---

rest-service/manager_rest/test/infrastructure/test_list_filters.py
rest-service/manager_rest/utils.py

For more information see https://www.python.org/dev/peps/pep-0513/

CY-775 Support manylinux1 plugins

---

rest-service/manager_rest/rest/resources_v3_1/manager.py

Instead of relying on access to NGINX files

CY-779 Get current SSL status from the request object

---

.circleci/config.yml
amqp-postgres/amqp_postgres/tests/test_amqp_postgres.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_events.py
rest-service/manager_rest/test/infrastructure/test_list_pagination.py
rest-service/manager_rest/test/infrastructure/test_list_sort.py

Instead of sqlite, which doesn't support all the things postgres does
(eg. ARRAY type), and well, let's test with what we deploy.

Use PostgreSQL in unittests

---

rest-service/manager_rest/manager_exceptions.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/test/endpoints/test_deployments.py
rest-service/manager_rest/test/mock_blueprint/blueprint_with_inputs.yaml

Adds support to the new exceptions that get_input can now raise.

CY-746 Handle new get_input evaluation exceptions

---

rest-service/manager_rest/test/base_test.py

Also make the timeout shorter so that we fail faster

Unittests: if postgres is unavailable, show a hint

---

rest-service/manager_rest/rest/rest_decorators.py

This will ensure better handling in client side and in secured scenarios

Adding handling for unexpected exceptions

---

tests/integration_tests/tests/test_cases.py

Makes the manager log saving process Exception safe.

Surround save logs with a try except

---

tests/integration_tests/resources/dsl/agent_tests/blueprint_with_namespaced_blueprint_import.yaml
tests/integration_tests/resources/dsl/agent_tests/blueprint_with_scripts.yaml
tests/integration_tests/resources/dsl/agent_tests/scripts/operations/simple_script.sh
tests/integration_tests/tests/agent_tests/test_namespaced_scripts.py

- Checking for running scripts from blueprint import (with namespace)
- Checking successful creation of agents

CY-637 : adding a integration test for running a namespaced blueprint import

---

packaging/ip_setter/files/opt/cloudify/manager-ip-setter/update-provider-context.py

Fix networks in IP setter

---

rest-service/manager_rest/config.py

It's a database connection setting

Config: ca_cert_path cannot be loaded from the db

---

cloudify_types/cloudify_types/component/component.py
cloudify_types/cloudify_types/component/tests/test_blueprints.py
cloudify_types/cloudify_types/component/tests/test_deployments.py
cloudify_types/cloudify_types/component/tests/test_execute.py
resources/rest-service/cloudify/types/types.yaml
tests/integration_tests/tests/agentless_tests/test_component_type.py
tests/integration_tests/tests/test_cases.py

- Adding the ability to scale component with a given deployment id with the auto-increment suffix flag

CY-1119: Adding more support for scaling Component

---

rest-service/manager_rest/execution_token.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/security/authentication.py
rest-service/manager_rest/security/user_handler.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_executions.py
rest-service/manager_rest/utils.py
rest-service/manager_rest/workflow_executor.py
tests/integration_tests/tests/agentless_tests/test_executions.py
workflows/cloudify_system_workflows/snapshots/postgres.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

* Create a random string as the token when an execution starts
* Store the token hashed in the DB
* Authenticate The Execution Token : make sure that the token passed exists and valid.
Valid token is connected to an active execution

CY-1084 Generate and authenticate the Execution Token

---

rest-service/manager_rest/config.py

In the shorthand method, load from both files and the db

load_configuration: load from db as well

---

resources/rest-service/cloudify/types/types.yaml

Added: `precreate`, `poststart`, `prestop`, `postdelete`.

CY-1175: additional lifecycle operations

---

resources/rest-service/cloudify/migrations/versions/423a1643f365_4_6_to_5_0.py
rest-service/manager_rest/storage/management_models.py

Otherwise `SET NULL` on deleting user doesn't make sense :)

Certificates table: make updater_id nullable

---

tests/integration_tests/tests/agentless_tests/test_executions.py

* The are new events of the new lifecycle operations
* Update the expected_messages according to the new events

Fix dry run integration test

---

tests/integration_tests/resources/plugins/target-aware-mock-v1_33/plugin.yaml
tests/integration_tests/resources/plugins/target-aware-mock-v1_33/setup.py
tests/integration_tests/resources/plugins/target-aware-mock-v1_33/target_aware_mock/tasks.py
tests/integration_tests/resources/plugins/target-aware-mock/target_aware_mock/tasks.py
tests/integration_tests/tests/agentless_tests/test_hooks.py
tests/integration_tests/tests/utils.py

added test:
**the plugin is installed with more than one version**
=> make sure we use the latest version
the test **the plugin is not installed** already exists

CY-1176 Add test_different_plugin_versions

---

rest-service/manager_rest/test/endpoints/test_deployments.py

wrt cloudify-cosmo/cloudify-common#262

Update the error message check in a test

---

rest-service/manager_rest/dsl_functions.py

- snapshot from version without this field got None and crash

capabilities: snapshot issue for 4.6

---

rest-service/manager_rest/dsl_functions.py

- snapshot from version without this field got None and crash

capabilities: snapshot issue

---

rest-service/manager_rest/security/authentication.py
rest-service/manager_rest/security/hash_request_cache.py
rest-service/manager_rest/server.py
rest-service/manager_rest/test/security/test_authentication.py
rest-service/setup.py

Temporary improvement until flask security package will merge and release the feature of caching verify_hash

Cache verify hash results

---

workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

Added fix for 4.6 snapshots to have stage_schema_revision set properly

CY-1254 - Restoring a 4.6 snapshot into 5.0 results in an error

---

packaging/mgmtworker/files/usr/lib/systemd/system/cloudify-mgmtworker.service

Mgmtworker: add a delay when restarting

---

cloudify_types/cloudify_types/component/component.py
cloudify_types/cloudify_types/component/tests/test_deployment.py
resources/rest-service/cloudify/types/types.yaml

- Updating component type definition and depends on lifecycle op

Cloudify types update

---

rest-service/manager_rest/rest/resources_v3_1/sites.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/test/endpoints/test_sites.py

* Fix sites update when the new name exists
* Fix getting site with 0,0 location

CY-1265 Fix sites update when the new name exists

---

rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_sites.py

* Add latitude and longitude to the response for the UI
* Add space to the location field in the response

Add latitude and longitude to the response

---

cloudify_types/cloudify_types/shared_resource/shared_resource.py
cloudify_types/setup.py

Which will be used for marking that deployment is valid

CY-1259: adding SharedResource needed support

---

tests/integration_tests/resources/scripts/reset_storage.py
tests/integration_tests/tests/agentless_tests/test_snapshot.py
workflows/cloudify_system_workflows/snapshots/networks.py
workflows/cloudify_system_workflows/snapshots/snapshot_create.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

See each commit message for detailed description

Snapshot-related fixes

---

resources/rest-service/cloudify/types/types.yaml

CY-1259: fixing typo in description

---

rest-service/manager_rest/rest/resources_v3_1/manager.py

The parts of managers and brokers that are premium-only should
be implemented in cloudify-premium. There's no reason they would
be implemented here.
Additionally, this means that tests that are defined in
cloudify-premium, check the code that is defined there as well.
There should be an accompanying cloudify-premium PR to this.

Move managers and brokers endpoints out to premium

---

workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

While the snapshot is being restored, the database is downgraded
and upgraded back, and the snapshot execution itself might not
be in the database during that time.
If we try to insert logs during that time, they won't be stored,
because they can't have a FK to a non-existent execution.
Pause amqp-postgres so that all the logs are only stored after
the database has finished restoring
[ci skip] because CI doesn't test snap-res anyway

Pause amqppostgres while restoring a snapshot

---

rest-service/manager_rest/rest/resources_v3/tenants.py
rest-service/manager_rest/security/__init__.py
rest-service/manager_rest/security/secured_resource.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_tenants.py

See commit messages for details.

Allow getting details of default_tenant on community 

---

tests/integration_tests/tests/agentless_tests/test_rest_service_pagination.py
tests/integration_tests/tests/agentless_tests/test_rest_service_sort.py

- Handling plugin upload process, which is async op.

integration-tests: handling race cond in tests

---

cloudify_types/cloudify_types/component/component.py
cloudify_types/cloudify_types/component/tests/test_deployment.py

- In the install process, the install of Component deployment could fail and not be created. So when a user will try to clean this
up by uninstalling the entire deployment with that Component that should not fail and just pass (with warning msg).

CY-1601: deleting not existing Component deployment

---

rest-service/manager_rest/constants.py

So that the mgmtworker might come up

CY-1627 Allow getting the brokers list without a license

---

rest-service/manager_rest/constants.py

Another day, another management endpoint that needs to be accessible

Also allow /managers without a license

---

rest-service/manager_rest/deployment_update/handlers.py
tests/integration_tests/resources/dsl/deployment_update_functions.yaml
tests/integration_tests/tests/agentless_tests/test_runtime_functions.py
tests/integration_tests_plugins/testmockoperations/tasks.py

See each commit message for details

CY-1710 Reevaluate operation inputs on deployment update

---

rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/dsl_functions.py
rest-service/manager_rest/resource_manager.py

This is factored out of #1912 and requires cloudify-cosmo/cloudify-common#360

CY-1732 Functions evaluation: pass a single storage object

---

rest-service/manager_rest/resource_manager.py

This reverts commit 77d9803760679b29be0e23a938851f83a67e724d.

Revert "CY-855 Fix node instance count bug (#1925)"

---

tests/integration_tests/tests/agentless_tests/test_depends_on_lifecycle_operation.py
tests/integration_tests/tests/agentless_tests/test_runtime_functions.py

Fixup integration tests

---

tests/integration_tests/tests/agentless_tests/test_depends_on_lifecycle_operation.py

Same way as previous commit, just missed this place before

...also fixup the other test inside test_depends

---

rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/test/endpoints/test_deployment_updates.py

Use the proper api for executing workflows, instead of an ad-hoc implementation

CY-1754 Dep updates: use resource_manager for the workflow

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/workflow_executor.py

- execute_wf tried to use a plugin, but there is no plugin to use
- execute_wf for cascading wf of Component was given the wrong blueprint_id

execute_wf : fix wrong usage

---

packaging/cloudify-rest-service.spec

remove not needed diamond plugin spec

Update cloudify-rest-service rpm spec

---

rest-service/manager_rest/dsl_functions.py
rest-service/manager_rest/storage/resource_models.py
tests/integration_tests/tests/agentless_tests/test_runtime_functions.py

That's what the dsl-parser expects, dicts, not models

dsl_functions: return items as dicts

---

rest-service/manager_rest/rest/resources_v1/executions.py
rest-service/manager_rest/rest/resources_v1/status.py
rest-service/manager_rest/rest/resources_v3_1/__init__.py
rest-service/manager_rest/rest/resources_v3_1/status.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/test/endpoints/test_status.py

* Check the connection of RabbitMQ and not only the
service
* Don't check the DB connection because passing our
authentication implies PostgreSQL is healthy
* Check syncthing functionallity - valid when at least
one device was seen recently
* Change the response format

CY-1598 Update the single manager status command

---

resources/rest-service/cloudify/migrations/versions/62a8d746d13b_5_0_to_5_0_5.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/summary.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_modify.py
rest-service/manager_rest/test/endpoints/test_nodes.py
rest-service/manager_rest/test/infrastructure/test_list_filters.py
rest-service/manager_rest/test/mocks.py

adds field to the database table
adds way to calculate it, but I expect this needs a bit of work
adding the migration
try to augment tests

add node instance index database field

---

packaging/cloudify-mgmtworker.spec

aligning the solution for jinja2 affecting the rpm build

mgmtworker rpm build

---

rest-service/manager_rest/rest/resources_v3_1/cluster_status.py

- added missing edge case
- small style refactors

cluster-status: small refactor

---

packaging/status-reporter/files/opt/status-reporter/status_reporter_configuration.yaml
packaging/status-reporter/requirements.txt
rest-service/manager_rest/cluster_status_manager.py
rest-service/manager_rest/rest/resources_v3_1/__init__.py
status-reporter/status_reporter/constants.py
status-reporter/status_reporter/manager_reporter.py
status-reporter/status_reporter/postgressql_reporter.py
status-reporter/status_reporter/rabbitmq_reporter.py
status-reporter/status_reporter/status_reporter.py

- implementing manager status reporter
- fixing missing timestamp in the status report
- fixing node id missing usage 
- fixing the token usage to work
- fixing cluster status endpoint for writing reports

CY-1718: implementing manager status reporter

---

packaging/status-reporter/files/opt/status-reporter/status_reporter_configuration.yaml
rest-service/manager_rest/cluster_status_manager.py
rest-service/manager_rest/rest/endpoint_mapper.py
status-reporter/setup.py
status-reporter/status_reporter/constants.py
status-reporter/status_reporter/postgresql_reporter.py
status-reporter/status_reporter/status_reporter.py
status-reporter/status_reporter/utils.py

Also, remove get_cloudify_config function.

CY-1717 Get the private_ip from the reporter config

---

rest-service/manager_rest/cluster_status_manager.py

status-reporter: moving the status reports location

---

rest-service/manager_rest/cluster_status_manager.py
status-reporter/status_reporter/postgresql_reporter.py

* Every node reports it's own status and we want to check
the status of the DB cluster.
* We make sure the master has at least one sync replication
with streaming status (or the cluster is in Fail).
* If not all the replications are in streaming status the cluster
status is degraded.

CY-2068 Add Postgres cluster-status logic

---

rest-service/manager_rest/cluster_status_manager.py

* Leave out the master when checking the expected
nodes count.

CY-2068 Fix db cluster check

---

rest-service/manager_rest/manager_exceptions.py
rest-service/manager_rest/rest/resources_v3_1/cluster_status.py
rest-service/manager_rest/rest/resources_v3_1/snapshots.py
rest-service/manager_rest/rest/rest_decorators.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/security/__init__.py
rest-service/manager_rest/security/secured_resource.py
rest-service/manager_rest/test/endpoints/test_snapshots.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

Which includes:
- Turning off manager status reporter
- Preventing any other reporter in the cluster to write a status

CY-2084: preventing status reporters to interfere with snapshot restore

---

resources/rest-service/cloudify/migrations/versions/62a8d746d13b_5_0_to_5_0_5.py
rest-service/manager_rest/storage/relationships.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/storage/resource_models_base.py

And also on visibility, and creator id

CY-2167 Add indexes on FK columns

---

resources/rest-service/cloudify/migrations/versions/62a8d746d13b_5_0_to_5_0_5.py

CY-2167 Add the indexes to migrations [ci skip]

---

resources/rest-service/cloudify/migrations/versions/62a8d746d13b_5_0_to_5_0_5.py
rest-service/manager_rest/rest/resources_v3_1/cluster_status.py
rest-service/manager_rest/rest/resources_v3_1/status.py
rest-service/manager_rest/storage/management_models.py
workflows/cloudify_system_workflows/snapshots/utils.py

Also, fix the migration when running upgrade node_id cannot be null.

CY-2154 Add last_see column to the managers table

---

rest-service/manager_rest/resource_manager.py
tests/integration_tests/tests/agentless_tests/test_resume.py

It's not stored, so no need to update it

CY-2150 Don't update execution token

---

rest-service/manager_rest/rest/resources_v3_1/status.py

* Update GET /status endpoint
* Change the syncthing check to look back twice the
sampling time and avoid missing reports.

CY-2197 Update last_seen interval check for syncthing failure

---

resources/rest-service/cloudify/migrations/versions/62a8d746d13b_5_0_to_5_0_5.py
rest-service/manager_rest/storage/management_models.py
rest-service/manager_rest/storage/relationships.py
workflows/cloudify_system_workflows/snapshots/postgres.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

A problem with the current impl occurred because the handling of the restore was in mid db migration

CY-2213: changing the snapshot restore for status reporters users

---

packaging/cloudify-mgmtworker.spec
packaging/cloudify-rest-service.spec
packaging/cloudify-status-reporter.spec

https://github.com/pypa/pip/issues/7217

pip: pin to lower version

---

mgmtworker/mgmtworker/worker.py

This means that if a mgmtworker dies while executing an operation,
it will be re-sent to another mgmtworker.
The other CY-1959 commits are for making sure that this re-sent
operation is then correctly marked as a resume

CY-1959 Mgmtworker: enable late_ack for operations

---

workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

- Those users do not exists in community

CY-2287: don't handle status-reporter users in community

---

packaging/status-reporter/files/opt/status-reporter/status_reporter_configuration.yaml
rest-service/manager_rest/rest/resources_v3_1/status.py

Getting the status is just really slow. Fix it by making it batch service status,
and also increase the timeout anyway.

CY-2288 Fix status reporter http timeout issue

---

tests/integration_tests/framework/docker_interface.py
tests/integration_tests/framework/wagon_build.py
tests/integration_tests/tests/test_cases.py
tests/setup.py

update to look for wagon before building wagon. That way we can test specific wagon without building. shortens tests.

update docker py version

---

tests/integration_tests/resources/dockerfiles/__init__.py
tests/integration_tests/tests/test_cases.py

Dropping pythongit here as well

Get cloudify-wagon-build-containers using requests [ci skip]

---

cloudify_types/cloudify_types/component/component.py
cloudify_types/cloudify_types/component/tests/test_deployment.py

Modify plugins upload mechanism by adding an icon file (described by
`icon_png_path`).

CY-2563 Process an icon uploaded fith plugin

---

rest-service/manager_rest/app_logging.py
rest-service/manager_rest/deployment_update/step_extractor.py
rest-service/manager_rest/test/endpoints/test_agents.py
rest-service/manager_rest/test/endpoints/test_attributes.py
rest-service/manager_rest/test/endpoints/test_plugins.py
rest-service/manager_rest/test/endpoints/test_utils.py
rest-service/manager_rest/test/infrastructure/test_list_filters.py
rest-service/manager_rest/test/mock_blueprint/host_agent_blueprint.yaml
rest-service/manager_rest/test/mock_blueprint/uses_script_plugin.yaml
rest-service/manager_rest/test/mocks.py
rest-service/manager_rest/upload_manager.py

This is mostly assorted random stuff that didn't fit into any overarching PR
and I didn't want such small-time changes as separate commits on master.
Which would work as well. But I'm going to do it this way.
(because if i opened 10 PRs then I'd be an old man by the time CI finished)

Py3 porting: unittest and logging changes

---

amqp-postgres/test-requirements.txt

amqp-postgres: revert test-reqs.txt to master [ci skip]

---

rest-service/manager_rest/storage/management_models.py
rest-service/manager_rest/storage/resource_models.py
rest-service/setup.py

snapshot loading is still done on py2, so let's dump with a
py2-compatible pickle protocol

DB models: use pickle protocol=2

---

packaging/cloudify-mgmtworker.spec

CY-2743 Mgmtworker: don't install stub packages anymore

---

rest-service/manager_rest/rest/resources_v2/events.py
rest-service/manager_rest/test/endpoints/test_events_v2.py

Added ability to remove events for specified timestamp range.
This patch is accompanied by the other one in cloudify-cli.

CY-2725 Filtering events delete by timestamp range

---

workflows/cloudify_system_workflows/snapshots/postgres.py

small issues python 3 related to snapshot restore workflow

CY-2827-Fix-Snapshot-Workflow-Py3-Compat

---

workflows/cloudify_system_workflows/snapshots/utils.py

Decode on the fringes, in a "sandwich" way.

snapshots' utils run(): decode stdout/stderr [ci skip]

---

workflows/cloudify_system_workflows/snapshots/postgres.py

some more minor issues with restore added details to JIRA

Cy 2827 fix more issues

---

packaging/cloudify-mgmtworker.spec
packaging/cloudify-rest-service.spec

CY-2633 Run mgmtworker on py3

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py

Display error in uninst/stop/update

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v2/plugins.py
rest-service/manager_rest/test/endpoints/test_deployments.py
rest-service/manager_rest/test/endpoints/test_plugins.py
workflows/cloudify_system_workflows/deployment_environment.py

Plugins are now installed on-demand, lazily. No need to install them
on upload

CY-3015 Don't install plugins up-front

---

tests/integration_tests/conftest.py

stop deleting my containers, man

inte-tests: when using --container-id, always keep container [ci skip]

---

tests/integration_tests/tests/agentless_tests/test_resume.py
tests/integration_tests_plugins/cloudmock/cloudmock/tasks.py

Resume integration test updates

---

tests/integration_tests/conftest.py

next to venv sources, also mount other files, in this case, migration
files. Those don't go into a virtualenv but just into the given
target directory directly

integration tests resources: also mount static files [ci skip]

---

tests/Jenkinsfile
tests/integration_tests/resources/dsl/multi_instance.yaml
tests/integration_tests/resources/dsl/multi_instance_large_scale.yaml
tests/integration_tests/resources/dsl/multi_instance_many_different_hosts.yaml
tests/integration_tests/tests/agentless_tests/test_n_instances.py
tests/integration_tests_plugins/testmockoperations/testmockoperations/tasks.py

update with the new plugin interfaces

inte-tests: fix test_n_instances.py

---

mgmtworker/mgmtworker/worker.py
resources/rest-service/cloudify/migrations/versions/387fcd049efb_5_0_5_to_5_1.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/plugins.py
rest-service/manager_rest/storage/models.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/workflow_executor.py

Add an endpoint to force-install a plugin, add a PluginState bookkeeping thing

CY-3094 Plugin force-install endpoints

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v1/blueprints.py
rest-service/manager_rest/rest/resources_v2/plugins.py
rest-service/manager_rest/rest/resources_v2/snapshots.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/test/endpoints/test_blueprints.py
rest-service/manager_rest/test/endpoints/test_plugins.py
rest-service/manager_rest/test/endpoints/test_snapshots.py
rest-service/manager_rest/test/endpoints/test_utils.py
rest-service/manager_rest/test/mocks.py
rest-service/manager_rest/upload_manager.py

Plugin download: defer to the fileserver

---

tests/integration_tests/framework/docker.py
tests/integration_tests/tests/agent_tests/test_agent_install_workflow.py

Also a locale thing in the tests

CY-3216 Integration test checking for amqp queue leaks

---

resources/rest-service/cloudify/migrations/versions/387fcd049efb_5_0_5_to_5_1.py

Yeah I just wrote that migration by hand, before, I think.
Now, it's actually auto-generated, and shouldn't be missing things
anymore.
Whoops.

5.1 migration: add CASCADE to plugins_states fks

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v2_1/plugins.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_plugins.py
rest-service/manager_rest/test/endpoints/test_utils.py
rest-service/manager_rest/utils.py

Mostly the CASCADE, and also some cleanups

CY-3302 Plugin uninstall fixes

---

rest-service/manager_rest/resource_manager.py
tests/Jenkinsfile
tests/integration_tests/resources/dsl/agent_tests/plugins/sourceplugin/plug1.py
tests/integration_tests/resources/dsl/agent_tests/plugins/sourceplugin/setup.py
tests/integration_tests/resources/dsl/agent_tests/with_agent_source_plugin.yaml
tests/integration_tests/resources/dsl/custom_workflow.yaml
tests/integration_tests/tests/agent_tests/test_plugins.py
tests/integration_tests/tests/agentless_tests/test_plugins.py
tests/integration_tests/tests/agentless_tests/test_workflow.py
tests/integration_tests/tests/test_cases.py
tests/integration_tests/tests/utils.py
tests/integration_tests_plugins/cloudmock/cloudmock/tasks.py
tests/integration_tests_plugins/mock_workflows/plugin.yaml

Add some integration tests and fix a race condition

CY-3302 Plugin install integration tests

---

workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

Another one of those!
Also, rewritten the logs to be %s

Snapshot restore: drop usage of ex.message

---

tests/integration_tests/framework/utils.py
tests/integration_tests/tests/agentless_tests/test_snapshot.py
tests/integration_tests/tests/test_cases.py

- put the SELECT query thing locally, i dont want a framework-global
util for that
- few other small changes

Integration tests: update test_snapshot

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v2/snapshots.py
tests/integration_tests/tests/agentless_tests/test_snapshot.py
workflows/cloudify_system_workflows/deployment_environment.py
workflows/cloudify_system_workflows/snapshot.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

Plugins are now installed on-first-use or on-demand.
They are not installed in snap-restore.

Snapshot restore: don't worry about plugins

---

rest-service/manager_rest/cluster_status_manager.py
rest-service/manager_rest/rest/resources_v3_1/status.py
rest-service/manager_rest/syncthing_status_manager.py

Refactored to make the code easier to follow and to make less requests.
This should mean that if any of the checks for status reporter behaviour show it behaving incorrectly it'll be easier to track down the cause (hopefully!).

CY-3440 Status reporter fixup

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v1/blueprints.py
rest-service/manager_rest/rest/resources_v1/deployments.py
rest-service/manager_rest/rest/resources_v2/plugins.py
rest-service/manager_rest/rest/resources_v2_1/plugins.py
rest-service/manager_rest/rest/resources_v3/secrets.py
rest-service/manager_rest/rest/resources_v3/tenants.py
rest-service/manager_rest/rest/resources_v3/user_groups.py
rest-service/manager_rest/rest/resources_v3/users.py
rest-service/manager_rest/rest/resources_v3_1/blueprints.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/resources_v3_1/sites.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/test/endpoints/test_blueprints.py
rest-service/manager_rest/test/endpoints/test_deployments.py
rest-service/manager_rest/test/endpoints/test_modify.py
rest-service/manager_rest/test/endpoints/test_plugins.py
rest-service/manager_rest/test/mocks.py

Deletes return 204, instead of including all the data and ALL the related rows.
Also, use cascades wherever possible.

CY-3420 Make DELETE endpoints return 204

---

rest-service/manager_rest/plugins_update/manager.py
rest-service/manager_rest/resolver_with_catalog_support.py

- cope with missing to_minor/to_latest filters
- add logging for when plugins are actually updated

CY-3446 cfy plugins update

---

rest-service/manager_rest/test/security/test_authentication.py
rest-service/manager_rest/utils.py

See cloudify-cosmo/cloudify-common#557 and
cloudify-cosmo/cloudify-cli#1136 for details.

CY-3552 Use b64encode for encoding credentials

---

mgmtworker/mgmtworker/hooks.py
tests/integration_tests/conftest.py
tests/integration_tests/tests/agentless_tests/test_license.py
tests/integration_tests/tests/agentless_tests/test_workflow.py

- add a mount to conftest
- fix delete tests in test_workflows
- fix a dep directory test in test_workflows
- fix error tests in test_license
- additional py3 compat in hook error handling
- more cleanup in intetests
See commits.

fix several integration tests

---

rest-service/manager_rest/cluster_status_manager.py

In order to keep the Status Reporter backwards-compatible, report services as a dict (a map) rather than a list.
Partially reverts #2337 .

CY-3624 Status Reporter services as a dict

---

rest-service/manager_rest/shell/update_plugin_imports.py

Update `uploaded-blueprints/` archives along with the `blueprints/`.

CY-3654 Update archived blueprint

---

rest-service/manager_rest/rest/resources_v1/events.py
rest-service/manager_rest/rest/resources_v3/events.py
rest-service/manager_rest/rest/rest_decorators.py
rest-service/setup.py

I can just write the 5 dict filters myself thank you

CY-3684 Drop toolz dependency

---

amqp-postgres/setup.py
cloudify_types/setup.py
mgmtworker/setup.py
packaging/cloudify-rest-service.spec
packaging/mgmtworker/stub_packages/cloudify-dsl-parser/setup.py
packaging/mgmtworker/stub_packages/cloudify-plugins-common/setup.py
packaging/mgmtworker/stub_packages/cloudify-rest-client/setup.py
packaging/mgmtworker/stub_packages/cloudify-script-plugin/setup.py
packaging/version_info
rest-service/setup.py
tests/integration_tests/resources/dsl/agent_tests/plugin-requires-old-package-blueprint/blueprint.yaml
tests/integration_tests/resources/dsl/agent_tests/plugin-requires-old-package-blueprint/plugins/requires-old-package-plugin/setup.py
tests/integration_tests_blueprint/aws-docl-machine-blueprint.yaml
tests/integration_tests_blueprint/os-docl-machine-blueprint.yaml
workflows/setup.py

This reverts commit 5a00006e5bd4344bdd8bd40f5918df3a7c057585.

Revert "Bump version"

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/plugins.py

Plugin installation state used to be set in these two places,
and the resource_manager one didn't take into account preexisting
installation state, always inserted a new entry. This meant that
installing again after an error would insert a new state,
instead of updating an existing one.
Now, have a single method that does take into account the preexisting
state (using the approach from plugins.py), and use that in
both places.

CY-3722 A common method for setting plugin installation state

---

rest-service/manager_rest/config.py

Instead of loading the whole model, load only the columns
we need.
This means that we won't try to load columns that aren't needed,
eg. .monitoring_username (and others).
This will allow a 5.1 restservice to at least load the rabbitmq
brokers when faced with a 4.x db (which happens in snapshot-restore)

Config: list rabbitmqbroker columns explicitly

---

packaging/ip_setter/files/opt/cloudify/manager-ip-setter/manager-ip-setter.sh

Update host label in Prometheus target files (not in the prometheus.yml)

RD-209 Update Prometheus host label

---

rest-service/manager_rest/rest/resources_v3_1/plugins.py

If this update runs at the same time as deleting the plugin
(which will happen, since we delete a plugin, and at the same time
agents delete its directory and attempt to update the state to
"uninstalled"), then we will see a race between updating the state
and deleting the rows.
If update happens first, great, the row is deleted later.
If delete happens first, the .get() will throw a 404 and all's good.
If however the delete happens between the .get and the update,
then we get an error; in this case, let's confirm that the
plugin is indeed deleted, and throw a 404 as expected.
Getting a 'stale' error in other cases than the plugin being
already deleted, should never happen, and will still be a 500.

Plugin update: cope with plugin being deleted concurrently

---

tests/integration_tests_plugins/testmockoperations/testmockoperations/tasks.py

Use an on-conflict handler for appending to runtime_props['invocations']
This way, appending to the runtime property will retry on a version
conflict

testmockoperations: use instance.update for appending

---

resources/rest-service/cloudify/migrations/versions/5ce2b0cbb6f3_5_1_to_5_1_1.py
rest-service/manager_rest/storage/resource_models.py

This PR:
1. Creates an abstract class named "_Labels" that will be used as the superclass for the labels' models.
2. Creates the "deployments_labels" table for the deployments' labels.
3. Updates the 5.1 -> 5.1.1 migration file to add the deployments_labels table on upgrade and remove it on a downgrade.

RD-470 Creating deployments_labels table

---

resources/rest-service/cloudify/migrations/versions/5ce2b0cbb6f3_5_1_to_5_1_1.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/responses.py
rest-service/manager_rest/storage/models.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_storage_manager.py

Updating the current rest endpoint `/deployments/DEPLOYMENT_ID` to include labels data.

RD-475 Add labels when creating deployments

---

packaging/ip_setter/files/opt/cloudify/manager-ip-setter/update-db.py
packaging/rest-service/files/opt/manager/scripts/load_permissions.py
resources/rest-service/cloudify/migrations/versions/5ce2b0cbb6f3_5_1_to_5_1_1.py
rest-service/manager_rest/config.py
rest-service/manager_rest/shell/update_plugin_imports.py
rest-service/manager_rest/storage/management_models.py
rest-service/manager_rest/storage/models.py
rest-service/manager_rest/storage/storage_utils.py
rest-service/manager_rest/test/base_test.py
workflows/cloudify_system_workflows/snapshots/fix_snapshot_ssh_db.py
workflows/cloudify_system_workflows/snapshots/restore_idd_script.py

This is phase 1, ie. inserting the data into the db, but it is still only fetched
when the process starts, not online

RD-488 Insert permissions/roles into the db

---

rest-service/dev-requirements.txt
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_deployments.py

Updating the current deployments' uni-tests with the new labels behavior.

RD-480 Update deployments unit tests with labels

---

rest-service/manager_rest/rest/endpoint_mapper.py
rest-service/manager_rest/rest/resources_v2/events.py
rest-service/manager_rest/rest/resources_v3_1/__init__.py
rest-service/manager_rest/rest/resources_v3_1/labels.py
rest-service/manager_rest/rest/rest_decorators.py

This PR adds a `/labels/deployments` rest endpoint to list the tenant's deployments' labels list.
It's related to https://github.com/cloudify-cosmo/cloudify-manager-install/pull/977.

RD-478 Create labels endpoint

---

rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_labels.py

Add unit-tests for the `/labels/deployments` endpoint.

RD-481 Add labels unit tests

---

rest-service/manager_rest/rest/resources_v3/manager.py

Based on some more code diving, this should be entirely safe- see https://cloudifysource.atlassian.net/browse/RD-585 for notes on what happens with existing users.

RD-585 Allow LDAP with existing users

---

jenkins/Jenkinsfile

Remember that activating a venv only sets envvars, and so it only
applies for the current shell session. It needs to be activated
again in every session.

Jenkinsfile: activate the virtualenv in each script

---

tests/integration_tests/conftest.py
tests/integration_tests/framework/amqp_events_printer.py

when disconnected, wait 3 seconds, and reconnect.
The thread stops when the program finishes because it's a daemon
thread.

inte-tests: make events_printer reconnect

---

packaging/cloudify-rest-service.spec

On an upgrade, automatically run the fixup-configuration scripts.
Also automatically run migrations too.

RESTservice spec: handle 5.1.1 upgrade

---

rest-service/manager_rest/storage/filters.py
rest-service/manager_rest/test/endpoints/test_filters.py

This PR implements the main logic of filters. Meaning, the conditions added to the query based on the provider filter rules.
I would like to get a review on the way I implemented it, there might be a more efficient way.

RD-693 Add filters functionality

---

amqp-postgres/test-requirements.txt
rest-service/dev-requirements.txt
rest-service/manager_rest/constants.py
rest-service/manager_rest/rest/filters_utils.py
rest-service/manager_rest/rest/resources_v2/deployments.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/resources_v3_1/filters.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/storage/filters.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_filters.py
rest-service/manager_rest/utils.py

Updating the filters mechanism to parse the given string into a standard structure. 
Complementary PR: https://github.com/cloudify-cosmo/cloudify-common/pull/623

Update filters mechanism

---

rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_filters.py

RD-704 More filters unittests

---

rest-service/manager_rest/rest/resources_v3_1/plugins.py

RD-1091 Fix a race condition in plugin update/delete

---

rest-service/manager_rest/rest/resources_v3_1/filters.py

We should validate the filter ID before trying to run queries on it.

Validate the filter ID

---

resources/rest-service/cloudify/migrations/versions/9d261e90b1f3_5_1_1_to_5_2.py
rest-service/manager_rest/rest/endpoint_mapper.py
rest-service/manager_rest/rest/resources_v3_1/__init__.py
rest-service/manager_rest/rest/resources_v3_1/executions.py
rest-service/manager_rest/storage/models.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

Create an execution group model, and start an execution group
from a deployment group

RD-1100 Starting execution groups

---

rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/test/endpoints/test_storage_manager.py

Being able to control transactions explicitly is going to be
useful for several features

RD-1186 storage_manager: add a .transaction() ctxmanager

---

rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

The PATCH with 'add'/'remove' approach.

RD-1162 Update deployment groups

---

rest-service/manager_rest/rest/resources_v2/events.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

Log/event listing.
It is somewhat ad-hoc in the endpoint, but I don't have a better idea.

RD-1265 List events by execution group

---

rest-service/manager_rest/rest/resources_v2/deployments.py
rest-service/manager_rest/rest/resources_v2/executions.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

Like #2588 but for execution groups

RD-1278 Filter executions by group id

---

rest-service/manager_rest/rest/endpoint_mapper.py
rest-service/manager_rest/rest/resources_v3_1/__init__.py
rest-service/manager_rest/rest/resources_v3_1/executions.py
rest-service/manager_rest/rest/rest_decorators.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

Get an execution group with details, including status.

RD-1319 GET single execution group

---

amqp-postgres/amqp_postgres/amqp_consumer.py
amqp-postgres/setup.py
rest-service/setup.py
tests/setup.py

* RD-1287 Pika version upgrade
* pika 1.1 compat: reverse order of arguments to basic_consume
Co-authored-by: asdf <tehasdf@gmail.com>

RD-1287 Pika version upgrade (#2620)

---

tests/setup.py

... and get rid of unused ones.

RD-1322 Update tests/ dependencies

---

rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py
rest-service/manager_rest/test/endpoints/test_storage_manager.py

It's currently ugly when searching by only filters and not id, and
can be made prettier

RD-1327 Prettify the 404 not found message

---

rest-service/manager_rest/rest/endpoint_mapper.py
rest-service/manager_rest/rest/resources_v3_1/__init__.py
rest-service/manager_rest/rest/resources_v3_1/executions.py
rest-service/manager_rest/rest/rest_decorators.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

This ports #2621 and #2630 to 5.2.0

RD-1319 GET single execution group 

---

tests/integration_tests/conftest.py
tests/integration_tests/framework/amqp_events_printer.py
tests/integration_tests/framework/utils.py

tests: more pika 1.1 compat

---

execution-scheduler/execution_scheduler/main.py

When there's no schedules to run, close the transaction.
Otherwise, the process will stay in "idle in transaction" mode for
a long time, keeping table locks and server resources for no reason.
This is only the case when we don't run the schedule, because if
we do, we commit the transaction in sm.update()

Execution scheduler: don't stay in transaction for a long time

---

execution-scheduler/execution_scheduler/main.py

* Fix bugs in exec. scheduler service

Fix bugs in exec. scheduler service (#2636)

---

resources/rest-service/cloudify/migrations/versions/9d261e90b1f3_5_1_1_to_5_2.py
rest-service/manager_rest/storage/management_models.py

Make maintenance_mode.requested_by a cascade=SETNULL

---

resources/rest-service/cloudify/migrations/versions/9d261e90b1f3_5_1_1_to_5_2.py

Rename execution_groups table indexes

---

resources/rest-service/cloudify/migrations/versions/9d261e90b1f3_5_1_1_to_5_2.py
rest-service/manager_rest/storage/relationships.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

RD-1371 Set ondelete=CASCADE for the execs/exec-groups m2m

---

rest-service/manager_rest/rest/resources_v1/blueprints.py

RD-1407 Return 404 on blueprint archive not found

---

workflows/cloudify_system_workflows/blueprint.py

RD-1414 upload_blueprint: update state when download fails

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/blueprints.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_blueprints.py
rest-service/manager_rest/test/endpoints/test_deployments.py

This PR handles updating blueprint labels.

RD-1453 Update blueprint labels

---

tests/integration_tests/tests/agentless_tests/test_blueprint_upload.py

This PR adds a number of integration tests to test the functionality of blueprints labels update.

Adding blueprint labels tests

---

rest-service/manager_rest/rest/resources_v3_1/__init__.py
rest-service/manager_rest/rest/resources_v3_1/nodes.py
rest-service/manager_rest/test/endpoints/test_nodes.py

Similar to creating nodes, a "batch put" for node instances.

RD-1451 Endpoint for creating node instances

---

rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/test/endpoints/test_deployments.py

Set more attributes in the PATCH, so that all the values that come
from the plan, can be set in the create-dep-env workflow.
For now, replacing them is going to be disallowed.

RD-1538 Allow more attributes in PATCH /deps/id

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/workflow_executor.py

Just allow taking a handler, so that users are able to create
an amqp connection up front, and avoid making an amqp connection
per execution.
The refactor I've dreamt of isn't going to be in this :/

RD-1539 Allow passing through the handler to workflow_executor

---

jenkins/build-pod.yaml

RD-1550 fix QoS for pod to make it Guaranteed and increase stability of pod

RD-1550 fix QoS for pod

---

rest-service/manager_rest/rest/resources_v3_1/nodes.py
rest-service/manager_rest/test/endpoints/test_nodes.py

node/instances create_many: pass deployment_id separately

---

jenkins/build-pod.yaml

Fix low resource limit for python-old container in CI/CD for better times.

Fix low resource limit for python-old container

---

rest-service/manager_rest/rest/resources_v3_1/agents.py
rest-service/manager_rest/rest/resources_v3_1/executions.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/workflow_executor.py

Make one connection, send many workflows. Way faster!

Use a single AMQPConnection for sending all executions in a group

---

jenkins/build-pod.yaml

Fix pod resources: raise the resources limit to prevent the pod from being evicted during the pipeline.

Fix pod resources

---

resources/rest-service/cloudify/migrations/versions/396303c07e35_5_2_5_3.py
rest-service/manager_rest/storage/relationships.py
rest-service/manager_rest/storage/resource_models.py

Both the DB-side, and the ORM-side. See commits.

Specialized FKs: resolve ordering issues

---

rest-service/manager_rest/plugins_update/constants.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/workflow_executor.py

Instead of taking fifty parameters, just take the execution object,
and figure stuff out from there.

Simplify workflow_executor.execute_workflow

---

jenkins/Jenkinsfile
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_blueprints.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py
rest-service/manager_rest/test/endpoints/test_deployments.py
rest-service/manager_rest/test/endpoints/test_executions.py
rest-service/manager_rest/test/endpoints/test_modify.py
rest-service/test-requirements.txt
workflows/cloudify_system_workflows/deployment_environment.py

Create deployment nodes and node-instances in the
`create_deployment_environment` workflow

RD-1360 Move creating node-instances to the workflow

---

rest-service/manager_rest/test/endpoints/test_deployment_groups.py

This is the other side of cloudify-cosmo/cloudify-common#709

RD-1655 Dep group tests: s/inputs/new_deployments/

---

rest-service/manager_rest/rest/resources_v3_1/searches.py

This PR adds swagger documentation to the `/searches/<resource>` endpoint. This documentation will be used by the UI to know the allowed filter_rules attributes, operators, and types.
Here is an example from getting `/api/v3.1/searches/deployments.help.json`
```
{
"path": "/api/v3.1/searches/deployments",
"description": "Represents an abstract RESTful resource. Concrete resources should",
"notes": "extend from this class and expose methods for each supported HTTP<br/>method. If a resource is invoked with an unsupported HTTP method,<br/>the API will return a response with status 405 Method Not Allowed.<br/>Otherwise the appropriate method is called and passed all arguments<br/>from the url rule used when adding the resource to an Api instance. …
```

RD-1646 Add swagger to searches endpoint

---

rest-service/manager_rest/rest/resources_v1/deployments.py

See: https://github.com/cloudify-cosmo/cloudify-manager/pull/1586 for a similar solution for the GET endpoint of all deployments

RD-1353 Make GET of a single deployment return workflows correctly

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/operations.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/workflow_executor.py

Several small bugfixes gathered under a single PR,
because I'm not gonna wait for CI multiple times.
See each commit separately.

RD-1640 and RD-1700 Bugfixes

---

workflows/cloudify_system_workflows/snapshots/snapshot_restore.py
workflows/cloudify_system_workflows/snapshots/utils.py

It needs to be on reading the metadata, not generating it.
The command for generating it is currently working correctly.

RD-1776 Apply composer revision fixup correctly

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_deployments.py
rest-service/manager_rest/test/endpoints/test_modify.py
workflows/cloudify_system_workflows/deployment_environment.py

This way, labels can use intrinsic functions as well.

RD-1647 Move creating labels into the workflow

---

amqp-postgres/test-requirements.txt
rest-service/dev-requirements.txt
rest-service/manager_rest/test/endpoints/test_execution_schedules.py

the counterpart to cloudify-cosmo/cloudify-common#727

tests: pass weekdays as a list

---

rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

Copy group labels to the deployments, when the label is added.
Also remove it from the deployments, when the label is removed
from the group.

RD-1317 Apply group labels to deployments

---

rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/test/endpoints/test_deployment_labels_dependencies.py
rest-service/manager_rest/test/mock_blueprint/blueprint_with_parent_labels.yaml

This PR created in order to add deployments to their parents if there are new labels get added during deployment update

RD-1492 Update deployment update api to handle environment changes

---

rest-service/manager_rest/rest/resources_v3_1/executions.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

Just delegate to cancelling each execution, but shortcut for
queued executions, and mark those as cancelled immediately.
Also see cloudify-cosmo/cloudify-common#738
and cloudify-cosmo/cloudify-cli#1266
and cloudify-cosmo/cloudify-manager-install#1109

RD-1535 Cancelling an execution group

---

rest-service/manager_rest/rest/filters_utils.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/test/endpoints/test_filters.py

Following the changes to allow special chars in labels, we need to update the way we validate labels' filter rules.

Allow special chars in labels filter rules

---

rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

Add a param to the group DELETE api, to also delete all deployments.
Scarily powerful, isn't it.
For now, this just calls the regular .check_deployment_delete on
every deployment. This is super wasteful, but we'll see about
improving it later.

RD-1810 Delete all deployments in a group

---

rest-service/manager_rest/resource_manager.py

Creating the executions must be in a transaction, because setting
deployment on the execution can load the blueprint from the
deployment, and that would flush the execution object into the db,
possibly before some of its required attributes were set.
Alternatively we could've used an `no_autoflush` block, but using
an explicit transaction allows us to create all the component
executions in a single transaction.
Note that every time we create & run an execution, creating the
execution object (or indeed thousands of them, in a group) can/should
be under a transaction, but the `.execute_workflow()` call itself
can't be, because we must make sure that the execution is saved into
the db before it hits rabbitmq (otherwise the mgmtworker could've
started executing it before it's been actually …

Create cascading executions in a transaction

---

rest-service/manager_rest/resource_manager.py
tests/integration_tests/tests/agentless_tests/test_deployment_statuses.py

* RD-1987 Fix test_deployment_statuses_for_scheduled_execution
* RD-1987 Fix queued deployment statuses

RD-1987 Fix test_deployment_statuses_for_scheduled_execution (#2884)

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/test/endpoints/test_capabilities.py
rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py
tests/integration_tests/tests/agentless_tests/test_inter_deployment_dependencies.py
workflows/cloudify_system_workflows/deployment_environment.py

Moving inter-deployment dependencies creation over to the deployment
environment creation.

RD-1602 Async inter deployment dependencies

---

rest-service/manager_rest/rest/resources_v3_1/executions.py

In case a workflow is not defined for a deployment in a deployment
group, don't fail spectacularly.  Instead log it and continue building
the execution group.

RD-1969 Catch and report NonexistentWorkflowError

---

tests/integration_tests/resources/dsl/simple_deployment.yaml
tests/integration_tests/resources/dsl/simple_deployment_with_parents.yaml
tests/integration_tests/tests/agentless_tests/test_environments.py

Add integration tests for environment

RD-1490 Update integration tests

---

tests/integration_tests/tests/agentless_tests/test_environments.py

Update integration tests for environments

RD-2087 Int-tests

---

packaging/cloudify-rest-service.spec
rest-service/manager_rest/update_managers_version.py

* Update manager version in DB during upgrade
* Add rest config envver
* Update cloudify-rest-service.spec

Update manager version in db

---

resources/rest-service/cloudify/migrations/versions/b92770a7b6ca_5_3_to_6_0.py

6.0 migration: fix type_ kwarg

---

workflows/cloudify_system_workflows/snapshots/postgres.py

Just see each commit, I explain in the messages there.

RD-2110 Snap-res DB fixes

---

tests/integration_tests/tests/agentless_tests/test_environments.py

Adding some missing test automation cases when:
1. Update (parent) deployment that has active environments
2. Add test case that uninstall child deployment and then uninstall parent as well

RD-2119 Add extra integration tests for environment

---

rest-service/manager_rest/rest/resources_v3_1/nodes.py
tests/integration_tests/tests/agent_tests/test_snapshots.py
tests/integration_tests/tests/agentless_tests/component/test_component_cascading.py
tests/integration_tests/tests/agentless_tests/scale/__init__.py

Porting https://github.com/cloudify-cosmo/cloudify-manager/pull/2891

Rd 1987 stabilize integ tests 530

---

rest-service/manager_rest/test/endpoints/test_deployment_groups.py

a few more tests, a few more asserts. Very boring.
Needs cloudify-cosmo/cloudify-common#753 for the attributes

dep-group tests: add more asserts

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/test/endpoints/test_executions.py

See each commit, these are mostly unrelated to each other

deployments + labels: several performance changes

---

resources/rest-service/cloudify/migrations/versions/396303c07e35_5_2_to_5_3.py

This ports the relevant commit from #2953 to 5.3.0. 
5.3.0 release status is.. unknown, but this is just in case we decide
in half a year to release a 5.3.1 after all.
If deployment labels already exist, we can't just add a `NOT NULL`
column just like that to the table, because obviously those existing
labels will only have nulls in that column.
Instead, make that column nullable, copy over the falues from the
`_deployment_fk` column, and only THEN make it `NOT NULL`.
(and in downgrade, copy over from `_labeled_model_fk` back to the
`_deployment_fk` column)

5.2→5.3 migration: handle existing labels

---

rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py
rest-service/manager_rest/test/endpoints/test_deployments.py
rest-service/manager_rest/test/endpoints/test_storage_manager.py
rest-service/manager_rest/test/mock_blueprint/blueprint_with_display_name.yaml
rest-service/manager_rest/test/mocks.py
workflows/cloudify_system_workflows/deployment_environment.py

Move the display name computation to the workflow, and add one for
deployment id (on the rest side, that can't be in the workflow)

RD-1276 Deployment id & display name from dsl

---

rest-service/manager_rest/rest/resources_v3_1/deployments.py

The new deployments created when extending a group can now also
accept the parameters 'site_name', 'skip_plugins_validation',
and 'runtime_only_evaluation'
Site is interesting in that we fetch them only up-front, once for all
deployments

RD-2175 More attributes for new_dep_spec

---

workflows/cloudify_system_workflows/snapshots/postgres.py

Ported from 6.0 (master): https://github.com/cloudify-cosmo/cloudify-manager/pull/2933/commits/d9279a595be52f4a1c11ab376ac4add31c57b3a0

prepend tables with the schema name

---

rest-service/manager_rest/rest/resources_v3_1/deployments.py

RD-2175 Allow `display_name` in new deployment specs

---

rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

... if all executions within are queued.

RD-2214 ExecutionGroup's status 'queued'

---

tests/integration_tests/tests/agentless_tests/multi_tenancy/test_user_groups.py

this is so that we dont need cloudify-premium

inte-tests: copy a constant

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v1/deployments.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py

This ports #2999 to 6.0.0
For the skip_plugins_validation, only do it once, if we're making
multiple deployments.

RD-2265 Check installed plugins in batch

---

rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/test/endpoints/test_storage_manager.py

Currently, in case there are multiple resources with the same name on multiple tenants, the `get()` function in the storage manager returns just the first result of the query. In case of multiple results, we would like it to throw an error and not return an arbitrary result. 
Associated PR: https://github.com/cloudify-cosmo/cloudify-premium/pull/769

CY-695 Fix arbitrary return from get

---

packaging/cloudify-rest-service.spec

this ports https://github.com/cloudify-cosmo/cloudify-manager/pull/3015 to 6.0.0

Update manager version after upgrade 6.0.0

---

rest-service/setup.py

... just like the werkzeug in a07120b592fde44cd48256d2e64ed5771506b38a

Don't upgrade to itsdangerous 2.0.0 version

---

tests/integration_tests/framework/amqp_events_printer.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

snapshot-restore: also pause the execution-scheduler, 6.0.0

---

rest-service/manager_rest/snapshot_utils.py
rest-service/manager_rest/test/infrastructure/test_snapshot_utils.py
workflows/cloudify_system_workflows/snapshots/populate_deployment_statuses.py

RD-2328 snap-res: populate deployment statuses via sql, 6.0.0

---

jenkins/Jenkinsfile

RD-2177 add base branch param

---

rest-service/manager_rest/manager_exceptions.py
rest-service/manager_rest/rest/resources_v3_1/plugins.py
rest-service/manager_rest/test/endpoints/test_config.py
rest-service/manager_rest/test/endpoints/test_deployments.py
rest-service/manager_rest/test/endpoints/test_executions.py
rest-service/manager_rest/test/infrastructure/test_list_filters.py

Cleanup manager_exceptions

---

packaging/cloudify-rest-service.spec
packaging/rest-service/files/opt/manager/scripts/create_system_filters.py
workflows/cloudify_system_workflows/snapshots/constants.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

Description in https://github.com/cloudify-cosmo/cloudify-manager/pull/3044

RD-2248 Creating system filters during upgrade (#3044)

---

rest-service/manager_rest/__init__.py
rest-service/manager_rest/server.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_blueprints.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py
rest-service/manager_rest/test/endpoints/test_plugins_updates.py
rest-service/manager_rest/test/security/test_authentication.py

Update a few places to stop using deprecated stuff. Removes several warnings.

rest tests: remove several warnings

---

rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/test/endpoints/test_deployment_labels_dependencies.py

Description in https://github.com/cloudify-cosmo/cloudify-manager/pull/3052

WDR-35 Enable sorting by environment type (#3052)

---

rest-service/manager_rest/storage/filters.py
rest-service/manager_rest/test/endpoints/test_filters.py

Description here https://github.com/cloudify-cosmo/cloudify-manager/pull/3067

RD-2416 Fix is_not and is_null filter operators

---

rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

RD-2411 dep-groups extend: also use display name from dsl, 6.0.0

---

rest-service/manager_rest/resource_manager.py

RD-2414 Set executions to failed when they can't run, 6.0.0

---

rest-service/manager_rest/resource_manager.py

…to done and delete the deployment

RD-2431 allow delete_deployment_environment of an uninitialized deployment

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/test/endpoints/test_executions.py

exec status after failed checks: also handle dequeueing

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/test/endpoints/test_executions.py

Set execution status to FAILED if global/dependencies checks fail

---

rest-service/manager_rest/cluster_status_manager.py
rest-service/manager_rest/prometheus_client.py

This is an attempt to have a little bit more readable `cluster_status_manager.py`.  Mostly cosmetic changes, except for the second commit, which modifies how we iterate over Prometheus' results.

RD-2499 Cluster status manager refactor

---

rest-service/manager_rest/rest/resources_v1/nodes.py

Used in cloudify-cosmo/cloudify-common#797 - see there for explanation

RD-2579 Add force to node-instances PATCH

---

rest-service/manager_rest/rest/resources_v3_1/operations.py

When the mgmtworker says "the set-node-instance task is done", that's
when we actually update the node-instance state. This allows the
mgmtworker to not actually send in the state-update request
separately.

RD-2650 Automatically update node-instance on task success

---

rest-service/manager_rest/execution_token.py

storage-manager is just unnecessary here, although that's not the
most important change.
Join tenant and creator, so that when the code next does
current_execution.tenant, and current_execution.creator (for the
purposes of set_current_tenant/set_current_user), those items
are already there, and don't require another query.

RD-2659 Optimize getting current_execution

---

rest-service/manager_rest/config.py

Two cherry-pick into `5.2.4-build` branch

CYBL-1132 cfy config update fix

---

rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/deployment_update/step_extractor.py
rest-service/manager_rest/test/endpoints/test_deployment_update_step_extraction.py

The step-extractor now works mostly in terms of dicts, and doesn't run
queries or anything.
It's also been completely rewritten. Enjoy the 1000-line commits.

RD-2611 Separate the step_extractor from the storage-manager

---

workflows/cloudify_system_workflows/snapshots/agents.py

fix the kwarg name

---

rest-service/manager_rest/rest/endpoint_mapper.py
rest-service/manager_rest/rest/filters_utils.py
rest-service/manager_rest/rest/resources_v3_1/__init__.py
rest-service/manager_rest/rest/resources_v3_1/searches.py
rest-service/manager_rest/storage/filters.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/storage/storage_manager.py
workflows/cloudify_system_workflows/snapshots/agents.py

This ports #3159 #3162 and #3164 to 6.1.0

RD-2746 Node-instance /searches for snap-create

---

rest-service/manager_rest/rest/resources_v2_1/deployment_update.py

This is a step towards deprecating PUT endpoint in the upcoming major
release.

RD-2786 Unify POST and PUT on deployment-update initiate endpoints

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v2/blueprints.py
rest-service/manager_rest/rest/resources_v2/deployments.py
rest-service/manager_rest/rest/resources_v3_1/searches.py
rest-service/manager_rest/rest/resources_v3_1/workflows.py
rest-service/manager_rest/rest/rest_decorators.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/storage/management_models.py
rest-service/manager_rest/storage/models_base.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/storage/resource_models_base.py
rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/test/endpoints/test_blueprints.py
rest-service/manager_rest/test/endpoints/test_deployments.py
rest-service/manager_rest/test/endpoints/test_storage_manager.py

This is mostly about making sure that there's no 1+N queries done when
listing deployments. We join relationships as needed, also examining
include.

RD-2773 Improve deployments-list performance

---

tests/integration_tests/tests/agentless_tests/test_deployment_statuses.py

The behaviour was removed in #3170 and this removes the
relevant inte-test

Remove pointless inte-test

---

tests/integration_tests/tests/agent_tests/test_agent_install_workflow.py

this test sometimes fails on jenkins, and a more informative message
is going to help me debug why

inte-tests: test_amqp_queues_list - more info in the assert message

---

tests/integration_tests/conftest.py
tests/integration_tests/resources/scripts/follow_events.py
tests/integration_tests/tests/agentless_tests/test_snapshot.py

Add a log, and make sure follow_events.py isn't stopped dead in its
tracks by a test breaking it

RD-2913 snapshot inte-tests: improve logging

---

rest-service/manager_rest/storage/filters.py
rest-service/manager_rest/storage/storage_manager.py

Pass through the information about which items were already joined,
and only join them if needed

RD-2923 Filters: only join columns if not already joined

---

rest-service/manager_rest/amqp_manager.py
rest-service/manager_rest/rest/resources_v3_1/agents.py

This reverts commit a2bdcf16856f1f1d4b54301768d5d8b1adf0b77f.

Revert "RD-2832 Don't overwrite the RabbitMQ user on agent_create (#3204)"

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/storage/resource_models.py
workflows/cloudify_system_workflows/deployment_update/workflow.py

Deployment-update has to be moved into a workflow, and so this is
the skeleton.
For now, I'm putting it under a "hidden" builtin workflow, which will
allow us to work on it and test it, but we'll only switch over... later

RD-2613 Create a new workflow for deployment-update

---

rest-service/manager_rest/rest/resources_v2_1/deployment_update.py

For now, simple enough. We'll be amending those as we build the
update workflow further.

RD-3006 Create/update endpoints for deployment-update

---

rest-service/manager_rest/deployment_update/step_extractor.py
rest-service/manager_rest/rest/responses.py
rest-service/manager_rest/test/endpoints/test_deployments.py
workflows/cloudify_system_workflows/deployment_update/step_extractor.py
workflows/cloudify_system_workflows/deployment_update/workflow.py

Toy with the step-extractor a bit, and call it from the workflow.
Creating the steps is going to be an operation of its own.

RD-3031 Extract update steps in the new dep-update workflow

---

rest-service/manager_rest/rest/endpoint_mapper.py
rest-service/manager_rest/rest/resources_v3_1/__init__.py
rest-service/manager_rest/rest/resources_v3_1/nodes.py

This is only really useful for the deployment-update. Other than that,
not much value in calling it.

RD-3086 An endpoint for updating node attributes

---

workflows/cloudify_system_workflows/deployment_update/workflow.py

Set outputs, workflows, etc, here.

RD-3087 Dep-up: set new deployment attributes

---

workflows/cloudify_system_workflows/deployment_update/workflow.py

Figure out what changes need to be made, and then actually apply them.
All in the workflow, using the new PATCH endpoints.

RD-3085 + RD-3086 dep-up: apply changes to nodes+instances

---

packaging/rest-service/files/opt/manager/scripts/create_system_filters.py

copy of https://github.com/cloudify-cosmo/cloudify-manager/pull/3244

RD-2998 Make `csys-k8s-filter` a deployment filter

---

rest-service/manager_rest/storage/resource_models.py

RD-3156 Add upload_execution to Blueprint.response_fields

---

rest-service/manager_rest/deployment_update/step_extractor.py
rest-service/manager_rest/test/endpoints/test_deployment_update_step_extraction.py
tests/integration_tests/resources/dsl/deployment_update/modify_relationship/base/modify_relationship_base.yaml
tests/integration_tests/resources/dsl/deployment_update/modify_relationship/modification/modify_relationship_modification.yaml
workflows/cloudify_system_workflows/deployment_update/step_extractor.py

When looking for relationships, also consider which one does it need to be;
if there's multiple identical relationships, choose whether we need the first,
second, third one, etc...

RD-3264 step_extractor: disambiguate identical relationships

---

rest-service/manager_rest/rest/resources_v3_1/nodes.py
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_removal.py
workflows/cloudify_system_workflows/deployment_update/workflow.py

Start with a small refactor, and then add a way to delete
nodes.
This is coming towards a bigger refactor soon, where we'd have
to split it into multiple modules! 400 lines is about the largest
module size that I like.
But not today, yet.

RD-3094 new dep-update: deleting nodes

---

tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_removal.py
workflows/cloudify_system_workflows/deployment_update/workflow.py

This implements new dep-upd for the test_removal inte-tests

RD-3272 New dep-update: handle removing relationships

---

tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_misc.py
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py
workflows/cloudify_system_workflows/deployment_update/workflow.py

- implement reinstalling instances
- implement reordering relationships
- add the tests

RD-3271 New dep-update: fix test_modification

---

rest-service/manager_rest/deployment_update/manager.py
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_misc.py
workflows/cloudify_system_workflows/deployment_update/workflow.py

The most interesting test in that group, is being able to run a custom
workflow.
And so, I refactor the thing a bit, to encapsulate all the params in that
class.

RD-3522 add test_deployment_update_misc for new dep-up

---

workflows/cloudify_system_workflows/deployment_update/workflow.py

Instead of computing the reorders and all that jazz, simply, at the
very end, compare the instance relationships to the plan relationships,
change the orders, and drop the ones that were removed. Two birds
with one stone!

RD-2384 Simplify reorder_relationships

---

rest-service/manager_rest/rest/resources_v3_1/sites.py

Marked as draft until https://github.com/cloudify-cosmo/cloudify-manager/pull/3321 is in

RD-3502 Support owner/timestamp for sites

---

rest-service/manager_rest/storage/resource_models.py

Look, I don't know what the previous implementation was about.
This one makes sense though!

RD-3573 Simplify compare_between_statuses

---

rest-service/manager_rest/rest/resources_v3_1/execution_schedules.py
tests/integration_tests/resources/dsl/deployment_update/modify_schedules/base/modify_schedules_base.yaml
tests/integration_tests/resources/dsl/deployment_update/modify_schedules/modification/modify_schedules_modification.yaml
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_misc.py
workflows/cloudify_system_workflows/deployment_environment.py
workflows/cloudify_system_workflows/deployment_update/workflow.py

Modify existing schedules (yes!),  add new schedules.
Don't remove old schedules, because those might've been added by
the user.

RD-2614 new dep-update: also update exec-schedules

---

workflows/cloudify_system_workflows/deployment_update/workflow.py

The field might well not be there, let's not break when that happens.

New dep-up: handle missing default_schedules

---

rest-service/manager_rest/resource_manager.py

Instead of recalcing the ancestors using the old way,
in update_exec_status, run the new method.
This is just the first call-site of recalc_ancestors, but the most
important one, because this runs more often than other places
delete_deployment is going to return the affected parent ids, but
it doesn't just yet.

RD-3753 Run recalc_ancestors rather than update_exec_status

---

rest-service/manager_rest/resource_manager.py

Instead of painstakingly removing items from the graph, just remove
the dependency objects, and let recalc_ancestors handle all the
re-calculating!

RD-3573 delete_deployment: use recalc_ancestors

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_deployment_labels_dependencies.py
rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py
workflows/cloudify_system_workflows/tests/test_create_deployment.py

This makes this test module WAY faster. Like ten times.
Eventually I'd like to see all the tests rewritten this way.

Rewrite test_deployment_labels_dependencies

---

mgmtworker/mgmtworker/worker.py

Similar to cloudify-cosmo/cloudify-agent#823 - this attribute is
now unused

RD-3407 Remove unused attribute

---

rest-service/manager_rest/resource_manager.py

Rather than `while True`, make sure to limit it to a finite count.
This makes me feel safer.
Also, don't just fetch the same executions in every loop - repeating
the same and hoping for different results, is the definition of
insanity, after all.
Instead, increase offset in each iteration, to allow some crawling
through the results.
This doesn't directly fix RD-3663, but it's a stopgap for now

RD-3663 Limit iteration in dequeueing

---

rest-service/manager_rest/rest/resources_v3_1/blueprints.py
tests/integration_tests/tests/agentless_tests/test_chown.py

We're going to use blueprint update but explicitely check if user is
allowed to modify ownership.

RD-3630 Allow to change blueprint's ownership

---

tests/integration_tests/tests/agentless_tests/test_concurrent_node_instance_update.py

TestConcurrentUpdate: wait for both executions

---

jenkins/Jenkinsfile
jenkins/rpm-pod.yaml
packaging/cloudify-mgmtworker.spec
packaging/mgmtworker/requirements.txt

To the same image used on master, and also update the usage

Update the rpmbuild image

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/storage/storage_utils.py

RD-3572 Lock deployments up-front

---

rest-service/manager_rest/storage/resource_models.py

RD-3680 Reduce memory usage when fetching labels 

---

rest-service/manager_rest/dsl_functions.py
rest-service/manager_rest/test/infrastructure/test_dsl_functions.py

Implemented as FunctionEvaluationStorage.get_sys() method which is
executed for runtime evaluated functions.

RD-3434 get_sys intrinsic function implementation

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/test/endpoints/test_executions.py

RD-3703 Dequeue create-dep-env before other workflows

---

rest-service/manager_rest/test/base_test.py

In #3388 we added tests that use those, so let's actually add them

RESTservice tests: prepare .user and .tenant

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/test/endpoints/test_executions.py

RD-3758 Drop the idea of dequeueing same-deployment first

---

rest-service/manager_rest/rest/responses_v3.py
rest-service/manager_rest/storage/resource_models.py

This is required for back-compat

Include host-id in agent response

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v1/executions.py
rest-service/manager_rest/rest/resources_v3_1/executions.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/storage/models.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/storage/storage_utils.py

Use The Big Lock™ here as well, to avoid deadlocks

RD-3805 Lock starting execution-groups

---

resources/rest-service/cloudify/migrations/versions/8e8314b1d848_6_2_to_6_3.py
rest-service/manager_rest/rest/resources_v1/nodes.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_nodes.py

Add a column, handle setting it in the endpoint, add a test

RD-3673 Add the ni.system_properties column

---

tests/integration_tests/tests/agentless_tests/test_deployment_workflows.py

inte-tests: bump expected workflows amount to 15

---

rest-service/manager_rest/rest/resources_v2_1/deployment_update.py
tests/integration_tests/tests/agentless_tests/deployment_update/__init__.py
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_addition.py
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_misc.py
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_mixed_operations.py
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_removal.py
workflows/cloudify_system_workflows/deployment_update/workflow.py

Instead of going through all the DeploymentUpdateManager
stuff, we will now simply launch the new workflow.

RD-3861 Switch deployment-update to use the new impl

---

tests/integration_tests/resources/dsl/deployment_update/modify_capability/base/modify_capability_base.yaml
tests/integration_tests/resources/dsl/deployment_update/modify_capability/modification/modify_capability_modification.yaml
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py
workflows/cloudify_system_workflows/deployment_update/workflow.py

Just another field to be updated.

RD-3726 dep-update: update capabilities as well

---

workflows/cloudify_system_workflows/dsl_import_resolver/resolver_with_catalog_support.py

... which is used also in dsl_parser

RD-3852 Use plugin's labels and tags read from DB

---

cloudify_types/cloudify_types/component/__init__.py
cloudify_types/cloudify_types/component/operations.py
cloudify_types/cloudify_types/shared_resource/__init__.py
cloudify_types/cloudify_types/shared_resource/operations.py
resources/rest-service/cloudify/types/types.yaml
tests/integration_tests/resources/dsl/capability_from_attribute.yaml
tests/integration_tests/resources/dsl/component_with_blueprint_id.yaml
tests/integration_tests/resources/dsl/shared_resource_id_from_input.yaml
tests/integration_tests/tests/agentless_tests/component/test_component_basics.py

Run this to get a refreshed view of the component deployment's
capabilities et al.

RD-1031 Implement a refresh operation for components/resources

---

tests/integration_tests/resources/dsl/deployment_update/modify_labels/base/modify_labels_base.yaml
tests/integration_tests/resources/dsl/deployment_update/modify_labels/modification/modify_labels_modification.yaml
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py
workflows/cloudify_system_workflows/deployment_update/workflow.py

Whoops. Forgot about those!
Also, the reason I forgot about those, is that there was no test
that checked for that. So now there is one.

RD-3899 New dep-update: also update labels

---

rest-service/manager_rest/rest/resources_v2_1/deployment_update.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/test/endpoints/test_operations.py
tests/integration_tests/tests/agentless_tests/test_inter_deployment_dependencies.py
tests/integration_tests/tests/agentless_tests/test_labels.py
tests/integration_tests/tests/agentless_tests/test_runtime_functions.py
workflows/cloudify_system_workflows/deployment_update/workflow.py

Those commits are mostly unrelated to each other, but they're
all about making the inte-tests board go green.

dep-update: fix several integration-tests

---

workflows/cloudify_system_workflows/deployment_update/workflow.py

old blueprints didnt have the labels field!

dep-up: update labels: handle no labels in the blueprint

---

rest-service/manager_rest/constants.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py
rest-service/manager_rest/test/endpoints/test_deployment_labels_dependencies.py

Description here: https://cloudifysource.atlassian.net/browse/RD-3890

Rd 3890 consumer ids

---

workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

Otherwise we don't add new ones on post-6.x restores.

CYBL-1407 Always restore snapshot filters

---

rest-service/manager_rest/rest/resources_v2_1/deployment_update.py

Apparently this doesn't happen automatically!

RD-3952 dep-update: bump deployment.updated_at

---

workflows/cloudify_system_workflows/tests/deployment_update/blueprints/description.yaml
workflows/cloudify_system_workflows/tests/deployment_update/blueprints/empty.yaml
workflows/cloudify_system_workflows/tests/deployment_update/blueprints/minimal_types.yaml
workflows/cloudify_system_workflows/tests/deployment_update/test_workflow.py

This test is mostly trivial, but establishes a framework

RD-3859 Add a local-workflow test for dep-update

---

rest-service/manager_rest/test/endpoints/test_deployment_updates.py

I'm gonna say those tests are enough for now. This is more about the
REST side, the workflow itself is of course tested in other places
already.

RD-3859 A few dep-update REST tests

---

resources/rest-service/cloudify/types/types.yaml
rest-service/manager_rest/test/endpoints/test_deployments.py

This declares the workflow defined in cloudify-cosmo/cloudify-common#972

RD-3856 Declare the check_drift workflow

---

rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py

RD-3951 update_idds: filter the labels query

---

resources/rest-service/cloudify/types/types.yaml
rest-service/manager_rest/rest/resources_v2_1/deployment_update.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_deployments.py
tests/integration_tests/conftest.py
tests/integration_tests/resources/dsl/deployment_update/old_workflow/base/old_workflow_base.yaml
tests/integration_tests/resources/dsl/deployment_update/old_workflow/modification/old_workflow_modification.yaml
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_misc.py
tests/integration_tests/tests/agentless_tests/test_deployment_workflows.py

RD-4096 Name the new dep-up workflow "update"

---

tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py
workflows/cloudify_system_workflows/deployment_update/workflow.py

Diff the planned number of instances, and if it changed, just pass it
into modify_deployment. Simple as that.

RD-2617 Dep-update: implement scale-down

---

tests/integration_tests/resources/dsl/blueprint_with_resource_tags.yaml
tests/integration_tests/resources/dsl/scripts/workflows/test_context_resource_tags.py
tests/integration_tests/tests/agentless_tests/test_plugin_labels.py
tests/integration_tests_plugins/mock_labels/plugin.yaml

RD-4131 Intrinsic functions in resource_tags test

---

rest-service/manager_rest/manager_exceptions.py
rest-service/manager_rest/rest/endpoint_mapper.py
rest-service/manager_rest/rest/resources_v3_1/__init__.py
rest-service/manager_rest/rest/resources_v3_1/community_contacts.py
rest-service/manager_rest/test/endpoints/test_community_contacts.py

https://cloudifysource.atlassian.net/browse/RD-3950
The google function: https://github.com/cloudify-cosmo/cloudify-gcloud-functions/blob/master/cloudifyCommunityCreateContact/main.py

RD-3950 Add POST Community Contacts EP

---

rest-service/manager_rest/rest/resources_v2/nodes.py
workflows/cloudify_system_workflows/deployment_update/workflow.py

We still don't know why was that ever the case - maybe it's not
anymore? Broken snapshot?
Anyway, those are the places.

RD-2356 Cope with scaling_groups set to none

---

rest-service/manager_rest/storage/resource_models.py

… after recent changes to cloudify-common.

RD-4117 Update validate_input_value call

---

rest-service/manager_rest/storage/utils.py

tenant_roles doesn't even exist as an attribute on the User model.

Make include work with entirely derived attributes

---

rest-service/manager_rest/resource_manager.py

Delete the deployment in the very same transaction, as marking
the execution finished.
Otherwise, clients who poll for the execution status, might be
surprised to find that when the execution finished, the deployment
isn't deleted just yet.
And indeed we see that, especially in `cfy uninstall`

RD-4307 Delete deployments while finishing delete-dep-env

---

rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/rest/search_utils.py
rest-service/manager_rest/storage/resource_models.py
workflows/cloudify_system_workflows/deployment_environment.py
workflows/cloudify_system_workflows/deployment_update/workflow.py
workflows/cloudify_system_workflows/search_utils.py
workflows/cloudify_system_workflows/snapshots/restore_idd_script.py

* using REST client,
* using storage_manager.

RD-4124 `blueprint_id` data type validation

---

jenkins/build-pod.yaml
rest-service/manager_rest/test/endpoints/test_blueprints.py
rest-service/manager_rest/test/endpoints/test_workflows.py

- yet another module rewritten! `test_workflows.py` this time around
- use "fast" mode for postgres. See third commit.

restservice tests speedups

---

pytest.ini
tests/integration_tests/conftest.py
tests/integration_tests/resources/benchmarks/one_node_bp/bp.yaml
tests/integration_tests/tests/benchmarks/conftest.py
tests/integration_tests/tests/benchmarks/test_bench_many_executions.py
tests/integration_tests/tests/benchmarks/test_bench_rest.py

I want to work on performance, so I need a way to measure it.
This is just 3 benchmarks, please do implement more!
Actual results don't really matter, because they HEAVILY depend
on your rig, but it's so that we have a way to compare perf
after making changes.

RD-4377 inte-tests: implement some benchmarks!

---

rest-service/manager_rest/config.py
rest-service/manager_rest/rest/resources_v3_1/operations.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_operations.py

Those are going to be useful for the user, to be able to list the
operations based on... those things.

RD-4292 Add more ways to filter listing operations

---

rest-service/manager_rest/rest/resources_v3_1/plugins.py

... just like we do for `labels` and `blueprint_labels`

RD-4363 Implement plugin.resource_tags manipulation

---

tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py
workflows/cloudify_system_workflows/idd.py

Just look at the idd's dependency_creator, and if it's not coming
from a function, it means it's created by the user explicitly.
And in that case, we keep it.
I do realize that this isn't bulletproof, ie. someone might've created
an idd with "get_capability" in the name, but at that point we're so
deep into direct inner workings of the manager, that I don't even.
Like, the user knows what they're doing at that point, because tbh
that user is likely me anyway. So, suck it, me: better stay in line
and name your dependency creators in a smart way!

RD-3903 Keep custom IDDs after dep-update

---

rest-service/manager_rest/config.py

- there's 3 similar functions, so let's refactor them to all take the
settings from the same base two sources, _get_sql_params and
_render_db_url - I think that way is nicer
- if there's no ssl, set explicitly sslmode=disable
- the async ones don't seem to like connect_timeout
- the sqlalchemy-async one wants 'ssl' rather than 'sslmode'. I don't
know why.
This makes this inte-test pass: integration_tests/tests/async_tests/test_audit_log.py
I'm not sure why haven't we seen that failure on jenkins. I don't think
we run that group there?
Anyway, this only fixes the "no-db-ssl" part. "db-with-ssl" is still
borked, because 'sslcert' and 'sslkey' aren't valid options for
sqlalchemy+asyncpg. It seems to me that it is just 100% borked and
needs to be fixed sqlalchemy-side.

RD-4433 Config: refactor getting async db_url

---

rest-service/manager_rest/test/base_test.py

Might as well spell out what's the settings that we need.

REST tests: if no db, give more details about what we want

---

rest-service/manager_rest/rest/resources_v1/executions.py
rest-service/manager_rest/rest/resources_v3_1/executions.py
rest-service/manager_rest/storage/resource_models.py

... but instead just `get_storage_manager()` when required.

Don't pass storage_manager to executions

---

tests/integration_tests/tests/agentless_tests/test_blueprint_upload.py

blueprint validate inte-tests: remove spurious print

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/security/user_handler.py
rest-service/manager_rest/storage/resource_models.py
tests/integration_tests/resources/scripts/reset_storage.py

See commits.
With this, hook inte-tests seem to pass.

RD-4557 inte-tests: create valid admin tokens

---

rest-service/manager_rest/test/endpoints/test_searches.py

Just put the appropriate entities to the DB (session), don't bother
using REST client

RD-4154 Endpoint tests speed-up

---

rest-service/manager_rest/constants.py

This is making no modifications so should be safe, and helps out the Stage team.

RD-4588 Allow unlicensed user.get call

---

tests/integration_tests/tests/agentless_tests/test_blueprint_upload.py

We now show the error in just execution['error'], and the UI (and CLI)
display that. So let's assert on that in the test.
Also, since #3608 - the error isn't even in events, it's just in the
exc['error'].
Should we have left it there? Dunno. Maybe. Anyway if it's in events,
then it's printed out twice (actually, 3 times), in the CLI. Which
just looked bad. Hm.

RD-4502 bp validate inte-tests: assert on exc.error

---

tests/integration_tests/tests/agent_tests/test_agent_install_workflow.py

Sometimes, the "blocking request/response" queue is going to be left
around for a bit. It will be cleaned up very quickly, but not always
quickly enough.
Oh well, thing's just async, so let's retry the asserts.
This is the call that isn't synchronous:
https://github.com/cloudify-cosmo/cloudify-common/blob/e824909490e93c304a4896d0afe31cd1c63aa4f8/cloudify/amqp_client.py#L583-L585

RD-4633 Retry the test_amqp_queues_list assertions

---

mgmtworker/mgmtworker/hooks.py

no need to use the admin token

RD-4649 hooks: use the hook token for fetching the plugin

---

cloudify_types/cloudify_types/shared_resource/execute_shared_resource_workflow.py

Same as in https://github.com/cloudify-cosmo/cloudify-manager/blob/f146f384af8903ddbb80464ac4d13b49911f7e5b/cloudify_types/cloudify_types/utils.py#L92

execute_shared_resource_wf: fixup getting restclient

---

rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/rest/search_utils.py
rest-service/manager_rest/storage/resource_models.py
workflows/cloudify_system_workflows/search_utils.py
workflows/cloudify_system_workflows/snapshots/restore_idd_script.py

RD-4711 Default `deployment_id` constraint value

---

rest-service/manager_rest/rest/resources_v3_1/tokens.py

This implements what was documented in cloudify-cosmo/cloudify-cli#1393

RD-4736 Token expiration: consider absolute datetimes UTC

---

rest-service/manager_rest/storage/resource_models.py

Validate data types which require deployment_id constraint using default
value of deployment_id also in case no other constraints were provided.

RD-4711 Always validate for default deployment_id

---

resources/rest-service/cloudify/types/types.yaml

Update and heal workflows are going to have operations specific to
them; let's declare the interface

RD-4464 Declare update & heal node operations

---

workflows/cloudify_system_workflows/plugins.py

plugins update workflow: remove debug label from the event

---

rest-service/manager_rest/test/endpoints/test_attributes.py

see https://github.com/cloudify-cosmo/cloudify-common/pull/1043

RD-421 Update test for `SELF` reference in `get_attribute` function

---

rest-service/manager_rest/rest/resources_v3_1/operations.py
rest-service/manager_rest/test/endpoints/test_operations.py

Automatically set those properties. Values TBD, but for right now,
they're this.

RD-4640 Set NI status & drift when installing it

---

tests/integration_tests/tests/agent_tests/test_cancel.py
tests/integration_tests/tests/agentless_tests/component/test_component_auto_inc_suffix.py
tests/integration_tests/tests/agentless_tests/component/test_component_basics.py
tests/integration_tests/tests/agentless_tests/component/test_component_cascading.py
tests/integration_tests/tests/agentless_tests/shared_resource/test_multi_tenancy.py
tests/integration_tests/tests/agentless_tests/shared_resource/test_on_demand_shared_resource.py
tests/integration_tests/tests/agentless_tests/shared_resource/test_relationship_running_workflow.py
tests/integration_tests/tests/agentless_tests/shared_resource/test_shared_resource_type.py
tests/integration_tests/tests/agentless_tests/test_depends_on_lifecycle_operation.py
tests/integration_tests_plugins/mock_workflows/plugin.yaml

after we upgraded `types.yaml` to this version https://github.com/cloudify-cosmo/cloudify-common/pull/1044

RD-4788 Fix integration tests for DSL version 1.4

---

tests/integration_tests/resources/dsl/agent_tests/install_agent_from_plugin.yaml
tests/integration_tests/tests/agent_tests/test_agent_install_from_plugin.py

Install an agent with this setting

Add a test for executable_temp_path

---

rest-service/manager_rest/rest/resources_v3_1/workflows.py
rest-service/manager_rest/rest/responses.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_workflows.py

Compute the boolean based on the availability_rules.
This only makes the value be included in the response, but soon,
we'll also block unavailable workflows from being run.

RD-4616 Include is_available in workflows list

---

resources/rest-service/cloudify/migrations/versions/272e61bf5f4a_6_3_to_6_4.py

No need to audit that table. It's internal, uninteresting, best-effort,
and emits way too many logs, because it's updated on pretty much
every action.

RD-4987 exempt usage_collector from the audit log

---

resources/rest-service/cloudify/migrations/versions/272e61bf5f4a_6_3_to_6_4.py
rest-service/manager_rest/config.py
rest-service/manager_rest/rest/resources_v3_1/manager_config.py
rest-service/manager_rest/storage/management_models.py
rest-service/manager_rest/test/endpoints/test_config.py

Implement the concept of an "admin-only" setting, whose values
are only viewable by admins, and only changeable by admins.

RD-5007 Admin-only config values

---

resources/rest-service/cloudify/migrations/versions/272e61bf5f4a_6_3_to_6_4.py

Things that run in snap-restore must have the schema there, because
snap-res tends to set search path to empty. It's kinda stupid.

6.4 migration: prefix the names with the schema name

---

rest-service/manager_rest/test/endpoints/test_maintenance_mode.py
rest-service/manager_rest/utils.py

Wow, this is scary. Let's not have this.

Drop is_internal_request

---

rest-service/manager_rest/dsl_back_compat.py

RD-5217 Backward compatible plugin.yaml generation

---

rest-service/manager_rest/upload_manager.py

Because updating a blueprint archive repacks it as `tar.gz`, the
name of the file should be changed accordingly.

RD-5284 Properly name blueprint archive file

---

workflows/cloudify_system_workflows/deployment_update/update_instances.py
workflows/cloudify_system_workflows/deployment_update/utils.py
workflows/cloudify_system_workflows/deployment_update/workflow.py

I'm going to be changing a lot around this, and workflow.py is
already 1k lines long, so let's factor this out.

RD-4466 deployment update: factor out a module

---

packaging/rest-service/files/opt/cloudify/encryption/update-encryption-key
rest-service/manager_rest/cluster_status_manager.py
rest-service/manager_rest/deployment_update/handlers.py
rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/dsl_functions.py
rest-service/manager_rest/plugins_update/manager.py
rest-service/manager_rest/resolver_with_catalog_support.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/license.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/syncthing_status_manager.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py
rest-service/manager_rest/upload_manager.py
rest-service/manager_rest/workflow_executor.py

This reverts commit e4a471df20c888e24f50f57941987684481ca041.
Required because summary uses group_by, which breaks this. Hooray!

Revert "Rd 5334 pagination metadata total fix (#3746)"

---

rest-service/manager_rest/rest/resources_v2_1/deployment_update.py
workflows/cloudify_system_workflows/deployment_update/update_instances.py
workflows/cloudify_system_workflows/deployment_update/workflow.py
workflows/cloudify_system_workflows/tests/deployment_update/blueprints/update_operation.yaml

The test cases in the blueprint hopefully explain it.
Anyway, this is somewhat rough for now, but I still want to get this
in as is, and refactor later.

RD-4466 Run heal before running update

---

resources/rest-service/cloudify/types/types.yaml
tests/integration_tests/tests/agentless_tests/test_workflow.py

This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-manager/pull/3782

RD-5367 workflow availability limits for Compute nodes

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/resources_v3_1/execution_schedules.py

Deployment workflows weren't being restored and that broke this.

RD-4684 Support restoring execution schedules

---

workflows/cloudify_system_workflows/tests/deployment_update/test_workflow.py

This operation might end up updating the same node multiple times
concurrently, if it's run on the node, and at the same time, on the
relationship.
Then, we get a version conflict, and test_workflow would (rarely)
fail.
To avoid that, use the .update(on_conflict) variant of updating
node instances.
Funnily, I was long looking for this race in the wrong place: I thought
that it was due to insufficient locking in c-common's drift update
of system-properties, but no, that one is locked just fine. It's
the _runtime_ properties, in the test operations, that were at fault!

workflow update test: rewrite using an update handler

---

jenkins/Jenkinsfile

no need to curl out to github (via getVersion). Just load the local packaging/version_info file.

jenkins: use the local version_info file for getting version

---

rest-service/manager_rest/rest/resources_v3_1/blueprints.py
rest-service/manager_rest/test/endpoints/test_utils.py

Multipart blueprint upload: PR review changes

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/test/endpoints/test_deployment_labels_dependencies.py

recalc_ancestors used to possibly recalc grandparents, but not always direct parents. If we missed any by the recursive query (we could have retrieved them all, if the original deployment still exists - ie. it wasn't deleted), then just retrieve them

RD-5237 Make sure to update sub_services_count of parents

---

rest-service/manager_rest/configure_manager.py
rest-service/manager_rest/test/infrastructure/test_configure_manager.py

return the password here, not the username :)

configure_manager: get_rmq_password: return the password

---

mgmtworker/cloudify_system_workflows/snapshots/postgres.py
mgmtworker/cloudify_system_workflows/snapshots/snapshot_restore.py
mgmtworker/cloudify_system_workflows/snapshots/utils.py
mgmtworker/mgmtworker/worker.py
resources/rest-service/cloudify/migrations/versions/edd6d829a209_6_4_to_7_0.py
rest-service/manager_rest/config.py
rest-service/manager_rest/workflow_executor.py
tests/integration_tests/tests/test_cases.py

All service management is now always supervisord

RD-5986 Drop systemd service management

---

mgmtworker/cloudify_system_workflows/snapshots/restore_idd_script.py
rest-service/manager_rest/snapshot_utils.py
tests/integration_tests/tests/agentless_tests/test_snapshot.py
tests/integration_tests/tests/test_cases.py

Several fixes, see commits separately. This fixes agentless_tests/test_snapshot.py

Fixup snapshot inte-tests

---

tests/integration_tests/resources/scripts/reset_storage.py

reset-storage: also re-activate the admin user

---

tests/integration_tests/tests/agentless_tests/test_audit_log.py

It didn't make sense to presume here that something will be actually deleted.

RD-6131 Fix test_audit_log_truncate test

---

execution-scheduler/requirements.txt
mgmtworker/requirements.txt
rest-service/requirements.txt

For some reason, snyk won't leave me be with this pointless suggestion. It keeps suggesting 0.38.0, which is yanked. 0.38.1 exists though.

reqs.txt: bump wheel to 0.38.1

---

mgmtworker/cloudify_system_workflows/search_utils.py
rest-service/manager_rest/rest/resources_v3_1/searches.py
rest-service/manager_rest/rest/search_utils.py
rest-service/manager_rest/storage/resource_models.py
tests/integration_tests/resources/dsl/blueprint_with_operation_name_data_type.yaml
tests/integration_tests/tests/agentless_tests/test_data_types.py

continuation of https://github.com/cloudify-cosmo/cloudify-manager/pull/3928 and https://github.com/cloudify-cosmo/cloudify-common/pull/1184

RD-6330 `operation_name` data type implementation

---

mgmtworker/cloudify_system_workflows/deployment_environment.py
mgmtworker/cloudify_system_workflows/tests/test_create_deployment.py

Don't evaluate the whole inputs - defaults must stay un-evaluated here.
That means if the default contains other function calls, whenever we use `get_input` (eg. in a property), that function call is essentially copied there, and only evaluated on demand. Then, defaults can contain other get_input calls (or secrets, or attributes)

RD-6427 create_dep_env: only evaluate input constraints

---

tests/integration_tests/tests/agentless_tests/test_snapshot.py

- `force` is now... nonexistent. So we must clean out the manager before the restore, via `reset_storage`
- since we're clearing out the manager, well, the snapshot is removed too. So download and reupload it.

inte-tests: snap-create: make the tests work with new snapshots

---

docker-compose.yml
rest-service/Dockerfile
rest-service/docker/entrypoint_config.sh
rest-service/manager_rest/configure_manager.py
rest-service/manager_rest/test/infrastructure/test_configure_manager.py

Move inserting the manager here, from c-m-i's script.
Also, insert that data in the config container.

RD-6566 configure_manager.py: insert manager & cert

---

service_containers/nginx/config/templates/rest_upstream.conf.template

RD-6354 nginx: enable http2

---

tests/integration_tests/tests/agentless_tests/test_environments.py

Whoops! I forgot to actually create the environment successfully :)

RD-6477 test_required_environment_capability: create the env

---

rest-service/manager_rest/rest/resources_v2/plugins.py

PluginsArchive: storage.list yields fileinfo objects

---

rest-service/manager_rest/manager_exceptions.py
rest-service/manager_rest/rest/resources_v3_1/manager.py
tests/integration_tests/tests/agentless_tests/test_deployment_resource.py
tests/integration_tests/tests/agentless_tests/test_resources.py
tests/integration_tests_plugins/testmockoperations/testmockoperations/tasks.py

...  with a file and its metadata (mtime)

RD-6614 FileServerProxy.put accepts multiform data

---

tests/integration_tests/tests/agentless_tests/scale/test_scale_out.py
tests/integration_tests/tests/agentless_tests/test_deployment_workflows.py

Two trivial fixes for the tests that have been failing.

6.4.2 inte-test fixes

---

rest-service/manager_rest/rest/resources_v3_1/agents.py
rest-service/manager_rest/test/endpoints/test_agents.py

Agent PATCH will now also allow setting more than just the state.

RD-6658 agents update: allow setting version & system

---

mgmtworker/cloudify_system_workflows/deployment_update/workflow.py
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py

If nodes were scaled, those new instance counts are not reflected in the plan.
Before creating the new deployment plan, update the blueprint plan with the current real instance counts.

RD-6908 dep-update: update plan with real instance counts

---

rest-service/manager_rest/config.py
rest-service/manager_rest/configure_manager.py
rest-service/manager_rest/test/infrastructure/test_configure_manager.py
rest-service/migrations/versions/edd6d829a209_6_4_to_7_0.py
tests/integration_tests/tests/agentless_tests/security/test_file_server_access.py
tests/integration_tests/tests/agentless_tests/test_blueprint_upload.py
tests/integration_tests/tests/agentless_tests/test_resources_available.py

RD-6586 Switch the default agent port to 443

---

rest-service/manager_rest/storage/storage_manager.py

1) full_access_list can't just pass things straight to ._add_value_filter,
it needs to go through the same resolving mechanism as with the
regular .list
2) just a getattr() isn't good enough, because turns out, it's not
only strings there, passing a column reference is allowed too
Both problems are hit by execution-scheduler/main.py,
```python
schedules = sm.full_access_list(
models.ExecutionSchedule,
filters={
models.ExecutionSchedule.enabled: True,
models.ExecutionSchedule.next_occurrence:
lambda x: x < datetime.utcnow()
}
)
```

RD-7068 Fixup filters with sm.full_access_list

---

api-service/requirements.in
api-service/requirements.txt
execution-scheduler/requirements.txt
rest-service/requirements.txt

This re-compiles requirements in the restservice venv; the main goal is updating `starlette` and `werkzeug`, for the snyk-reported vulns.
Note that all 3 of these are in the same venv, so they all must be updated in tandem...

Update dependencies in the restservice virtualenv

---

mgmtworker/cloudify_system_workflows/snapshots/snapshot_restore.py
mgmtworker/cloudify_system_workflows/tests/snapshots/test_restore.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py

* align restore part with what rest-service actually expects,
* created_by -> creator
:facepalm:

RD-6742 Inter-deployment dependencies snapshot fix

---

api-service/requirements.in
execution-scheduler/requirements.in
mgmtworker/requirements.in
mgmtworker/requirements.txt
rest-service/requirements.in

... and also update requirements.in

Pin mgmtworker's cloudify-* dependencies to 7.0.0

---

rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_searches.py

this is a cherry-pick of #4091

RD-7046 Enable filtering deployments by ID in search

---

rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_deployments.py

Just declaring the assoc-proxy, that's all.

RD-6954 Add dep.latest_execution_workflow_id

---

mgmtworker/cloudify_system_workflows/snapshots/agents.py
mgmtworker/cloudify_system_workflows/snapshots/snapshot_create.py

Similar to what the old snapshots did, the new snapshots also must store these settings.

RD-7132 snap-create: store agents' broker config

---

tests/integration_tests/tests/agent_tests/test_snapshots.py

Since this test is an "agent" test for snap-restore, it'd make sense for it to also test the next obvious step, ie. upgrading the agents :)
Snapshots without upgrading are very well tested by agentless tests anyway...

RD-7005 Add an agent upgrade to the agents/snapshots test

---

mgmtworker/cloudify_system_workflows/snapshots/snapshot_restore.py
mgmtworker/cloudify_system_workflows/snapshots/ui_clients.py
mgmtworker/cloudify_system_workflows/tests/snapshots/test_restore.py

This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-manager/pull/4141

RD-7094 Make snapshot restore logs for UI better

---

rest-service/manager_rest/rest/resources_v3_1/status.py

If a metric for a service is missing, and the service is optional, don't report it at all.

RND-354 status: omit missing optional services

---

mgmtworker/cloudify_system_workflows/snapshots/snapshot_restore.py
mgmtworker/cloudify_system_workflows/tests/snapshots/partial_snapshot_contents/metadata.json
mgmtworker/cloudify_system_workflows/tests/snapshots/snapshot_contents/metadata.json

... and not just snapshot version.

RND-362 Recognise snapshot flavour by file content

---

mgmtworker/cloudify_system_workflows/snapshot.py
mgmtworker/cloudify_system_workflows/snapshots/snapshot_create.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v2/snapshots.py
rest-service/manager_rest/test/endpoints/test_maintenance_mode.py
rest-service/manager_rest/test/infrastructure/base_list_test.py
tests/integration_tests/tests/agentless_tests/test_deployment_statuses.py
tests/integration_tests/tests/agentless_tests/test_executions.py

This is is a slightly modified cherry-pick of https://github.com/cloudify-cosmo/cloudify-manager/pull/4151 (the default value for legacy parameter is set to True).

RDN-363 Snapshot create `legacy` parameter

---

mgmtworker/cloudify_system_workflows/snapshot.py
mgmtworker/cloudify_system_workflows/snapshots/constants.py
mgmtworker/cloudify_system_workflows/snapshots/snapshot_create.py
mgmtworker/cloudify_system_workflows/snapshots/snapshot_create_legacy.py
mgmtworker/cloudify_system_workflows/snapshots/snapshot_restore.py

It is possible now to create both legacy (default in 7.0) and new (default in 7.1) snapshots.

RND-373 Restore legacy snapshot code

---

rest-service/manager_rest/rest/resources_v3_1/summary.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_executions.py
rest-service/manager_rest/test/endpoints/test_nodes.py

This ports #4161 to 7.0.0
Essentially just see the first commit :)
The idea is, let's just avoid passing status_display to the storage-manager, and instead, summarize on status, and then rewrite the results as needed.

RND-390 Executions summary: specialcase status_display

---

mgmtworker/requirements-3.6.txt

cloudify-agent and cloudify-common used by mgmtworker

Use 7.0.0 version of dependencies for py36 venv

---

tests/integration_tests/tests/agent_tests/test_snapshots.py
tests/integration_tests/tests/test_cases.py

Just a bit more coverage this way. Also checks the stop-agent-script!

agent upgrade test: also stop old agent

---

mgmtworker/cloudify_system_workflows/snapshots/snapshot_restore.py

This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-manager/pull/4197

Cache metadata information about snapshot format (legacy/new)

---

rest-service/setup.py

need to pin flask in rest service as >v3 removes decorators that we need

Update setup.py to pin flask version

---

tests/requirements.txt
tests/setup.py

those are actually needed here!

inte-tests: add pyyaml & cryptography

---

mgmtworker/cloudify_system_workflows/snapshots/snapshot_create.py
mgmtworker/cloudify_system_workflows/snapshots/snapshot_restore.py
tests/integration_tests/tests/agentless_tests/test_snapshot.py

Testing appending modified entities to the snapshot as it is created.

RND-715 Zero-downtime snapshots tests

---

tests/integration_tests/tests/agent_tests/test_snapshots.py

Just wait a moment between creating and installing deployments in the test

RND-782 Fix integration test: snapshot with agents

---

tests/integration_tests/tests/agentless_tests/test_inter_deployment_dependencies.py

This adds a test for cloudify-cosmo/cloudify-common#1294

CYBL-2049 Add a test for IDDs with 0 node-instances

---

service_containers/rabbitmq/Dockerfile

Ported from fusion repos, original task: https://cloudifysource.atlassian.net/browse/RND-741

fixed issue with rabbitmq permissions

---

mgmtworker/cloudify_system_workflows/idd.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/test/endpoints/test_executions.py
tests/integration_tests/tests/agentless_tests/test_rest_service_list_filters.py
tests/integration_tests/tests/async_tests/test_audit_log.py

This is now necessary for flake8 to pass

Fix style with new version of flake8

---

api-service/requirements.txt

Now that we can merge to this branch, set it to require 7.0.2-buil again

api service: reqs.txt: revert to 7.0.2-build

---

rest-service/manager_rest/rest/resources_v1/nodes.py
rest-service/manager_rest/test/endpoints/test_nodes.py
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_misc.py

This ports RND-1091 to 7.0.2
* Node instance update: skip the version check for no-op updates
The point of this commit is, if the update is not actually changing anything, i.e. if the old runtime props are the same as new, skip the version check, so that if many operations at the same tame set the same values, they aren't denied.
Or in cases where runtime-props are "changed" to the same value, which can still happen, and often happens in the case of e.g. the terraform plugin.
* add a test
changing runtime props to the same value, even with the version being older, doesn't actually throw a 409
* add an integration-test
This is actually the scenario from RND-1091, and let's check that no conflict error is thrown

RND-1091 node-instance update: skip version check for no-ops

---

mgmtworker/cloudify_system_workflows/dsl_import_resolver/resolver_with_catalog_support.py

No need to parse the response more than once.

upload_missing_plugin: avoid calling .json() many times

---

service_containers/rabbitmq/Dockerfile

RND-741 rabbitmq image: apply chmod

---

mgmtworker/cloudify_system_workflows/snapshots/snapshot_restore.py

This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-manager/pull/4312

CYBL-2097 Do not fail in case a snapshot archive is already present

---

rest-service/manager_rest/cluster_status_utils.py
rest-service/manager_rest/rest/resources_v3_1/cluster_status.py

This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-manager/pull/4319

CYBL-2091 Implement cluster status for k8s environment

---

rest-service/manager_rest/cluster_status_utils.py

After https://github.com/cloudify-cosmo/cloudify-helm/pull/135 changes kube-state-metrics is used to find out about the state of manager services.  This patch is a slight alignment required on manager's side afterwards.

CYBL-2091 NE-6423 Fix cluster status generation

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/test/endpoints/test_executions.py

_validate_execution_update: allow no-op update

---

rest-service/manager_rest/rest/resources_v3_1/status.py

The metrics provided by Prometheus + kube-state-metrics are slightly different than those reported in other environment.

CYBL-2091 NE-6423 Update how manager status is determined in k8s

---

rest-service/manager_rest/cluster_status_utils.py

For cluster status evaluation, assume DB and BROKER services are external (`is_external=True`) in case of missing metrics.  This is compliant with manager status evaluation (`cfy status`).

NE-6423 Assume external if missing metrics

---

rest-service/manager_rest/cluster_status_utils.py

This patch makes the backend part more alligned with what frontend expects to receive.

NE-6423 More detailed reports for missing services

---

mgmtworker/cloudify_system_workflows/snapshots/snapshot_restore.py
rest-service/manager_rest/storage/resource_models.py

Instead of 500, just return an empty list

list_workflows: cope with malformed workflows

---

rest-service/manager_rest/resource_manager.py

This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-manager/pull/4427

Do not run executions on already processed deployments

---

execution-scheduler/execution_scheduler/main.py
execution-scheduler/execution_scheduler/tests/test_execution_scheduler.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_executions.py

porting https://github.com/fusion-e/fusion-manager/pull/484

NE-28695 Handle render_message exceptions during scheduled executions

---

mgmtworker/cloudify_system_workflows/deployment_environment.py
mgmtworker/cloudify_system_workflows/deployment_update/workflow.py
mgmtworker/cloudify_system_workflows/search_utils.py
rest-service/manager_rest/rest/resources_v3_1/nodes.py
rest-service/manager_rest/test/endpoints/test_nodes.py
rest-service/manager_rest/utils.py

Port NE-30898 from fusion-e
https://github.com/fusion-e/fusion-manager/pull/515
needs https://github.com/cloudify-cosmo/cloudify-common/pull/1338

NE-30898 Rename duplicate node instance IDs in create

---

jenkins/Jenkinsfile
rest-service/manager_rest/resource_manager.py

Port https://github.com/fusion-e/fusion-manager/pull/556
dequeue: make sure render_message errors are propagated

NE-38559: Port NE-36814
