plugins/riemann-controller/riemann_controller/resources/manager.config
run-tests.sh
tests/testenv/processes/riemann.py

Riemann now receives an environment variable called HOSTING_VM to allow it to connect to different host other than localhost when initiating an AMQP connection.

Cfy 2173 configure riemann for external hosts

---

workflows/cloudify_system_workflows/snapshot.py

This is a "dead code" and can be safely removed.

Removed one unnecessary function

---

rest-service/manager_rest/es_storage_manager.py
rest-service/manager_rest/file_server.py
rest-service/manager_rest/file_storage_manager.py
rest-service/manager_rest/resources.py
rest-service/manager_rest/server.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/security/test_userstore_and_roles_reload.py
rest-service/manager_rest/test/test_nodes.py
tests/workflow_tests/test_deployment_nodes.py

Instead of comparing `node_instance.version` inside the rest service, use
elasticsearch's index API: it does the version check itself.
Checking on the rest service side has a race condition problem because
when handling multiple update requests in parallel, separate concurrent rest
service processes will fetch the old version at the same time, do the check
independently, and will all write.

CFY-5185 use ES for the version checking when updating instances

---

rest-service/manager_rest/es_storage_manager.py

The Elasticsearch python client maintains a connection pool using
keepalive to talk to elasticsearch over persistent connections.
Store the client rather than creating a new one on each access,
to allow it to use the persistent connections.

CFY-5218 Store the ES client to use connection pooling

---

resources/rest-service/cloudify/fs/fdisk.sh
resources/rest-service/cloudify/fs/mkfs.sh
resources/rest-service/cloudify/fs/mount-docker.sh

`ctx runtime-properties` throws an error when looking up an undefined
runtime property. Scripts looking up runtime props that might not be
defined, need to guard against that.

FS scripts: Don't rely on `ctx runtime-props undefined` returning empty

---

rest-service/manager_rest/maintenance.py
rest-service/manager_rest/test/test_app.py

A 404 error could result in a 500, which obscured it, leading to an
unhelpful error. Make sure the maintenance mode handler doesn't
break on un-routed requests.

CFY-5286 Don't hide 404 errors

---

resources/rest-service/cloudify/install_agent.py

.bytes_stream is Cloudify REST Client's method. Request's is
actually .iter_content

CFY-5135 Use .iter_content, not .bytes_stream

---

rest-service/manager_rest/rest/resources_v1/events.py
rest-service/manager_rest/rest/resources_v2.py
rest-service/manager_rest/rest/rest_decorators.py
rest-service/manager_rest/test/endpoints/test_events.py
rest-service/manager_rest/test/endpoints/test_rest_decorators.py
rest-service/setup.py

In this PR, the `paginate` and `sortable` decorators are refactored to improve the request argument validation they provide. This should be helpful to avoid in the future problems such as the one addressed by cloudify-cosmo/cloudify-manager-blueprints#462
As you'll see the validation is performed trough the [`voluptuous`](https://pypi.python.org/pypi/voluptuous) library. I'm aware that flask restful has its own [argument parsing](http://flask-restful-cn.readthedocs.io/en/0.3.5/reqparse.html) module that is used in some other parts of the code. However, the documentation itself states that that module is no longer maintained and I don't think that the `argparse` style API is a good fit here, so I decided to search another library and `voluptuous` seems to be the one that [Armin …

CFY-6091. Improved validation

---

rest-service/manager_rest/security/authentication.py

We used to only bump the `last_login_at` field when authenticating
with a token. This change makes it so it's always bumped when
authenticating, token or password.

CFY-6327 Update `last_login_at` on authenticate

---

rest-service/manager_rest/config.py
rest-service/manager_rest/constants.py
rest-service/manager_rest/flask_utils.py
rest-service/manager_rest/server.py
rest-service/manager_rest/storage/management_models.py
rest-service/manager_rest/storage/storage_utils.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_deployments.py
rest-service/manager_rest/test/security/test_base.py
rest-service/manager_rest/test/security_utils.py
rest-service/manager_rest/utils.py
tests/integration_tests/framework/postgresql.py
tests/integration_tests/tests/agentless_tests/security/security_base.py
tests/integration_tests/tests/agentless_tests/test_deployment_resource.py
tests/integration_tests/tests/agentless_tests/test_script_mapping.py
tests/integration_tests/tests/agentless_tests/test_snapshot.py
tests/integration_tests/tests/agentless_tests/test_workflow.py
tests/integration_tests/tests/utils.py
workflows/cloudify_system_workflows/snapshots/estopg.py
workflows/cloudify_system_workflows/snapshots/postgres.py

- Make the default tenant ID constant (set to 0)
- Prevent deletion of the default tenant
- Streamline the creation of the default tenant
- Make more use of the default tenant constants (instead of strings)

CFY-6317 Protect default tenant

---

rest-service/setup.py

Test cases have started failing all of sudden apparently because `six==1.10.0` is required in some dependency while the rest service itself required `six==1.8.0`. However, I haven't seen any place in which the rest service code makes use `six`, so it makes sense to remove the dependency from `setup.py` to fix the conflict.

Remove six dependency

---

rest-service/manager_rest/security/tenant_authorization.py
rest-service/manager_rest/storage/management_models.py
rest-service/manager_rest/storage/storage_manager.py

* Tenant get/list returns all users linked to the tenant (including those linked through user-groups).
* Tenant/Group/User names are sorted in tenant/user/user-group responses.

CFY-6344 Fix a bug in getting/listing tenants

---

rest-service/manager_rest/rest/resources_v1/events.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_events.py

In this PR, the `node_id` and `operation` columns are added to the `events`/`logs` tables. This is needed because otherwise the output logs miss this information.
Before the changes:
`2017-01-26 16:16:17.946  CFY <my-deployment> Sending task 'cloudify_agent.installer.operations.create'`
After the changes:
`2017-01-26 16:16:17.946  CFY <my-deployment> [vm_xiz0br.create] Sending task 'cloudify_agent.installer.operations.create'`
where `vm_xiz0br` is the `node_id` and `create` the `operation`.

CFY 6090. Add missing node_id and operation to events

---

rest-service/manager_rest/rest/resources_v1/tokens.py
rest-service/manager_rest/rest/resources_v1/version.py
rest-service/manager_rest/rest/resources_v3.py
rest-service/manager_rest/security/__init__.py
rest-service/manager_rest/security/secured_resource.py
rest-service/manager_rest/test/endpoints/test_version.py
rest-service/manager_rest/test/security/test_authentication.py

- For selected calls, the tenant authorization will be skipped
- Currently 3 calls will not require a tenant in the request header - version get, tenants list and tokens get

CFY-6350 Add ability to make rest calls without tenant header

---

rest-service/setup.py
workflows/cloudify_system_workflows/snapshot.py
workflows/cloudify_system_workflows/tests/test_snapshot.py
workflows/tox.ini

In this PR, the `zip64` extensions are enabled when writing a zip file for snapshots.
Besides this, there's a test case that verifies that a huge zip file can be created, but it's disabled because it takes really long to complete and is not really testing the code, but the `zipfile` python library.
Aside from that, there are a couple of changes in requirements, the `six` dependency removal is really a backport from #693, but I'm not sure about why I needed to add `wagon` to the tox environment. Shouldn't be already included in `dev_requirements`?

CFY 6333. Enable zip64 in snapshots

---

circle.yml

In this PR, the test commands in the circleci file have been consolidated into a single one using multi line strings to improve readability.
Note: while I was looking at the code and the test case output, I realized that only 7 out of 8 containers were being used. In the last one (number 7) the dependencies were installed, but no test case was executed since there was no match in the `case` statement. Hence, I've updated the project configuration in circleci to request only 7 containers. I thought about splitting the load using the empty container, but the jobs that take the longer (nodes 3 and 5) already run a single command, so it wouldn't have improved the overall build time.

Readable circleci config

---

rest-service/tox.ini
workflows/tox.ini

In this PR, the test case output verbosity is reduced by removing the `-v` and `-s` flags from `nosetests` commands being executed. The reason for this is that currently the test case output is so verbose that it's not possible to check the output when an error happens in circleci without downloading the log file because the web UI doesn't display huge files.
In addition to this, coverage reporting options are removed as well because that data isn't being for anything currently. They will be added in the future if this changes.
Note that [arguments passing through tox](http://tox.readthedocs.io/en/latest/example/general.html#interactively-passing-positional-arguments) has been enabled, so if anybody needs to set any of those flags to run the test cases locally it's still possible to do so …

Reduce test case output verbosity

---

circle.yml

In this PR, the configuration for Circle CI is updated to generate the tox virtualenvs during the dependencies phase, so that they can be cached. This way, there is no need to re-create them for every test run.
From what I've seen what is saved is just a few seconds, but still for a so small diff, I think it's worth the change.

Cache tox environment in circle ci

---

circle.yml

In this PR, the python version used to run the test cases is updated from 2.7.9 to 2.7.11.
The reason for this is that version 2.7.9 is not installed by default in the default image in Circle
CI and the installation takes around 2 minutes for every test run and container.
I don't know if there's a strict requirement about the python version, but the on that I get in a VM with CentOS 7 that I've used to bootstrap a manager is 2.7.5, so it seems that really any 2.7.x version might be in use depending on the image.

Update python version to 2.7.11 in Circle CI

---

workflows/cloudify_system_workflows/snapshots/es_snapshot.py
workflows/cloudify_system_workflows/snapshots/snapshot_create.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

In this PR, events stored in Elasticsearch are no longer included in snapshots.
There is another part to consider the issue resolved, which would be making sure that an old snapshot with elasticsearch data is restored by correctly inserting event information in postgres. That will be addressed in a separate PR.

CFY 6280. Do not include es data in snapshots

---

rest-service/manager_rest/rest/resources_v1/events.py
rest-service/manager_rest/rest/resources_v2/events.py
rest-service/manager_rest/test/endpoints/test_events.py

In this PR code has been updated to support parameters that were not part of the initial implementation like `_include` to apply projections and `_range` to filter by timestamp. This means that the integration test cases that depend on this behavior have been fixed.
Note that there are still a couple of test cases that need to be fixed that depend on a `message.text` parameter that was used to match messages using full-text search. This will be addressed in a separate PR.

CFY 6332. Fix events integration tests cases

---

workflows/cloudify_system_workflows/snapshots/snapshot_create.py
workflows/cloudify_system_workflows/snapshots/utils.py
workflows/cloudify_system_workflows/tests/snapshots/__init__.py
workflows/cloudify_system_workflows/tests/snapshots/tests_utils.py

This PR is port of the fix to enable zip64 in 3.4.2 to 4.0.
Related: #706

CFY 6333. Port enable zip64 in snapshots

---

run-tests.sh

In this PR, the tox virtual environments that were created in different CircleCI nodes are now created just in the first node. This is because, I've realized that, when parallelism is set, CircleCI uses the first node to decide what needs to be cached. Hence, all the tox environments should be created in the same node to take full advantage of caching.

CircleCI cache tox in first node

---

resources/rest-service/cloudify/types/types.yaml

In this PR, the `service_name` property is added to the `cloudify.datatypes.AgentConfig`

CFY-6382. Add service_name property to AgentConfig

---

resources/rest-service/cloudify/types/types.yaml

In this PR, the `service_name` property is added to the `cloudify.datatypes.AgentConfig`
Port of: #743

CFY 6382. Add service_name property (port to 4.0)

---

circle.yml
rest-service/tox.ini
run-tests.sh
workflows/tox.ini

In this PR, the `install_command` used in tox configuration files is updated to include the `-U` flag. This should take care of the case in which a cloudify package has been cached in a tox virtualenv, but it's been updated later by pushing a new change to github using the same version number.

Always upgrade packages in tox virtualenvs 

---

rest-service/dev-requirements.txt
rest-service/manager_rest/rest/resources_v1/events.py
rest-service/manager_rest/rest/resources_v2/events.py
rest-service/manager_rest/test/endpoints/test_events.py

In this PR, the filtering implementation is updated so that is no longer needed to always get events. Now both events and logs are optional and any of them (or both) can be retrieved in an API request.

CFY 6395. Filter by either events or logs

---

rest-service/manager_rest/rest/rest_decorators.py
rest-service/manager_rest/test/endpoints/test_events.py
rest-service/manager_rest/test/endpoints/test_rest_decorators.py

In this PR, support for empty values has been added back to the `rangeable` rest decorator. This means that instead filtering by `field,from,to`, it's possible not to include one of the `from`/`to` fields: `field,,to` or `field,from,`. This way it's possible to use the filter when only an upper/lower limit is needed.
Datetime parsing has been improved as well by using `dateutil.parser.parse` because from what I've seen the `Datetime` validator from `voluptuous` wasn't accepting iso8601 datetime which should be accepted by the events endpoint.

CFY 6557. Support empty values in rangeable decorator

---

rest-service/manager_rest/rest/resources_v1/events.py
rest-service/manager_rest/test/endpoints/test_events.py

In this PR, support for the following filters is added to the events endpoint: `blueprint_id`, `event_type`, `level` and `message`/`message.text`.
Note: For the `message`/`message.text` filter the `ILIKE` operator is used which is not equivalent to full text search. Consequently, even if filtering by message is supported, it is not equivalent in terms of functionality or performance to what it was available when data was indexed through Elasticsearch.

CFY-6408. Support more filter fields

---

resources/rest-service/cloudify/install_agent_template.py
workflows/cloudify_system_workflows/snapshots/agents.py

The new agents upgrade process is as follows:
* Upon issue of a `cfy agents install` command, a new
`install_agent.py` script is rendered, with a REST token and the SSL
certificate inside it.
* It is then moved to a special location inside the file server
(/resources/cloudify_agent), with a fresh UUID prepended to it.
* The request is sent to the celery client on the agent machine,
and processed by the worker thread there (this is as it was before)
* The old agent downloads the script, which holds all the info
necessary to update the SSL certificate, and then proceed to
download and install the new agent package, as before

CFY-6577 Fix agents upgrade after snapshot restore

---

rest-service/manager_rest/storage/resource_models.py
workflows/cloudify_system_workflows/snapshots/estopg.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py
workflows/cloudify_system_workflows/snapshots/utils.py

In this PR, the ability to restore events/logs from a 3.4.2 snapshot into a 4.0 manager has been added.
It has been tested by creating a snapshot in a 3.4.2 manager and restoring it in a 4.0 one. After that the events/logs could be retrieved for the new tenant created during the restore process.
The only thing that looks weird is that the `restore_snapshot` execution remains with `started` state after the restore has finished. I've verified that this happens also with the current code in `master`, so it's not related to this branch.  In any case, it would be worth investigating it.

CFY 6280. Restore es_data into postgres

---

rest-service/manager_rest/test/endpoints/test_events.py
tests/integration_tests/tests/agentless_tests/test_events.py

In this PR the problem with integration tests using the `message` parameter have been fixed by:
- Updating the query syntax to the one using the `LIKE` operator
- Removing the test case that was testing Elasticsearch query details that no longer apply

CFY 6332. Fix search event message integration test

---

rest-service/manager_rest/rest/resources_v1/events.py
rest-service/manager_rest/rest/resources_v2/events.py
rest-service/manager_rest/test/endpoints/test_events.py

In #785 a problem was introduced because `Node` and `NodeInstance` model were added to the events query. What happens is that the event count doesn't match the event list actually returned because the query discards events for which no `Node` or `NodeInstance` is set.
In this PR, that problem is solved using outer joins.

CFY 6645. Use outer joins to allow for empty node values

---

rest-service/manager_rest/rest/resources_v3.py
rest-service/manager_rest/test/endpoints/test_events_v3.py

In this PR, unused fields (`id` and `message_code`) are removed from events endpoint in API v3.

CFY 6648. Remove unused fields from events

---

rest-service/manager_rest/rest/resources_v1/events.py
rest-service/manager_rest/rest/resources_v3.py
rest-service/manager_rest/storage/models_base.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_events.py
rest-service/manager_rest/test/endpoints/test_events_v3.py
rest-service/manager_rest/test/endpoints/test_models_base.py

In this PR, timestamps for events and logs are updated, so that when they are serialized the timezone in which the manager machine is configured is taken into account.
For example, if the manager is in UTC:
`2017-03-22 11:42:30.032  CFY <linuxdp1> 'install' workflow execution succeeded`
if the manager is in `Asia/Jerusalem`:
`2017-03-22 13:42:30.032+02:00  CFY <linuxdp1> 'install' workflow execution succeeded`
and if the manager is in `America/New_York`:
`2017-03-22 07:42:30.032000-04:00  CFY <linuxdp1> 'install' workflow execution succeeded`

CFY 6652. Serialize timestamps using manager timezone

---

rest-service/manager_rest/rest/resources_v1/events.py
rest-service/manager_rest/test/endpoints/test_events.py

When an impossible filter condition was passed (such as `event_type` and `cloudify_log` or `level` and `cloudify_event`), the rest server crashed because no query was generated.
In this PR, this is fix by returning a simple query that always returns an empty result set.

CFY 6408. Fix filter by type

---

rest-service/manager_rest/test/endpoints/test_events.py

In this PR, the select events test cases are extended to include the count query. A few problems, which could affect pagination of results for the events endpoint, have been found and are now fixed.

Add count query to events test cases

---

rest-service/manager_rest/storage/resource_models.py

In this PR, the `error_causes` column is added to the event model.
The column type is set to text for now even though the content will be JSON data. The deserialization code will be submitted in a separate PR.

CFY-6479 Add error_causes column to event model

---

rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_events.py

In this PR, the schema for `Event` and `Log` is updated to add the `reported_timestamp` field and a default value is set to `timestamp` to set it to `current_timestamp` when a new record is inserted.
Related: cloudify-cosmo/cloudify-manager-blueprints#528

CFY-6647 Add reported_timestamp field and set default to timestamp

---

rest-service/manager_rest/rest/resources_v1/events.py
rest-service/manager_rest/storage/models_base.py
rest-service/manager_rest/storage/resource_models.py
tests/integration_tests/tests/agentless_tests/test_execution_logging.py

In this PR, the execution logging test is fixed thanks to the fact that the task error causes are now included in the API response from the events endpoint.
Depends on:  cloudify-cosmo/cloudify-manager-blueprints#540, cloudify-cosmo/cloudify-cli#576

CFY 6479. Fix test execution logging

---

tests/integration_tests/tests/agentless_tests/test_events.py

In this PR, the events integration tests that broke after applying the change to use a flat structure have been fixed.

CFY 6648. Fix events integration tests

---

tests/integration_tests/tests/agentless_tests/test_task_retries.py

In this PR, the following test case:
`integration_tests.tests.agentless_tests.test_task_retries.TaskRetriesTest.test_operation_retry`
is fixed and refactored.
The fix is basically using the properties of the new flat event structure instead of the old nested one with context.

CFY 6648. Fix task_operation_retry

---

tests/integration_tests/tests/agentless_tests/test_snapshot.py
workflows/cloudify_system_workflows/snapshots/estopg.py

In this PR, the problems with timestamps in snapsthot are fixed by restoring the following fields:
Elasticsearch | PostgreSQL
------------- | ----------
`@timestamp`  | `timestamp`
`timestamp`   | `restored_timestamp`
Note: this doesn't fix the test cases yet, but fixes the problem related to snapshot timestamps

CFY 6647. Fix restore snapshot timestamp

---

tests/integration_tests/tests/agentless_tests/test_task_retries.py

This is a followup of #802 in which `test_operation_retry` is made more stable by making sure that the event data is correctly ordered to avoid assertion failures when events have exactly the same timestamp.

CFY-6648. Make sorting order by event type explicit

---

tests/integration_tests/tests/agentless_tests/test_snapshot.py

In this PR, an assertion that was causing problems in snapshot integration test cases has been removed because it's not longer needed.

CFY-6660. Remove deployment permission assertion

---

tests/integration_tests/framework/constants.py
tests/integration_tests/framework/docl.py
tests/integration_tests/framework/env.py

* resources.tar.gz is now renamed to cloudify-manager-resources.tar.gz.
This is due to the fact that the "cloudify-manager-resources" is used
elsewhere in the code

CFY-6582 Fix problems related to docl

---

resources/rest-service/cloudify/migrations/versions/9aa6f74c9653_4_0_1.py

In this PR:
- the timestamp index for events/logs is no longer dropped in the migration upgrade from 4.0 to 4.0.1
- the timestamp default is unset in the migration downgrade from 4.0.1 to 4.0

CFY 6718. Timestamp index and default

---

resources/rest-service/cloudify/migrations/schema.py
rest-service/manager_rest/storage/storage_utils.py
tests/integration_tests/framework/flask_utils.py
tests/integration_tests/framework/postgresql.py
tests/integration_tests/tests/agentless_tests/test_snapshot.py
workflows/cloudify_system_workflows/snapshots/postgres.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py
workflows/cloudify_system_workflows/snapshots/utils.py

In this PR, the ability to restore 4.0 snapshots by running database schema migrations has been implemented.
Note that the migration scripts need to run in the manager virtualenv while the postgres restore itself runs in the management worker virtualenv. When a better design for restoring snapshots is in place, this should be refactored.

CFY 6718. Restore 4.0 snapshot

---

resources/rest-service/cloudify/migrations/schema.py
workflows/cloudify_system_workflows/snapshots/constants.py
workflows/cloudify_system_workflows/snapshots/snapshot_create.py
workflows/cloudify_system_workflows/snapshots/utils.py

In this PR, the current schema revision is added to the snapshot metadata.
This will make easier in the future to restore snapshots from different versions without having a explicit mapping from cloudify version to database schema revision.

CFY 6718. Store schema revision in snapshot metadata

---

rest-service/manager_rest/storage/relationships.py
rest-service/manager_rest/storage/resource_models_base.py

Pretty much all of our resources are queried with a WHERE on tenants,
so let's make that indexable by default.
This is mostly required for the events and logs tables, which can grow 
very large, so we really don't want seq scans on those tables.

Add index=True to the Tenant FK

---

tests/integration_tests/tests/agentless_tests/test_snapshot.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

In this PR, the code to restore snapshots is updated to take into account the schema revision that is included in the metadata starting from 4.0.1.
Notes:
- this change is expected to be merged in 4.1.
- a local snapshot was used for testing. When 4.0.1 is released, a new snapshot needs to be created and uploaded to the s3 bucket used to store testing snapshots.

CFY 6835. Use schema revision on snapshot restore

---

resources/rest-service/cloudify/migrations/versions/333998bc1627_4_0.py
resources/rest-service/cloudify/migrations/versions/9aa6f74c9653_4_0_1.py

As reported by @mcouthon, the migration scripts where broken when #855 was merged because they still use the old `LodalDateTime` type.
In this PR, that is replaced by `UTCDatetime` which was used in the past. Note that that is SQLAlchemy type that changes serialization, but uses the same underlying database type. Hence, there's no need to create a new migration script.

CFY-6652 Fix datetime type in migration scripts

---

resources/rest-service/cloudify/migrations/schema.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py
workflows/cloudify_system_workflows/snapshots/utils.py

Postgresql port isn't always 5432 - when running a cluster, it's by default 15432.
This change makes the port parametrized, by passing the whole `postgresql_host` from restservice - which contains both the host and the port, eg. "localhost:15432"
The `self._config` for the snapshot restore contains that value (it is created here https://github.com/cloudify-cosmo/cloudify-manager/blob/master/rest-service/manager_rest/resource_manager.py#L97 ), so we use that - pass the whole config to the utils `db_schema` function, which passes it to the `schema.py` script via a cmdline arg, where it is used for creating a flask app that is used by flask_migrate

CFY-6864 schema.py: use the same postgresql_host as restservice

---

rest-service/manager_rest/rest/resources_v1/events.py
rest-service/manager_rest/rest/resources_v3.py
rest-service/manager_rest/test/endpoints/test_events.py
rest-service/manager_rest/test/endpoints/test_events_v3.py

In this PR, the `reported_timestamp` value stored in the database is returned in API calls.
Before this PR, the `reported_timestamp` field was just a copy of `timesamp` because there was no `reported_timestamp` field in the database yet.
Thanks @dmitryAII  for reporting the problem.

CFY 6647. Return reported timestamp in events API

---

workflows/cloudify_system_workflows/snapshots/utils.py

Snapshots made on older manager versions (eg. 4.0.1) don't have the
Stage data yet, so we should handle the case of the files not being
there.

CFY-6908 Don't try to restore stage files if they're not present

---

rest-service/manager_rest/flask_utils.py

In this PR, the function to get postgres configuration now depends on the manager configuration and falls back to the same hardcoded defaults if no configuration is defined (`MANAGER_REST_CONFIG_PATH` environment variable needs to be set).

CFY-6882. Use manager configuration to get database one

---

rest-service/manager_rest/amqp_manager.py

This is to prevent escaping problems from happening in scripts that
just quote the password value.

CFY-6997. Restrict allowed characters in rabbitmq user password

---

resources/rest-service/cloudify/migrations/versions/3496c876cd1a_drop_server_side_event_timestamp_.py
rest-service/manager_rest/storage/resource_models.py

In this PR, the schema for the events and logs tables is updated to drop the server side default that was inserting `timestamp` values automatically. This is because the timestamp value was in localtime, not UTC, in PostgreSQL and there's no common syntax supported by both PostgreSQL and SQLite to add that default (SQLAlchemy should handle that, but it doesn't yet).
Hence, the timestamp value is either generated by SQLAlchemy using `datetime.utcnow` or passed explicitly (as logstash does).

CFY-7005. Default timestamp values as UTC

---

rest-service/manager_rest/rest/rest_decorators.py
rest-service/manager_rest/test/endpoints/test_rest_decorators.py

Passing timezone aware timestamp to PosgreSQL through SQLAlchemy doesn't
seem to work well in manual tests

CFY-7005 Parse timestamps as UTC values and remove timezone info

---

tests/integration_tests/tests/agentless_tests/test_deployment_creation.py
workflows/cloudify_system_workflows/deployment_environment.py
workflows/setup.py

In this PR, a `retry` decorator has been added to the function in which the `OSError` exception was being raised. After this change, the test case in which the problem is reproduced passes successfully.

CFY-6728. Retry if file already exists

---

tests/integration_tests/resources/dsl/dockercompute_timezone.yaml
tests/integration_tests/resources/dsl/scripts/operations/timezone_configure.sh
tests/integration_tests/tests/agent_tests/test_events.py
tests/integration_tests/tests/agentless_tests/test_events.py

In this PR, a new events test class is added to the integration tests. This new class inherits from the old one meaning that all test cases are repeated using a different timezone configuration with the addition of a couple ones that verify that the timestamp values are within the expected range in UTC.

CFY-7005. Add event test cases with different database timezone

---

tests/integration_tests/tests/agentless_tests/test_events.py

In this PR, a message is included in the assertion that verifies that all timestamps are in UTC. This way, if the test case fails in the future, the message will include the timestamps that are out of the expected range.

CFY-7005. Add exception message to `test_timestamp_in_utc`

---

tests/integration_tests/resources/dsl/plugins/target_aware_mock.yaml
tests/integration_tests/resources/plugins/target_aware_mock/setup.py

The mismatch between versions caused a test not to pass

CFY-7084 Change plugin version to one independent of Cloudify's version

---

rest-service/manager_rest/storage/storage_manager.py
workflows/cloudify_system_workflows/snapshots/fix_snapshot_ssh_db.py

Without this, the update runs, but the changes seem to be lost (presumably something to do with the way the storage manager is being used here causing it not to commit correctly?).

Make snapshot agent key converter apply db changes

---

packaging/restservice/build.spec

This should help resolve problems like this: https://stackoverflow.com/questions/45809699/cloudify-manager-bootstrapping-rest-service-failed

Upgrade virtualenv when installing the REST service (#948)

---

rest-service/manager_rest/rest/resources_v1/status.py
rest-service/manager_rest/rest/resources_v3_1/manager.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/utils.py

Instead of calling `sed` from the restservice code, let's add
a script that will do the necessary config changes.
This way, we can also run that script from within cluster code,
and also we won't need to enable `sudo` for `sed`, only for this
specific script.

CFY-7188 Use a script to set manager SSL state

---

resources/rest-service/cloudify/types/types.yaml

And it should represent a single network name, not a dict of networks

CFY-7197 Agent config should have a `network` property (not `networks`)

---

workflows/cloudify_system_workflows/snapshots/utils.py

In this PR, the new `authorization.conf` file is included in a snapshot when is created.
As a side effect, when a snapshot is restored that includes `authorization.conf`,
it will be copied to the expected location as well. Also if the file is not included
in the snapshot it will be ignored, that is, nothing needs to be done,
since there will be already a file there.

CFY-7240. Include authorization.conf in snapshot

---

rest-service/manager_rest/server.py

App context isn't required for the .init_app(app) call. That method
will use the app passed to it as an argument, not the context one.

Initializing flask-sqlalchemy: don't push app context

---

rest-service/manager_rest/server.py
rest-service/manager_rest/wsgi.py

This will allow importing CloudifyFlaskApp without invoking side
effects at import time.
gevent must now use manager_rest.wsgi:app
instead of manager_rest.server:app.

CFY-7328 Instantiate the app in a separate wsgi.py module

---

rest-service/manager_rest/config.py

This allows loading the configuration passing a filename directly,
without the need to go through env vars. This will make it easier to
use the config from parts of the code that aren't run inside the
restservice.

CFY-7328 Config: add the load_from_file method

---

resources/rest-service/cloudify/migrations/versions/406821843b55_add_role_column_to_users_tenants_table.py
rest-service/manager_rest/storage/management_models.py

In this PR, a custom secondary table is created to add the new `role_id` column to the `users_tenants` table.
Related #973

CFY-7257. Add roles column to secondary table

---

resources/rest-service/cloudify/migrations/versions/7aae863786af_add_role_column_groups_tenants_table.py
rest-service/manager_rest/storage/management_models.py

In this PR, the database schema is updated to add a `role_id` column to the `groups_tenants` table, so that a role can be assigned to a group when added to a tenant.

CFY-7258. Use association object

---

rest-service/manager_rest/storage/management_models.py
rest-service/manager_rest/storage/models.py
rest-service/manager_rest/storage/storage_utils.py
rest-service/manager_rest/test/security_utils.py

In this PR, the original secondary table design is replaced with an association object.
This is because the secondary table doesn't provide a way to access the `role_id` column
at the ORM level and that is something that will be needed to add/remove tenants to a user. 
Note that back references are set to new attributes (`user_associations` and `tenant_associations`)
while association proxies are used to keep the old attributes (`users` and `tenants`).
This way, old code that uses those attributes don't need to be updated.
Also, there's a cascade parameter in the relationships that will be used in a separate PR
when removing users from a tenant.

CFY-7257 Use association object instead of secondary table

---

rest-service/manager_rest/storage/management_models.py

In this PR, a creator function is added to the association proxies, so that an association can be created easily when there's no need to set the role in that association. 
In addition to this, the `User.all_tenants` property problems have been fixed. The issue was related to lists returned by association proxies not having a `.append` method.

CFY-7258 Add creator function to association proxies

---

rest-service/manager_rest/storage/storage_manager.py

When the storage_manager is used outside a request context, it throws
an error because it tries to automatically filter on the current
user. (only happens in list, not in eg. get)
This change makes it so that the user won't be checked if not run
from a request.
This will allow using the storage manager for more things (not just
getting) in cloudify-premium, and in the future, also in the admin cli.

CFY-7338 storage_manager: don't break when used outside request context

---

rest-service/manager_rest/workflow_executor.py

Celery tasks don't require the users/groups related to a tenant, so
we don't need to send them.
If we did want to send them, we'd have to serialize them. Currently
the users and groups end up as sqlalchemy association proxy lists
of models, which can't be json-encoded directly.
Future work might involve whitelisting the attributes instead of
blacklisting, ie. creating a new dict there with just the few
attributes that are required, instead of serializing the whole
tenant object and removing the few attributes we don't want.

Celery: don't send users/groups related to a tenant

---

rest-service/manager_rest/storage/management_models.py

In this PR, the `User.all_tenants` property is updated to return a dictionary where the keys of the dictionary are the tenants associated with that user and the values are the role associated with that user in the context of the tenant.
Besides this, there are other changes to make it easier to work with the association objects:
- fix string representation
- get role object through relationship
Finally the `Tenant.all_users` method is updated to return a list instead of an association proxy list which has side effects that the code that uses it doesn't take into account and might cause problems like the ones seen in integration tests where a new instance of an ORM object conflicts with another one that is already in persistent state with the same primary key.

CFY-7257. Update all_tenants property to return a dictionary

---

resources/rest-service/cloudify/migrations/versions/406821843b55_add_role_column_to_users_tenants_table.py
rest-service/manager_rest/storage/management_models.py

In this PR, the migration script that adds the `role_id` column to the `users_tenants` table is updated to set the system-wide user role as the default value for the association. In addition to this, once the column has been filled in with values, a `NOT NULL` constraint is added to make sure that the column always contains a value.

CFY-7257. Set user tenant role in migration

---

rest-service/manager_rest/storage/management_models.py
rest-service/manager_rest/storage/relationships.py

In this PR, the association classes use the `foreign_key` helper function instead of the more verbose sqlalchemy alternative.

CFY-7258. Use foreign key helper

---

resources/rest-service/cloudify/migrations/versions/406821843b55_add_role_column_to_users_tenants_table.py
resources/rest-service/cloudify/migrations/versions/7aae863786af_add_role_column_groups_tenants_table.py

In this PR, the `user` role is set by default to every user and group that is part of a tenant
Requires: cloudify-cosmo/cloudify-premium#280

CFY-7258. Set 'user' role by default in migration scripts

---

rest-service/manager_rest/storage/management_models.py

In this PR, a couple of minor changes are applied now that a `role_id` column is always set in the group tenants association.

CFY-7259. Remove unneeded conditional

---

resources/rest-service/cloudify/migrations/versions/406821843b55_add_role_column_to_users_tenants_table.py
rest-service/manager_rest/security/authorization.py

In this PR, system roles are updated to their new default values:
Before | After
-------|------
user | default
admin | sys_admin
Requires: a separate PR where the new `default` and `sys_admin` roles are inserted into the database

CFY-7258. Set system roles to new default values

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/storage/resource_models.py

The creator is set explicitly anyway, as is the resource availability
field, and the tenant shouldn't be inherited as well, because the
blueprint can be global anyway, in which case there's no point in
inheriting the tenant from it.

CFY-7357 Deployments shouldn't inherit the blueprint's tenant/creator

---

rest-service/manager_rest/utils.py
workflows/cloudify_system_workflows/snapshots/estopg.py

The association seems to be already there, so adding a new one just
causes a duplication error.

CFY-7356. Do not append any association

---

rest-service/manager_rest/storage/management_models.py
rest-service/manager_rest/test/endpoints/test_user.py

In this PR, the `User.all_tenants` dictionary is returned in the API response.

CFY-7259. Return tenants dictionary in API response

---

rest-service/manager_rest/storage/management_models.py
rest-service/manager_rest/test/endpoints/test_user.py

In this PR, the `get_data` flag is taken into account to make sure that `User.tenants` is either a count of tenants or a dictionary of tenants with the associated roles.

CFY-7259. Take_get data flag into account

---

rest-service/manager_rest/rest/resources_v3/tenants.py

In this PR, the endpoint to update the group-tenant association is added.
Requires:
- cloudify-cosmo/cloudify-manager-blueprints#699
- cloudify-cosmo/cloudify-premium#294

CFY-7373. Add endpoint to update group-tenant association

---

rest-service/manager_rest/storage/storage_manager.py

Authorization queries for a tenant, so we need to be able to look up
tenants BEFORE current_tenant is set.
It used to be that _add_permissions_filter checked for is_resource
before ever checking for administrator, so we should go back to that
behaviour, because now checking for administrator needs a tenant.
So this change simply moves the .is_resource check to BEFORE
touching current_tenant at all.
This also makes _add_permissions_filter be more similar to
_add_tenant_filter.

storage_manager: check .is_resource before checking for admin

---

rest-service/manager_rest/rest/rest_utils.py

In this PR, the error message returned when a role is not found is improved. Instead of returning all roles, it just returns the roles of the expected type.
Before:
```
$ cfy tenants add-user -t my-tenant -r unknown my-user
An error occurred on the server: 400: Invalid role: `unknown`. Valid roles are: ['sys_admin', 'manager', 'user', 'viewer', 'default']
```
After:
```
$ cfy tenants add-user -t my-tenant -r unknown my-user
An error occurred on the server: 400: Invalid role: `unknown`. Valid tenant_role roles are: ['manager', 'user', 'viewer']
```

CFY-7350. Only tenant roles in error message

---

rest-service/manager_rest/storage/management_models.py

In this PR, the data returned by the tenant model is updated to display the roles associated with users and groups when the `--get-data` flag is used.
Before:
```
$ cfy tenant get my-tenant --get-data
Getting info for tenant `my-tenant`...
Requested tenant info:
+-----------+---------------------+---------+
|    name   |        groups       |  users  |
+-----------+---------------------+---------+
| my-tenant | my-group,my-group-2 | my-user |
+-----------+---------------------+---------+
```
After:
```
$ cfy tenant get my-tenant --get-data
Getting info for tenant `my-tenant`...
Requested tenant info:
+-----------+-----------------------------------------------------+------------------------------------------------+
|    name   |                        groups                       | …
```

CFY-7417. Get tenant with data

---

resources/rest-service/cloudify/migrations/script.py.mako
resources/rest-service/cloudify/migrations/versions/406821843b55_add_role_column_to_users_tenants_table.py

This is due to the fact that role IDs have changed in this version,
and so we can't rely on `2` being the role ID of the `user` role (it is
`manager` in 4.2)

CFY-7418 Alter `users_roles` role_id entries with manual values

---

rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/storage/management_models.py
rest-service/manager_rest/test/base_test.py
tests/integration_tests/framework/amqp_events_printer.py
tests/integration_tests/framework/env.py
tests/integration_tests_blueprint/scripts/utils.py
tests/integration_tests_plugins/mock_workflows/workflows.py
workflows/cloudify_system_workflows/snapshots/influxdb.py
workflows/cloudify_system_workflows/snapshots/utils.py

In this PR, the `to_response` methods are updated to handle the `get_data` flag directly.

CFY-7373. Return response data directly

---

rest-service/manager_rest/storage/management_models.py
rest-service/manager_rest/test/security_utils.py

In this PR, the tenant users response is fixed using the tenant roles for each user, not the system role.
Also, in test data the system-wide role and the user tenant role are kept separate and different to avoid confusion.

CFY-7350 Fix users response in tenants

---

rest-service/manager_rest/storage/management_models.py

In this PR, the response for the `cfy tenants` and `cfy users` commands is updated to include the `tenant-role` field to make clear what is the role assigned to a user in a tenant. All other roles coming from groups are also listed.
Before:
```
$ cfy tenants get my-tenant --get-data
Getting info for tenant `my-tenant`...
Requested tenant info:
+-----------+---------------------------------------------------+------------------------------------------------+
|    name   |                       groups                      |                     users                      |
+-----------+---------------------------------------------------+------------------------------------------------+
| my-tenant | {u'my-group-2': u'manager', u'my-group': u'user'} | {u'my-user': [u'manager', u'user', …
```

CFY-7350. Return tenant role

---

rest-service/manager_rest/rest/resources_v3/tenants.py
rest-service/manager_rest/rest/resources_v3/user_groups.py

In this PR, the following names are disallowed:
- tenant: `users` and `user-groups`
- user group: `users`
This is because with the current API design, if any of those resources were created, then it wouldn't be possible to delete it.

CFY-7457. Disallow problematic names

---

rest-service/manager_rest/rest/resources_v3_1/manager.py

The mutation is not detected, we need to actually assign it for the
options to be saved.

CFY-7332 Set SSL in cluster: re-assign cluster options

---

rest-service/manager_rest/rest/resources_v1/events.py

When an events list is retrieved from the API the count might not match the actual number of events returned if a duplicate row is found.
This is because events and logs are joined together using the `UNION` operator which, as described in the PostgreSQL documentation *eliminates duplicate rows from its result, in the same way as DISTINCT, unless UNION ALL is used*.
In this PR, the advice from the documentation above is followed and `UNION ALL` is used instead of just `UNION`.
Note: two rows might be identical in a query that retrieves events and logs because the `_storage_id` column is not included in the select statement to do so.

CFY-7444. Do not discard row duplicates in UNION operator

---

rest-service/manager_rest/rest/resources_v3/secrets.py

In this PR, the API endpoint to create a secret is updated to allow for an `upsert` flag to be passed in the json data. When the flag is set, if the secret already exists, it is updated.

CFY-7562. Secret create update_if_exists

---

rest-service/setup.py

Moved to cloudify-premium, where it is used

CFY-7673 Remove signxml requirement

---

packaging/cloudify-rest-service.spec

So that it gets removed on uninstall

.spec: own the whole /opt/restservice

---

rest-service/manager_rest/VERSION
rest-service/manager_rest/__init__.py
rest-service/manager_rest/config.py
rest-service/manager_rest/rest/resources_v1/version.py
rest-service/manager_rest/test/endpoints/test_version.py

Instead of using the VERSION file to encode the version/edition
at build time, we'll be using the config file for the edition
and we'll query the actually installed version.

CFY-7735 Get edition from the config file

---

tests/integration_tests/tests/agentless_tests/test_ssl.py

This is because we're now using the CA cert to sign the external now, which makes it so that only the CA cert can be used for validation.

Use the CA cert in the SSL test instead of the external cert

---

packaging/cloudify-logstash.spec.dependencies

Quick fix removes Oracle JRE (OpenJDK doesn't cause this bad interaction, & will be automatically fetched through yum during the mock build)

CFY-7618 fix logstash jre dependency install

---

rest-service/manager_rest/manager_exceptions.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/mock_blueprint/plugin.yaml

When installing a plugin with executor: central_deployment_agent,
check that the plugin is valid for the manager's distro & platform.
This validation is only done if the yaml file was provided,
and in the yaml file, the executor for the plugin is
central_deployment_agent. If the yaml file was not provided, this check
is not performed.
If the plugin's supported platform/distro differs from the manager's,
an error is raised.

CFY-7805 When installing plugins, validate manager platform

---

packaging/cloudify-riemann.spec
packaging/riemann/files/etc/sudoers.d/cloudify-riemann
packaging/riemann/files/usr/lib/systemd/system/cloudify-riemann.service

- Dedicated `sudoers.d` file for the `riemann` user
- Allow `riemann` to not require TTY
- Allow `riemann` to run `/bin/bash` as `cfyuser`
- Riemann service runs under `riemann` user without impersonation

CFY-7868: Fixed sudo usage

---

packaging/cloudify-rabbitmq.spec
packaging/rabbitmq/files/etc/cloudify/rabbitmq/rabbitmq-env.conf

For this file to be used, we'd have to specify it in the configuration.
It's easier to simply put that value in the configuration instead.
For some reason, specifying this file with `RABBITMQ_CONF_ENV_FILE`
doesn't seem to work for me, but putting `RABBITMQ_NODENAME` in the
EnvironmentFile does work.

CFY-7899 Delete rabbitmq-env.conf

---

packaging/rabbitmq/files/etc/logrotate.d/cloudify-rabbitmq

Instead of using an init script, call rabbitmqctl directly so
that we can pass the rabbitmq nodename

RabbitMQ logrotate script: pass nodename to rabbitmqctl

---

packaging/ip_setter/files/usr/lib/systemd/system/cloudify-manager-ip-setter.service

The scripts require the database, so it should be declared as well

CFY-7917 Make ipsetter require postgresql in systemd

---

packaging/ip_setter/files/usr/lib/systemd/system/cloudify-manager-ip-setter.service

Quoting the docs,
>Note that this setting is independent of and orthogonal to the requirement dependencies as configured by Requires=, Wants= or BindsTo=. It is a common pattern to include a unit name in both the After= and Requires= options, in which case the unit listed will be started before the unit that is configured with these options.

ipsetter: explicitly After= the database

---

packaging/ip_setter/files/usr/lib/systemd/system/cloudify-manager-ip-setter.service

it's not allowed for `oneshot` services

ipsetter: remove restart

---

rest-service/manager_rest/security/authorization.py

If the user is inactive, we need to actually validate that.

CFY-7931 Validate deactivated users

---

packaging/build_rpm.py

This is necessary in case the dependencies themselves contain
variables

build_rpm.py: render the spec file before getting dependencies

---

packaging/rest-service/files/usr/lib/systemd/system/cloudify-restservice.service

Access to port 8100 is only expected from within the manager's machine.
We should bind to 127.0.0.1 as a security measure.

gunicorn only listens to localhost

---

packaging/rabbitmq/files/etc/cloudify/rabbitmq/rabbitmq.config

The management UI is still potentially useful, so let's not disable
it entirely just yet.
Docs for these configuration options are at:
https://www.rabbitmq.com/management.html

CY-96 Make rabbitmq management port be localhost-only and SSL

---

rest-service/manager_rest/amqp_manager.py
rest-service/manager_rest/test/base_test.py
rest-service/setup.py
tests/integration_tests/framework/flask_utils.py
workflows/cloudify_system_workflows/snapshots/restore_amqp.py

Instead of using pyrabbit, which doesn't support ssl, let's drop
down to requests, and reimplement the required simple functionality

CY-156 Implement a rabbitmq API client using requests

---

workflows/cloudify_system_workflows/snapshots/restore_amqp.py

Instead of amqp_host, which can be something other than localhost

CY-96 Use amqp_management_host in snapshot restore

---

tests/integration_tests/framework/constants.py
tests/integration_tests/framework/flask_utils.py
tests/integration_tests/resources/scripts/reset_storage.py
tests/integration_tests/tests/test_cases.py

The storage resetting parts must connect to the database, and to the
rabbitmq management API. Those should be only listening on localhost,
and not be reachable from outside, so to connect to them, the script
must live on the manager.
This change is about moving the reset_storage code from being run on
the test host, to a script that is being run on the manager container

CY-96 Tests reset_storage: move to a script

---

packaging/mgmtworker/files/usr/lib/systemd/system/cloudify-mgmtworker.service

because a hard-coded limit of 5 doesn't make any sense.

CY-181: configurable bucket size

---

workflows/cloudify_system_workflows/snapshots/networks.py

snapshots create failed because runtime properties was empty.

CY-189-snapshot create to fail

---

tests/integration_tests/framework/flask_utils.py

It's used with `global` so it must be defined first

flask_utils: add missing variable

---

packaging/ip_setter/files/opt/cloudify/manager-ip-setter/manager-ip-setter.sh

Because we're either binding on `localhost` or an external endpoint, there's no point in replacing this IP with the private one.

CFY-7877 No longer update influxDB IP in IP setter

---

tests/integration_tests/tests/agentless_tests/test_executions.py

By using sets instead of lists. Apparently events aren't always ordered perfectly when received by the client, so using sets removes the need for order.

Fix sporadic dry_run test failures

---

plugins/riemann-controller/riemann_controller/tasks.py

This fixes an issue where riemann config is not removed and this can lead to a new deployment having VMs healing when first deployed.

Remove riemann config directories when deployment is deleted

---

rest-service/manager_rest/cryptography_utils.py
rest-service/manager_rest/rest/resources_v3/secrets.py
rest-service/manager_rest/rest/resources_v3_1/secrets.py
workflows/cloudify_system_workflows/snapshots/credentials.py

When restoring a snapshot with agents, in the restore process we save the ssh keys as secrets. In the restore we are using the current encryption key but after the restore the key is changed to the one in the snapshot. So after the snapshot restore those secrets can't be decrypted. We added the encryption_key parameter to secrets create rest api. It should be used internally only in snapshot restore process, when we create the agent's ssh keys as secrets and want to use the encryption key from the snapshot.

CY-271 Fix the restore of snapshot with agents

---

packaging/cloudify-mgmtworker.spec
packaging/mgmtworker/requirements.txt
packaging/mgmtworker/stub_packages/cloudify-dsl-parser/setup.py
packaging/mgmtworker/stub_packages/cloudify-plugins-common/setup.py
packaging/mgmtworker/stub_packages/cloudify-rest-client/setup.py
packaging/mgmtworker/stub_packages/cloudify-script-plugin/setup.py

This is to continue supporting old Cloudify plugins that would
otherwise break, because during installation they would install
the old plugins-common/rest-client/etc wheels that were contained in
the wagon.
This solution should make the pip freeze command we're using to create
the constraints file for the mgmtworker venv during plugin installation
contain the same package names, and thus prevent the installation
of the older ones in the plugin venv.

CFY-7661 Create stubs for repos that were merged into cloudify-common

---

tests/integration_tests/tests/agentless_tests/test_manager_misc.py

Logrotate lives in cron.daily now, not cron.hourly

CY-333 Run the right logrotate script

---

packaging/rabbitmq/files/etc/cloudify/rabbitmq/rabbitmq.config

RabbitMQ uses the 'cacertfile' setting as the chain to send with
the server certificate (in addition to using it for client
cert verification).
This means the certfile setting must contain the server cert, and
cacertfile must contain the intermediaries, if any.
In certfile, the additional intermediary is ignored, so we can use
the cloudify_internal_cert bundle there.
In cacertfile, the server file is ignored, so there we can also use
the same bundle.

CY-348 rabbitmq: provide the internal cert as cacertfile

---

resources/rest-service/cloudify/migrations/versions/c7652b2a97a4_4_3_to_4_4.py

* The problem was that the command `alter type execution_status add value 'kill_cancelling'` cannot run inside a transaction block.
* The solution was to commit the current transaction.

Fix the upgrade of the last migration file

---

rest-service/manager_rest/test/endpoints/test_deployments.py

* We changed the behavior when get_attribute fails in outputs
* Instead of raising an error and fail all the outputs, we put the error string where it failed
so the valid outputs will be visible

Fix illegal output test

---

.circleci/config.yml

- There a connection with the build of manager install repo, so this step is needed

CY-412 : Remove filter on build_rpms job

---

packaging/rabbitmq/files/etc/cloudify/rabbitmq/rabbitmq.config

Only allow strong ciphers when connecting to RabbitMQ.
This list of ciphers covers all ciphers that are ranked as "Advanced" and "Advanced+" by OWASP (see: https://www.owasp.org/index.php/TLS_Cipher_String_Cheat_Sheet)
Seems like RabbitMQ works with the auto-generated internal cert just fine.

CY-528: Only allow strong ciphers

---

packaging/rabbitmq/files/usr/lib/systemd/system/cloudify-rabbitmq.service

`/var/run` is deprecated, should use `/run` instead.

CY-568: removed /var prefix

---

packaging/amqp-postgres/files/usr/lib/systemd/system/cloudify-amqp-postgres.service

Without a restart delay, the service is restarted many times in a short time
if the database is down. Then, systemd's burst limiting kicks in, and it stops
restarting it.
Instead, let's wait after each restart, to give the db some time to actually start.
Then systemd will keep restarting amqp-postgres until it actually starts, and it
will never limit it, because it restarts slowly enough.

amqp-postgres service: set RestartSec=2

---

amqp-postgres/amqp_postgres/postgres_publisher.py
amqp-postgres/amqp_postgres/tests/test_amqp_postgres.py
rest-service/manager_rest/test/base_test.py

The batch `INSERT` can fail in case the execution was already deleted.
If this happens, the whole batch of logs/events used to be discarded.
This change makes it so that in that case, the batch is not discarded
anymore, but we retry inserting it - one event/log at a time, no batching
in this fallback case.
This case makes inserts slower in case of errors, but keeps them fast in
the common no-error case.

amqp-postgres: fallback to no batching in case of errors

---

amqp-postgres/amqp_postgres/postgres_publisher.py

I created a method to DRY things up and then forgot to use it
in one place >.>

amqp_postgres: use the helper method for inserting

---

workflows/dev-requirements.txt
workflows/setup.py

this solves the binary conflict that caused the build to fail, which was in that version

CY-471 : Updating pycopg2

---

rest-service/manager_rest/resource_manager.py

`running or queuedexecutions` → `running or queued executions` (added space)

Fix typo in error message

---

amqp-postgres/amqp_postgres/main.py
amqp-postgres/amqp_postgres/postgres_publisher.py
amqp-postgres/amqp_postgres/tests/test_amqp_postgres.py

Currently an error thrown in the db thread won't cause the whole
application to exit with code 1 (and be restarted by systemd).
Let's pass the error to the main thread and raise it there.

amqp_postgres: pass errors to the main thread

---

rest-service/setup.py

- Following the addition of cli to flask with click, we need to fix click's version for our own cli

click - Adding to dependency

---

rest-service/manager_rest/rest/resources_v3/tenants.py
rest-service/manager_rest/rest/responses_v3.py

So that listing tenants doesnt show the (encrypted) credentials

Use the tenant response with credentials only for the GET endpoint

---

rest-service/manager_rest/test/endpoints/test_executions.py
rest-service/manager_rest/test/mock_blueprint/empty_blueprint.yaml

- adding a test for installing an empty valid blueprint
- This was done because now you can import uploaded blueprints, so the full range of blueprints should be allowed

CY-728 : removing the restriction of required node templates in a blueprint

---

workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

don't `','.join` a string, that just messes it up

snapshot-restore: make "waiting for plugins" message readable

---

tests/integration_tests/resources/dsl/agent_tests/install_agent_from_plugin.yaml
tests/integration_tests_plugins/dockercompute/operations.py

* Don't override the create operation of the agents install lifecycle
* Add to the start operation the logic of installing agent from plugin

CY-764 Fix the integration test install_agent_from_plugin

---

resources/rest-service/cloudify/types/types.yaml

They are now also used on windows (since 4.4 new agents)

Update types.yaml note: heartbeats

---

rest-service/manager_rest/config.py

If not declared, restservice shows a warning

Declare the `public_ip` config field

---

tests/integration_tests/framework/docker_interface.py
tests/integration_tests/framework/wagon_build.py
tests/integration_tests/resources/dockerfiles/__init__.py
tests/integration_tests/tests/test_cases.py
tests/setup.py

These changes make it possible to test plugin changes on a manager.
See example in:
https://github.com/cloudify-incubator/cloudify-openstacksdk-plugin/tree/CY-800-OpenstackSDK-Integration-Testing
from there:
```python
pytest -s integration_testing/test_manager.py
```

Add Ability to Test Plugins on Manager w/ Wagon Build

---

rest-service/manager_rest/rest/resources_v3_1/agents.py
workflows/cloudify_system_workflows/snapshots/agents.py

* While restoring agents, it will create the agent record in the DB but
will not creare the rabbitmq user.
* Later in the restore we run the restore_amqp script and rabbitmq users
will be created.

CY-763 Add create_rabbitmq_user parameter to agents create

---

rest-service/manager_rest/dsl_functions.py
rest-service/manager_rest/test/endpoints/test_capabilities.py
rest-service/manager_rest/test/mock_blueprint/blueprint_with_capabilities.yaml
rest-service/manager_rest/test/mock_blueprint/blueprint_with_get_capability.yaml
rest-service/manager_rest/test/mock_blueprint/blueprint_with_nested_capability_bad_index_type.yaml
rest-service/manager_rest/test/mock_blueprint/blueprint_with_non_existent_nested_attr_of_capability.yaml
rest-service/manager_rest/test/mock_blueprint/blueprint_with_non_existent_nested_index_of_capability.yaml
rest-service/manager_rest/test/mock_blueprint/capability_chain_1.yaml

- This makes it behave similarly to get_attribute.
- Preserves old behavior.

CY-866 Add ability to get_capability to get nested property

---

rest-service/manager_rest/resolver_with_catalog_support.py
rest-service/manager_rest/test/endpoints/test_blueprints.py

Using the new api for receiving fully parsed blueprint from import

CY-642: updating the import blueprint api

---

rest-service/manager_rest/test/infrastructure/test_parse_with_resolver.py
rest-service/manager_rest/test/mock_blueprint/blueprint_with_2_layer_blueprint_import.yaml
rest-service/manager_rest/test/mock_blueprint/blueprint_with_blueprint_import.yaml

- Due to naming limitation of the host agent name

CY-642: changing the namespace delimiter

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v1/executions.py
rest-service/manager_rest/test/endpoints/test_executions.py

Resuming a failed/cancelled executions (needs to be done manually,
and is called a "force resume" as opposed to a regular automatic
"resume" which happens on mgmtworker restarts) resets the failed
operations to pending and sets their restart count to 0.

CY-821 Allow resuming failed/cancelled executions

---

workflows/cloudify_system_workflows/snapshots/snapshot_restore.py
workflows/cloudify_system_workflows/snapshots/utils.py

...not before, because that would create the token for the previous
admin user

Restore the admin token after restoring the admin user

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/workflow_executor.py

So that workflows can know if they are being resumed or run for the
first time

Add a 'resume' kwarg to the workflow context

---

rest-service/manager_rest/config.py

Use the same new way as in endpoint, to have a postgres array contains
operator (the @> operator)

Config loading: use the new array filtering method

---

.circleci/config.yml

This will free up many CI containers when working with PRs

CI: run old version unittests only on master

---

mgmtworker/mgmtworker/worker.py

No need to do that, they will be executed again by virtue of
using late-acks

Mgmtworker: don't resume executions on startup

---

rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_config.py

Also fix config tests to cope with the items already being in the
database

Unittests: keep config table in drop_db

---

rest-service/manager_rest/test/base_test.py

* Older versions clients don't know the 'site_name' param

CY-1253 Fix unit tests

---

rest-service/manager_rest/resource_manager.py
tests/integration_tests/resources/dsl/resumable_mgmtworker.yaml
tests/integration_tests/tests/agentless_tests/test_resume.py
tests/integration_tests_plugins/cloudmock/tasks.py

Tasks that are already retried don't need to be reset, because
there's a task retrying them that will run instead

reset_operations: don't reset retried tasks

---

rest-service/manager_rest/storage/storage_manager.py

* Regular join ignores records with null value in a FK column
* For example, in the deployments table we have a nullable FK - site_name.
When we get the deployments list the recordes with the null in site_name won't return.
* It happens only when we use this column name in _include, _sort or filters

Change the join of the get query to left outer join

---

rest-service/manager_rest/constants.py
rest-service/manager_rest/utils.py
tests/integration_tests/tests/agentless_tests/test_resume.py
tests/integration_tests/tests/test_cases.py

See commit messages.
This fixes the `KeyError: tasksgraph_list` error encountered when an operation
is retried, as a non-admin user

Resource authorization: fallback to resource_name permission 

---

rest-service/manager_rest/rest/resources_v3_1/deployments.py

* Throws an error when site_name = '' instead of ignoring it

Fix for site validation when creating a deployment

---

resources/rest-service/cloudify/types/types.yaml

- Due to that lifecycle related workflows are traveling on the nodes' relationships graph by order in their different operations, and cascaded workflow is run in parallel which is against the needed order of execution. So for all related lifecycle wf this is disabled

Cascading workflows - not cascading for lifecycle related wf

---

tests/integration_tests/tests/agentless_tests/test_subgraph_retries.py
tests/integration_tests/tests/agentless_tests/test_task_retries.py
tests/integration_tests/tests/agentless_tests/test_wf_api.py

[ci skip] because CI doesn't test integration tests

Tests: use config to set retries

---

tests/integration_tests/tests/agentless_tests/test_resume.py

Not name, getting a single name gets just that, we want the
whole workflows config...
[ci skip]

Integration tests: get config by just scope

---

tests/integration_tests/tests/agentless_tests/test_hooks.py

* Without the retry the test might fail if it ends before the hook of the
workflow_succeeded ran.

Fix test_multiple_hooks test by adding retry

---

cloudify_types/cloudify_types/component/component.py
cloudify_types/cloudify_types/component/tests/client_mock.py
cloudify_types/cloudify_types/component/tests/test_deployment.py
cloudify_types/cloudify_types/component/utils.py

When trying to upload already existing secrets with the same value, we should pass else fail

CY-1444: handling creation of existing secrets

---

amqp-postgres/amqp_postgres/postgres_publisher.py

After a batch, if an execution wasn't found, drop the fact that it
wasn't found from the cache, because it might well exist on the
next batch.

amqp-postgres: drop None cached executions after every batch

---

tests/integration_tests/tests/agentless_tests/test_events.py

This is a workaround for CY-1455, and must be reverted when that is
done.
CI isn't testing integration tests, so
[ci skip]

test_snapshots_events: wait for the db to finish upgrading

---

amqp-postgres/amqp_postgres/postgres_publisher.py
tests/integration_tests/tests/agentless_tests/test_events.py

This reverts #1504
We only use the TIMESTAMP WITHOUT TIME ZONE type, and those are not
affected by the timezone setting. However, the now() function is.
This means that when we used now() without the `AT TIME ZONE`
specifier, we inserted timestamps at local timezone in amqp-postgres,
however we did insert timestamps at utc in the restservice side, due
to #1493
The comment was wrong when it said that the "DB is changing": the
DB timezone setting doesn't affect neither inserts or selects from
TIMESTAMP WITHOUT TIME ZONE columns, it only affects the output of
the now() function (and it also affects TIMESTAMP WITH TIME ZONE
columns, but we don't use those).

amqp-postgres: insert timestamp at utc

---

tests/integration_tests/tests/agentless_tests/test_snapshot.py

Otherwise, we can get deadlocks randomly.
This is a temporary measure, it should be fixed properly as CY-1455

Integration tests: wait after starting snapshot-restore

---

tests/integration_tests/tests/agent_tests/test_events.py
tests/integration_tests/tests/agentless_tests/test_events.py

Log/event storing is async, so allow additional time for it to
happen.
Integration tests arent tested in ci, therefore...
[ci skip]

Events integration test: allow some time to store events [ci skip]

---

tests/integration_tests/resources/dsl/resumable_mgmtworker.yaml
tests/integration_tests/tests/agent_tests/test_resume.py
tests/integration_tests/tests/agentless_tests/test_events.py
tests/integration_tests/tests/agentless_tests/test_resume.py
tests/integration_tests/tests/agentless_tests/test_workflow.py
tests/integration_tests/tests/test_cases.py
tests/integration_tests_plugins/cloudmock/tasks.py

Tests that check that restart workflow runs both stop and start,
and also that it's resumable in both of these phases (the workflow
itself - the operations might well not be, but in the test, they are)

Add restart workflow integration tests

---

tests/integration_tests/tests/test_cases.py

Use `in` to match events by substring. This works for how it's used
in both the events tests and the resume tests
[ci skip]

Integration tests: wait_for_event match by substring

---

packaging/cloudify-rest-service.spec

No reason restservice would really _require_ nginx.
Having restservice but not nginx makes sense if it's a separate
restservice container.
Also, this change is specifically so that restservice can be installed
before nginx.

Restservice rpm: don't require nginx

---

rest-service/manager_rest/workflow_executor.py

It's not needed anymore because we'll be using the restservice
to query the tenants

CY-1043 Don't include rabbitmq credentials in workflow context

---

tests/integration_tests/tests/agent_tests/test_resume.py
tests/integration_tests_plugins/cloudmock/tasks.py

When the logs are parametrized and sent as an argument, the "starting
operation" event log contains the arguments, so the wait_for_event
actually only waits for that - start of the operation, instead of
for the actual event to be sent.
Instead, just hardcode the messages, it's clear enough and no real
reason to parametrize them anyway

Integration tests: agent resume tests - hardcode logs

---

tests/integration_tests/tests/agentless_tests/test_rest_service_pagination.py
tests/integration_tests/tests/agentless_tests/test_rest_service_sort.py

For sorting, installation is irrelevant, so don't do it.
By marking the wagon as requiring a platform different than the
manager (here: windows), the manager won't attempt to install it.
This also means the plugin-name-change mechanic (where we change the
plugin name from "x" to "installing-x" while it's being installed)
won't come into play, so this will prevent the test from failing
on an unexpected plugin name.

integration tests test_plugins_sort: don't install the plugins

---

rest-service/manager_rest/rest/resources_v1/status.py

If postgres or rabbitmq isn't there, return empty instead of
throwing an indexerror

Status: don't throw on missing services

---

resources/rest-service/cloudify/migrations/versions/62a8d746d13b_5_0_to_5_0_5.py
rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_deployment_updates.py
rest-service/manager_rest/test/endpoints/test_executions.py
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_misc.py

- Adding blueprint_id to Execution table
- Creating the migration script and adding the field
- Adding blueprint_id to relevant execution creation

CY-1539: keeping blueprint_id in executions list

---

rest-service/manager_rest/server.py

Add an empty value so that it doesn't break v1 and v2 clients
This has to be reverted after v1 and v2 are removed

ManagerExceptions: add server_traceback

---

rest-service/manager_rest/deployment_update/handlers.py
tests/integration_tests/tests/agentless_tests/test_depends_on_lifecycle_operation.py

The context used to be duplicated in task_kwargs.cloudify_context and
in task_kwargs.kwargs.__cloudify_context.
Now it's only the latter, so stop using the first one, which doesn't
exist anymore.

CY-1711 Accessing operations: use the right cloudify-context

---

rest-service/manager_rest/test/endpoints/test_deployment_updates.py

It uses a new attribute, execution.blueprint_id

Mark test_update_execution_attributes as api 3.1+

---

rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/resource_manager.py

Allowing again dep update wf to manage itself in regards to wf overlapping (which we prevent in the basic execute_wf), this is due to that plugins update needs to run multi-dep update wf.

Plugin update failure

---

rest-service/manager_rest/rest/resources_v3_1/status.py

If a service that is run by systemd is not up yet, it's in falied state and no need to use uninit data

status endpoint - fix services check

---

packaging/ip_setter/files/opt/cloudify/manager-ip-setter/manager-ip-setter.sh

IPSetter changes the certs, so nginx needs to be reloaded

IPSetter: reload nginx

---

packaging/ip_setter/files/opt/cloudify/manager-ip-setter/manager-ip-setter.sh

Reverts cloudify-cosmo/cloudify-manager#1953
We'll be moving the reload to `cfy_manager create-internal-certs` instead

Revert "IPSetter: reload nginx" - move to cfy_manager

---

rest-service/manager_rest/security/__init__.py

- In case of redonly setup of the manager, there is a need to access GET /brokers endpoint.
So this endpoint needs to allow readonly for that and that alone.

CY-1804: making brokers endpoint to support readonly setup

---

cloudify_types/cloudify_types/component/component.py
cloudify_types/cloudify_types/component/tests/test_blueprint_handling.py
cloudify_types/cloudify_types/component/tests/test_deployment.py
cloudify_types/cloudify_types/component/tests/test_execute.py
cloudify_types/cloudify_types/component/tests/test_polling.py

When we scale a Component with uploading a blueprint, one
Component will finish uploading it's blueprint with the same name and fail the others.
So when we catch the error, we will cont as usual.

CY-1752: fixing blueprint upload race cond

---

rest-service/manager_rest/constants.py
rest-service/manager_rest/utils.py
tests/integration_tests/tests/agentless_tests/test_license.py

* This check used to approve endpoints that included allowed endpoints.
For example, the 'status' endpoint is allowed, so this check approved
also the new (not merged yet) 'cluster-status' endpoint.

CY-1890 Fix allowed specific endpoints check in maintenance mode or with no license

---

rest-service/manager_rest/storage/storage_utils.py

Previously the status reporters would have a `user` role inside the default tenant (by mistake), now they have a single role which has very limited permissions.

CY-1731 Fix role assignment

---

rest-service/manager_rest/resource_manager.py
tests/integration_tests/tests/agentless_tests/test_runtime_functions.py

This makes it so that values are no longer rendered-in when
the deployment is updated

CY-2049 Correctly store runtime_only_functions on the deployment

---

rest-service/manager_rest/server.py

We're not using more than 1 connection per worker, so a pool
larger than 1 connection is just a waste of resources

CY-1988 Set sqlalchemy pool size to 1

---

tests/integration_tests/resources/scripts/reset_storage.py
workflows/cloudify_system_workflows/snapshots/postgres.py

Don't take the db_nodes table from the snapshot.

Keep db_nodes table when restoring a snapshot

---

rest-service/manager_rest/utils.py

* When the mgmtworker sends a request: host=172.17.0.2,
remote_addr=172.17.0.2 and the is_internal_request function passes.
* When nginx sends the internal auth request, host=cloudify-rest
so it used to fail.

CY-2125 Fix internal request check

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/workflow_executor.py

* We create a new execution token when we resumed execution.
* Before the resumed operation had the old token in the context
and the quthentication failed.
* Now we update the context of the operations with the new execution
token.

CY-2123 Update the execution token for resumed execution

---

tests/integration_tests/tests/agentless_tests/test_manager_status.py

- Adding some sleep for the rabbit service to come back up
- Reading all the log of the restservice, becasue we don't know when the check fails and the file is small

CY-2127: fixing rabbit down in manager status test

---

rest-service/manager_rest/cluster_status_manager.py

* When one manager is down, there is no updated status report,
so there is no info on it's services.
* Added defaults for this case when one manager is down and
there is no info on the rabbit or db services.

CY-2139 Fix cluster-status when one manager is down

---

mgmtworker/mgmtworker/worker.py

instead of attempting to access the tenant rabbitmq creds on the
workflow context - they aren't there in this task - use the api
endpoint via get_tenant()

CY-2141 kill-cancel handler: get tenant credentials from API

---

packaging/ip_setter/files/opt/cloudify/manager-ip-setter/manager-ip-setter.sh

Starting it makes a dependency loop with the ipsetter as well
(ipsetter runs before status-reporter, so when in the ipsetter script we
attempt to do this, status-reporter can't start, because ipsetter didn't exit yet,
because it's waiting for the status-reporter to restart)

CY-2222: no starting status reporter in ip-setter

---

rest-service/manager_rest/rest/resources_v3_1/operations.py

Allowing getting a single operation per id so that dispatch.py can
examine operation state to decide whether it's running a resume or not

CY-1959 Add GET /operations/id

---

tests/integration_tests/tests/agent_tests/test_agent_install_workflow.py

With installing plugins, it takes a bit more than 60 seconds

Install agent integration test: increase timeout

---

rest-service/manager_rest/cluster_status_manager.py

* There can be more replicas the master has than the
number of db nodes in our db_nodes table.
* A customer can have an extra node replicating
from the cluster. For example in geo repl use case.

Fix db cluster status check, allow more replicas

---

rest-service/manager_rest/rest/resources_v3_1/status.py
rest-service/manager_rest/security/__init__.py
rest-service/manager_rest/security/authentication.py
rest-service/manager_rest/security/secured_resource.py
rest-service/manager_rest/test/endpoints/test_status.py

* The SecuredResourceReadonlyMode decorator was created for a use case
when we have 2 Cloudify sites (geo-replication) and the standby manager
has only read access to the DB.
* We still wanted the cluster-status to work on the read-only one so
we created this decorator and it is currently in use only in
2 apis (/status and /brokers).
* This use case is not relevant anymore, therefore I remove all
occurrences of SecuredResourceReadonlyMode.

CY-2304 Remove SecuredResourceReadonlyMode decorator and use SecuredResource instead

---

packaging/cloudify-mgmtworker.spec

it now has py3-only modules in in
this can be reverted after mgmtworker is ported to py3

mgmtworker: don't break on bytecompile errors

---

README.md

Readme: remove landscape.io

---

packaging/mgmtworker/requirements.txt

Fabric is now an optional dependency, so let's install
it in the mgmtworker

CY-2534 Mgmtworker: install cloudify-agent with fabric

---

resources/rest-service/cloudify/types/types.yaml

An `external_resource` property is added to the schema definition of
`cloudify.datatypes.ComponentDeployment`.

CY-2468 Add deployment.external_resource property

---

amqp-postgres/test-requirements.txt

Similar to the restservice, we need the extra dependency in
amqp-postgres tests, because the tests use the same infra as
the restservice tests.
This dependency also pulls in networkx and pyyaml

amqp-postgres unittests: install common with extra dependencies

---

rest-service/manager_rest/rest/resources_v1/executions.py
rest-service/manager_rest/rest/resources_v2/executions.py
rest-service/manager_rest/rest/resources_v2/snapshots.py
rest-service/manager_rest/rest/resources_v2_1/deployment_update.py

verify_and_convert_bool has a isinstance(.., text_type) - while
data coming in from the request is indeed text (ie. unicode),
literals in our code aren't necessarily (bare strings in py2, being
bytes).
Instead, just pass bool literals. No reason to pass strings,
be it text or bytes.

CY-2609 verify_and_convert_bool: use bool literals

---

rest-service/manager_rest/storage/management_models.py

this is unicode, so use tempfile's unicode api, as opposed to the
default bytes api

write_ca_cert: cert contents is unicode

---

resources/rest-service/cloudify/types/types.yaml

The `abort_started` flag (default `False`) enables roll back of any
started deployment modifications.

CY-2314 Add abort_started param for scale workflow

---

packaging/cloudify-rest-service.spec

Use python3 to make the restservice virtualenv, so it'll use that
python to actually run it.
This also makes amqp-postgres run py3, because it's using the
same virtualenv as restservice

CY-2632 Run restservice on py3

---

rest-service/manager_rest/rest/resources_v2_1/deployment_update.py

no reason to have it there
doing .get on a multidict, if the item is a list, returns the first
value of that list, because that's what multidict does. That makes
`reinstall_list` only return the first item from it, and that breaks

deployment update: don't use multidict for request.json

---

tests/integration_tests/resources/dsl/deployment_update/modify_inputs/base/modify_inputs_base.yaml
tests/integration_tests/resources/dsl/deployment_update/modify_inputs/modification/modify_inputs_modification.yaml
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py

A test to verify if update and install steps are executed as they should be
during the update workflow.

CY-2688 Add test_modify_inputs_ops_order

---

resources/rest-service/cloudify/migrations/versions/7b883ec574ea_5_0_5_to_5_1.py
rest-service/manager_rest/storage/resource_models.py

So far there were hardly any constraints for plugins stored in database.
All validation was handled in Python code.
This patch adds a constraint (and an index as well) for `package_name`
and `package_version` in `plugins` table to be unique.

CY-2592 Add unique indexes to SQL database

---

packaging/ip_setter/files/opt/cloudify/manager-ip-setter/manager-ip-setter.sh

This is to work around a problem with very long instance names on openstack, which 'hostname -s'
then truncates. If it happens to truncate ending with a hyphen then we generate an invalid DNS
SAN in a cert.
It is set to cloudify in case a generated VM has another hostname set, so that we don't put the
original VM's name in the certs when IP setter runs.

Set hostname to cloudify in IP setter

---

rest-service/manager_rest/test/endpoints/test_plugins.py
rest-service/manager_rest/upload_manager.py

Recently added plugin's `title` field should by default be equal to `package_name`.

CY-2776 Make package_name a default plugin's title

---

packaging/cloudify-status-reporter.spec

As it now requires it, it has been failing on broker and DB which don't have it.

Make status reporter create cfyuser group

---

packaging/amqp-postgres/files/usr/lib/systemd/system/cloudify-amqp-postgres.service
packaging/mgmtworker/files/usr/lib/systemd/system/cloudify-mgmtworker.service

that way, they are stopped when rabbitmq is stopped

amqp-postgres & mgmtworker: don't require rabbitmq

---

packaging/cloudify-status-reporter.spec

It's now used by the manager install.

Add cfyuser user on status reporter install

---

packaging/cloudify-status-reporter.spec

Trying to add with the group already existing fails silently, thanks yum.

Don't fail to add cfyuser in status reporter

---

tests/Jenkinsfile

not used here, but it's going to be used on jenkins.
That part of the build is not under source control, unfortunately, but well, downloading
a jenkinsfile from source control needs to know which branch to use. And declaring the
branch param makes it appear in jenkins's UI.

integration-tests jenkinsfile: add a BRANCH param [ci skip]

---

mgmtworker/mgmtworker/worker.py
rest-service/manager_rest/workflow_executor.py
tests/integration_tests/conftest.py

kill-canceling has been broken for quite a while, but this fixes it.
Now that we have integration-tests that can actually be run, it was very easy to fix!
The relevant test is `integration_tests/tests/agentless_tests/test_resume.py -k test_resume_cancelled_resumable`

Add rest_host to the kill-cancel context

---

tests/integration_tests/conftest.py
tests/integration_tests/tests/agentless_tests/test_workflow.py

This is mostly just for development/working on the tests themselves.
Allows much faster iteration.

Allow running integration-tests on a pre-created container

---

rest-service/manager_rest/cluster_status_manager.py

Instead of using Prometheus `instance` label, let's use `host`.

Use host label to identify cluster nodes

---

tests/integration_tests_plugins/cloudmock/cloudmock/tasks.py

Add downloading a file to the resume test function, next to the
other things we do when running a resumable function.
This is because in the past, we noted how download resource doesn't
work after a resume (in some version of 4.x), so this is a regression
test.

CY-2276 Resume integration tests: download a resource

---

workflows/cloudify_system_workflows/snapshots/snapshot_restore.py
workflows/cloudify_system_workflows/snapshots/utils.py

It turned out during investigation that stage service restart was already done, but before stage DB migration, so I just moved it a bit further in the flow.
* Removed stage service restart just after stage files restore
* Added stage service restart just after rest service restart (which is after stage DB restore) to allow WidgetBackends table refresh

CY-3161 - Move stage service restart after DB restore to allow WidgetBackends table refresh

---

packaging/cloudify-mgmtworker.spec

This is where source plugins are going to be installed,
so this directory needs to exist

Add the mgmtworker/env/source_plugins dir [ci skip]

---

mgmtworker/mgmtworker/worker.py

When kill-cancelling, always bypass maintenance. Killing stuff
is as forceful as we can get, so we need to bypass everything.
And it's useful, because you mostly only kill things when trying
to recover a manager that is in an invalid state; and recovering
managers is what maintenance mode is for

Kill-cancel: bypass maintenance

---

resources/rest-service/cloudify/migrations/versions/387fcd049efb_5_0_5_to_5_1.py

it was added in the upgrade, needs to be dropped in the downgrade.
Whoops.

5.0.5 -> 5.1 migration downgrade: drop plugins_states [ci skip]

---

resources/rest-service/cloudify/migrations/versions/387fcd049efb_5_0_5_to_5_1.py
rest-service/manager_rest/storage/resource_models.py

People do have indexes for eg. ubuntu trusty + ubuntu precise that
don't differ by anything else.
And indeed, even we do have them in tests, eg. test_snapshots.py,
test_4_4_snapshot_restore_with_bad_plugin_fails

Plugins UNIQUE index: add distro_ver/distro_rel to the index

---

resources/rest-service/cloudify/migrations/versions/387fcd049efb_5_0_5_to_5_1.py

`default` is the python-side default, used when creating ORM
objects on the python side. In the migrations, we don't create
any ORM objects, so `default` is useless entirely there.
Instead, `server_default` is what makes sqlalchemy make an actual
default on the DB side:
```
keep_old_deployment_dependencies | boolean                     | not null default true
```

5.1 migration: keep_old_dependencies: use server_default

---

mgmtworker/mgmtworker/worker.py

Relying on systemd to restart when the connection is lost is
not enough:
it will restart us indeed, but only once the process really exits.
However, it might take a very long time for the process to exit,
because all the threads need to finish first.
Example: we start handling an operation that takes 2 hours,
and immediately we lose connection to rabbitmq. The process will
only be restarted once all its threads are done, so we will stay
up for 2 hours more, with no rabbitmq connection, and so no other
workflows will be handled during that time.
Instead, stop relying on external restarts, and reconnect immediately.
Just a `while True` is fine - sigint still stops us, and we don't
need any other stop conditions.
Also, preparing the config is retried as well, in case some new
rabbitmq …

CY-3237 Mgmtworker: retry connection

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v1/deployments.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_deployments.py
workflows/cloudify_system_workflows/deployment_environment.py

Deleting the deployment from inside the workflow means that
the execution is deleted (via cascade from deployment) while it is
still running.
Deleting executions that are running leads them to fail.
This means deleting deployments from inside delete-dep-env
is racy, because if it just happens to poll the execution state
(to see if it was cancelled) after it was already deleted, it's
going to get a 404 and break.
Instead, delete the deployment after the delete-dep-env workflow
has finished.

CY-3320 Delete deployment after deleting dep env

---

tests/integration_tests/tests/agent_tests/test_agent_install_workflow.py

we are going to be asserting on queues/exchanges after uninstalling
the agent, so we must fetch the list of queues/exchanges after
uninstalling the agent.
We used to uninstall the agent, and then assert on the list of
exchanges that we fetched while the agent was still installed.
I think it was a pre-merge cleanup gone wrong.

test_amqp_queues_list: re-fetch queues/exchanges for assertions

---

rest-service/manager_rest/upload_manager.py

Instead of using file_server_root as a base directory for resource upload,
use a tempdir.  This way partially uploaded stuff will not interfere with
the Cloudify operation (Syncthing for example).

Upload stuff to temporary directory

---

rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/test/endpoints/test_storage_manager.py

In `_paginate`, make `get_all_results` just omit limit & offset.
Before, it was just doing nothing.
Also, the test was creating 1001 items, and then checking
that with `get_all_results` it returns 1000 (not all ie. 1001).
WHAT THE HELL.
Anyway, fixed the test, and also made it be 10 & 20 instead of 1001,
because inserting 1000 items via the storage managers takes on
the order of 10 seconds.

CY-3435 get_all_results: omit the limit/offset clauses

---

rest-service/manager_rest/storage/relationships.py
rest-service/manager_rest/storage/resource_models.py

When deleting a deployment, the DB itself must do the cascade to executions,
because doing it on the python side takes too long, and that times out the request.
(with enough executions, of course)
Also, refactor passing in the backref into relationships a bit, so that this level
of configurability is actually possible

CY-3420 Passive_deletes for executions

---

rest-service/manager_rest/workflow_executor.py

If the plugin needs to be installed, because the workflow function
comes from a plugin, we need to pass through _all_ the information
required to install it. Which also includes the source field, in case
it's a source plugin.

CY-3455 execute_workflow: also pass through plugin source

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v1/deployments.py
rest-service/manager_rest/storage/relationships.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/storage/storage_manager.py

Deleting deployments can lead to fetching an unbounded amount of
items - executions and node instances - to delete it ORM-side, and to
return them as part of the response.
Instead of deleting them ORM-side, delete them DB-side: we already
have the CASCADE set up on the DB side, we just need to say
passive_deletes so that sqlalchemy knows not to touch the
relationship.
Instead of returning the whole deployment object, with embedded
relationships, just return a mock object with just the id.
We can't avoid returning _something_ because the 4.6 CLI expects us
to return a dict.
We'll only do it for deployments, because this is the most affected
endpoint, and other endpoints aren't having problems in practice
(and this is a 4.6 fix, on an as-needed basis)

CY-3420 Lightweight deployments delete

---

rest-service/manager_rest/cluster_status_manager.py

Should be Healthy/Fail for nodes, not Active/Inactive.

CY-3253 Make cluster status return expected values

---

workflows/cloudify_system_workflows/deployment_environment.py

It should be under the replicated /opt/manager/resources/deployments

CY-3536 Move deployment workdir

---

rest-service/manager_rest/resource_manager.py

when running PATCH to update the delete-dep-env execution status,
which makes the deployment be actually deleted, that makes the
execution be deleted as well, and the request returns 500.
Instead, pre-render the execution to-be-returned ahead of time,
before we delete it.
It is a bit ugly to return a rendered dict from here, but we don't
really have a better way.
A long-term better way would be to not ad-hoc'ly get/render
attributes from the database in rendering, but only fetch them
once. But that's a framework-level question.

deployment delete: return a rendered execution object

---

rest-service/manager_rest/app_logging.py
rest-service/manager_rest/manager_exceptions.py
rest-service/manager_rest/security/authentication.py
rest-service/manager_rest/server.py

All kinds of bad auth can flood the logs with useless logs.
The big offender is the status checkers, as even the built-in one
generates one log every 15 seconds, and of course there can be
user-specific ones on top of that.
These logs are also useless for detecting attacks, as they don't
include any kind of identification with them (eg. an IP). Nginx logs
serve better for that.
Hide the auth logs by default, by making them debug-level.

CY-3539 Error logging: make auth error logs DEBUG

---

rest-service/manager_rest/rest/resources_v3_1/plugins.py

The field is optional, doesn't mean it'll be defaulted to none
or anything. It can still be missing. Use `.get` for it.

CY-3534 Plugin state update: 'error' is optional

---

rest-service/manager_rest/test/mocks.py

This replicates the back-compat change we did
in cloudify-cosmo/cloudify-common#562

REST unittests: allow 200 in delete

---

rest-service/manager_rest/shell/update_plugin_imports.py

In case a plugin is declared in a blueprint but not used in a plan,
just skip it.

CY-3577 cfy plugins update

---

tests/integration_tests/tests/agent_tests/test_plugin_update.py

If no changes are required, we now return NO_CHANGES_REQUIRED,
not SUCCESSFUL. So make the tests cope with that.

plugin update inte-tests: handle no-changes-required

---

workflows/cloudify_system_workflows/snapshots/snapshot_create.py

If snapshot creation fails, reraise so that we fail the execution.
As opposed to returning "Snapshot creation failed. Execution succeeded".

CY-3587 create_snapshot: fail the execution when snapshot fails

---

rest-service/manager_rest/deployment_update/step_extractor.py
rest-service/manager_rest/test/endpoints/test_deployment_update_step_extraction.py

Group members is a list, but there is no difference between a group
with members [a, b] and a group with members [b, a]. It is the same
group and should compare equal.

Dep-update: when comparing groups, ignore members ordering

---

rest-service/manager_rest/app_context.py
rest-service/manager_rest/test/infrastructure/test_parse_with_resolver.py

We can't just set the parser settings on the app, because that can
get persisted across requests, and then multiple requests will
wrongly use the same parser settings (eg. same plugin_mappings).
Instead, use a per-request variable.
It would be good to not use these context variables at all, but
just pass the arguments through instead, but for now...

RESTservice: use a request-local for the .parser_context

---

tests/integration_tests/tests/agent_tests/test_plugin_update.py

Next to testing that the right version of the plugin was used,
also fetch the plugins and assert on its stored state.

inte-tests: add plugin state checks to the plugin update tests

---

rest-service/manager_rest/config.py

We can have multiple brokers, so let's use a list for storing
their addresses.

CY-3615 Use lists for AMQP host/management host

---

tests/integration_tests/tests/agentless_tests/test_manager_status.py

2 seconds is not enough of a wait because dependent services might
need more time to start. For example, stop/starting rabbitmq will
also lead to its dependent services (amqp-postgres) to stop/start,
and that takes a bit longer than 2 seconds. It seems 5 seconds is
enough.

TestManagerStatus: increase service wait time

---

tests/setup.py

instead of providing the list of packages. The problem is, the
list of packages was provided wrong anyway, because it didn't
include sub-packages.

inte-tests setup.py: use find_packages

---

rest-service/manager_rest/config.py
rest-service/manager_rest/server.py

When creating a CloudifyFlaskApp, if load_config is False, then
disallow automatic loading from the db on access.
TBH maybe we should get rid of the automatic loading altogether.

Don't force loading the config from db

---

mgmtworker/mgmtworker/monitoring.py
mgmtworker/mgmtworker/worker.py
rest-service/manager_rest/cluster_status_manager.py

Not only Syncthing should be notified on changes to the manager nodes list,
but also a Cloudify Monitoring Service.  The latter one is going to rewrite
federated managers target list.

CY-3689 Update monitoring on manager addition/removal

---

mgmtworker/mgmtworker/worker.py

If the agent doesn't have a queue property, we want to just ignore
it (we can't do anything anyway) instead of dying.
This can happen for agents who weren't installed properly
(which, btw, is one of the reasons you might want to kill-cancel
in the first place)

RD-178 kill-cancel: cope with malformed agents

---

tests/integration_tests/tests/agent_tests/test_events.py

That function doesn't exist anymore.
Hardcode the username instead. It was effectively hardcoded before
anyway, just in that function instead.

inte-tests: don't import get_postgres_conf

---

rest-service/manager_rest/cluster_status_manager.py

Now a slightly different approach to filtering-out Prometheus
federated results should be taken.

Filter out non-local services from federated results

---

mgmtworker/mgmtworker/monitoring.py
mgmtworker/setup.py

Prometheus alerts parameter defining how long should alert be pending
is delivered from Prometheus `global.scrape_interval` parameter.  `for`
value is smaller of the two: 15s or `scrape_interval`.

RD-78 Derive Prometheus alerts `for` param from config

---

tests/integration_tests/tests/agent_tests/test_resume.py
tests/integration_tests_plugins/dockercompute/dockercompute/operations.py

Detaching from the parent process so that the agent is not
killed when the mgmtworker dies
Also, the ad-hoc detach in test_resume.py is now unnecessary

inte-tests: daemonize the script when installing an agent

---

workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

The request looking for plugin install executions, currently lists
all executions ever, which is way too expensive. Instead,
only look for install_plugin executions, and only fetch a few
columns from it, to reduce the response size even more

snap-res: narrow down the executions list request

---

rest-service/manager_rest/cluster_status_manager.py
rest-service/manager_rest/prometheus_client.py

Start using federated Prometheus data recorded on each manager node to
determine Cloudify cluster status.

RD-79 Get rid of remote Prometheus calls

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py

We would like to create a `PATCH /deployments/DEPLOYMENT_ID` endpoint to patch existing deployments. Currently, this endpoint will be used to patch the deployment's labels.

RD-476 Create PATCH deployment-id endpoint

---

rest-service/manager_rest/cluster_status_manager.py

With the recent transition to recording rules, status reporter can have
the same system service process reported more than once (because of the
`sum by` aggregation used in recording rules).  While this might be a
little bit controversial and could mean some mis-configuration, it is
perfectly safe to assume values `>= 1` mean process is running (just
as `== 1` indicated it when simple queries were used).

RD-544 Even more than one system service is fine

---

rest-service/manager_rest/storage/models_base.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/storage/storage_manager.py

When listing the existing deployments' labels' keys, we have a problem identifying in which tenant these deployments are.
This can be solved by declaring the labeled object's model (using the labeled_model attribute) in the different labels models and filtering the tenant using it.

Handling labels tenant

---

rest-service/manager_rest/rest/endpoint_mapper.py
rest-service/manager_rest/rest/resources_v3_1/__init__.py
rest-service/manager_rest/rest/resources_v3_1/labels.py

Implementing the `/labels/deployments/<key>` endpoint to list all values of a specific key in a tenant.

RD-479 list key values

---

tests/integration_tests/framework/constants.py
tests/integration_tests/framework/flask_utils.py
tests/integration_tests/resources/scripts/reset_storage.py

It's now db-based and not file-based and so this script must
work like that as well.
Persist permissions between tests because that's what we've always
done.

inte-tests: reset_storage.py: cope with the new permissions engine

---

resources/rest-service/cloudify/migrations/versions/5ce2b0cbb6f3_5_1_to_5_1_1.py
rest-service/manager_rest/storage/management_models.py
workflows/cloudify_system_workflows/snapshots/fix_snapshot_ssh_db.py
workflows/cloudify_system_workflows/snapshots/postgres.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

In snapshot-restore, keep the permissions table data around in a file, similar to what we do
with other config tables.
However for this one, only restore it if it's not in the snapshot. We do want to allow the user to keep their permissions :)

RD-599 Snapshot-restore support for permissions

---

rest-service/manager_rest/rest/resources_v3_1/plugins.py

We wrap everything with SQLStorageException. The logic is the same,
let's just use the right exception type.

Plugin state update: except the right exception type

---

resources/rest-service/cloudify/migrations/alembic.ini
resources/rest-service/cloudify/migrations/env.py
resources/rest-service/cloudify/migrations/versions/3483e421713d_rename_availability_to_visibility.py
resources/rest-service/cloudify/migrations/versions/387fcd049efb_5_0_5_to_5_1.py
resources/rest-service/cloudify/migrations/versions/406821843b55_add_role_column_to_users_tenants_table.py
resources/rest-service/cloudify/migrations/versions/423a1643f365_4_6_to_5_0.py
resources/rest-service/cloudify/migrations/versions/4dfd8797fdfa_4_2.py
resources/rest-service/cloudify/migrations/versions/62a8d746d13b_5_0_to_5_0_5.py
resources/rest-service/cloudify/migrations/versions/7aae863786af_add_role_column_groups_tenants_table.py

This allows using alembic directly, eg.:
```bash
cd /opt/manager/resources/cloudify/migrations/
/opt/manager/env/bin/alembic upgrade head
```
instead of having to go through flask-migrate.
Also, `alembic upgrade --sql head > file.sql` now works too!
The changes are about replacing ORM usage in the migrations, with
sql/expression-layer stuff instead, so eg. instead of `session.add(obj)`,
to insert things in the migration, we use `op.bulk_insert()` with a
list of dicts, etc.

RD-664 Allow using alembic directly to migrate

---

tests/integration_tests/tests/agent_tests/test_agent_install_from_plugin.py
tests/integration_tests/tests/agent_tests/test_list_agents.py

The fixture should be used to run tests that use dockercompute plugin.

Use fixture `allow_agent` in agent tests

---

resources/rest-service/cloudify/migrations/versions/387fcd049efb_5_0_5_to_5_1.py
resources/rest-service/cloudify/migrations/versions/62a8d746d13b_5_0_to_5_0_5.py

With modern versions of sqlalchemy, .where() takes one argument,
and that needs to be and'ed, not multiple arguments.

Downgrade migrations: use compatible .where() syntax

---

tests/integration_tests/conftest.py
tests/integration_tests/framework/constants.py
tests/integration_tests/framework/docker.py
tests/integration_tests/tests/agent_tests/test_usage_collector.py
tests/integration_tests/tests/agentless_tests/test_license.py
tests/integration_tests/tests/agentless_tests/test_usage_collector.py
tests/integration_tests/tests/usage_collector_base.py

This PR fixes the usage_collector integration tests by:
1. Disabling the `cron` jobs on the manager container. This way, the usage_collector cron jobs won't be activated during the tests. And besides, it doesn't make sense for a cron job to work during tests, it's better to activate the scripts manually. 
2. Changing the `customer_id`  in the container license to `MockCustomer`. Until now, if `test_license.py` ran before the usage_collector tests, the customer_id would have changed from `mock_customer` to `MockCustomer` as defined in the test's licenses. This is prevented by changing the `customer_id` in the container license to `MockCustomer`. Moreover, to keep the correct license on the container, we "reset" the license at the end of each license test. 
3. Cleaning the usage_collector …

RD-507 Fix usage collector integration tests

---

resources/rest-service/cloudify/migrations/versions/5ce2b0cbb6f3_5_1_to_5_1_1.py

When migrating the db on a machine that already has the auth.conf
file, load permissions from that file. And insert them.

RD-666 Load permissions from the file during migrations

---

jenkins/Jenkinsfile
rest-service/manager_rest/load_permissions.py

For loading your existing authorization.conf into the permissions
table on-demand.
Use by `/opt/manager/env/bin/python -m manager_rest.load_permissions`

Add a load_permissions script

---

tests/integration_tests/conftest.py
tests/integration_tests/framework/docker.py

It's useful to log the `docker run` call because then developers can
copy it and use it for running their containers manually,
with all the mounts formatted in. I do it all the time.
With pytest, this log is not going to be shown by default,
but you can `--log-cli-level=info` (or pytest.ini).

inte-tests: log `docker run` command

---

rest-service/manager_rest/update_rest_db_config.py

This is to be run by the user (or maybe we'll make it automatic?)
after upgrading a 5.1.0 to a 5.1.1, to rewrite cloudify-rest.conf
so that it has a list of DB servers instead of using HAproxy.
To run it, `/opt/manager/env/bin/python -m manager_rest.update_rest_db_config`

RD-681 Script to update restservice config after dropping haproxy

---

rest-service/manager_rest/rest/resources_v3_1/labels.py

This PR covers:
[RD-749](https://cloudifysource.atlassian.net/browse/RD-749): Sort returned keys and values in alphabetical order.
[RD-750](https://cloudifysource.atlassian.net/browse/RD-750): Add the `_search` parameter to enable subset string search.

RD-750 Add search and sorting to labels

---

rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/rest_utils.py

Following a UI request, we would like to limit the labels' keys and values to a maximum length of 56 characters.

RD-748 Limit labels length

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/storage/storage_manager.py

At the end of any execution that ended in status `canceled`, `failed`, or `terminated`, the manager goes through the inter_deployment_dependencies table and evaluates each target_deployment_func to a deployment ID, and the corresponding deployment is being retrieved from the DB. The error occurs when this deployment doesn’t exist in the DB, either because it was deleted or because it wasn’t created yet. 
To solve this issue, this PR:
1. Fails silently in case the relevant deployment doesn't exist. 
2. Updates the inter deployment dependencies only when the execution ended in state `terminated`. 
Moreover, this PR adds a logging message to `storage_manager.get()` in case `fail_silently=True`. This way we will know if an element was supposed to be retrieved from the DB.

RD-827 Fix delete deployment with component fails

---

rest-service/setup.py
workflows/setup.py

Older versions than 3.2 are raising dependabot security alerts.

RD-1049 Update cryptography

---

amqp-postgres/test-requirements.txt
rest-service/dev-requirements.txt
rest-service/manager_rest/rest/endpoint_mapper.py
rest-service/manager_rest/rest/resources_v3_1/__init__.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/resources_v3_1/filters.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/storage/filters.py
rest-service/manager_rest/storage/models.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_filters.py

This PR:
1. Creates a `/filters` endpoint (RD-696). [This is the complement PR is cloudify-manager-install](https://github.com/cloudify-cosmo/cloudify-manager-install/pull/1046).
2. Creates the `GET /filters` endpoint to list all filters (RD-697).
3. Creates the `PUT /filters/<filter_id>` endpoint to create a new filter (RD-699).

RD-695 Create filters endpoint

---

workflows/setup.py

Include the whole package, because otherwise some subpackages
are missed (specifically, dsl_import_resolver)

workflow setup.py: include the whole package

---

workflows/setup.py

it should be `cloudify_system_workflows*` with the `*`, but it might as
well be just this too

setup.py: fix find_packages syntax

---

amqp-postgres/test-requirements.txt
rest-service/dev-requirements.txt
rest-service/manager_rest/rest/resources_v2/deployments.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/resources_v3_1/filters.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_deployments.py
rest-service/manager_rest/test/endpoints/test_filters.py

Adding filter rules to deployments list. 
Much of the code changes are related to passing the code from filters.py (API v3.1) to rest_utils.py so it can be used from deployments.py (API v2.0).
The complementary PR in cloudify-common is https://github.com/cloudify-cosmo/cloudify-common/pull/622

RD-694 Filters in deployments list

---

rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_version.py
rest-service/manager_rest/test/security/test_base.py

Parametrize TestClient to use the passed-in credentials, instead of
hardcoding admin credentials.
With this, `create_client_with_tenant` actually uses the provided username.

unittests: allow creating clients with different users

---

cloudify_types/cloudify_types/component/component.py

Retrieve a `workflow_parameters` from the Cloudify context and use it to
run executions from the Components.

RD-655 Use `workflow_parameters` in components

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/storage/resource_models.py

A fix in an algorithm that chooses which blueprints would be affected
by a plugin removal.  Deployments are not taken into considerations,
blueprint-plugins relationships are based on blueprint plans solely.
Also in case a plugin is used in any blueprint and hence should not be
removed, the list printed out as an error message contains valid
blueprint ids.

RD-653 Identify blueprints for a removed plugin

---

resources/rest-service/cloudify/migrations/versions/9d261e90b1f3_5_1_1_to_5_2.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

Given default blueprint and default inputs, create deployments 
while creating the deployment group

RD-1098 dep groups: create deployments from inputs

---

rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/plugins_update/constants.py
rest-service/manager_rest/plugins_update/manager.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v2_1/deployment_update.py
rest-service/manager_rest/rest/resources_v3_1/plugins.py
rest-service/manager_rest/test/endpoints/test_plugins_updates.py
workflows/cloudify_system_workflows/plugins.py
workflows/cloudify_system_workflows/tests/test_plugins.py

The `force` parameter is used to force plugin update on blueprints used (also) as components.

RD-872 Allow --force plugins update in components

---

rest-service/manager_rest/rest/resources_v2/deployments.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/resources_v3_1/executions.py
rest-service/manager_rest/storage/resource_models.py

It must be unfortunately separate because `@create_filters` has
no way to figure out the sql necessary for this.
This is the way to filter by a many-to-many. With the any.

RD-1121 Deployment list: filter by group id

---

rest-service/manager_rest/rest/rest_decorators.py

hasattr eats the underlying exception if one is thrown when
computing .response_fields
This way doesn't.
I do realize we're now not going to throw the `RuntimeError`, but
instead we'll just throw an AttributeError as is more proper anyway

marshal_with: don't hide ORM exceptions

---

tests/integration_tests/tests/agent_tests/test_plugin_workdir.py
tests/integration_tests/tests/agent_tests/test_plugins.py
tests/integration_tests_plugins/dockercompute/dockercompute/operations.py
tests/integration_tests_plugins/dockercompute/plugin.yaml

This PR added in order to fix integration tests that trying to install agent using plugin type with detach service
`cfyuser's homedir` was moved over to `/etc` because writing to `/opt` would require root access which we wanted to avoid.

RD-1179 Fix detach agent installation failed tests

---

mgmtworker/mgmtworker/monitoring.py

When deploying an alert about missing metrics for Prometheus a os.rename
function was used.  That sometimes resulted in an error in case both
source and destination were not on the same filesystem (OSError 18:
Invalid cross-device link).  Using shutil.move instaed of os.rename
fixes that.

CBYL-1094 Move files between filesystems with ease

---

resources/rest-service/cloudify/migrations/versions/9d261e90b1f3_5_1_1_to_5_2.py
rest-service/manager_rest/storage/resource_models.py

Used to be named deployment_group. This way is consistent with
other stuff.

Rename DeploymentGroups table to deployment_groups

---

rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/test/endpoints/test_deployments.py

As specified in the design doc, when listing deployments using filters, we need to specify how many deployments were filtered out of the total number of deployments. Auxiliary PRs:
https://github.com/cloudify-cosmo/cloudify-cli/pull/1194

RD-1191 Adding filters ratio

---

rest-service/manager_rest/rest/resources_v1/deployments.py
rest-service/manager_rest/rest/resources_v2/deployments.py

labels are defined in the Deployment table as a backref from the DeploymentLabel table and not as a column. So, putting labels in the _include parameter doesn't work. The solution for this is to get the whole Deployment element and let the _include parameter refine the returned results, according to the values specified in it.

RD-796 Adding deployments labels to include

---

cloudify_types/cloudify_types/component/component.py

Propagate workflow parameters across (sub)components only in case the
original workflow_id matches the workflow_id executed on a
(sub)component.

RD-1232 Parameters propagation in components fix

---

execution-scheduler/execution_scheduler/main.py

It is supposed to be `-`, not `_`, eg. https://github.com/cloudify-cosmo/cloudify-manager/blob/a5b68e05602e3b15aba688632bfff66a8cf2cbca/packaging/cloudify-rest-service.spec#L149

Fix typo in exec-scheduler log path

---

execution-scheduler/execution_scheduler/main.py
tests/integration_tests/conftest.py

This takes a column, not a string

Scheduler: use storage-manager filters correctly

---

tests/integration_tests/framework/amqp_events_printer.py

During integrations_tests we (sometimes) kill the container after the
test, thus events printer gets connection reset.  This patch prevents
unhandled exceptions from being thrown in that case.

RD-1337 Don't complain about lost stream in pytest

---

resources/rest-service/cloudify/migrations/versions/9d261e90b1f3_5_1_1_to_5_2.py
rest-service/manager_rest/storage/management_models.py

Might as well do that instead, no reason to cascade=DELETE.
This is more predictable, dropping a user doesn't silently sometimes
exit maintenance mode then

Make maintenance_mode.requested_by a cascade=SETNULL

---

resources/rest-service/cloudify/migrations/versions/9d261e90b1f3_5_1_1_to_5_2.py

The table is named execution_groups, so let's prefix the index
names with that, not execution_group (singular).
This makes `alembic revision --autogenerate` return empty

Rename execution_groups table indexes

---

rest-service/manager_rest/constants.py
rest-service/manager_rest/rest/filters_utils.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/resources_v3_1/labels.py
rest-service/manager_rest/test/endpoints/test_filters.py

After discussing with @qooban and Ofer, we understood that labels' keys and values should not be limited to 56 characters. This PR implements it.

RD-1313 Revert labels length limit

---

tests/integration_tests/tests/agentless_tests/test_execution_schedules.py

The test logic was faulty:
1 minute wait is not actually enough to guarantee a run of the execution because, e.g
* schedule created in 12:00:01 -> next occurrence is computed to 12:01:00
* check_schedules runs in 12:00:59 and the new schedule goes ignored b/c its next occurrence has not yet come
* check_schedules runs in 12:01:59, catches the next occurrence and runs the execution
so we need to wait a maximum of 2 minutes to ensure the test passes

RD-1204 Fix schedules integration test

---

rest-service/manager_rest/constants.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/test/endpoints/test_deployments.py

Label keys with the prefix `csys-` should be reserved for internal use. I.e. the user can only assign such labels if they have an implementation.

RD-982 Handling labels with csys prefix

---

rest-service/manager_rest/rest/resources_v1/blueprints.py

A 404 is a better "not found" message than a 500.

RD-1407 Return 404 on blueprint archive not found

---

amqp-postgres/test-requirements.txt
rest-service/dev-requirements.txt
rest-service/manager_rest/rest/endpoint_mapper.py
rest-service/manager_rest/rest/resources_v3_1/__init__.py
rest-service/manager_rest/rest/resources_v3_1/labels.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_labels.py
rest-service/manager_rest/test/mock_blueprint/blueprint_with_labels.yaml

This PR adds the endpoint `labels/blueprints`. Currently, blueprints' labels are only supported when supplied through the blueprint itself under `blueprint-labels`. 
The complementary PR for the rest client is https://github.com/cloudify-cosmo/cloudify-common/pull/663.

RD-1410 Add labels/blueprints endpoint

---

rest-service/manager_rest/shell/update_plugin_imports.py

* RD-1375 Improve blueprint_identifier readibility
Instead of using hyphen to join tenant and blueprint_id to printout some
statistics, we'll use '::'.
* nit: removed unused variable
* Workaround ill-formatted `imports:` entries
In case these entries had no indentation the script failed to identify
them.  Now it can work with ill-formatted YAMLs too.

RD-1375 More changes to the update_plugin_imports script

---

rest-service/manager_rest/config.py

This ports #2685 to 5.2.0:
Otherwise, the restservice will stay dead forever, if a DB node
is blackholing traffic.
I used 5 as the timeout because it seems good enough. You'd have
already thrown your holy hand grenade by 3.
Note that (as opposed to the requests in RESTClients), this is
both the connect+read timeout, there's no need to distinguish here.

RD-1429 Add a timeout to the patroni requests

---

rest-service/manager_rest/upload_manager.py

This is called in the last "blueprint state update" call of the
upload_blueprint workflow. This is so that, if the blueprint is
downloaded from a url, the restservice knows to unpack the
blueprint archive then.
So if the upload_blueprint workflow hits the node who _doesn't_ have
the blueprint (because it wasn't replicated yet due to replication
lag), it needs to hit the other node as well, to tell that one to
unpack the archive.

RD-1414 Throw NotFound if blueprint is not found in extract

---

rest-service/manager_rest/rest/resources_v3_1/__init__.py
rest-service/manager_rest/rest/resources_v3_1/nodes.py
rest-service/manager_rest/test/endpoints/test_nodes.py

Add an endpoint for batch-creating Nodes.
This is going to be useful for the "async deployment creation" track, where
we move creating nodes & node-instances out to a workflow. Then the workflow
of course needs a way to create those nodes.

RD-1450 Endpoint for creating Nodes

---

rest-service/manager_rest/shell/update_plugin_imports.py

* Open blueprints for correction in binary mode
Required for yaml.scan() to retrieve position of import strings
properly.
* Write encoded bytes (not string)

RD-1466 update_plugin_imports tweaks and fixes

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/blueprints.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/upload_manager.py

Rather than polling on blueprint state, wait on the execution instead.
Blueprint state can unfortunately change several times, but the
execution status is actually reliable.

RD-1506 Blueprint upload: wait for the execution

---

rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/test/endpoints/test_storage_manager.py

The flag needs to be set to false FIRST, otherwise ._safe_commit
will of course do nothing.

sm.transaction: make sure to actually commit

---

rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/rest/resources_v2_1/deployment_update.py
rest-service/manager_rest/rest/rest_utils.py

In some rare (?) cases there might exist deployments with invalid type
of inputs (e.g. '20' stored where input type should be integer).  This
patch adds functionality to attempt to automatically cast types of input
values to expected (a.k.a. inputs auto-correction).

CYBL-1107-Automatically fix inputs' types

---

rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/rest/resources_v2_1/deployment_update.py
rest-service/manager_rest/rest/rest_utils.py

In some rare (?) cases there might exist deployments with invalid type
of inputs (e.g. '20' stored where input type should be integer).  This
patch adds functionality to attempt to automatically cast types of input
values to expected (a.k.a. inputs auto-correction).

Inputs type casting functionality

---

rest-service/manager_rest/plugins_update/constants.py
rest-service/manager_rest/plugins_update/manager.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/plugins.py
rest-service/manager_rest/test/endpoints/test_plugins_updates.py
tests/integration_tests/tests/agent_tests/test_plugin_update.py
workflows/cloudify_system_workflows/plugins.py
workflows/cloudify_system_workflows/tests/test_plugins.py

--auto-correct-types flag issued with plugins update should be passed
down to the deployments update flows.

RD-1515 Add --auto-correct-types to plugins update

---

rest-service/manager_rest/test/endpoints/test_execution_schedules.py
rest-service/manager_rest/test/infrastructure/test_scheduling_rules.py
rest-service/manager_rest/utils.py
rest-service/setup.py
workflows/setup.py

This allows the user to specify complex weekday rules (via CLI or a blueprint), such as ''3mo, l-fr", which will evaluate to "run every 3rd Monday and last Friday of a month"

RD-1397 Allow schedules handle complex weekdays

---

rest-service/manager_rest/rest/resources_v3_1/deployments.py

'inputs' is used in `_add_group_deployments`, and is used in tests

dep-groups PUT: allow the "inputs" parameter

---

resources/rest-service/cloudify/migrations/versions/396303c07e35_5_2_5_3.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/upload_manager.py

- FK in the deployments table that points to the create-dep-env execution
- FK in the blueprints table that points to the upload-blueprint execution
Both are nullable so that snapshot-restore doesn't need any special treatment.
They'll just be null. (and old versions don't have an upload-blueprint
execution anyway)
`ondelete=SET NULL` means that when the execution is deleted, the FK is set to null.
`cascade='all, delete'` means that when the deployment is deleted (but only from the orm),
the execution is deleted as well.

RD-1506 + RD-1568 Add specialized execution FKs

---

resources/rest-service/cloudify/migrations/versions/396303c07e35_5_2_to_5_3.py
rest-service/manager_rest/constants.py
rest-service/manager_rest/manager_exceptions.py
rest-service/manager_rest/rest/endpoint_mapper.py
rest-service/manager_rest/rest/filters_utils.py
rest-service/manager_rest/rest/resources_v2/blueprints.py
rest-service/manager_rest/rest/resources_v2/deployments.py
rest-service/manager_rest/rest/resources_v3_1/__init__.py
rest-service/manager_rest/rest/resources_v3_1/filters.py
rest-service/manager_rest/storage/filters.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_deployments.py
rest-service/manager_rest/test/endpoints/test_filters.py
rest-service/manager_rest/utils.py

This PR modifies the filters value column to be of the following form:
```
[
{
key: <key>,
values: [<list of values>],
operator: <LabelsOperator> or <AttrsOperator>,
type: <label or attribute>
}
]
```
For this change to take place, some changes were made to the code: 
- Adding the `filtered_resource` column to the `filters` table. Since we introduce the ability to filter by a model's attributes, we need to determine which model is being filtered. This column was added to support this. 
- Changing the `equal` and `not_equal` operators to `any_of` and `not_any_of` respectively, based on some comments that were raised during the design of the feature. 
- Splitting the `/filters` endpoint to `/filters/blueprints` and `/filters/deployments`. This was done for the same reason specified in the …

RD-1519 Modify filters value column

---

rest-service/manager_rest/storage/filters.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/storage/storage_utils.py
rest-service/manager_rest/storage/utils.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_blueprints.py
rest-service/manager_rest/test/endpoints/test_filters.py

This PR implements the logic for filtering deployments and blueprints by allowed attributes, which are:
For blueprint: `created_by`. 
For deployments: `blueprint_id`, `created_by`, `site_name`.
Complementary PR https://github.com/cloudify-cosmo/cloudify-premium/pull/742

RD-1521 Implement attributes filter rules

---

rest-service/manager_rest/plugins_update/manager.py
rest-service/manager_rest/test/endpoints/test_plugins_updates.py
workflows/cloudify_system_workflows/plugins.py
workflows/cloudify_system_workflows/tests/test_plugins.py

* Easier to read temporary blueprint metadata
While updating plugins a temporary blueprint is created.  This patch
makes its `id` and `description` more descriptive, which will help to
find the original blueprint from which the copy was created.
* No RuntimeError on failed deployment update
Do not raise RuntimeError in case one of the deployments to update fails
to be updated.  Instead just send event/log and continue.
* Make manual update or continuation possible
In case there were deployments which failed to be updated during plugin
update flow, make the temporary blueprint visible and log the deployment
IDs for reference.
* Make a blueprint duplicate for updated deployments
If some of the updated deployments were successful and others were not,
let's make a copy of the original …

RD-1514 plugins update decoupling

---

resources/rest-service/cloudify/migrations/versions/396303c07e35_5_2_to_5_3.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_storage_manager.py
tests/integration_tests/resources/dsl/sleep_workflows.yaml
tests/integration_tests/tests/agentless_tests/test_deployment_statuses.py
tests/integration_tests/tests/agentless_tests/test_executions.py
tests/integration_tests/tests/test_cases.py

The objective behind this PR is to add support for multiple deployment statuses related to the following:
1. `latest_execution_status`: and this represent the latest execution workflow by translating the execution values to the following one:
- in_progres
- completed
- cancelled
- failed
2. `installation_status`: and this is mainly to check if the deployment status is active or inactive by checking the statuses of node instances associated with the deployment
3. `deployment_status`: and this represent the overall status based on the the values generated by `latest_execution_status` &&   `installation_status`
later  on we are going to expose sub_services and sub_environments statuses so that we can get a full picture of whats going on

RD-1480 Expose latest execution state for deployment

---

rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/plugins_update/manager.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v2_1/deployment_update.py
rest-service/manager_rest/test/endpoints/test_plugins_updates.py
workflows/cloudify_system_workflows/plugins.py
workflows/cloudify_system_workflows/tests/test_plugins.py

The purpose of this modification is to provide the administrator with a tool to reconcile the statuses of deployment updates according to statuses of relevant executions.
The new `reevaluate_active_statuses` flag in the `DeploymentUpdateManager.stage_deployment_update()` will force reevaluation of active deployment-updates' statuses based on following scheme:
```
execution status | new plugins_update status
------------------+---------------------------
terminated       | successful
failed           | failed
cancelled        | failed
cancelling       | failed
force_cancelling | failed
kill_cancelling  | failed
```
requires: https://github.com/cloudify-cosmo/cloudify-common/pull/702

CYBL-1114 Reevaluate deployment update statuses

---

rest-service/manager_rest/shell/update_plugin_imports.py

* Get rid of unnecessary REPO parameter
* Allow to define EXACT_VERSION
If a plugin has the parameter `EXACT_VERSION` set, it's value will be
always used as a suggested plugin version.

RD-1637 Use EXACT_VERSION in update-plugin-imports script

---

amqp-postgres/test-requirements.txt
rest-service/dev-requirements.txt
rest-service/manager_rest/rest/endpoint_mapper.py
rest-service/manager_rest/rest/filters_utils.py
rest-service/manager_rest/rest/resources_v2/blueprints.py
rest-service/manager_rest/rest/resources_v2/deployments.py
rest-service/manager_rest/rest/resources_v3_1/__init__.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/resources_v3_1/searches.py
rest-service/manager_rest/rest/rest_decorators.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/storage/storage_manager.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_blueprints.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py
rest-service/manager_rest/test/endpoints/test_deployments.py
rest-service/manager_rest/test/endpoints/test_filters.py
rest-service/manager_rest/test/endpoints/test_searches.py

This PR adds the `POST /searches/<resource>` endpoint. The purpose of this endpoint is to use filter rules when listing deployments or blueprints. 
Complementary PRs:
https://github.com/cloudify-cosmo/cloudify-common/pull/701
https://github.com/cloudify-cosmo/cloudify-manager-install/pull/1087

RD-1520 Create post searches endpoint

---

rest-service/manager_rest/manager_exceptions.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py

In the synchronous deployment-create, if create-dep-env throws an error,
give it back to the user.
This is as opposed to just returning the deployment and acting as if
nothing is wrong.

RD-1648 Sync deployment creation: return errors

---

resources/rest-service/cloudify/migrations/versions/396303c07e35_5_2_to_5_3.py
rest-service/manager_rest/rest/resources_v3_1/executions.py
rest-service/manager_rest/storage/resource_models.py

This will be used in starting/queueing the groups, to mean how many
executions can run at the same time

RD-1640 Add exec_groups.concurrency

---

resources/rest-service/cloudify/migrations/versions/396303c07e35_5_2_to_5_3.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/operations.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_operations.py

Make the execution track its total and finished operation counts.
The operation endpoints deal with keeping that count up to date.

RD-1700 Add operation counts on the execution model

---

rest-service/manager_rest/storage/resource_models.py

The `labels` attribute in the `deployments` model is defined as a backref from the `labels` model. Therefore, there is no need to define it as a `declared_attr`.

Drop labels attribute from deployments model

---

rest-service/manager_rest/constants.py
rest-service/manager_rest/utils.py
tests/integration_tests/tests/agentless_tests/test_license.py

The UI needs to use the endpoint `GET /users/<user-name>?_get_data=true` before a valid license is uploaded. 
The current implementation that allows calling endpoints without a valid license, allows calling all methods of the endpoint. 
This PR modifies this implementation to allow only a specific method of an endpoint, so e.g. the user will be able to call `GET /users/<user-name>`, but won't be able to call `PUT /users/<user-name>` without a valid license.

RD-1106 Add get users to allowed endpoints

---

rest-service/manager_rest/rest/resources_v3_1/filters.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_filters.py

We need to modify the update filters command to support the update of attributes filter rules separately from labels filter rules. This way, the user will be able to update only labels filter rules or only attributes filter rules.

RD-1711 Modify filters update endpoint

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/executions.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

Actually use .concurrency for exec-groups.
Also a bugfix, in the first commit.

RD-1640 groups: execute up to the concurrency limit

---

rest-service/manager_rest/constants.py
rest-service/manager_rest/storage/filters.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_filters.py

Updating the filter rules' operators names to:
start_with → starts_with
end_with → ends_with
contain → contains
not_contain → not_contains
Complementary PR: https://github.com/cloudify-cosmo/cloudify-premium/pull/747

RD-1694 fix operators names

---

resources/rest-service/cloudify/migrations/versions/396303c07e35_5_2_to_5_3.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/storage/models.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_storage_manager.py

This PR is created in order to do the following:
1. Add sub statuses columns for both services and environments 
2. Add sub counters columns for both services and environments
3. Add support to check cyclic dependencies between deployment labels
4. Add support propagate deployment statuses in created graph
5. Add support to  propagate counters for deployment when add/remove node from grap

RD-1488 Adding statuses and counter to sub service and envs

---

rest-service/manager_rest/rest/filters_utils.py
rest-service/manager_rest/test/endpoints/test_filters.py

The currently implemented logic lowers all keys and values of a filter. This means that if a user is created with capital letters, applying the filter created_by=<capitalized user name> won’t work. This PR fixes it.
Complementary PR: https://github.com/cloudify-cosmo/cloudify-premium/pull/748

RD-1696 Fix capitalization for attributes filter rules

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/storage/resource_models.py

They used to be called via `._execute_system_workflow`, but this seems more correct

Use the regular executor for dep-env workflows

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v1/deployments.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/resources_v3_1/executions.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

Instead of starting all the create-dep-envs at the same time,
make an execution-group and put them in that. The create-dep-env
executions will then be run using the queueing mechanism.
To do that, there's a few refactors and some divorcing needed!
See each commit message. It does get tied all together at the
end, I promise.

RD-1359 Start group create-dep-envs in an exec-group

---

rest-service/manager_rest/manager_exceptions.py
rest-service/manager_rest/server.py

We would like to show the user in the CLI the string form of a filter rule in case of an error. In order to do this, we need to pass the invalid filter rule and error reason as attributes of the exception to the rest-client. The CLI, in turn, will modify these attributes into a nice error message for the user. 
Complementary PR: https://github.com/cloudify-cosmo/cloudify-common/pull/721

Handle invalid filters exception

---

rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/plugins_update/constants.py
rest-service/manager_rest/plugins_update/manager.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v2_1/deployment_update.py
rest-service/manager_rest/rest/resources_v3_1/plugins.py
rest-service/manager_rest/test/endpoints/test_plugins_updates.py
workflows/cloudify_system_workflows/plugins.py
workflows/cloudify_system_workflows/tests/test_plugins.py

* Use --force parameter to fill PluginsUpdate.forced
The --force parameter is going to mark PluginUpdate to be forcefully
updated (i.e. regardless of the fact that the blueprint is used to
create a component).
* Propagate --force parameter down to the plugins.update functions
* Fix plugins update tests

RD-872 Allow --force plugins update in components (#2586)

---

rest-service/manager_rest/test/endpoints/test_deployments.py
rest-service/manager_rest/test/mock_blueprint/blueprint_with_default_groups.yaml
workflows/cloudify_system_workflows/deployment_environment.py

In the blueprint, deployment_settings.default_groups is the list
of groups the deployment is going to belong to when created.

RD-1164 create-dep-env: join dep-groups declared in the DSL

---

rest-service/manager_rest/test/endpoints/test_filters.py

Instead of deleting the base filters tests class, let's just change the `__test__` attribute of it.

Modify filters tests

---

rest-service/manager_rest/rest/resources_v3_1/filters.py

The current permissions' names for filters endpoints are `filters_<operation>`, where the convention is `filter_<operation>`
Associated PR https://github.com/cloudify-cosmo/cloudify-manager-install/pull/1092

RD-1697 Modify filters commands permissions names

---

rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

Instead of `inputs` in the new-deployments list, allow `id`, `inputs`,
`labels`. The new deployment will be created from those, instead of
from just inputs.
Refactor the thing a bit so that it's split into separate methods.

RD-1655 dep-groups: create deployments: allow id, inputs

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v1/deployments.py
rest-service/manager_rest/storage/resource_models.py

similar to what we did for create, also split out creating the
delete-dep-env execution, from actually running it.

RD-1810 delete-dep-env: split out making the execution

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/test/endpoints/test_deployments.py
rest-service/manager_rest/test/mock_blueprint/blueprint_with_default_schedules.yaml
workflows/cloudify_system_workflows/deployment_environment.py

Move creating the schedules to the workflow, so that they don't need to be
created up-front, and so that their definitions can use intrinsic functions

RD-1603 Create schedules in create-dep-env

---

rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

Add and remove deployments to a group, based on another group.
This gives us the "clone group" feature, because you can just create a
group, and set its deployments to ones defined by another group.
Removing isn't something that was asked for, but why not.

RD-1196 Add/remove deployments given by a group

---

rest-service/manager_rest/storage/resource_models.py

Just declaring an association proxy allows using group IDs in filters,
eg. in the summary request.

RD-1416 group assoc proxies for deps & execs

---

rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_deployments.py
tests/integration_tests/resources/dsl/updated_blueprint_with_labels.yaml
tests/integration_tests/tests/agentless_tests/test_labels.py

During the deployment update, any label specified in the labels section of the new blueprint should be added to the deployment. No labels are deleted in the process. 
Associated PRs: 
https://github.com/cloudify-cosmo/cloudify-common/pull/732
https://github.com/cloudify-cosmo/cloudify-cli/pull/1255

RD-1534 Handle labels in deployment update

---

rest-service/manager_rest/storage/filters.py
rest-service/manager_rest/test/endpoints/test_filters.py

When trying to filter a list of resources first by a `created_by` filter rule and then by labels' filters, the process fails. This happens because SQLAlchemy can't determine how to add the labels' join. The error is e.g.: 
```
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'Join object on Join object on
deployments(139701398608192) and users(139701400069960)(139701286089224) and sites(139701398997368)' and
deployments_labels'; tables have more than one foreign key constraint relationship between them. 
Please specify the 'onclause' of this join explicitly.
```
To solve this, we do what the error message suggests, specify the `oncluase` of the labels' join explicitly. 
We also modify a unit test to test this use case.

RD-1832 Fix join failure in filters

---

resources/rest-service/cloudify/migrations/versions/396303c07e35_5_2_to_5_3.py
rest-service/manager_rest/manager_exceptions.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/base_test.py
rest-service/manager_rest/test/endpoints/test_deployment_labels_dependencies.py
rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py
rest-service/manager_rest/test/endpoints/test_storage_manager.py
workflows/cloudify_system_workflows/deployment_environment.py

This PR created in order to update the following:
1. Add support to attach deployment(services)/environments to deployment object
2. Add support to include new extra fields as part of the deployment response related to environments
3. Add support to update deployments count for sub-deployments (environments && services) in API response

Rd 1485 update deployment apis

---

resources/rest-service/cloudify/migrations/versions/396303c07e35_5_2_to_5_3.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/storage/models.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py
workflows/cloudify_system_workflows/deployment_environment.py

Labels for the groups: they are automatically applied to deployments
created by the group.
In the future, we'll also extend it to all deployments in the group, not just
_created by_ the group.

RD-1317 Labels for deployment-groups

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/storage/storage_manager.py

Fetch the queued executions under a lock, because otherwise they
can be started several times, if multiple workers at the same time
finish an execution and try to dequeue them.

Lock fetching queued executions

---

rest-service/manager_rest/storage/resource_models.py

It needs to _stay_ in resource_fields so that filters can
be applied to that.
But it needs to not be in response_fields, so that it's not part
of the response.

Execution: move execution_group_id to resource_fields

---

tests/integration_tests/conftest.py

we've made the external cert be signed (by default) by the "main"
CA (which is the internal CA), as opposed to self-signed.
This was because this was more friendly to the user, because now
they can just provide a single CA cert+key and have both certs signed
by that.
That change was in:
https://github.com/cloudify-cosmo/cloudify-manager-install/pull/1105/commits/b699a4edebb7bd8beac7b4064c707e4f758615af

inte-tests: use cloudify_internal_ca_cert.pem

---

rest-service/manager_rest/rest/resources_v3_1/deployments.py

The labels validation was done after the deployment was inserted into the DB.
This caused an issue where the deployment was created, even though invalid labels were provided.
The fix for this issue is to put the labels validation before the deployment creation.

RD-1909 Fix deployment creation with invalid labels

---

rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/test/endpoints/test_deployments.py

We should allow special characters in labels. The rules are: 
* A label key will support all alphanumeric basic chars (English only). No spaces, no special characters other than `-`, `.`, `_`.
* A label value may contain a single line of text, no newline, no tabs. It may start with any allowed character. Allowed characters will include all characters except quotes. The following are required: `-`,`_`, `.`, `’`.
* Labels should still be saved in lowercase. 
* Labels' keys and values are limited to 256 chars.

RD-1693 Allow special chars in labels

---

rest-service/manager_rest/rest/resources_v3_1/searches.py

`_include` did not appear in the `/searches` swagger, even though it is supported. 
@Gelio, FYI

Add _include to searches swagger

---

rest-service/manager_rest/storage/resource_models.py

This method used to access `self.execution` twice, in separate
transactions. This was then separate DB lookups, which could be
ordered differently. In other words,
`self.executions[:concurrency] + self.executions[concurrency:]` was
not necessarily the whole thing (it would often be all of them, because
postgres prefers sequential access, but not always).
This led to some executions being handled twice: they would get both
their status changed to queued, and be started. The start would then
throw the 401; and later they would be dequeued normally and succeed.
...and some executions would not be handled at all (because the
"twice" ones took their place) and would stay "pending" forever.
We could've added an `order by` to the collection, but a better
way is to just only fetch it once.

exec-group start: only fetch the executions list once

---

rest-service/setup.py
workflows/setup.py

In order to keep the same library version accross all repositories,
let's downgrade to cryptography==3.3.2 (which is the last version
compatible with Python 2.7).

RD-1902 Use cryptography 3.3.2

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/test/endpoints/test_executions.py

current_tenant needs to be set to the actual tenant object, not
to the proxy. If it's set to the proxy, then the proxy points to the
proxy, and the next attempt to access utils.current_tenant throws.

CYBL-1139 execute_queued_workflow: preserve current_tenant

---

resources/rest-service/cloudify/migrations/versions/396303c07e35_5_2_to_5_3.py
rest-service/manager_rest/storage/resource_models.py

Use `server_default` instead of `default` for Non empty counter deployment fields where it should be inserted 0 by default. However, on snapshot restore it failed to default `0` into already existing deployment rows which caused issue on snapshot restore from version < 5.3.0

RD-1943 Use server_default instead of default for deployments counters

---

resources/rest-service/cloudify/migrations/versions/396303c07e35_5_2_to_5_3.py
rest-service/manager_rest/constants.py
rest-service/manager_rest/rest/resources_v3_1/filters.py
rest-service/manager_rest/rest/resources_v3_1/labels.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_filters.py
rest-service/manager_rest/test/endpoints/test_labels.py

The system filters infrastructure follows these guidelines: 
- System filters will be defined in the DB using a boolean "flag" named `is_system_filter`. 
- System filters are `csys-` prefixed, and therefore a user won't be able to create a `csys-` prefixed filters.
- A user shouldn't be able to modify or delete a system filter.
I also changed in this PR the names of the constants `CFY_PREFIX` and `CFY_LABELS` to more accurate ones - `RESERVED_PREFIX` and `RESERVED_LABELS`.

RD-1868 System filters infrastructure

---

rest-service/manager_rest/storage/resource_models.py

Make the unique constraint for the latest_execution foreign key unique in the mode side to avoid and stop alembic from keep generating it every time there is a change on the model

RD-1956 Change unique constraint for latest execution foreign key

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/blueprints.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/rest_utils.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_deployment_labels_dependencies.py
rest-service/manager_rest/test/mock_blueprint/blueprint_with_invalid_parent_labels.yaml
rest-service/manager_rest/test/mock_blueprint/blueprint_with_valid_parent_labels.yaml

This PR created in order to handle the following:
1. Handle statuses propagation to upper deployments and update the overall deployment status based on sub-services and sub-environments
2. Add validation on the blueprint creation and deployment when reference invalid parent inside DSL
3. Add validation on delete/stop/uninstall/update when deployments has  sub-services and sub-environments
4. Update counter for deployment when one its sub-services and sub-environments get deleted

RD-1487 Handle statuses propagation and delete deployment

---

resources/rest-service/cloudify/migrations/versions/396303c07e35_5_2_to_5_3.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/executions.py
rest-service/manager_rest/storage/resource_models.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py
rest-service/manager_rest/workflow_executor.py

Rewrite .reset_operations a bit to make bulk actions easier,
and implement a resume for a whole execution group.
It will only resume the executions that are indeed cancelled/failed.
If there are any executions still running, they will be unaffected.

RD-1535 Resume an execution group

---

rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/manager_exceptions.py
rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/test/endpoints/test_deployment_labels_dependencies.py
rest-service/manager_rest/test/endpoints/test_deployment_updates.py
rest-service/manager_rest/test/mock_blueprint/blueprint_with_invalid_csys_environment_input.yaml
rest-service/manager_rest/test/mock_blueprint/blueprint_with_valid_csys_environment_input.yaml
rest-service/manager_rest/test/resources/deployment_update/depup_step/invalid_one_label.yaml
rest-service/manager_rest/test/resources/deployment_update/depup_step/one_csys_input.yaml
rest-service/manager_rest/test/resources/deployment_update/depup_step/one_label.yaml

This PR created in order to add automatic labels when using `csys-environment` inside blueprint inputs so that we can link between child and its parent without needing to add explicit labels

RD-1484 Add automatic label to children when using csys-environment input

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py
tests/integration_tests/conftest.py
tests/integration_tests/framework/utils.py
tests/integration_tests/tests/agentless_tests/component/test_component_cascading.py
tests/integration_tests/tests/agentless_tests/security/security_base.py
tests/integration_tests/tests/agentless_tests/test_deployment_workflows.py
tests/integration_tests/tests/agentless_tests/test_events.py
tests/integration_tests/tests/agentless_tests/test_executions.py
tests/integration_tests/tests/agentless_tests/test_labels.py
tests/integration_tests/tests/agentless_tests/test_resume.py
tests/integration_tests/tests/agentless_tests/test_secrets.py
tests/integration_tests/tests/agentless_tests/test_snapshot.py
workflows/cloudify_system_workflows/deployment_environment.py

Multiple, mostly unrelated fixes for integration tests.
Unfortunate that they're all in a single PR, but imagine waiting
for CI 18 times.
Most of them has to do with either:
1. using external ssl
2. the new queueing mechanism
3. async deployment create

several integration test fixes

---

rest-service/manager_rest/resource_manager.py

Fix issue when delete child deployment that still reference parent label values to deployment that no longer exist

RD-1989 Fix issue when delete child that its parent is no longer exist

---

rest-service/manager_rest/resource_manager.py

Re-calculate the deployment parent statuses after adding label parents to already installed children services or environment

RD-1991 Propagate installed child deployment to their parents

---

cloudify_types/setup.py

this is the same version as in cloudify-common.
Otherwise, we get a lot of version conflicts, eg. when running
the ctx executable in mgmtworker (`/opt/mgmtworker/env/bin/ctx`)

cloudify-types: bump requests version

---

rest-service/manager_rest/deployment_update/handlers.py
rest-service/manager_rest/rest/resources_v3_1/nodes.py

default to the empty list, not the empty dict
Also rename the variable in dep-up. It's obvious that it's not a dict
there, because we immediately do .append and .remove on it.
Also change the getattr default in dep-up: I think it's actually
never used for .plugins, but might be for plugins_to_install
This fixes the inte-tests in test_deployment_update_misc.py

node.plugins is a list, not a dict

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/test/endpoints/test_capabilities.py
rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py
tests/integration_tests/tests/agentless_tests/test_inter_deployment_dependencies.py
workflows/cloudify_system_workflows/deployment_environment.py

* Create inter deployment dependencies w/ deployment
Moving inter-deployment dependencies creation over to the deployment
environment creation.
* Add target_deployment_func in InterDeploymentDependencies.put
Until today the inter-deployment dependencies REST endpoint did not
handle target_deployment_func.  As we plan on using it instead of
a direct DB access when creating inter-deployment dependencies, it's
a must-have.
* Update test_deployment_creation_creates_dependencies endpoint test
* Get rid of inter-deployment dependencies creation in manager
* Add a comment (explaination)
Why not passing `target_deployment_func` in case a `target_deployment`
is provided.
* Fix integration test_dependencies_are_created
Adjust the test for the code changes in inter-deployment dependencies
creation. …

RD-1602 Async inter deployment dependencies

---

workflows/cloudify_system_workflows/snapshots/constants.py
workflows/cloudify_system_workflows/snapshots/populate_blueprint_statuses.py
workflows/cloudify_system_workflows/snapshots/snapshot_restore.py

This solves bugs related to blueprints restored from versions prior to 5.2 having no status

RD-2018 Update blueprint statuses in snapshot restore

---

resources/rest-service/cloudify/migrations/versions/b92770a7b6ca_5_3_to_6_0.py
rest-service/manager_rest/storage/resource_models.py

Plus make _execution_fk nullable with additional constraint that exactly
one of _execution_fk and _execution_group_fk must not be null for any
given record in these tables.

RD-1418 Add _execution_group_fk to logs and events tables

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py

passing labels here is incorrect, because they're not evaluated yet,
wrt. intrinsic functions. It is create-deployment-environment who
sets labels.

create_deployment: remove pointless `labels`

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/storage/storage_manager.py

For the dequeueing, and "same-deployment-first", we can avoid having
to do two (locking) queries, because we can just get the sorting done
in a single query.
Additionally, make sure we queue, if there are already queued executions
(FIFO semantics for executions).
See commit messages too.

RD-2046 Drop a query to avoid deadlocks

---

resources/rest-service/cloudify/migrations/versions/b92770a7b6ca_5_3_to_6_0.py
rest-service/manager_rest/rest/resources_v1/events.py
rest-service/manager_rest/storage/resource_models.py

Let's get rid of `events.id` and `logs.id` which were always empty anyway.

RD-1969 Get rid of events.id and logs.id columns

---

rest-service/manager_rest/resource_manager.py

in execute_workflow, make sure to refetch & reevaluate the deployment
and parameters.
This happens in the same transaction as checking if create-dep-env finished.
Otherwise, there's a race:
1. The deployment is fetched
2. We check if create-env finished (in check-for-active-executions)
3. Even if we reevaluated the params, without refetching the deployment,
the deployment might've been only updated after 1.
Also, check out the commit messages

RD-2056 Reevaluate parameters when starting executions

---

rest-service/manager_rest/deployment_update/manager.py
rest-service/manager_rest/storage/resource_models.py
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_misc.py
tests/integration_tests/tests/test_cases.py
workflows/cloudify_system_workflows/deployment_environment.py

For making the dep-update async so that it can be called for a
deployment group: I give up. It's not possible to refactor it enough
in this timeframe.
Instead, I'm going to cheat!
Add a new builtin workflow that just creates a deployment update.
THAT workflow can well be run for a group (as a bonus, it can be also
used for scheduling and whatever else).

RD-1816 Deployment update workflow

---

rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/test/endpoints/test_deployment_groups.py

Deduplicate the deployments to add first, by using a set, before adding labels.
This avoids adding the label multiple times to the same deployment, if it was
in multiple sources

add deployments to groups: only add labels once

---

workflows/cloudify_system_workflows/snapshots/postgres.py

This fixes the deadlock issue in snapshot restore.
Ported from https://github.com/cloudify-cosmo/cloudify-manager/pull/2933/commits/ea36f0777be0b1f52dfc7e604ea562cc2135b532

RD-2110 Lock tables explicitly up front

---

rest-service/manager_rest/dsl_functions.py
rest-service/manager_rest/test/endpoints/test_capabilities.py
rest-service/manager_rest/test/mock_blueprint/blueprint_with_group_capabilities.yaml
rest-service/manager_rest/test/mock_blueprint/blueprint_with_group_capabilities_2.yaml

This implements the storage logic for `get_group_capability`.
This is the logic part, AKA the interesting part, however it's
all mostly a single function anyway, with like fifty possible
modes of working.
Requires cloudify-cosmo/cloudify-common#752

RD-1165 Storage backend for get_group_capability

---

rest-service/manager_rest/resource_manager.py
rest-service/manager_rest/rest/resources_v3_1/deployments.py
rest-service/manager_rest/rest/rest_utils.py

The deployment update as part of create-dep-env must be locking,
so that concurrent changes are not lost.
See commit messages

Lock the deployment when updating its attributes

---

resources/rest-service/cloudify/migrations/versions/396303c07e35_5_2_to_5_3.py
resources/rest-service/cloudify/migrations/versions/b92770a7b6ca_5_3_to_6_0.py

Two separate fixups, see each separately.
This allows migrations to actually run in cases:
- upgrade 5.2→5.3, if the system already has labels (eg. a 5.2 snapshot with deployment labels)
- downgrade 6.0→5.3 if there exist execution group logs/events
This allows downgrading like `/opt/manager/env/bin/alembic downgrade 9d261e90b1f3` (that id = 5.2) to run, and afterwards, `alembic upgrade head`

Migrations: handle labels + group events
