rest-service/manager_rest/rest/rest_utils.py
Instead of the `sm.get` + `+=` + `sm.update`, use a single query that
does `UPDATE deps SET deps.count = deps.count + 1`.
No need for multiple queries then, and so no race conditions.
=> Use an `UPDATE` query for modifying sub-deployment counts

rest-service/manager_rest/constants.py
Requiring this makes its behaviour different from the status endpoint,
and breaks tests.
Also, since we replicate the license, if it's broken on one manager
then it's broken on all, and a LB allowing traffic will let a user
see that.
=> RD-2147 Don't require license for OK endpoint

tests/integration_tests/tests/agentless_tests/test_executions.py, tests/integration_tests/tests/agentless_tests/test_snapshot.py, tests/integration_tests/tests/test_cases.py, tests/integration_tests/tests/utils.py, workflows/cloudify_system_workflows/deployment_environment.py
The major change here is in the inter-deployment-dependencies creation: deployment contexts without an external client don't store a tenant_name
=> Rd 2230 fix integ tests 600

rest-service/manager_rest/rest/resources_v2_1/deployment_update.py
Dep-update unpacks and parses the new blueprint so that it can parse
the blueprint to figure out the differences.
However, it must also clean up, obviously!
Also, let's make it go under a subdirectory ('updated_blueprint')
in the deployment directory - that's way better than just removing
the deployment directory entirely: it could've been used for other
things as well.
=> CYBL-1156 Dep-update: cleanup the unpacked new blueprint

resources/rest-service/cloudify/migrations/versions/b92770a7b6ca_5_3_to_6_0.py, rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_deployment_groups.py
Additional template variables for the deployment ID template.
Note that `count` requires actually keeping a counter. So I add
a column.
The other two are trivial.
=> RD-2249 deployment id template: more variables

rest-service/manager_rest/rest/resources_v2_1/deployment_update.py
This ports #2973 to 5.2.2
Dep-update unpacks and parses the new blueprint so that it can parse
the blueprint to figure out the differences.
However, it must also clean up, obviously!
Also, let's make it go under a subdirectory ('updated_blueprint')
in the deployment directory - that's way better than just removing
the deployment directory entirely: it could've been used for other
things as well.
=> RD-2246 Dep-update: cleanup the unpacked new blueprint

workflows/cloudify_system_workflows/deployment_environment.py
`ctx.deployment.tenant_name` does not exist. This one does.
=> Dep-env: use ctx.tenant_name

rest-service/manager_rest/rest/resources_v3_1/executions.py
They're already finished, nothing more to do. Don't attempt to cancel
them because that's just a 400.
=> RD-2251 Exc-group cancel: skip already-finished executions

tests/integration_tests/resources/scripts/prepare_reset_storage.py, tests/integration_tests/resources/scripts/reset_storage.py
Just using one that was stored is not enough, because we re-create the
admin user, and so the token changes as well.
That is visible in the resume tests, where we do restart the mgmtworker.
=> reset_storage.py: regenerate admin token

tests/integration_tests/framework/flask_utils.py, tests/integration_tests/resources/scripts/prepare_reset_storage.py, tests/integration_tests/tests/constants.py
It has to be hardcoded somewhere, might as well be in the prepare
script, not in the separate json file.
Then, we dont need to copy the json file from host, we entirely
prepare it container-side.
=> Store the manager_config in the prepare script

rest-service/manager_rest/rest/resources_v3_1/deployments.py
Before, with `filter_rules=[]` we got a list of all deployments added to
the deployment group.  This patch fixes that.
=> RD-2263 Use `filter_rules` only in case it's not empty

packaging/cloudify-agents.spec
Drop ubuntu14 from agent.spec file so that we no need to ship it with the agent rpm
=> RD-2226 Drop ubuntu14 from agent spec file

packaging/cloudify-agents.spec
Drop ubuntu14 from agent.spec file so that we no need to ship it with the agent rpm
=> Rd 2226 drop ubuntu 14 522

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/test/endpoints/test_executions.py
Put as much as possible up front in a single transaction. 
This avoids a 500 in inte-tests when the db is cleaned before the
whole thing actually finishes, but it makes a lot easier to reason
about that function anyway, because the execution doesn't
need to be refetched multiple times.
=> update_execution_status: use a single transaction

rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/test/endpoints/test_deployment_groups.py
Same as the ID is templated, also template display_name.
Note that display_name will only be templated if it's passed in the
spec (no DSL support) and if it's just a string (no intrinsic
functions support)
=> RD-2287 dep-groups: also template display_name

rest-service/manager_rest/test/endpoints/test_searches.py
The searches unit tests failed on Jenkins with the following error 
```
AssertionError: {'id'[12805 chars] 'val1', 'created_at': '2021-05-11T11:19:52.75[393 chars]': 0} != {'id'[12805 chars] 'val2', 'created_at': '2021-05-11T11:19:52.75[393 chars]': 0}
```` 
I think this happens due to minor time changes. To solve this we can just assert the IDs are equal, instead of the whole object, and the test functionallity will stay the same.
=> Fix searches tests flakiness

resources/rest-service/cloudify/migrations/versions/b92770a7b6ca_5_3_to_6_0.py, rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/resources_v3_1/executions.py, rest-service/manager_rest/storage/relationships.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_deployment_groups.py
Add a way to save exec-group results.
Deployments for which the execution succeeded, are added to the
success target group.
Deployments for which the execution failed, are added to the failure
target group.
Also see the docstring for the rest-client in cloudify-cosmo/cloudify-common#768
We store this in 2 ways: when setting the target groups, to catch
executions that were already finished by then; and also in
update-execution-status, so that other executions are processed
as they finish.
=> RD-1419 Save exec-group results into dep-group

rest-service/setup.py
Werkzeug 2.0.0 (released on 11th May 2021) relies on typing.NoReturn
attribute.  It was introduced in Python 3.6.5 while the integration
tests run with Python 3.6.0:
```
created virtual environment CPython3.6.0.final.0-64
```
We might think about upgrading testing environment one day, but for the
time being this patch might just be good enough.
=> Don't upgrade to werkzeug 2.0.0 version

tests/integration_tests/tests/agentless_tests/test_executions.py
Similar to #3018 - waiting for executions to end.
With this, every test in test_executions.py, cleans up after itself,
ie. waits for all of its exeuctions to end.
Otherwise, those executions will be left running in the mgmtworker,
but cleaned up from the db, which will just result in 401s in the log,
when the mgmtworker tries to actually run them. Ugly.
(and no, we can't "clean" the mgmtworker, there's no way to do that)
=> tests_executions: add more wait-for-execution

tests/integration_tests/tests/agentless_tests/test_executions.py
This ports #3018 and #3019 to 6.0.0
we shouldn't leak that other execution we queued, otherwise we'll
be getting errors in the mgmtworker later. Wait for it to finish
properly - in several places.
=> test_queue_system_while_system: wait for executions

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/storage/models_base.py, tests/integration_tests/tests/agentless_tests/test_events.py
We store datetimes (specifically: execution.created_at) as timestamps
without tz. That is great.
However, when we send datetimes to the db, we send them WITH the
timestamp (which happens to be +0000). That doesn't fit.
Specifically, it breaks this comparison: https://github.com/cloudify-cosmo/cloudify-manager/blob/bfeeb857eac91d56d0af3c75df2f73e65e5cb8d1/rest-service/manager_rest/resource_manager.py#L1057
It compares the column (no tz) to the datetime in the query (with tz).
Postgres does this by converting the no-tz datetime into a with-tz
timestamp, using the db's currently set tz. That works well when the
db's tz is UTC, but breaks otherwise.
And indeed, in the events test, we set the db's tz to Asia/Jerusalem.
That just happens to be + from UTC, so in the queued test, execution2
might …
=> RD-2273 queued exec inte-tests: handle changed timezones

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/storage/models_base.py, tests/integration_tests/tests/agentless_tests/test_events.py
This ports #3027 to 6.0.0. See there for explanation.
=> RD-2273 queued exec inte-tests: handle changed timezones, 6.0.0

tests/integration_tests/framework/amqp_events_printer.py, workflows/cloudify_system_workflows/snapshots/snapshot_restore.py
Similar to pausing amqp-postgres, those db-using services must not
run while the db is being down/upgraded. The scheduler even more so,
because if it just happens to try and run something during that time,
oh boy is that going to break.
=> snapshot-restore: also pause the execution-scheduler

rest-service/manager_rest/deployment_update/manager.py
... because the workflow uses a new blueprint after all
=> RD-2316 First update a blueprint then run workflow using it

cloudify_types/setup.py, rest-service/setup.py, tests/setup.py, workflows/setup.py
There are different versions of some of the dependencies in other
repositories (cloudify-common, cloudify-agent, cloudify-cli).  This
patch upgrades those in cloudify-manager as well.
=> Pre-release fixes (dependencies and such)

tests/integration_tests/tests/agentless_tests/test_executions.py
this tests schedules 2 executions, waits for them to start, and
finishes. Instead, it must wait for them to end. If it doesn't, then
they might just start installing the plugin, the next test will see
"oh the plugin is being installed, ok", this already-finished test
will stop due to the db cleanup, all kinds of weird interactions.
Let's just avoid all of that.
=> inte-tests: wait for executions to finished in the 2-scheduled test

rest-service/manager_rest/storage/relationships.py, rest-service/manager_rest/storage/resource_models.py
It is already unique in the migrations: https://github.com/cloudify-cosmo/cloudify-manager/blob/177df8794b0caccb4ad3bcc549a997e923187b5e/resources/rest-service/cloudify/migrations/versions/396303c07e35_5_2_to_5_3.py#L282
Make the code reflect it as well.
With this, `alembic revision --autogenerate` will return empty.
=> dep.latest_execution: declare the column unique

rest-service/manager_rest/snapshot_utils.py, rest-service/manager_rest/test/infrastructure/test_snapshot_utils.py, workflows/cloudify_system_workflows/snapshots/populate_deployment_statuses.py
Instead of going all python-side, make a few sql queries that do the same.
This is way faster.
=> RD-2328 snap-res: populate deployment statuses via sql

resources/rest-service/cloudify/migrations/versions/a31cb9e704d3_6_0_to_6_1.py, rest-service/manager_rest/config.py
Some of the config schema values should will be declared more precisely as `integer` instead of just `number`.
This is the way to avid silly messages like `[retry 1/5.0]` instead of just `[retry 1/5]`.
=> RD-2350 Config schema numbers to integer

packaging/cloudify-rest-service.spec, packaging/rest-service/files/opt/manager/scripts/create_system_filters.py, resources/rest-service/cloudify/migrations/versions/b92770a7b6ca_5_3_to_6_0.py, workflows/cloudify_system_workflows/snapshots/constants.py, workflows/cloudify_system_workflows/snapshots/snapshot_restore.py
We would like to create default system filters that will allow the UI to filter environments and services easily. 
The first try was to just create them during the manager installation, but the created filters were gone after snapshot restore.  This PR fixes it.
The first idea for the fix was to create the system filters during the alembic upgrade. This doesn't work as `default_tenant` tenant and `admin` user are created only after the upgrade and are necessary for the creation of the filters. 
The second fix, that does work, is using a script for creating the system filters during installation, `cfy_manager upgrade`, and snapshot restore. 
This PR needs to be merged before its associated one, https://github.com/cloudify-cosmo/cloudify-manager-install/pull/1160, in order for its CI to …
=> RD-2248 Creating system filters during upgrade

rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/storage/storage_manager.py, rest-service/manager_rest/test/endpoints/test_deployment_labels_dependencies.py
Deployments cannot be sorted by `environment_type` because it is defined as a `property` and not as a `resource_field` of the table. 
This PR fixes it by defining `environment_type` as `hybrid_property`, which according to [this line](https://github.com/cloudify-cosmo/cloudify-manager/blob/master/rest-service/manager_rest/storage/models_base.py#L216) counts as a `resource_field`, and thus solves the issue.
=> WDR-35 Enable sorting by environment type

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/resources_v3_1/operations.py, rest-service/manager_rest/storage/resource_models.py
This makes the endpoint slightly faster, saving on the order of 3ms
per call (and one roundtrip, if the db is remote).
Instead of fetching-and-updating the execution operation counts,
use a sql UPDATE query. We never retrieve the former count, so
no need for locking.
Best see each commit separately
=> RD-523 Optimize the operation-update call

tests/integration_tests/resources/scripts/prepare_reset_storage.py
In inte-tests, we set the manager config to have 0 retries and 0
retry-interval; this saves some time on failing tests (don't want
to wait the default 15 minutes), but is too unrealistic. Actual
usage of the manager will of course always have some retries.
These settings try to be more realistic, while still being as fast
as possible.
=> inte-tests config: add some retries

cloudify_types/cloudify_types/component/component.py, rest-service/manager_rest/manager_exceptions.py, rest-service/manager_rest/rest/resources_v1/executions.py, rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/rest/resources_v3_1/executions.py, rest-service/manager_rest/rest/rest_decorators.py
The race with components+cancelling is that when we ask to cancel
an execution which contains components, we also cancel the running
component executions.
...but only running component executions!
However, if we cancel the main execution, and only afterwards the
currently running operation, starts the component execution, then
the newly-created execution is of course started and running.
To prevent that, we add the concept of endpoints that are unavailable
to be called from executions-that-are-being-cancelled.
In other words, if an execution has received a cancel request, it can
no longer do things like start new executions, or create deployments.
=> RD-2352 Don't start new executions from executions being cancelled

rest-service/manager_rest/storage/storage_manager.py, rest-service/manager_rest/test/endpoints/test_deployment_labels_dependencies.py
Default sorting fails when evaluating queries that use `GROUP BY`, such as `summary`. This is reverted in this PR.
**Nevertheless**, this also means that when sorting deployments bt `environment_type`, deployments with `environment_type=''` will be sorted arbitrarily. https://cloudifysource.atlassian.net/browse/RD-2389
=> Revert default sorting

tests/integration_tests/framework/docker.py
This makes the inte-tests containers a bit lighter, while
still having it run pretty much just as fast
=> inte-tests: limit the gunicorn worker count

rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/test/endpoints/test_deployment_groups.py
instead of only looking at the template from the request (spec),
also check the one in the dsl.
Remember that the display name can contain intrinsic functions,
and if it does, then we don't template anything.
=> RD-2411 dep-groups: use display-name template from dsl

rest-service/manager_rest/storage/filters.py, rest-service/manager_rest/test/endpoints/test_filters.py
The `is_not` and `is_null` filter operators didn't consider resources with no labels. This PR fixes it by using the resource table `_storage_id` column instead of the labels table `_labeled_model_fk` column.
=> RD-2416 Fix is_not and is_null filter operators

rest-service/manager_rest/resource_manager.py
If create-dep-env fails, the other executions for that deployment can't
run, so set them failed, because otherwise they're pending forever.
Actually, this does it in 3 (!) ways, to also catch other kinds of errors
as well.
=> RD-2414 Set executions to failed when they can't run

tests/integration_tests/tests/agentless_tests/test_task_retries.py
those tests assert on the amount of retries done, so they need
to set a known amount of retries beforehand
recently i've changed the amount in #3058 for all tests, and these
retry tests, still assume the previous amounts were in place
=> inte-tests: set subgraph_retries config in the retries test

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/test/endpoints/test_executions.py
If these checks fail, set the status to failed, and raise.
As opposed to leaving the execution in 'pending'.
Force commit there so that we can commit even though we raise.
=> Set execution status to FAILED if global/dependencies checks fail

rest-service/manager_rest/storage/resource_models.py
it's going to be useful.
The previous implementation of repr was just the base-class one,
which includes all of .get_identifier_dict (ie. the "primary key")
=> Execution repr: add workflow_id

tests/integration_tests/tests/agentless_tests/test_manager_status.py
Sometimes tests `test_status_*_inactive` would make Prometheus report a
particular service as inactive.  Its polling/scraping mechanism is not
designed to deal with a swift changes in the services' statuses, i.e. it
takes time to update them.
Restarting Prometheus forces it to re-scrape the statuses.
=> Force Prometheus re-scraping before testing status

tests/integration_tests/tests/agentless_tests/test_manager_status.py
Exporters are responsible for presenting Prometheus with services'
metrics.  We should make sure these metrics are up-to-date before
scraping them.
=> Restart exporters before re-scraping data

workflows/cloudify_system_workflows/snapshots/postgres.py, workflows/cloudify_system_workflows/snapshots/snapshot_restore.py
The snapshot can contain permission changes, so the restservice
must reload them.
Bumping updated_at is enough for it to know that the permissions
(and configs) need to be reloaded.
=> RD-2373 Reload permisisons after restoring a snapshot

rest-service/manager_rest/config.py, rest-service/manager_rest/plugins_update/manager.py, rest-service/manager_rest/security/authentication.py, rest-service/manager_rest/storage/management_models.py, rest-service/manager_rest/test/endpoints/test_deployments.py, rest-service/manager_rest/test/endpoints/test_execution_schedules.py, rest-service/manager_rest/test/endpoints/test_executions.py, rest-service/manager_rest/test/endpoints/test_operations.py, rest-service/manager_rest/test/endpoints/test_storage_manager.py, rest-service/manager_rest/test/mocks.py
there is never a reason to use the local time. Always use utc.
Otherwise we'll have problems comparing those datetimes, when one
is locally-generated, and another comes from a remote system, who
does use utc (eg. the ui)
Also, using local times is a good way to have your time-comparing
tests fail on non-utc machines.
=> replace datetime.now() calls with datetime.utcnow()

tests/integration_tests/tests/agentless_tests/test_runtime_functions.py
Without the runtime-eval flag, outputs are not re-evaluated.
=> CY-2152 Add a no-runtime-eval test

rest-service/manager_rest/resource_manager.py
In case a blueprint is being deleted with a `force` flag, don't worry
about its status.  Just delete it.
=> RD-2471 Force blueprint deletion regardless of state

workflows/cloudify_system_workflows/snapshots/postgres.py
We've added a before-request with a query from config&roles,
and of course that causes deadlocks in snapshots.
So lock them up front as well.
FWIW, this test repros it well:
```
integration_tests/tests/agentless_tests/test_snapshot.py -k test_snapshot_status_returns_correct_status
```
=> RD-2502 snap-res: lock more tables

rest-service/manager_rest/storage/resource_models.py
When sorting the deployments list by environment_type and applying a labels filter, SQLAlchemy throws an auto-correlation error. 
This happens because calling the same table twice (`FROM deployments_labels`) in the same query is not allowed unless you use an alias. This PR fixes this by adding an alias.
=> WDR-35 Fix sorting by environment_type with filter

rest-service/manager_rest/rest/resources_v2/deployments.py, rest-service/manager_rest/storage/storage_manager.py, rest-service/manager_rest/test/endpoints/test_deployments.py, rest-service/manager_rest/test/endpoints/test_storage_manager.py
This PR adds the functionality of searching on deployment id **_or_** deployment display name by simply making `OR` as the default operator for searches.
=> RD-2524 Use OR operator for search_name and search

rest-service/manager_rest/test/base_test.py, rest-service/manager_rest/upload_manager.py, workflows/cloudify_system_workflows/blueprint.py
The first commit explains it, so see there.
The second commit makes sure that the error gets propagated
to the user.
=> RD-2486 Throw an error if the blueprint dir already exists

rest-service/manager_rest/rest/rest_utils.py, tests/integration_tests/tests/agentless_tests/test_environments.py
1. Fix an actual race in `propagate_deployment_statuses`
2. Fix a tests-only race, by waiting for the update to finish
3. Now the retry isn't needed! (it wouldn't help 1 anyway)
=> RD-2532 Make test_environments less flaky

tests/integration_tests/framework/utils.py
The profile context path has changed between v5.2.2 and v5.2.3, so we should also change it in the integration tests.
=> Fix profile context in integration tests

packaging/cloudify-rest-service.spec
`cfy_manager upgrade` hangs when trying to upgrade the DB. This happens because it's waiting on locks that might be held by other services. This PR fixes it by stopping these services before the upgrade and starting them again afterward.
=> RD-2574 Fix hanging upgrade

tests/integration_tests/tests/agent_tests/test_events.py, tests/integration_tests/tests/agentless_tests/test_events.py, workflows/cloudify_system_workflows/snapshots/postgres.py
this sets to NOW(), but it needs to set in utc, because we use utc
everywhere, when using that column
=> snap-res refresh_roles: store timestamps in utc

rest-service/manager_rest/manager_exceptions.py, rest-service/manager_rest/rest/resources_v3/manager.py
Detect the error when LDAP server is not running and display correct message when user trying to set invalid or LDAP server that is not listening
=> RD-588 Update error message when ldap is not running

rest-service/manager_rest/rest/resources_v3_1/operations.py
When the SendNodeEvent task succeeds, insert the event. This means
that the task no longer needs to insert the event explicitly,
saving a request.
=> RD-2650 Automatically insert node-events on task success

rest-service/manager_rest/security/authentication.py
Only commit the transaction if we did any changes to the user:
we don't set login times and counters in requests authenticated
by an execution token.
Committing otherwise means that all objects fetched from the db
before (current execution, current tenant, and the user indeed)
will have to be re-fetched on next access
=> RD-522 Auth: only commit if the user actually changed

rest-service/manager_rest/rest/resources_v3_1/operations.py
The returned operation is unused anyway. Skipping the serialization
saves a few ms.
=> RD-2660 Operations update: return 204

rest-service/manager_rest/rest/resources_v3/events.py, rest-service/manager_rest/rest/resources_v3_1/operations.py, rest-service/manager_rest/rest/rest_decorators.py
See the docstring.
For now, only the most-heavily-used endpoints are going to use
this, and other endpoints can still benefit from auto-loading if
they so wish.
=> RD-2661 Detach current_execution/current_tenant from the session

rest-service/manager_rest/storage/resource_models.py
* Revert "RD-2655 Add Deployments' display_names when listing Nodes (#3127)"
This reverts commit 608ca9be9e847bff716314cb27f31ac2517cbace.
* Add REST field Node.deployment_display_name
This is a different approach, the one that actually allows for use of
`_include` and `_sort` query parameters.
=> RD-2655 Add REST field Node.deployment_display_name

rest-service/manager_rest/rest/resources_v1/events.py
Besides `deployment_id`, a `deployment_display_name` will be used in our
UI to make the widgets more user-friendly and readable.
This patch adds `Deployment.display_name` field as a part of the
Manager's response to the `GET /events` request.
=> RD-2686 Add deployment_display_name to events list

workflows/cloudify_system_workflows/snapshots/postgres.py, workflows/cloudify_system_workflows/snapshots/snapshot_restore.py
We must avoid having the db in a state in which we can't send in
requests. If we restore the dump first, and only then run the
restore-current-execution query, then in the time between those
two calls, requests can't be run. And since the events/logs are
a rest request now, any `ctx.logger` call between those two, will fail.
To avoid that, just restore the current execution in the same call
as restoring the dump.
=> snap-res: restore current execution by appending the dump

rest-service/manager_rest/rest/resources_v3_1/operations.py
operation.name is the task name eg `plugin.module.task`, while the
context one is the interface name eg `cloudify.interfaces.lifecycle.create`
inte-tests assert that we use the latter, so yeah, thats what it's
supposed to be
(eg `integration_tests/tests/agentless_tests/test_task_retries.py::TaskRetriesTest::test_operation_retry`)
=> operation events: use the context name for event.operation

tests/integration_tests/tests/agentless_tests/test_task_retries.py
currently this is what is sent in, not sending_task. I'm gonna say
that this is better anyway.
=> test-task-retries: expect a task_started event

rest-service/manager_rest/server.py, tests/integration_tests/resources/scripts/follow_events.py, workflows/cloudify_system_workflows/snapshots/postgres.py, workflows/cloudify_system_workflows/snapshots/snapshot_restore.py, workflows/cloudify_system_workflows/snapshots/utils.py
Spend as little time with the db/restservice in an unusable state, and
don't attempt to use it during that time.
See each commit for details.
=> snapshot-restore: avoid using the db when downgraded

rest-service/manager_rest/shell/update_plugin_imports.py
... beacause shutil.move works with different filesystems (and
os.rename doesn't)
=> CYBL-1191 Use shutil.move instead of os.rename in plugins update script

jenkins/build-pod.yaml
it seems we leak some connections. This isn't a fix, but a workaround,
hopefully we can fix the leak and then this can be reverted.
=> RD-2721 build-pod: increase the amount of connections to the test DB

rest-service/manager_rest/server.py
(This ports one commit from #3149 to 6.1.0)
the query doesn't care which one is first - config or roles, but
we always unconditionally lock the roles table in snap-res.
And if config is first, that's not locked by snap-res if the
snapshot is older than 4.6, and so there might be a deadlock between
this, and the snapshot itself
=> config last-updated query: change the order of the parts

rest-service/manager_rest/rest/resources_v3/events.py, rest-service/manager_rest/test/endpoints/test_events.py
For requests authenticated by the rest token, the execution id
must be passed in separately.
The other side of this is cloudify-cosmo/cloudify-common#829
=> RD-2751 events create: allow passing in execution id

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/test/base_test.py
This is as opposed to the previous implementation of the mgmtworker
sending hooks separately. Now, the restservice will send them when
the execution state changes.
It already used to do that on queued, but now it's more general.
=> RD-2751 Send hooks when execution state changes

tests/integration_tests/tests/agentless_tests/test_hooks.py
no need to use .load in these tests. safe_load is better and doesn't
cause warnings.
=> test_hooks: use yaml.safe_load

amqp-postgres/amqp_postgres/amqp_consumer.py
ever since cloudify-cosmo/cloudify-common#830 we don't send a hook
together with the actual event text message. The hook is sent
separately by the restservice, and the event text message is
created by the mgmtworker.
This led to the message being printed twice, once by the mgmtworker's
event, and once by the amqp-postgres catching the hook. So let's have
it not print the hook.
=> amqp-postgres: ignore hook messages

tests/integration_tests/tests/agentless_tests/test_task_retries.py
this mostly reverts the idea from #3147 because since
cloudify-cosmo/cloudify-common#831 we do send that event as well
=> test_operation_retry: expect sending_task

rest-service/manager_rest/rest/endpoint_mapper.py, rest-service/manager_rest/rest/filters_utils.py, rest-service/manager_rest/rest/resources_v3_1/__init__.py, rest-service/manager_rest/rest/resources_v3_1/searches.py, rest-service/manager_rest/storage/filters.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/storage/storage_manager.py
Very similar to already-existing searches, although node-instances have
no filters model (no stored filters) and no labels model (they don't have
labels). So existing infra must be made to be able to work without those.
=> RD-2746 Implement /searches for node-instances

workflows/cloudify_system_workflows/snapshots/agents.py
With enough node-instances, the .list call will break when passing the
list of ids in the URL. Instead, use the endpoint that goes by POST
=> RD-2746 snap-res agents: use the searches endpoint

rest-service/manager_rest/shell/common.py, rest-service/manager_rest/shell/substitute_import_lines.py, rest-service/setup.py
The `substitute_import_lines.py` script can be used to substitute
`imports:` lines in blueprints, prior to running `cfy plugins update`
on these blueprints.  It's somewhat similar to the
`update_plugin_imports.py` - it precedates actual plugins update
workflow.
=> RD-2758 Add a script to substitute import lines in blueprints

rest-service/manager_rest/resource_manager.py
When an execution is queued, that is usually because there's another
one for that deployment already running. We'll keep that running one
as the "latest", and the one that is queued, will become the
.latest_execution once it starts running.
I don't think there was a compelling reason to have a queued execution
be already the "latest", we just said "might as well", but the other
way around makes more sense. And if there's several executions
queued, why would any of them be latest and not the others?
Remember that the order in which several queued executions will
actually run, might not yet be known at the time of queueing them,
because they might belong to exec-groups, and the actual running
order will be influenced by that as well.
Anyway, the real reason for this change is that updating …
=> RD-2598 Don't set a queued execution as latest (yet)

rest-service/manager_rest/rest/resources_v1/events.py
No real reason to go by storage_id, which isn't technically guaranteed
to have any application-level meaning. I'm not sure this will fix the
inte-test which is only failing on jenkins, but it's a good idea to
do this anyway.
=> RD-2828 events list: default sort to timestamp

tests/integration_tests/tests/agentless_tests/test_runtime_functions.py
Use .update_with_existing_blueprints instead of .update
=> inte-tests: use the non-deprecated rest-client call

rest-service/manager_rest/rest/resources_v3_1/operations.py, tests/integration_tests/tests/agentless_tests/test_executions.py
Use the new format_event_message API introduced in cloudify-cosmo/cloudify-common#842
Also fix the dry-run test
=> RD-2891 Operation events: also store events for subgraphs

rest-service/manager_rest/rest/resources_v1/deployments.py, rest-service/manager_rest/rest/resources_v2/deployments.py
The orm now does return actual orm objects from this, not keyedtuples,
so this quip is unnecessary.
=> RD-2846 Drop useless .asdict calls

mgmtworker/mgmtworker/worker.py
This deals with workflows/executions, not with operations. It ends up
trying to fetch the operation, using the execution id instead (haha),
gets a 404, and carries on, assuming the operation isn't stored.
I mean, it's not an operation. Just don't do it. Override the
method to do nothing instead.
A better solution would probably be to not use a inheritance hierarchy
here (why is a workflow consumer a child of an operation consumer?)
but for now, this removes the 1-per-execution 404 call in the rest logs
=> mgmtworker workflow consumer: don't update operation state

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/resources_v2/executions.py, rest-service/manager_rest/storage/resource_models.py
Similar to #3168 but for executions. Then, `cfy exe li` is going to
be just one query to fetch executions, not 1+n.
I'm only linking it to that jira so that we can find this PR easily in
case we want to port 2773 into a 6.1.1 or something.
=> RD-2773 Autoload relationships when listing executions

rest-service/manager_rest/storage/resource_models.py
`@property` fields should be avoided in models, because they don't work
well witn `_include` - the orm has no idea what should it join, if all it sees
is an opaque property.
Instead, it could work with assoc_proxies, declared_attrs, and hybrid_properties
This changes deployment.latest_execution_status to be an assoc proxy
(note, we already have a field named the same in exec-schedules, and it is
a proxy there)
=> RD-2900 Allow using latest_exec_status in _include

rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_storage_manager.py
Not all of them just yet, but several interesting ones.
Replace `@property`, which can not be used in `_include` or `_sort`,
with ORM-instrumented descriptors instead, which can.
For the most part it'll be assoc_proxy, which also makes it shorter!
=> RD-2900 Replace `@property` in models with ORM attributes

rest-service/manager_rest/rest/resources_v1/deployments.py, rest-service/manager_rest/rest/resources_v3_1/deployments.py
If `?all_sub_deployments=false`, we will need `id`, so include it
automatically, if it's not included otherwise
=> RD-2916 deployments GET: automatically include `id` if needed

tests/integration_tests/tests/agent_tests/test_snapshots.py, workflows/cloudify_system_workflows/snapshots/postgres.py, workflows/cloudify_system_workflows/snapshots/snapshot_restore.py
The deadlocks are too much, man.
Just pause the restservice as well, and then, there's no concurrent
access.
Reading the db while it's being downgraded is a bad idea anyway.
=> RD-2913 snap-res: pause restservice as well

tests/integration_tests/tests/agentless_tests/component/test_component_auto_inc_suffix.py, tests/integration_tests/tests/agentless_tests/component/test_component_basics.py, tests/integration_tests/tests/agentless_tests/component/test_component_cascading.py, tests/integration_tests/tests/agentless_tests/shared_resource/test_relationship_running_workflow.py, tests/integration_tests/tests/agentless_tests/shared_resource/test_shared_resource_type.py, tests/integration_tests/tests/utils.py
Component tests like to leave executions running when they finish,
because there's still executions in the component deployments.
Let's make sure they all finish and don't interact with the framework
or other tests.
=> RD-2929 inte-tests: wait for all execs in component tests

tests/integration_tests/tests/agentless_tests/deployment_update/__init__.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_addition.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_misc.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_mixed_operations.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_removal.py
replace the dep-update-only wait_for_execution functions, with the
common base class wait_for_execution_to_end instead
also, instead of wait_for_successful_state, assert it synchronously,
there's no reason a wait would be needed there
=> inte-tests: dep-update tests - use common wait_for_exec

tests/integration_tests/tests/agentless_tests/deployment_update/__init__.py
this removes a bunch of deprecation warnings
=> dep-update inte-tests: s/node_id/id/

rest-service/manager_rest/deployment_update/manager.py
Capabilities is another attribute to be changed on the updated
deployment, and it's very trivial to do so, it was just missed before.
=> RD-2937 dep-update: also update capabilities

tests/integration_tests/resources/scripts/prepare_reset_storage.py
this is the default value, so reset-storage should reset it back to
the default value, not to something else
=> inte-tests: reset subgraph_retries to 0

workflows/cloudify_system_workflows/snapshots/credentials.py, workflows/cloudify_system_workflows/snapshots/snapshot_restore.py, workflows/cloudify_system_workflows/snapshots/utils.py
Instead of implicit rest calls via workflow-context, use explicit rest calls here.
Those workflow-context ones were broken ever since we've made it cache
the rest-client, and so the internal._switch_tenant stopped working.
Instead of fixing it, let's drop it entirely.
=> RD-2926 snap-res: avoid using deployments_contexts

tests/integration_tests/tests/utils.py
We used to schedule executions for the next minute from now, but
trimming seconds from the timestamp.  That resulted in executions being
scheduled in a few seconds (or milliseconds even).  This patch fixes
that.
=> RD-2961 Fix execution schedules in tests

workflows/cloudify_system_workflows/snapshots/fix_snapshot_ssh_db.py
That's what the backref is called. We used to have both, now we only
have .instances
Funnily, this was the only usage in c-manager, so I'm going to just
keep the one, then.
=> snap-res fix_db_ssh.py: s/.node_instances/.instances/

rest-service/manager_rest/amqp_manager.py, rest-service/manager_rest/rest/resources_v3_1/agents.py
In case `agent_create` request comes in with a `create_rabbitmq_user`
flag enabled, we attempt to create a separate RabbitMQ user for that
agent.  In case the account already existed, we would have overwritten
it thus breaking the tenant's or the manager's interaction with the
broker.  This patch prevents that from happening.
=> RD-2832 Don't overwrite the RabbitMQ user on agent_create

mgmtworker/mgmtworker/worker.py, rest-service/manager_rest/rest/resources_v3_1/operations.py
Old common expects a 200, not 204, from this endpoint
=> RD-2976 Compat with updating operation state for old plugins

resources/rest-service/cloudify/migrations/versions/03ad040e6f78_6_1_to_6.2.py
`creator_name` and `execution_id` can be set at the same time.
=> RD-3009 Update audit_log_creator_or_user_not_null constraint

workflows/cloudify_system_workflows/deployment_update/workflow.py
Just adding to the skeleton.
I'm going to organize this workflow in a graph, so that all the
potentially-expensive computations can be stored and resumed if
cancelled, and in the future also replaced by remote tasks,
so that they can be split between nodes.
After this, there's going to be a second graph as well, for all the
installation.
=> RD-3006 Create a dep-update object in the workflow

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/resources_v2_1/deployment_update.py, workflows/cloudify_system_workflows/deployment_update/workflow.py
Make a separate graph for the destructive operations, and in it,
create new nodes and node-instances.
For now, only adding nodes is implemented. Removing and modifications
will come later.
=> RD-3039 Make new nodes in the dep-update workflow

tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_removal.py
Those tests used to assert that nonexistent (removed) operations throw
an error, however now it's a no-op instead. So those tests must now
assert that nothing has changed instead (in this case:
runtime-properties, which would have been changed by those operations,
if they still existed)
=> RD-3077 dep-update inte-tests: cope with no-op executions

rest-service/manager_rest/manager_exceptions.py, rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/rest/rest_decorators.py, rest-service/manager_rest/rest/rest_utils.py
Allow changing deployment attributes, but only from a deployment-update.
The decorator will be useful for some other endpoint (nodes/node-instances patch)
=> RD-3087 Allow setting new attributes in deployment-update

rest-service/manager_rest/rest/resources_v1/nodes.py, rest-service/manager_rest/test/endpoints/test_nodes.py
Other than changing node-instance runtime-props, we can now also change
relationships too.
=> RD-3086 Allow updating relationships for node-instances

tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_addition.py
Same testcases (inherited), but a different implementation!
=> RD-3040 Run inte-tests with the new deployment-update workflow

packaging/rest-service/files/opt/manager/scripts/create_system_filters.py
The filter relies on blueprint's `obj-type` label having a value of
`k8s` (possibly among some others).
=> RD-2998 Create a `csys-k8s-filter` system filter

packaging/rest-service/files/opt/manager/scripts/create_system_filters.py
The filter relies on blueprint's `obj-type` label having a value of
`k8s` (possibly among some others).
=> RD-2998 Add csys-k8s-filter for blueprints

rest-service/manager_rest/shell/substitute_import_lines.py
... in case we're unable to determine `imports:` line position when
parsing a blueprint in substitute-import-lines scripts.
=> CYBL-1248 Handle invalid blueprint syntax

rest-service/manager_rest/storage/resource_models.py
A patch for Cloudify>=6.0
copied from https://github.com/cloudify-cosmo/cloudify-manager/pull/3246
=> RD-3156 Add upload_execution to Blueprint.response_fields

execution-scheduler/execution_scheduler/main.py, mgmtworker/mgmtworker/worker.py, rest-service/manager_rest/deployment_update/manager.py, rest-service/manager_rest/plugins_update/manager.py, rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/resources_v1/deployments.py, rest-service/manager_rest/rest/resources_v1/executions.py, rest-service/manager_rest/rest/resources_v2/snapshots.py, rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/rest/resources_v3_1/executions.py, rest-service/manager_rest/storage/models_base.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/storage/storage_manager.py, rest-service/manager_rest/test/base_test.py, rest-service/manager_rest/test/endpoints/test_deployment_groups.py, rest-service/manager_rest/test/endpoints/test_executions.py, rest-service/manager_rest/test/mocks.py, rest-service/manager_rest/upload_manager.py, rest-service/manager_rest/workflow_executor.py, tests/integration_tests/tests/agentless_tests/component/test_component_cascading.py
Make it cleaner what parts of starting an execution are under a
transaction, and what must not be.
This should do away with the deadlocks when starting/dequeueing
(note: I haven't touched update-dep-status just yet).
This is done by splitting rendering an execution, from actually sending
it. Rendering can be done on any execution, in a transaction, even if the
execution is not committed yet. Sending is sending.
Commit messages go into more depth on that.
=> RD-2965 + RD-3117 Refactor starting executions

rest-service/manager_rest/resource_manager.py
Old blueprints, like from a 4.5 snapshot, don't have this field
at all, and then the .get() returns None, and a None is not a good
target for a `x in None` check. Needs to default to something
that can be a container.
This fixes `integration_tests/tests/agentless_tests/test_snapshot.py::TestSnapshot::test_v_4_5_restore_snapshot_without_imported_blueprints`
=> RD-3121 delete_blueprint: handle blueprints w/o imports

tests/integration_tests/framework/docker.py
=> inte-tests: selinux compat for config mounting

rest-service/manager_rest/resource_manager.py
It's not quite started yet - it'll be started once it gets picked
up by the mgmtworker.
Also drop the additional .update(), it's not needed, because we commit
anyway - and it's not even all the attrs that changed (anymore)
(because now .render_message is what sets the new token)
=> RD-3221 execution resume: only set pending, not started

rest-service/manager_rest/resource_manager.py, workflows/cloudify_system_workflows/plugins.py
When the dep-upd inside of plug-upd times out, we'll continue on
to setting the plug-upd execution's state to FAILED, and we can't
just delete the temp blueprint! If the dep-upd started, deployments
might be using it!
First, set all deployments to use the original blueprint, instead.
If (by race) some deployments still use the temp one, then don't
delete it anyway, just un-hide it so that the user has a chance to
clean up.
=> RD-3235 Plugins update: don't delete deployments on timeout

rest-service/manager_rest/resource_manager.py
The temporary blueprint might well be missing, primarily in case
there were no changes to be made. In that case, let's not 500, but just
do nothingi nstead.
=> RD-3235 plugin-update: handle no .temp_blueprint

resources/rest-service/cloudify/migrations/versions/8e8314b1d848_6_2_to_6_3.py
I mean, the trigger depends on the function. Trying to drop the
function first just throws an error.
=> 6.3 migration: drop the trigger before dropping the function

cloudify_types/cloudify_types/component/operations.py, cloudify_types/cloudify_types/component/tests/client_mock.py, cloudify_types/cloudify_types/component/tests/test_deployment.py, cloudify_types/cloudify_types/component/utils.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_storage_manager.py
The main part is gating the create_deployment opreation behind
runtime properties (ie. check-and-set). This isn't 100% race-proof,
because we still can fail mid-request etc, but it makes any race
very low probability. (and in case it breaks, we'll just not create
the deployment, so it's not catastrophic, it just won't work until
the user cleans up the deployment)
Also some refactors.
=> RD-3183 Make component.create_deployment resumable

tests/integration_tests/tests/agentless_tests/test_concurrent_node_instance_update.py
It doesn't make sense to start 2 executions, but only wait for
one, and do the asserts while the other is still running.
Wait for both!
=> TestConcurrentUpdate: wait for both executions

cloudify_types/cloudify_types/component/operations.py
When the thing is deleted, we need to clean up, otherwise
they'll already be there on a reinstall :)
=> Component: clean the new runtime-props on delete

workflows/cloudify_system_workflows/deployment_update/workflow.py
Gotta handle no new-blueprint, because only the inputs might have
changed. In that case, use the old blueprint, and still update
the inputs.
=> RD-3108 new dep-update: update deployment inputs

tests/integration_tests/resources/scripts/reset_storage.py
Because we cannot rely on current_app existing in the context of
reset_storage script.
=> Initialize config.instance.logger explicitely

tests/integration_tests/conftest.py
This reverts commit cddebab74352a9f38eebb3211de7d0be83578d88.
=> Revert "Use a machine-specific docker image in integration tests"

rest-service/manager_rest/rest/resources_v1/executions.py, rest-service/manager_rest/workflow_executor.py
This will not run the execution. It will be used for snapshot restores.
=> RD-2871 Support setting state on new execution

rest-service/manager_rest/app_logging.py
We don't keep anything interesting in the form data anyway, we almost
always use json instead. (which is request.json() rather
than request.form)
However, accessing request.form (which we did for
_every single request_) breaks one important usecase: the fileserver
(and cloudify-api) auth endpoint.
For auth_request, nginx sends through all the headers, but not the
request body (because the internal auth request is a GET request).
That means the auth request gets a non-zero content-length but an
empty request body, and so accessing `request.form` waits forever
for the body. If content-type was application/json, then accessing
request.form would not wait, because in that case flask always just
returns empty for .form
=> restservice log_request: omit form data

tests/integration_tests/tests/agentless_tests/deployment_update/__init__.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_addition.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_misc.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_mixed_operations.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_removal.py
Put the _do_update in a single place, and have all of the test
classes import it.
Also, this adds tests for the mixed_operations one.
=> New dep-update inte-test: factor out a mixin

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/storage/storage_utils.py
Before touching multiple deployments as part of some update call
(most importantly, `update_execution_status), acquire a super-global
lock (super-global, ie. ALL restservice instances, on all nodes - it's
a db advisory lock).
This is a bit unfortunate and of course lowers throughput a bit (not
all that much, because well, those aren't the most-frequently-used
endpoints), but it's the nuclear option to make sure that deadlocks
don't happen. We can't lock deployments in different orders, if we
just lock the whole thing, right.
RD-3573 is going to implement smarter queries for dep-label-deps,
which is going to hopefully make this unnecessary, restoring our
throughput.
=> RD-3572 Lock deployments up-front

rest-service/manager_rest/server.py, rest-service/manager_rest/test/base_test.py
using the engine directly leaks connections (in the tests).
Use the session so that we use the already-open connection.
Without this, to run tests (especially with -n5), I needed to start
the db with `max_connections=BIGNUMBER`. With this, the default is fine,
and indeed even small numbers are fine.
I'm not sure why did we use the engine directly. But if we do want
to use the engine directly, then we'd have to explicitly handle
closing the connection. Instead, let's just use the session, allowing
sqlalchemy to do the connection lifecycle automatically
=> cope_with_db_failover: query via session, not via the engine

rest-service/manager_rest/rest/resources_v3/events.py
`timestamp` is actually passed in normally by the client.
`reported_timestamp` is the time of inserting into the db.
Is it named the wrong way around? Perhaps.
=> Events/logs: allow passing in timestamp

rest-service/manager_rest/rest/resources_v1/events.py, tests/integration_tests/resources/scripts/follow_events.py
I'm not sure why was it working before, but now we see fails in the
test_timestamp_range test, because the test does expect exclusive
at the upper end. Were we dropping the milliseconds bit from timestamps
before?
Anyway, the range is now going to be explicitly lower-inclusive,
upper-exclusive, same as eg. python's range() function.
=> Events list: make the timestamp range end-exclusive

rest-service/manager_rest/server.py
Now that we're using session management here, rollback after
running the query;  otherwise, if the first "pg_is_in_recovery()"
call failed (because a reconnection has occured), the next one might
fail as well due to an already-errored-out session. After the
query, roll it back, and start fresh.
=> cope_with_db_failover: rollback afterwards

rest-service/manager_rest/storage/resource_models.py
Add `deployment.display_name` and `deployment.creator.username` to the
message sent over to mgmtworker as the execution's context.  These
values are going to be available as `ctx.deployment.display_name` and
`ctx.deployment.creator`.
=> RD-3435 More deployment details in context

rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py
Note: this just implements the query, doesn't actually use it
yet - that'll come in the next PRs.
This is a way to retrieve a whole sub-tree of dependent
deployments, as opposed to the current approach, which
selects ALL THE DEPENDENCIES EVER and then formats them
into a tree.
There's a generic query on the InterDepDeps class itself,
and then a bunch of frontend interface methods on the
Deployment model.
=> RD-3573 Recursive query for dependency retrieval

rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py
This isn't used yet, but it will be (in the next PR, or one of them).
This adds a query that fetches all the data needed to recompute
a subtree: ie. given a deployment storage id, it will fetch details
required to compute that deployment's status(es), and those of
its parents, and those parents' parents, etc.
I'm keeping this query semi-private, because of how specific it
is, and not very useful for anything else than the one call site
(that it is yet to have).
It is a bit unfortunate that this writes the whole query from
scratch, rather than using the other methods, but I've tried,
and I haven't been able to do it in a way that made anything
cleaner.
=> RD-3573 Retrieve all data needed to recalc a tree

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/rest/rest_utils.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py
A single tree-traversing function to recalculate all statuses & counts
for parents of the given deployments.
This uses the `_get_update_tree` query from before, and it is not
yet used itself, but it will be!
=> RD-3573 Recalculate all ancestors sub-counts&statuses 

jenkins/Jenkinsfile, jenkins/build-pod.yaml, jenkins/rpm-pod.yaml, rest-service/setup.py
... because higher versions require libffi which is not available in our
CentOS builders
=> Pin cffi version to be lower than 1.15

tests/integration_tests/framework/utils.py, tests/integration_tests/tests/agent_tests/test_list_agents.py, tests/integration_tests/tests/agent_tests/test_plugin_update.py, tests/integration_tests/tests/agentless_tests/deployment_update/__init__.py, tests/integration_tests/tests/agentless_tests/multi_tenancy/test_list_tenant_filter.py, tests/integration_tests/tests/agentless_tests/multi_tenancy/test_tenants.py, tests/integration_tests/tests/agentless_tests/multi_tenancy/test_users.py, tests/integration_tests/tests/agentless_tests/security/test_file_server_access.py, tests/integration_tests/tests/agentless_tests/test_deployment_resource.py, tests/integration_tests/tests/agentless_tests/test_script_mapping.py, tests/integration_tests/tests/agentless_tests/test_snapshot.py, tests/integration_tests/tests/agentless_tests/test_workflow.py, tests/integration_tests/tests/test_cases.py
This ports #3295 to 6.2.1, dropping rest-service dependency in the
inte-tests.
=> RD-2996 Drop manager_rest dependency in integration tests (#3295)

workflows/cloudify_system_workflows/deployment_update/workflow.py
There's no real reason to compute this, but we used to pass that dict
to the custom workflows, so let's keep back-compat, at least for now.
=> RD-3523 New dep-upd: compute modified_entity_ids

rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_deployment_groups.py
No need to make a full deployment with a create-dep-env run on it
and everything. Those tests only care about exec-groups and
dep-groups, not about the deployment.
This speeds it up by about 90 seconds.
=> Speedup test_deployment_groups.py

rest-service/manager_rest/storage/resource_models.py
Fetching visibility/tenant_id like that didn't actually use the
declared relationship (the one with lazy=joined).
No, it used a separate join, and it actually emitted a cross join.
This is why the restservice starts using tens of gigabytes of ram at
some point.
To use the declared relationship, we have to use it explicitly,
like this.
=> RD-3680 Reduce memory usage when fetching labels

rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/storage/storage_manager.py, rest-service/manager_rest/test/endpoints/test_storage_manager.py
`sm.list(models.X, filters={'id': []})` should return no results,
because the filter-by list is empty.
However, currently it instead returns all entries, because
it takes it to mean "apply no filters".
Well that's silly. Let's fix it to mean the former.
=> RD-3681 sm.list: return empty, for empty filter lists

rest-service/manager_rest/test/base_test.py
We don't really want to set up external auth, even if premium
is installed, in these tests.
=> Mock out external auth in REST tests

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/storage/models.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_deployments.py
This seems correct! I won't bet my head on it, but I've also added
a couple tests to prove to myself that it is indeed correct :P
Add a method to check when are deployments allowed to be
uninstalled and deleted. Deployments are allowed to be
uninstalled/deleted when they have no children (that
aren't components) or dependents. You can only uninstall
components, if their main deployment is being uninstalled
as well. (then, component's uninstall + delete, is run as
part of the component node's delete operation)
Hopefully the docstring + tests make that clear to some
degree.
Also, note that I'm only checking direct dependencies here: no
need for the full tree, because if a deployment were to have
a tree of dependencies, it obviously also has some direct
dependencies as well, so that is …
=> RD-3689 delete deployment: fix the excluded-ids check

rest-service/manager_rest/resource_manager.py
Other csys- labels can contain things that SHOULD be mixed-case,
eg deployment ids :)
=> RD-3699 Only lowercase csys-obj-type, not other labels

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/test/endpoints/test_executions.py
Make sure that create-dep-env is dequeued before executions of
any other workflows that use that deployment.
The "only dequeue executions that belong to deployments who
have no active executions" check is just not enough.
Instead, only dequeue executions, who:
- are either create-dep-env (so their deployment will NOT possibly 
have any other executions running)
- belong to deployments that have:
- no other executions _running_
- no create-dep-env _queued_
That is to say, if a create-dep-env is even queued, then no other
executions for that deployment can possibly run.
Trying to run them would result in just an error, and indeed we
used to just throw an error.
=> RD-3703 Dequeue create-dep-env before other workflows

resources/rest-service/cloudify/migrations/versions/8e8314b1d848_6_2_to_6_3.py, rest-service/manager_rest/config.py, rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/storage/models.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_executions.py
Make sure to check non-active exec-groups, when dequeuing executions.
Otherwise, already-at-capacity groups could be all that's returned from
our query, and we'd dequeue nothing.
This is the reason we used to always de-generate to running, like, 5
executions at a time, tops, even if there were thousands queued.
With this change, we'll dequeue up to... well, up to the new setting.
By default it's 20, which is still quite a lot, but if you know you'll be
running very simple workflows, you might as well crank it up.
=> RD-3663 Dequeue more executions

rest-service/manager_rest/resource_manager.py
In case create-dep-env finished between:
- the time we checked for if we need to queue (and decided that we
don't, because create-dep-env finished)
- and the time we fetched the deployment (where it didn't have
workflows populated yet, because create-dep-env didnt finish yet)
then the execution would attempt to run, but won't be able to, because
we have an old version of the deployment fetched in memory.
Refresh it to get the workflows.
=> RD-3757 Refresh the deployment before starting an execution

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/test/endpoints/test_executions.py
This makes for different sorts in different processes, which - again -
leads to deadlocks. I mean, this isn't very necessary, let's just
get rid of this idea.
=> RD-3758 Drop the idea of dequeueing same-deployment first

rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_deployments.py
If external_source is set, there won't be a `self.deployment`,
so attempting to access `self.deployment.id` is futile.
In that case, format the message a bit differently.
=> RD-3761 check_deployment_delete: handle external source

jenkins/build-pod.yaml, rest-service/manager_rest/test/base_test.py
We don't want someone to run those tests on a real manager, and have
them wipe their db! Now that would be funny, but let's prevent it.
=> REST tests: rename the db to cloudify_test_db

resources/rest-service/cloudify/types/types.yaml
Under the cloudify.interfaces.monitoring interface. This seems to be
the most fitting interface.
=> RD-3674 Declare the check_status operation

resources/rest-service/cloudify/types/types.yaml
Product preferred that, and might as well, tbh.
=> RD-3674 Move check_status under the validation interface

rest-service/manager_rest/server.py
This should stabilise the DB failover tests.
=> Allow a little more time for DB failover

rest-service/manager_rest/test/infrastructure/base_list_test.py, rest-service/manager_rest/test/infrastructure/test_list_filters.py, rest-service/manager_rest/test/infrastructure/test_list_pagination.py
This speeds them up MASSIVELY, the whole directory used to be on the
order of 4 minutes, but it's on the order of 1 minute now.
The idea is, instead of creating actual real plugins etc, just to
test listing and filtering, only create the models directly.
=> Speed up: rewrite several infrastructure/ tests

rest-service/manager_rest/resource_manager.py, tests/integration_tests/resources/dsl/deployment_update/modify_idd/base/modify_idd_base.yaml, tests/integration_tests/resources/dsl/deployment_update/modify_idd/modification/modify_idd_modification.yaml, tests/integration_tests/resources/dsl/deployment_update/modify_idd/shared.yaml, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py, workflows/cloudify_system_workflows/idd.py
Let's not lose component/sharedresource IDDs in a dep-update.
Those aren't in the plan, so that means we can't just blindly
overwrite all the IDDs of a deployment with just the ones from
the new plan, we need to keep some as well.
This isn't perfect just yet, but RD-3903 will make it better, someday.
=> RD-3904 dep-update: keep non-plan IDDs

tests/integration_tests/resources/dsl/deployment_update/modify_inputs/base/modify_inputs_base.yaml, tests/integration_tests/resources/dsl/deployment_update/modify_inputs/modification/modify_inputs_modification.yaml, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py, workflows/cloudify_system_workflows/deployment_update/workflow.py
Make sure to keep new deployment.inputs correct: drop ones that
were removed, and add new ones (even if the old blueprint didnt
declare any)
=> RD-3909 dep-up: drop removed inputs

tests/integration_tests/tests/agent_tests/test_plugin_update.py
For right now, I don't know which way to solve it. I'll just mark
the test xfail, and figure it out later, in RD-3911.
(I think we'll end up just changing the asserts indeed. Or maybe
just plugin-update is going to force-install it, not dep-update itself)
=> RD-3911 Ignore test_plugin_update

resources/rest-service/cloudify/migrations/versions/8e8314b1d848_6_2_to_6_3.py, rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_storage_manager.py, tests/integration_tests/tests/agentless_tests/test_plugin_labels.py, workflows/cloudify_system_workflows/deployment_environment.py
A new column per deployment is added.  Values come from `blueprint.plan['resource_tags']`
=> RD-3908 Add `resource_tags` to deployments

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/rest_utils.py
1. A component should be the consumer of its creator deployment (by parent label) but not vice-versa! - i.e. a "component.*" type IDD shouldn't register a consumer.
2. Fixed skipping on existing consumer label to only skip if the existing label is for the same source AND target
3. Fixed shared resources not adding a consumer label by themselves (as opposed to by a "get_capability" IDD which may not necessarily exist)
=> RD-3890 Various fixes to consumer-id labels

rest-service/manager_rest/rest/resources_v2_1/deployment_update.py, tests/integration_tests/tests/agentless_tests/deployment_update/__init__.py
It used to be synchronous before, let's keep it this way for now.
This also allows me to revert the test to the previous state, in which
it didn't wait for previews.
=> RD-3887 Synchronous dep-update preview

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/resources_v2_1/maintenance_mode.py, tests/integration_tests/tests/agentless_tests/test_snapshot.py
No use dequeueing executions while we're in maintenance mode,
they'll just error out starting.
Instead, dequeue them when exiting maintenance mode.
=> RD-3727 Dequeue executions after exiting maint-mode

workflows/cloudify_system_workflows/deployment_update/workflow.py, workflows/cloudify_system_workflows/idd.py
cloudify-cosmo/cloudify-common#968 exposes all those methods on the
workflow context, so we don't need to use the restclient directly.
This will allow us to also use dep-update in local workflows as well.
=> RD-3859 dep-up: use workflow_ctx instead of rest-client

cloudify_types/cloudify_types/component/operations.py
This is better because we are setting `csys-obj-parent` label not only
in case there were no deployment labels already set.
=> Modify adding csys-obj-parent label on components

resources/rest-service/cloudify/types/types.yaml
Just declaring it is pretty simple, isn't it
This is going to be the operation that checks for "configuration drift",
ie. every node is going to examine it's actual state, and compare with
the declared state (ie. properties)
=> RD-3855 Declare the check_drift operation

resources/rest-service/cloudify/types/types.yaml
Like #3463 but for relationships.
Each relationship can also check its state and compare it to the
declared configuration. (eg. is a volume mounted at the declared
location, or somewhere else?)
=> RD-3855 Declare the check_drift operation for rels

rest-service/manager_rest/rest/resources_v3/secrets.py
Otherwise any user with `user` tenant role can modify secret's
ownership (`viewer` could not).
=> RD-3239 Check if user is allowed to set secret's ownership

rest-service/manager_rest/rest/rest_utils.py
Returning on empty dependencies_list _after_ the filtering
`if dep.target_deployment_func and not dep.external_target`
caused the function to ignore IDDs of `sharedresource` type if there are no IDDs of `get_capability` type - leading to a missing consumer labeling in such case
=> RD-3993 Don't return prematurely before labeling SR

cloudify_types/cloudify_types/shared_resource/operations.py, cloudify_types/cloudify_types/shared_resource/tests/test_shared_resource.py
We want to be extra-careful when auto-uninstalling a deployment. Added here:
1. A sanity-check that issues a warning if the source deployment (i.e. the consumer of the shared resource) is not labeled as a consumer in the shared resource
2. A try-except around the uninstall of the shared resource. If the uninstall is blocked (because the last labeled consumer which triggers an uninstall of the resource is not _actually_ the last deployment which depends on the resource), we get an 400 error. In such case - don't fail the uninstall of the consumer, but issue an appropriate warning.
Reasons for this to happen:
1. Consumer labels were manually tampered with (we will eventually block this option)
2. Another deployment uses the resource as get-capability, not as a shared resource
=> RD-3994 Don't fail on SR uninstall failure

amqp-postgres/amqp_postgres/main.py, amqp-postgres/amqp_postgres/tests/test_amqp_postgres.py, rest-service/manager_rest/config.py, rest-service/manager_rest/rest/resources_v3_1/agents.py, rest-service/manager_rest/test/base_test.py, rest-service/manager_rest/utils.py, rest-service/manager_rest/workflow_executor.py, tests/integration_tests/resources/scripts/reset_storage.py, workflows/cloudify_system_workflows/snapshots/restore_amqp.py
Instead of creating a long-lived tempfile, pass it to the amqp client
(and rabbitmq api client) as just a string with the contents.
There's quite a few places!
=> RD-3941 Pass the amqp cert's content

tests/integration_tests/resources/dsl/wait_after_fail.yaml, tests/integration_tests/tests/agentless_tests/test_executions.py, tests/integration_tests_plugins/cloudmock/cloudmock/tasks.py
Hopefully self-explanatory.
This replaces the removed test in cloudify-cosmo/cloudify-common#971
=> RD-4003 A test for wait_after_fail

rest-service/manager_rest/security/authentication.py
Turns out that since our sanity-check deployment authenticates on the default user, and it always runs at manager start,
we have always registered a "login" even if the manager was never actually used
=> RD-4011 Don't collect logins in sanity mode

tests/integration_tests/tests/agentless_tests/test_snapshot.py
`cfy_manager restart` no longer supports `--force` flag
=> RD-2293 Drop `--force` flag in a test

rest-service/manager_rest/rest/rest_utils.py, rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py
Avoid just a `sm.list()` that queries for all csys-consumer-id labels,
because that would also return labels of unrelated deployments, and
we'd end up missing the ones we're actually looking for, because
they could be paginated away.
Also some refactors.
=> RD-3951 update_idds: filter the labels query

rest-service/manager_rest/rest/resources_v3_1/operations.py, tests/integration_tests/tests/agentless_tests/test_runtime_functions.py, workflows/cloudify_system_workflows/deployment_update/workflow.py
This is like #1919 (CY-1710), but for the new dep-update.
For the most part, it copies the code, just to this place.
Instead of the whole dep-update happening on the REST side, it now
happens in the workflow; but some parts must still happen in
restservice, of course.
Anyway, this is a bit heavy-handed, but I'll just move the whole update
thing to a pretty-much-RPC call in POST /operations.
This call is going to do the same thing that the old dep-up did:
examine stored operations, and update them with the new inputs.
=> RD-3907 New dep-update: implement updating operation inputs

rest-service/manager_rest/rest/resources_v3_1/operations.py
In case a new blueprint does not define `operation_name`, return `None`
instead of valid inputs.
=> RD-4093 New dep-update: implement updating operation inputs fixes

resources/rest-service/cloudify/types/types.yaml, rest-service/manager_rest/rest/resources_v2_1/deployment_update.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_deployments.py, tests/integration_tests/conftest.py, tests/integration_tests/resources/dsl/deployment_update/old_workflow/base/old_workflow_base.yaml, tests/integration_tests/resources/dsl/deployment_update/old_workflow/modification/old_workflow_modification.yaml, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_misc.py, tests/integration_tests/tests/agentless_tests/test_deployment_workflows.py
The `csys-new-deployment-update` idea is wrong, because
people do rely on the update workflow's name being actually
"update".
So, let's rename it to `update`, then. This also, hopefully, keeps
back-compat with old blueprints.
=> RD-4096 Name the new dep-up workflow "update"

rest-service/manager_rest/storage/resource_models.py
It was missing from the returned object, but it is part of a workflow.
Missing it caused some workflows be mistakenly marked as changed
in dep-updates.
=> RD-4105 workflows list: also return is_cascading

rest-service/manager_rest/rest/resources_v3_1/nodes.py, tests/integration_tests/resources/dsl/deployment_update/scale_instance/base/scale_instance_base.yaml, tests/integration_tests/resources/dsl/deployment_update/scale_instance/modification/scale_instance_modification.yaml, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py, workflows/cloudify_system_workflows/deployment_update/workflow.py
A Node has all the fields counting its instances, but they aren't
updated right now.
Let's update them.
This will allow further work with implementing scaling in dep-update.
=> RD-2617 Dep-update: update the stored instance amounts

rest-service/manager_rest/rest/resources_v3_1/__init__.py, rest-service/manager_rest/rest/resources_v3_1/nodes.py, rest-service/manager_rest/test/endpoints/test_nodes.py
This is going to be only useful from dep-update. Don't you dare
use it otherwise.
I mean, you can, if you want to break your shit. I'll still try to stop
you, via the `@only_deployment_update`.
=> RD-2617 Implement deleting node-instances

workflows/cloudify_system_workflows/deployment_update/workflow.py
Well, if we remove nodes first, then removing instances would possibly
fail, because their nodes are already gone.
=> RD-4212 dep-up: remove nodes AFTER removing instances

tests/integration_tests/conftest.py
Well, that's a pretty damn weird location for the config.yaml file.
But that's what it currently is, and I want to be able to test out
my nonstandard config.yaml default.
=> inte-tests: add config.yaml to mounted sources

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/storage/storage_manager.py
Otherwise, the "skipped by filter" message prints out the total
count on the manager, rather than just the count of the other items
that the user _is able to see_
=> RD-4259 sm.count: honor tenants filter

tests/integration_tests/framework/docker.py
In cloudify-cosmo/cloudify-manager-install#1323 we made docker managers
don't use external ssl by default. But in these tests, we do expect
the client to be using ssl. So let's enable it.
=> RD-4159 inte-tests: enable external ssl

rest-service/manager_rest/rest/rest_decorators.py
Without this, applying an _include to the query makes _include_hash unusable.
=> Allow retrieving password hash with filter

resources/rest-service/cloudify/migrations/versions/1fbd6bf39e84_4_5_to_4_5_5.py, resources/rest-service/cloudify/migrations/versions/423a1643f365_4_6_to_5_0.py, resources/rest-service/cloudify/migrations/versions/62a8d746d13b_5_0_to_5_0_5.py, resources/rest-service/cloudify/migrations/versions/8e8314b1d848_6_2_to_6_3.py, resources/rest-service/cloudify/migrations/versions/9d261e90b1f3_5_1_1_to_5_2.py, resources/rest-service/cloudify/migrations/versions/a31cb9e704d3_6_0_to_6_1.py, resources/rest-service/cloudify/migrations/versions/a6d00b128933_4_4_to_4_5.py, resources/rest-service/cloudify/migrations/versions/c7652b2a97a4_4_3_to_4_4.py, rest-service/manager_rest/storage/models_base.py
We used to be able to render migrations to just SQL statements,
but recently we've broken it. This brings it back.
It's not used just yet, but eventually I'd like to render the SQL
at build time, and apply it when installing the manager (instead
of applying python-level migrations).
This will be important for being able to split services into separate
containers, because now the DB will be able to create itself, as
opposed to the restservice creating it.
=> RD-4306 Allow migrations to be rendered to SQL

rest-service/manager_rest/storage/filters.py, rest-service/manager_rest/storage/models_base.py, rest-service/manager_rest/storage/storage_manager.py, rest-service/manager_rest/storage/utils.py
Otherwise we can't filter results in new snapshots.
=> Make _include work with non-orm attributes

rest-service/manager_rest/storage/models_base.py
We pass the string `null` here, so no need to jsonify it. Let's treat it like
an actual literal.
=> JSONString: assume literal_bindparam is already jsonified

resources/rest-service/cloudify/migrations/versions/1fbd6bf39e84_4_5_to_4_5_5.py, resources/rest-service/cloudify/migrations/versions/a6d00b128933_4_4_to_4_5.py, resources/rest-service/cloudify/migrations/versions/c7652b2a97a4_4_3_to_4_4.py
Look, the `COMMIT` calls, that I got rid of in #3538, were required
after all!
Turns out, `alter type` must not run in a transaction:
```
sqlalchemy.exc.InternalError: (psycopg2.errors.ActiveSqlTransaction) ALTER TYPE ... ADD cannot run inside a transaction block
```
Unfortunate. But at least, instead of a bare `COMMIT`, we can use this
feature, that alembic added _specifically_ for this case.
It at least suggests that this is the command that must run outside
transactions, as opposed to a seemingly-unrelated bare `COMMIT`.
ref https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.migration.MigrationContext.autocommit_block
=> RD-4306 Migrations: do `alter type` outside transactions

rest-service/manager_rest/rest/resources_v2/plugins.py
Until this change, the list of plugins returned after a caravan upload
was empty, which resulted in rather silly:
```
$ cfy plugins bundle-upload
Starting upload of plugins bundle, this may take few minutes to complete.
Bundle uploaded, 0 Plugins installed.
```
=> RD-4356 List the plugins installed as caravan

rest-service/manager_rest/rest/resources_v3_1/deployments.py, tests/integration_tests/resources/scripts/reset_storage.py
In case the tenant dir is missing (removed by.. something? maybe
removed by the reset-storage!), let's just create it. This also
mirrors the way we do it in create-dep-env, where we do use makedirs.
I'm not 100% happy to change the behaviour, because maybe
reset-storage could've just been more intelligent instead, but...
well, I think it's a good change anyway.
=> deployment create-with-workdir: use makedirs

rest-service/manager_rest/rest/resources_v3_1/operations.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_operations.py
No need to require the name. We can allow to just list all graphs
for the given execution.
=> RD-4328 Allow filtering graphs by just execution-id

cloudify_types/cloudify_types/component/operations.py
the flag is declared in types.yaml, but used to do nothing
=> RD-4265 component dep: honor the external_resource flag

rest-service/manager_rest/rest/resources_v3_1/permissions.py, rest-service/manager_rest/storage/management_models.py, rest-service/manager_rest/test/base_test.py, rest-service/manager_rest/test/endpoints/test_permissions.py
- don't allow creating the same permission twice
- ..but if someone did, do allow deleting them
Like, this would've been better as a `UNIQUE` constraint, but
I'm not gonna add a constraint before new snapshots. Because
that would just explode in upgrade, if someone already had
duplicates.
=> RD-4410 Permissions api: handle duplicated permissions

tests/integration_tests/tests/benchmarks/conftest.py
I'm not sure why would it be missing, pytest_sessionstart is right
there, but apparently it sometimes doesnt run.
=> inte-tests: handle missing stash[benchstorage]

rest-service/manager_rest/rest/resources_v3_1/tokens.py
While stage is switching over, GET on tokens should still work.
With the wrong permission (not copied correctly during the refactor),
it'll only work for admin.
=> Use correct legacy token get permission

api-service/cloudify_api/server.py
Just see the docstring for explanation.
With this, apiservice should be able to run on clusters. Otherwise
it doesn't work at all, when postgres ssl verification is requested.
=> RD-4433 apiservice: hack around asyncpg.connect + sqla + ssl

rest-service/manager_rest/rest/search_utils.py
Because it depends on resource model in use:
* for Blueprints `id` will be compared with constraint's name_pattern
* for Deployments it will be `display_name`
=> Properly map name_pattern constraints to filter rules

rest-service/manager_rest/rest/resources_v3_1/blueprints.py, rest-service/manager_rest/upload_manager.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_removal.py, tests/integration_tests/tests/agentless_tests/test_agent_alive_verification.py, tests/integration_tests/tests/agentless_tests/test_blueprint_upload.py, tests/integration_tests/tests/agentless_tests/test_blueprint_upload_autoupload_plugins.py, tests/integration_tests/tests/agentless_tests/test_secrets.py
Validating a blueprint is async, and only starts an execution in the
background.
Before, the user was expected to list the executions, and find the
one they just started, by workflow id and parameters.
That's a bit silly, so let's just return the execution, so that the
user just receives the id they're supposed to poll.
=> RD-4482 Blueprint validate: return the execution

rest-service/manager_rest/resource_manager.py, tests/integration_tests/resources/dsl/agent_tests/with_agent_scalable.yaml, tests/integration_tests/tests/agent_tests/test_agent_scale.py, tests/integration_tests_plugins/dockercompute/dockercompute/operations.py
We can't just delete all of them and then recreate. That of course
would cascade and delete all related objects (eg: agents table).
Instead, do the usual 3-step program of "delete the ones that are
missing from old, add the ones that are missing from new, update
otherwise".
Also add an inte-test
=> RD-4400 Scale rollback: keep preexisting instances around

rest-service/manager_rest/update_managers_version.py
THe envvars are required now.
FWIW
```
[root@89fdec379c0c /]# /opt/manager/env/bin/python -m manager_rest.update_managers_version 6.3.3
[root@89fdec379c0c /]# cfy mana li
You are trying to run cluster related commands on an all-in-one Cloudify Manager!
HA Cluster manager nodes
+--------------+------------+------------+---------+---------+--------------+----------------+--------------------------+---------------------------+
|   hostname   | private_ip | public_ip  | version | edition | distribution | distro_release |        last_seen         |          networks         |
+--------------+------------+------------+---------+---------+--------------+----------------+--------------------------+---------------------------+
| 89fdec379c0c | 172.17.0.2 | 172.17.0.2 |  6.3.3  | premium | …
```
=> RD-4553 update_managers_version: load configuration

tests/integration_tests/tests/agentless_tests/test_audit_log.py
This is just how many logs we emit right now. Because we also emit
a log on that .list() request as well.
Should we? I don't know. That's for RD-4567 to decide. But for right
now we do it this way, so let's assert this way as well.
=> RD-4567 test_audit_log: expect the currently-correct amount of logs

cloudify_types/cloudify_types/shared_resource/operations.py
This also corrects the behavior when the SharedResource _is_ on-demand: if the resource is inactive -> install it, whether or not there are consumers defined for it. The extra consumers will determine when the resource is _uninstalled_
=> RD-4341 Throw error when trying to connect an inactive SharedResource

workflows/cloudify_system_workflows/blueprint.py
The critical right before raise isn't needed. We show the traceback
nicely.
=> RD-4502 upload_blueprint: remove unnecessary logs

cloudify_types/cloudify_types/utils.py, tests/integration_tests/tests/agentless_tests/shared_resource/test_multi_tenancy.py
Yeah, I don't know what else to do. 
It doesn't seem there's a REST call we can do that'd make sense, to
attach those IDDs - neither of the clients (local or external) is guaranteed
to have access to both tenants. In fact, that might very well be the reason
we use a separate client, because our current user doesn't have access
to the other tenant.
So, I just give up, and treat the "other tenant" client as an external client.
This means no blocking IDDs between them. Too bad.
=> RD-4575 components: consider different tenant an external host

rest-service/manager_rest/storage/management_models.py
Avoid committing explicitly, because that could break the encapsulating
transaction. Instead, sm.put commits only when necessary (ie. when
we're not in a transaction).
Also, `user=self,` rather than `_user_fk`, because providing a fk
means that `t.user` will only be set after committing (when the token
object gets repopulated from the database).
=> RD-4626 create_auth_token: replace db.session with sm.put

tests/integration_tests/tests/agentless_tests/test_audit_log.py
Eh. Anyway, asserting on more specific things, rather than the
very-broad "count all auditlogs". We can't guarantee they're always
going to be this way, and this many, in the face of all the users table
and usage_collector table updates (on each request)
=> inte-tests: rewrite some test_audit_log asserts

mgmtworker/mgmtworker/hooks.py, tests/integration_tests/tests/agentless_tests/test_hooks.py
After executing the hook (which possibly is a no-op), delete the
associated token.
=> RD-4649 Remove hook tokens after running hooks

rest-service/manager_rest/rest/resources_v3_1/searches.py, rest-service/manager_rest/rest/search_utils.py
Inputs or workflow parameters of type `capability_value` should not be
allowed to be in a form of an intrinsic functions.
=> RD-4613 Don't allow intrinsic functions as `capability_value`

rest-service/manager_rest/rest/resources_v3/users.py
Okta users contain an @ which is blocked by the validation.
=> RD-4655 Allow deleting okta users

mgmtworker/mgmtworker/worker.py, tests/integration_tests/tests/agent_tests/test_cancel.py, tests/integration_tests_plugins/cloudmock/cloudmock/tasks.py
Mgmtworker operations weren't killed, just because we used to send
the message to the wrong exchange. Whoops.
=> RD-4688 kill-cancel: kill mgmtworker operations

cloudify_types/cloudify_types/component/polling.py
We want to "return true" if the component execution is cancelled,
and we're cancelled as well. But maybe we haven't been cancelled just
yet, maybe we're still cancelling.
=> Component execution polling: don't break on cancelling

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/test/base_test.py, rest-service/manager_rest/test/endpoints/test_executions.py, rest-service/manager_rest/test/mocks.py, rest-service/manager_rest/utils.py, rest-service/manager_rest/workflow_executor.py
Instead of creating the amqp client when necessary, create it on first
access, and store it. That way, we only pay the high cost of setting up
a TLS connection to rabbitmq once.
=> RD-4627 Use a long-running connection for amqp

rest-service/manager_rest/storage/storage_manager.py, rest-service/manager_rest/storage/utils.py, rest-service/manager_rest/test/endpoints/test_plugins_updates.py
Without this, including both blueprint_id and temp_blueprint_id causes two
outer joins against the same table, which results in sadness and exception.
=> RD-4817 Support include on plugin updates

rest-service/manager_rest/security/user_handler.py
Check if the user isn't none BEFORE attempting to access its
.is_bootstrap_admin attribute, duh.
=> HTTP auth: check user existence before using it

rest-service/manager_rest/storage/storage_manager.py, rest-service/manager_rest/test/endpoints/test_plugins_updates.py
We need to include the includes in the joins, but we need to alias any duplicated
table names.
=> Perform all joins, even with multiple tables

resources/rest-service/cloudify/types/types.yaml
This reverts commit 0d48407415359e011cd5ca50db6db6e84b8e5f51.
This is because we allow importing files which use earlier version of
DSL than the blueprint.  One can use `cloudify_dsl_1_3` types.yaml in a
`cloudify_dsl_1_4` blueprint.
https://github.com/cloudify-cosmo/cloudify-common/pull/1045
=> Revert "RD-4788 Define Cloudify DSL version 1.4 (#3655)"

rest-service/manager_rest/manager_exceptions.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_executions.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py
Fortunately, all the infra for throwing exceptions is already there,
because we already disallow starting executions in some cases
(eg. wrong input types). So all we need to do is to throw
an exception and that's that.
=> RD-4616 Disallow starting unavailable workflows

resources/rest-service/cloudify/types/types.yaml, rest-service/manager_rest/test/endpoints/test_labels.py
Add two properties for cloudify.nodes.Root (and all its children) which
are used to handle resources external to Cloudify.
For the implementation details go over to https://github.com/cloudify-cosmo/cloudify-common/pull/1053
=> RD-429 External resource settings for cloudify.nodes.Root

rest-service/manager_rest/rest/resources_v2/nodes.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_nodes.py
I'll hide these behind a querystring flag. It's not ideal, but we need to
examine all instances, and there might be quite a few of them.
=> RD-4612 Add drifted/unavailable instance counts

rest-service/manager_rest/security/audit.py, rest-service/manager_rest/security/user_handler.py, rest-service/manager_rest/server.py
Otherwise, we never clear current execution id from the audit log,
and then it persists between requests.
=> RD-4995 auditlog: clear variables on each request

rest-service/manager_rest/test/base_test.py
We can't just .first without an ordering. What user would that be?
There's more than one in the db after all (eg. admin and
status_reporter).
I think this is why we've been seeing pretty-rare flakiness on the
tests, where eg. in the config tests, the updater was a different
user than we expected.
=> REST tests: select the expected user/tenant

resources/rest-service/cloudify/migrations/versions/272e61bf5f4a_6_3_to_6_4.py, rest-service/manager_rest/rest/resources_v1/events.py, rest-service/manager_rest/rest/resources_v3/events.py, rest-service/manager_rest/rest/resources_v3_1/operations.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_operations.py
And also to operations!
Now, it'll be possible to know which manager (or which agent) emitted
an event, or was the one handling an operation.
=> RD-4923 Add manager_name/agent_name to logs/events

workflows/cloudify_system_workflows/snapshots/snapshot_restore.py
api_token_key doesnt exist anymore
=> Snap-res: when loading the admin user, skip nonexistent fields

rest-service/manager_rest/test/migrations/test_migration_required.py
1. Drop the `Migrate()` call, it's not necessary, base_test already
does it
2. The `downgrade()` isn't needed after all. My fault, sorry! The
way it works, `migrate()` only creates a migration, doesn't apply
it (that'd be `upgrade()`). Of course, if we leave the migration
file around (which we don't, cf. `unlink()`), then the next run
would've applied it, and THEN we'd need downgrade.
3. Now also printint out the contents of the migration file. This is
very useful (to me), because now I can just run this test if
I want to generate some migrations, I don't need to run a manager.
=> Make the test_migration_required test print out the migration

tests/integration_tests/tests/agentless_tests/test_blueprint_upload_autoupload_plugins.py
Uploading this blueprint can and does timeout a lot.
=> Plugin autoupload inte-tests: use async_upload

rest-service/manager_rest/rest/resources_v3/users.py
Same rationale as RD-4655 where injection possibilities were checked.
=> RD-5024 Allow GET on okta users

resources/rest-service/cloudify/migrations/versions/272e61bf5f4a_6_3_to_6_4.py, rest-service/manager_rest/rest/resources_v1/nodes.py, rest-service/manager_rest/rest/resources_v2/nodes.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_nodes.py, rest-service/manager_rest/test/endpoints/test_storage_manager.py
Store the counts of drifted/unavailable instances on the node, and on
the deployment, as a column. That way, we'll be able to list those
in a performant manner, and also filter on them as well.
I do recommend reading the commits separately!
=> RD-4408 Instance drift/status counts

resources/rest-service/cloudify/types/types.yaml
Thankfully, "old" heal accepts **kwargs, so this types.yaml will be
compatible with the existing implementation.
=> RD-4465 Declare parameters for the next-get heal workflow

tests/integration_tests_plugins/cloudmock/cloudmock/tasks.py
Well the agent is still on 2.7. Whoops.
=> inte-tests: bring back py2.7 compat in the cloudmock plugin

cloudify_types/setup.py
We're missing the new password_secret subpackage... let's just use
find_packages so next time we add one, it's not a problem again
=> cloudify-types: use find_packages in setup.py

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/test/endpoints/test_labels.py
Some labels (currently only csys-consumer-id) are computed by the
manager, so setting them by the user doesn't make sense.
Originally the idea was to throw a 4xx error when the user attempts
to change that label (add or remove), but I think it's better to
just ignore that label.
This is because the update_labels rest call wants the user to provide
the set of the new labels (which it must, to allow deletion). So we'd
be requiring the user to always pass through the computed label
unchanged. That seems silly. Let's allow the user to pass it, or not
pass it, and we'll just keep the label as it needs to be anyway.
=> RD-4429 deployment labels: don't update computed labels

rest-service/manager_rest/test/infrastructure/test_include.py
This behaviour was removed in cloudify-cosmo/cloudify-common#1100
=> Remove obsolete test: test_execution_with_status_field

jenkins/Jenkinsfile, workflows/cloudify_system_workflows/deployment_update/update_instances.py, workflows/cloudify_system_workflows/deployment_update/workflow.py, workflows/cloudify_system_workflows/tests/deployment_update/blueprints/property_input.yaml, workflows/cloudify_system_workflows/tests/deployment_update/blueprints/update_operation.yaml, workflows/cloudify_system_workflows/tests/deployment_update/test_workflow.py, workflows/test-requirements.txt
Now, node-instances, instead of just always being reinstalled, will
be either reinstalled, or have the update interfaces called instead.
=> RD-4466 The new update-or-reinstall flow

workflows/cloudify_system_workflows/deployment_update/update_instances.py
This just makes it actually work. We still need to separate
checking relationships drift, but first, I want to have the tests
be green.
=> RD-4466 simplify _can_be_updated

rest-service/manager_rest/rest/resources_v2_1/deployment_update.py, rest-service/manager_rest/test/endpoints/test_deployment_updates.py
Now we want to be able to run an "empty" update, which will not change
the deployment itself, but it'll run the update interfaces as needed.
The other side of this is cloudify-cosmo/cloudify-cli#1423
=> RD-4466 dep-update: allow empty update

workflows/cloudify_system_workflows/deployment_update/update_instances.py
1. Check drift only on the instances considered for update, no need to
check drift on instances that were removed, or just added
2. Also remove those instances from the must-reinstall list; they can
get there when their containing instance is reinstalled, because
we then also add to must_reinstall its whole contained subgraph
=> RD-4466 dep-update: skip reinstalling removed instances

rest-service/manager_rest/rest/resources_v2_1/deployment_update.py, workflows/cloudify_system_workflows/deployment_update/update_instances.py, workflows/cloudify_system_workflows/deployment_update/workflow.py, workflows/cloudify_system_workflows/tests/deployment_update/blueprints/force_reinstall.yaml, workflows/cloudify_system_workflows/tests/deployment_update/blueprints/minimal_types.yaml, workflows/cloudify_system_workflows/tests/deployment_update/test_workflow.py
This will force all node-instances that were changed, to be
reinstalled, instead of running their update interfaces.
=> RD-4466 dep-up: add force_reinstall

rest-service/manager_rest/storage/resource_models_base.py
Still, leave the default-to-parent around. Unfortunate. Mostly because
of tests. But let's keep it. Eh.
=> RD-5354 When creating resources, default creator to current_user

rest-service/manager_rest/rest/resources_v3_1/plugins.py
Any execution can install a plugin under the hood, and so, this request
should always be allowed, if in an execution. If the user was allowed
to start an execution, they're also allowed to update plugin state,
that's it.
=> RD-5130 Allow updating plugin state in executions

rest-service/manager_rest/storage/storage_manager.py, rest-service/manager_rest/test/endpoints/test_deployment_groups.py
Otherwise we can manage to end up trying to join deployment_groups on deployments.labels.
=> RD-5363 Do joinedloads independently

cloudify_types/cloudify_types/utils.py
Compare only the fields which are defined both in node's properties and
node instance's runtime properties.
=> RD-5336 `check_drift` properties comparison fixup

workflows/cloudify_system_workflows/deployment_update/update_instances.py, workflows/cloudify_system_workflows/tests/deployment_update/blueprints/minimal_types.yaml, workflows/cloudify_system_workflows/tests/deployment_update/blueprints/without_install.yaml, workflows/cloudify_system_workflows/tests/deployment_update/test_workflow.py
Things that were never installed, must not be touched by update at all.
=> RD-5353 dep-up: skip updating uninitialized instances

rest-service/manager_rest/rest/resources_v3_1/operations.py
Instead of setdefault, just set it. Otherwise, if the node was
considered eg. having drift before the installation, it would still
have it. That doesn't make sense. Installation is supposed to leave
the node pristine and new.
This is mostly only visible in reinstalls (especially called by heal).
Without this, we had eg. the component heal operation, run more times
than necessary (it was still retried after a reinstall, until it
got around to running check_status again)
=> RD-5434 node-instance install: always clear drift/status

cloudify_types/cloudify_types/component/operations.py, rest-service/manager_rest/resource_manager.py, tests/integration_tests/tests/agentless_tests/component/test_workflows.py, tests/integration_tests_plugins/cloudmock/cloudmock/tasks.py
Similar to uninstall (and update), heal needs to be considered an ok
workflow to run in components as well: it can do uninstall...
This is to mean: a component is fine to run a heal, if its parent is
currently running a heal. (same logic as for uninstall)
=> RD-5405 Exempt heal from the dependency check

tests/integration_tests/resources/dsl/blueprint_with_plugins_from_catalog.yaml, tests/integration_tests/tests/agentless_tests/test_blueprint_upload_autoupload_plugins.py
Since the lowest version of Openstack plugin supported by RedHat 8 is 2.14.25, let's use it in the test
=> Autoupload test bump openstack plugin version

cloudify_types/cloudify_types/component/__init__.py, cloudify_types/cloudify_types/component/operations.py, cloudify_types/cloudify_types/shared_resource/operations.py, cloudify_types/cloudify_types/utils.py, resources/rest-service/cloudify/types/types.yaml, tests/integration_tests/tests/agentless_tests/component/test_workflows.py
* Modify how Component node's properties are compared
We are comparing only selected node's properties with the same set
of runtime_properties coming from node_instance.
* Define update operation for component node
which is to run a deployment update on a deployment it represents.
* Tests
this is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-manager/pull/3776
=> RD-5404 Define an update operation for Component

tests/integration_tests/tests/agentless_tests/test_plugins.py
It USUALLY finishes in the 2 seconds, but there's nothing that
guarantess it will. Let's poll for up to a minute.
=> inte-tests: corrupted-plugin: replace hardcoded sleep with polls

rest-service/manager_rest/rest/resources_v3_1/status.py, tests/README.md, tests/integration_tests/conftest.py, tests/integration_tests/framework/docker.py, tests/integration_tests/tests/agentless_tests/test_manager_status.py
- you can now run inte-tests with a lightweight managerr
- the status endpoint now considers stage to be optional (RD-5465)
- drop some non-essential parts of the status inte-test
=> inte-tests: use --lightweight to skip some services

cloudify_types/cloudify_types/component/operations.py, cloudify_types/cloudify_types/utils.py, rest-service/manager_rest/deployment_update/handlers.py, rest-service/manager_rest/test/endpoints/test_nodes.py
* The post-heal validation check shouldn't raise exceptions when a drift
is detected (because heal doesn't fix drift, update does).
* Throw a `NonRecoverableError` when deployment is not healthy,
because it's not likely it'll become healthy and we would be just wasting
time waiting for 60 retries of `heal`.
This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-manager/pull/3785
=> RD-5502 Don't bother with drift check after heal

tests/integration_tests/tests/agent_tests/test_list_agents.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_addition.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_removal.py, tests/integration_tests/tests/agentless_tests/test_events.py
Currently we skip 5 inte-tests, and that's always reported by the
slack reporting. Let's stop skipping them - unskipped some, removed some.
=> Stop skipping several inte-tests

rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_operations.py
Otherwise we can't restore operations to the appropriate tasks graph
without doing one list call per tasks graph (rather than per execution).
=> RD-2873 Provide tasks graph ID with operations

rest-service/manager_rest/rest/resources_v3_1/blueprints.py, rest-service/manager_rest/rest/rest_utils.py, rest-service/manager_rest/test/endpoints/test_blueprints.py, rest-service/manager_rest/test/endpoints/test_utils.py, rest-service/manager_rest/test/mocks.py, rest-service/manager_rest/upload_manager.py
This means we can stop messing around with dict encoding in query params.
=> RD-2873 Accept blueprints as multipart/form

packaging/cloudify-agents.spec
For CI to work in cloudify-agent, those packages need to be built at all. But currently the jobs that make them, don't work. To make those jobs work, we need to be able to commit into cloudify-agent, and to do that, CI must pass there.
This is to be reverted after those jobs pass.
=> RD-5692 Temporarily skip windows & altarch agents

resources/rest-service/cloudify/migrations/versions/272e61bf5f4a_6_3_to_6_4.py
This allows migrations to be rendered to .sql without syntax
errors (see #3836 )
=> RD-5930 Fix 6.4 migrations rendering to .sql

packaging/db-schema.sql
This is the DB schema rendered by:
cd /opt/manager/resources/cloudify/migrations/
/opt/manager/env/bin/alembic upgrade --sql 272e61bf5f4a
For now, I'm just exposing this file right here. In the future, we'll probably replace this with something automatically rendering the newest version in CI
=> RD-5930 Render DB schema to .sql

packaging/agents/copy_packages.py
The previous code turned e.g. `manylinux-x86_64-agent_7.0.0-.dev1.tar.gz` into `manylinux-x86.tar.gz`
=> RD-5988 Fix agent package renaming

packaging/cloudify-agents.spec
We only asked for python3 to be installed, not 'python' (2).
=> Use correct python for agent packaging

rest-service/manager_rest/configure_manager.py, rest-service/manager_rest/storage/storage_utils.py, rest-service/manager_rest/test/base_test.py, rest-service/manager_rest/test/endpoints/test_tenants.py, rest-service/manager_rest/test/infrastructure/test_configure_manager.py, rest-service/manager_rest/test/security_utils.py, tests/integration_tests/resources/scripts/reset_storage.py
The original reason for this was that we used to use `create_default_user_tenant_and_roles` in only a few places, and one of them was tests. And that meant we printed out the username&password A LOT of times when running the tests.
Well, there's not that many places that use this function. Turns out we don't need it at all.
Instead:
- configure_manager will be the main place that creates (or updates) the user during installation/setup
- base_test will have its own short way of creating the user. It was mocking out the big thing (rabbitmq) anyway
- reset_storage.py (inte-tests) will just... not remove the admin user. It'll remove other users instead. That'll make the reset script way faster (no rabbitmq interaction needed), but it does mean inte-tests must not change the admin user's …
=> RD-6073 Factor out creating the admin user to configure_manager

rest-service/manager_rest/config.py, rest-service/manager_rest/configure_manager.py, rest-service/manager_rest/test/infrastructure/test_configure_manager.py
`configure_manager.py` tries to insert tenants, while also adding them to rabbitmq - that last part, only if a rabbitmq broker is configured.
Well, so we had better configure rabbitmq brokers FIRST :)
=> configure_manager: load rabbitmqs before inserting tenants

rest-service/manager_rest/rest/resources_v3_1/blueprints.py
... because we also support `blueprint_archive_url`
=> RD-6131 More fixes in blueprint validation

mgmtworker/cloudify_system_workflows/dsl_import_resolver/resolver_with_catalog_support.py
... when fetching objects with `requests.get`.  Otherwise, because of some urllib3 "feature" we're getting slightly misleading error messages: `Read timed out. (read timeout=5)` while the process really times out on connection (not read).
=> RD-6131 Let's use connect timeout = read timeout

tests/integration_tests/resources/dsl/agent_tests/plugin-requires-old-package-blueprint/blueprint.yaml, tests/integration_tests/resources/dsl/agent_tests/plugin-requires-old-package-blueprint/plugins/old_package_source_plugin.yaml, tests/integration_tests/tests/agent_tests/test_existing_vm.py
Mark `test_source_plugin_requires_old_package` as expected to fail (until we find a way to deal with plugins based on Python 3.6)
=> RD-6131 Align DSL versions in test blueprints

resources/rest-service/cloudify/migrations/versions/edd6d829a209_6_4_to_7_0.py, rest-service/manager_rest/storage/management_models.py
Before that patch (some of) the tests failed with the following error messages:
```
12:14:14 [INFO] [Flask Utils] Resetting PostgreSQL DB
14:14:21  Traceback (most recent call last):
14:14:21    File "/opt/manager/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
14:14:21      self.dialect.do_execute(
14:14:21    File "/opt/manager/env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
14:14:21      cursor.execute(statement, parameters)
14:14:21  psycopg2.errors.ForeignKeyViolation: update or delete on table "users" violates foreign key constraint "users_roles_user_id_fkey" on table "users_roles"
14:14:21  DETAIL:  Key (id)=(1) is still referenced from table "users_roles".
```
=> RD-6131 Remove users_roles rows on user/role delete

resources/rest-service/cloudify/migrations/versions/edd6d829a209_6_4_to_7_0.py, rest-service/manager_rest/snapshot_utils.py, rest-service/manager_rest/storage/resource_models.py
Rewrite using a loop rather than writing everything out.
Anyway, the real point of this change, is the `json_empty` check: it's not always a json "'null'", because in case of inserting the models directly via sql (eg. in snapshot-restore), it'll be just a SQL null...
=> snapshot_utils: rewrite migrate_pickle_to_json

tests/integration_tests/resources/dsl/plugin_properties_some_missing.yaml, tests/integration_tests/tests/agentless_tests/test_plugins.py, tests/integration_tests_plugins/with_properties/with_properties/tasks.py
Because not all of the properties must be set.
https://github.com/cloudify-cosmo/cloudify-common/pull/1164
=> RD-6186 Test for plugin properties not set on import

rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_executions.py, tests/integration_tests/resources/dsl/custom_workflow_with_intrinsic_fn.yaml, tests/integration_tests/resources/dsl/scripts/workflows/test_deployment_id_parameters.py, tests/integration_tests/tests/agentless_tests/test_workflow.py
Allow (the default) values for the custom workflow parameters to be declared using intrinsic functions, e.g.
```yaml
tosca_definitions_version: cloudify_dsl_1_5
inputs:
a_blueprint_id:
type: blueprint_id
b_blueprint_id:
type: blueprint_id
workflows:
test_parameters:
mapping: scripts/workflows/test_deployment_id_parameters.py
parameters:
blueprint_id:
type: blueprint_id
default: {get_input: a_blueprint_id}
```
or
```python
client.executions.start(
deployment_id='d1',
workflow_id='test_parameters',
parameters={'blueprint_id': {'get_input': 'b_blueprint_id'}},
)
```
=> RD-6091 Intrinsic functions in workflow parameters

rest-service/manager_rest/constants.py, rest-service/manager_rest/test/endpoints/test_community_contacts.py, rest-service/manager_rest/test/endpoints/test_tenants.py
Turns out, there's only very few (really - one) changes required to make the restservice compatible with Python 3.11 - and it makes the tests faster indeed!
The cloudify-premium thing is to some degree unrelated, but that's how I ended up running the tests, so I'm cleaning that up too.
=> Python 3.11 compat

resources/rest-service/cloudify/types/types.yaml, resources/rest-service/cloudify/types/types_1_3.yaml, resources/rest-service/cloudify/types/types_1_4.yaml, rest-service/manager_rest/test/endpoints/test_deployments.py
- Add filtering parameters to `install`
- Add filtering parameters to `uninstall`
- Declare the `reinstall` workflow
This is done in all types (1_5, 1_4, 1_3), because the parameters don't depend on dsl version (only on the manager version). However 1_3 of course doesn't get 1_4+ dsl features, ie. availability_rules and item_type
=> RD-6284 types.yaml: new workflow parameters

rest-service/manager_rest/manager_exceptions.py, rest-service/manager_rest/rest/endpoint_mapper.py, rest-service/manager_rest/rest/resources_v3_1/__init__.py, rest-service/manager_rest/rest/resources_v3_1/manager.py, rest-service/manager_rest/server.py
When the user hits /monitoring, they'll be presented with a http basic auth prompt in their browser, and then they can access prometheus, if they log in as admin.
This is the other part of cloudify-cosmo/cloudify-manager-install#1444
=> RD-6290 Implement MonitoringAuth

packaging/cloudify-mgmtworker.spec
This venv contains an upgraded version of pip (and also all our cloudify-common libs) as a base for plugin installations
=> RD-6082 mgmtworker rpm: include a python3.6 base venv

resources/rest-service/cloudify/migrations/versions/edd6d829a209_6_4_to_7_0.py, rest-service/manager_rest/storage/management_models.py
When creating a user, default their created_at to now. Note: this also makes created_at be the default_sort_column.
Also, this causes a migration, because now, created_at is not nullable. That means we must default the value to something, and well, the something has to be the migration time.
=> default value for Users.created_at

rest-service/manager_rest/server.py
We don't ever want anything but utf-8 here.
If this is not set, it might default to ascii, and then saving non-ascii strings into the db, is going to cause UnicodeEncodeErrors.
=> RD-6395 REST: set sqlalchemy client_encoding to utf-8

mgmtworker/cloudify_system_workflows/idd.py, rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/rest_utils.py, rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py, tests/integration_tests/tests/agentless_tests/test_inter_deployment_dependencies.py, tests/integration_tests_plugins/cloudmock/cloudmock/tasks.py
In cloudify-cosmo/cloudify-common#1186 we introduce a new format of returned IDDs, that also includes the "context" (also see commit messages).
This makes sure that the manager is able to work with this new format.
=> RD-5953 Use the new dep-plan IDD format

rest-service/manager_rest/rest/rest_utils.py, tests/integration_tests/tests/agentless_tests/test_inter_deployment_dependencies.py
Well the test is pretty complex. But just read the docstring :)
Also, add a pre-check for a more readable error. This will happen when you do `{get_capability: {get_attribute: ..}}` in case the attribute returns a non-string. If we allowed the non-string to go into the db select, we'd get a psycopg2 db error, and that one was completely unreadable.
=> RD-5952 Add a multi-instance IDD test

resources/rest-service/cloudify/migrations/versions/edd6d829a209_6_4_to_7_0.py, rest-service/manager_rest/dsl_functions.py, rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/resources_v2_1/deployment_update.py, rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/rest/rest_utils.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/storage/storage_manager.py, rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py, rest-service/manager_rest/test/endpoints/test_permissions.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py, tests/integration_tests/tests/agentless_tests/test_deployment_workflows.py, tests/integration_tests/tests/test_cases.py
The first commit message explains most of it. It's still ugly/wrong, but it's better than before, and it does fix the specific case...
Please do read commit and commit messages separately, there's quite several things here:
- the cyclic check itself
- some tests
- better error reporting for the dep-update failure (due to dependency errors)
- another IDD fixup (snap-restore-related)
- some cleanups
- also at the end, fixups to tests that are... well, unrelated, but I want to have the tests green already :P
=> RD-5946 Fix the "cyclic dependency" check for dep-update

rest-service/manager_rest/rest/resources_v3_1/searches.py, rest-service/manager_rest/test/endpoints/test_searches.py
This will prevent having both `deployment_id` set and having a `deployment_id` key in `constraints` (which led to problems later in `scaling_group_name_matches()` function).
=> RD-5507 Pop id-s from search constraints

rest-service/manager_rest/dsl_back_compat.py, rest-service/manager_rest/rest/resources_v1/blueprints.py, rest-service/manager_rest/rest/resources_v2/plugins.py, rest-service/manager_rest/rest/resources_v2/snapshots.py, rest-service/manager_rest/rest/resources_v3_1/blueprints.py, rest-service/manager_rest/test/endpoints/test_plugins.py, rest-service/manager_rest/upload_manager.py
In this, I aim to rewrite `upload_manager.py`, in order to:
- I'm waging class warfare - replace all the UploadXXX classes, with just `upload_blueprint`, `upload_plugin`, etc functions
- for each kind of resource uploaded, there's a very clear place that moves the uploaded file to its final destination
- make the "plugin/caravan" part a bit less stupid. It now just decides whether the input is a caravan, wagon, or a zip, just right there in the function
- avoid copying the uploaded file unnecessarily
Before reviewing, I suggest to first examine the [Rewrite UploadedSnapshotsManager](https://github.com/cloudify-cosmo/cloudify-manager/pull/3939/commits/052b08dd9f07f9b1caa2cd16cb5ea632387fb6ca) commit only. It is the smallest one here, and illustrates well the idea of the other changes too. …
=> RD-6476 Rewrite upload_manager.py

rest-service/manager_rest/rest/resources_v3/tenants.py, rest-service/manager_rest/rest/resources_v3/user_groups.py, rest-service/manager_rest/rest/resources_v3/users.py, rest-service/manager_rest/rest/rest_decorators.py
Now, those actions will be possibly allowed by the external auth! External auth handler can now return a "handler" for any of those actions.
If they don't (which is the default, authenticators need to opt-in), then the action is still disallowed.
=> RD-6493 Replace no_external_authenticator with check_external_authenticator

rest-service/manager_rest/rest/resources_v3_1/blueprints.py, rest-service/manager_rest/rest/resources_v3_1/operations.py, rest-service/manager_rest/test/endpoints/test_blueprints.py
Even when skip_execution is passed, we still want to call the upload_blueprint_archive_to_file_server function.
And then, we won't have any messages to send. And that also implies async_upload, as in, there's nothing to wait _for_.
=> Blueprint upload: on skip_execution, still store the files

rest-service/manager_rest/constants.py, rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/test/endpoints/test_executions.py
When starting/cancelling/resuming executions, make sure to look at all node instances that can contain a component deployment id.
This means:
- if there's 0 instances, well, don't throw a 500, but there's no cascade to be done
- if there's 1 instance, this will work the same as before
- if there's >1 instances, pull the deployment id from all of them.
Also, rewrite that whole method using DB-side filtering, rather than python-side.
If we do want this to be ported into 6.4.x, that "DB methods" commit must be skipped in the port, because 6.4.x doesn't have JSON columns.
=> RD-6293 Executions cascade: handle all node-instances

rest-service/manager_rest/rest/resources_v3_1/status.py, rest-service/manager_rest/server.py, rest-service/manager_rest/test/base_test.py, rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py, rest-service/manager_rest/upload_manager/manager.py, rest-service/manager_rest/utils.py, rest-service/manager_rest/workflow_executor.py
Some cleanups, mainly around the tests (commits describe each change):
- drop reset_app
- simplify copy_resources
- drop put_mock_deployments
- drop utils.mkdirs
- deduplicate get_amqp_client
=> Several test cleanups: drop server.reset_app

mgmtworker/cloudify_system_workflows/deployment_update/update_instances.py, mgmtworker/cloudify_system_workflows/deployment_update/workflow.py, mgmtworker/cloudify_system_workflows/tests/deployment_update/blueprints/minimal_types.yaml, mgmtworker/cloudify_system_workflows/tests/deployment_update/test_workflow.py, rest-service/manager_rest/rest/resources_v2_1/deployment_update.py
CLI says:
```
-r, --reinstall-list TEXT      Node instances ids to be reinstalled as part
of deployment update. They will be
reinstalled even if the flag --skip-reinstall
has been supplied
```
But that was somehow missing from the dep-update. Heh. Now it's back, and now it has a test, too.
=> RD-6288 dep-update: bring back `reinstall_list`

mgmtworker/cloudify_system_workflows/deployment_update/workflow.py, mgmtworker/cloudify_system_workflows/tests/deployment_update/blueprints/single_node.yaml, mgmtworker/cloudify_system_workflows/tests/deployment_update/blueprints/single_relationship.yaml, mgmtworker/cloudify_system_workflows/tests/deployment_update/test_workflow.py
Before, update handled instances in the order of:
1. Uninstall removed instances
1. Install added instances
1. Reinstall/update changed instances
That means if we add an instance, and also change an instance that the added one depends on, we need to run relationship operations twice: once after adding the new instance, and then after reinstalling the dependency.
With this change, we reinstall/update BEFORE installing new instances.
Thanks to this, we only need to run relationship operations once.
=> RD-6634 Update: run reinstalls before new installs

cloudify_types/cloudify_types/component/operations.py, cloudify_types/cloudify_types/component/tests/base_test_suite.py, cloudify_types/cloudify_types/component/tests/client_mock.py, cloudify_types/cloudify_types/component/tests/test_blueprint_handling.py, cloudify_types/cloudify_types/component/tests/test_check_drift.py, tests/integration_tests/tests/agentless_tests/component/test_component_auto_inc_suffix.py
I ended up rewriting check_drift almost entirely. Heh. I do suggest viewing commits separately.
But anyway, the point of this change, is so that when auto_inc_suffix is set, don't consider deployment IDs drifted, if the specified deployment id was e.g. "dep", but the actual deployment id is "dep-42" (i.e. with the suffix)
=> RD-6635 Component check_drift: handle auto_inc_suffix

rest-service/manager_rest/persistent_storage.py
make_streaming_response expects to get a path under /resources, ie. the URL part of a file to send. This is because X-Accel-Redirect wants a location in nginx, not a path to a file.
So, from the restservice, we return X-Accel=/resources/foo.txt, nginx goes to the /resources location, and sees the `alias {{ manager.file_server_root }};` directive there (on AIO), and serves file from that.
Also, no need to check for file existence right here. Nginx will just do it.
=> RD-6613 LocalStorageHandler.proxy: use `path` correctly

rest-service/manager_rest/rest/endpoint_mapper.py, rest-service/manager_rest/rest/resources_v3/__init__.py, rest-service/manager_rest/rest/resources_v3/secrets.py, rest-service/manager_rest/rest/resources_v3_1/__init__.py, rest-service/manager_rest/rest/resources_v3_1/blueprints.py, rest-service/manager_rest/rest/resources_v3_1/plugins.py, rest-service/manager_rest/test/endpoints/test_blueprints.py, rest-service/manager_rest/test/endpoints/test_plugins.py, rest-service/manager_rest/test/endpoints/test_secrets.py
set-visibility is available instead; the rest-client already uses set-visibility for its .set_global methods.
Set-global has been mentioned to be deprecated in the rest-docs since like 4.3, and we note that set-global was broken for some time already.
This is relevant for plugins, blueprints, secrets.
Also add a test for set-visibility, for each of the resources mentioned.
=> RD-6639 Remove /set-global endpoints

rest-service/manager_rest/rest/resources_v3_1/manager.py
This is a fix for broken integration tests:
* `integration_tests/tests/agentless_tests/test_deployment_resource.py::DeploymentResourceTest::test_get_and_download_deployment_resource`,
* `integration_tests/tests/agentless_tests/component/test_component_basics.py::ComponentTypeTest::test_component_creation_with_blueprint_in_internal_directory`.
e.g. `GET /resources/blueprints/default_tenant/` will now produce something like
```yaml
{
"files": [
"bp/blueprint.yaml",
"bp/scripts/workflows/workflow.py"
]
}
```
=> RD-6613 List files relative to request path

rest-service/manager_rest/rest/resources_v3_1/manager.py
Do not remove just any `/resources/` in FileServerProxy request path, but only the string that starts it.
=> RD-6613 A bugfix

mgmtworker/cloudify_system_workflows/deployment_environment.py, mgmtworker/cloudify_system_workflows/tests/test_create_deployment.py, rest-service/manager_rest/dsl_functions.py, rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/test/infrastructure/test_dsl_functions.py, tests/integration_tests/tests/agentless_tests/test_environments.py
- When creating a deployment, check requirements, and if there's some missing capabilities, throw an error.
- Change the "missing parent" message to say "environment", not "deployment". More specific, I guess.
New error messages:
```
'create_deployment_environment' workflow execution failed: 404: Environment referenced by `csys-obj-parent` not found: env2
'create_deployment_environment' workflow execution failed: Environment not found, but environment capabilities are required: cap1
'create_deployment_environment' workflow execution failed: Environment env does not have the required capabilities: cap2
'create_deployment_environment' workflow execution failed: Environment env does not have the required capabilities: cap1.key1.0
```
=> RD-6477 create-dep-env: check blueprint requirements

rest-service/manager_rest/rest/resources_v3/secrets.py
We don't really want to store a tuple there :)
Sometimes a trailing comma is a comma too much!
=> Secrets update_provider_options: store a single value

rest-service/manager_rest/manager_exceptions.py, rest-service/manager_rest/rest/resources_v3_1/manager.py
Instead of relying on the browser http basic auth popup, rely on stage's cookies. Much nicer UX.
This goes with cloudify-cosmo/cloudify-manager-install#1458
=> RD-6717 MonitoringAuth: use stage login page

rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_searches.py
For failed deployments, workflows cna be None, and in that case, let's not throw a typerror.
=> RD-6739 Workflow searches: cope with None workflows

rest-service/manager_rest/rest/endpoint_mapper.py, rest-service/manager_rest/rest/resources_v3_1/__init__.py, rest-service/manager_rest/rest/resources_v3_1/manager.py
This functionality is now implemented in `FileServerProxy.get()` method, so we can remove the separate class and the (obsolete) endpoint.
=> Drop FileServerIndex endpoint

cloudify_types/cloudify_types/polling.py, cloudify_types/cloudify_types/utils.py, tests/integration_tests/resources/dsl/component_with_not_existing_blueprint_package.yaml
Component's `upload_blueprint` operation already calls `wait_for_blueprint_to_upload()` so it can very easily use async_upload directly. Almost no changes required!
And deployment creation already uses async.
=> RD-6789 Component: use async blueprint upload

rest-service/manager_rest/rest/resources_v2_1/deployment_update.py
The method is deprecated for a long time and was kept for back-compat only.
=> RD-2798 Drop the DeploymentUpdate PUT method

packaging/rest-service/files/opt/manager/scripts/create_system_filters.py, rest-service/manager_rest/configure_manager.py
With this, system filters are always kept up-to-date, both on the regular c-m-i AIO install, and in the split-services install as well.
Thankfully, the existing function already checks what exists, and only inserts the missing pieces.
Still leave the original script around, because things like upgrade or snap-restore use it.
=> RD-6765 Move creating system filters to configure_manager

service_containers/rabbitmq/config/rabbitmq.config
This ports cloudify-cosmo/cloudify-manager-install#1465 to the split-services deployment
=> RD-6802 rabbitmq: disable consumer_timeout

rest-service/manager_rest/storage/storage_manager.py
This fixes `Select statement '<sqlalchemy.sql.selectable.Select object at ....>' returned no FROM clauses due to auto-correlation` when there's both filtering and sorting by labels
=> RD-6001 Alias sort by labels to avoid autocorrelation with filters

tests/integration_tests/tests/agentless_tests/test_secrets_providers.py
This updates the tests to work with the api change after cloudify-cosmo/cloudify-common#1234
=> inte-tests: use `provider_name` argument in secrets.create

cloudify_types/cloudify_types/utils.py
In here, we can throw more than just a JSONDecodeError: we can also throw a UnicodeDecodeError, and that commonly happens when `res` is a binary blob - which is common when the blueprint is a zip.
=> RD-6881 Component: don't break on zip blueprint_archive

tests/integration_tests/conftest.py
After #4031 this path has changed
=> inte-tests: correct path to migrations mount

mgmtworker/cloudify_system_workflows/snapshots/compute_blueprint_requirements.py, mgmtworker/cloudify_system_workflows/snapshots/snapshot_restore.py, rest-service/manager_rest/snapshot_utils.py, rest-service/manager_rest/test/infrastructure/test_snapshot_utils.py
In snapshot-utils, calculate blueprint requirements, for old blueprints that don't have had their requirements computed yet.
In case anything breaks, maybe the plan isn't quite the format that we expected, just give up and set empty requirements...
=> RD-6589 Snapshot utils: calculate blueprint requirements

mgmtworker/mgmtworker/worker.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/workflow_executor.py
Similar to passing rest_host, we'll also let the worker know what port to connect to us on.
For now, this is 53333, but being able to parametrize it, is the first step to be able to change it!
=> RD-6586 Pass through rest_port when sending workflow messages

mgmtworker/Dockerfile, rest-service/Dockerfile
Those are actually required to install reqs.txt - I think it was missed before due to all the caching I had going on, but now that I actually ran that clean, I noted that these are needed.
Additionally, I'll parametrize PREMIUM in the restservice dockerfile as well, in case I wanted to build a non-premium restservice image (which I currently do want)
=> RD-6766 mgmtworker dockerfile: install the missing libs

rest-service/manager_rest/rest/resources_v3_1/plugins.py
plugins.get_yaml is called from the import resolver in mgmtworker, which needs an all_tenants authorization, similarly to 
https://github.com/cloudify-cosmo/cloudify-manager/blob/master/rest-service/manager_rest/rest/resources_v2/plugins.py#L45
=> Allow all tenants in the auth of plugins.get_yaml

tests/integration_tests/tests/agent_tests/test_plugins.py
After cloudify-cosmo/cloudify-agent#867 the plugins are put in the agent dir, rather than near the env.
Anyway, the env is usually going to be like /opt/cloudify-agent-7.0.0/ and the agent user won't necessarily going to have write privileges for that dir (indeed, it had better not have write rights there).
So the agent must store the plugins in a directory where it does have write rights, like right here.
(in the case of this test, basedir and agent dir just happen to be the same...)
=> RD-6658 inte-tests: update expected plugin path

rest-service/manager_rest/config.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/workflow_executor.py, rest-service/migrations/versions/edd6d829a209_6_4_to_7_0.py
This is the port that the mgmtworker is going to connect to, and then, pass it through to the agents.
Further work will involve making it different per-network
=> RD-6586 Make the default agents/REST port configurable

docker-compose.yml, service_containers/fileserver/Dockerfile
After cloudify-cosmo/cloudify-helm#77 we can just use the base image directly, and this is not required anymore.
=> RD-6766 Drop the fileserver container

tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py, workflows/cloudify_system_workflows/deployment_update/workflow.py
If nodes were scaled, those new instance counts are not reflected in the plan.
Before creating the new deployment plan, update the blueprint plan with the current real instance counts.
=> RD-6908 dep-update: update plan with real instance counts

tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py
Obviously, 1_5 doesn't exist in 6.4.2
=> Inte-tests: use dsl 1_3 for test_update_scaled

api-service/cloudify_api/main.py, api-service/cloudify_api/routers/__init__.py, api-service/cloudify_api/routers/health.py
The endpoint is going to be used solely for monitoring purposes, so it is not burried under /api/v3.1/ path prefix and will be used directly (http://:8081/health)
=> RD-6885 Add /health endpoint in apiservice

packaging/cloudify-rest-service.spec
Instead of relying on RPM scriptlets, let's execute alembic migration in cloudify-manager-install restservice upgrade procedure.
=> RD-7044 Move db migration to cloudify-manager-install

rest-service/manager_rest/configure_manager.py
internal_rest_port can now be passed in from the config, and it will be stored in the config table.
The config setting is already used by the workflow_executor, so all we need to do, is to store it!
=> RD-6586 configure_manager: store internal_rest_port

rest-service/manager_rest/configure_manager.py
The "create-admin-token" part will now be a "subcommand" similar to db-wait and rabbitmq-wait.
The reason is, we want to be able to run create-admin-token, without running the actual "configure" parts.
And that is because normally create-admin-token runs in the mgmtworker initcontainer, while the configure parts run in the restservice one. So that's why we want them to be separate.
=> RD-7052 configure_manager: make create-admin-token separate

mgmtworker/cloudify_system_workflows/search_utils.py, mgmtworker/cloudify_system_workflows/tests/snapshots/test_restore.py, mgmtworker/cloudify_system_workflows/tests/test_create_deployment.py, rest-service/manager_rest/storage/filters.py, rest-service/manager_rest/storage/storage_manager.py, rest-service/manager_rest/storage/utils.py, tests/integration_tests/resources/scripts/prepare_reset_storage.py
When `_include`-ing an attribute that is an `association_proxy`, we didn't join the actual relationship, which led to 1+N queries.
This was shown by a client call like the one in the `only include what we need` commit here:
```python
nis = client.node_instances.list(
node_id=node_ids, _offset=offset, _include=['id', 'node_id'])
```
This is because `get_column` returns... something... or None... and there's nothing to really join on for us, on the storage_manager level.
And so, it seems that `get_column` is the wrong abstraction here. And since it's wrong, and I don't immediately have a better one, I decided to just un-abstract it, and get columns everywhere via `getattr()`, and follow the assoc-proxy only where required.
Maybe someday we'll find the correct one, but for right now, I think …
=> RD-7054 Join rels when `_include` contains assoc_proxy

rest-service/manager_rest/storage/storage_manager.py
Only join assoc proxies when they're proxying to a single attribute. When they're proxying to a whole object, this join cannot work.
Notably, listing user-groups with include=tenants, fails when trying to join this way, because of the usergroup -> usertenantassoc -> tenant relationship structure there...
Yes that means "object" proxies like usergroups->tenants will still emit 1+N. We still need a better solution for that.
=> RD-7069 Don't attempt to join "object" assoc-proxies

rest-service/manager_rest/storage/storage_manager.py, rest-service/manager_rest/test/base_test.py, rest-service/manager_rest/test/endpoints/test_nodes.py
1. deref the fields inside of `summarize` the same way we do elsewhere. Still looking for a better general approach. For right now, it's still this.
2. In get_base_query, follow chained assoc-proxies as well, building the joinpath as we go
3. Add a test for summaries at all...
=> RD-7070 Make summary work with chained assoc-proxies

rest-service/manager_rest/rest/resources_v3_1/deployments.py
When deleting a group with deployments, delete the group first, and only then start the delete-dep-env executions.
Otherwise, there's a race between the executions and the group delete, and for large enough groups, it'll cause concurrent access and ultimately errors.
=> CYBL-2013 Delete dep-group: run workflows after the delete

rest-service/manager_rest/storage/storage_manager.py
same as in .list and in .full_access_list, filters need to be brought to the same representation before actually using them.
This fixes `integration_tests/tests/agent_tests/test_usage_collector.py`
=> sm.count: resolve filters before applying them

rest-service/manager_rest/storage/management_models.py, rest-service/manager_rest/test/endpoints/test_storage_manager.py
Using a property like that returns the first role's name, yes... but filtering on it doesn't work at all.
Before RD-7054, `sm.list(User, filters={'role': 'sys_admin'})` used to just... return all users :) The filter was not applied at all.
After RD-7054, the filter was now applied, but comparing a `class_property_object == 'sys_admin'` just returned False, and we ended up doing essentially a `.filter(False)`, so that `sm.list` call would just return no users.
That made some tests fail, including e.g.
`integration_tests/tests/agentless_tests/multi_tenancy/test_users.py -k test_delete_last_sysadmin_fails` Before, they were passing, but that was a false positive, because the filter was just returning all users (even non-admins).
With this change, user.role is now a bit smarter, and we have …
=> RD-7078 Replace the user.role property with a relationship

execution-scheduler/execution_scheduler/main.py, rest-service/manager_rest/maintenance.py, rest-service/manager_rest/storage/storage_manager.py, rest-service/manager_rest/test/endpoints/test_maintenance_mode.py, rest-service/manager_rest/update_managers_version.py
Turns out we don't really need .full_access_list: it's used in only a few places, and it's easily replaceable by just direct queries. I prefer that, and it'll make the upcoming changes easier, by reducing the storage-manager scope somewhat.
Also, for the maintenance-mode test: I replace the python-side forloop with a query - so I also change the test to not have status=None, but a valid status, because I don't really want to make the query have to cover None.  (and if an execution does have None somehow - we don't really want to block maintenance on it anyway. So that used to be a bug, really)
=> RD-206 Replace sm.full_access_list with direct queries

mgmtworker/cloudify_system_workflows/snapshots/ui_clients.py, mgmtworker/cloudify_system_workflows/tests/snapshots/test_create.py
* dropping MultipartEncoder in blueprints' snapshot restore,
* test fix: blueprint's metadata are a list not a dict,
* small refactor,
* docstrings.
This is `7.0.0-build` cherry-pick of https://github.com/cloudify-cosmo/cloudify-manager/pull/4105
=> RD-4801 Composer snapshots cleanup

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/resources_v2/deployments.py, rest-service/manager_rest/rest/resources_v2/executions.py, rest-service/manager_rest/rest/resources_v3_1/agents.py, rest-service/manager_rest/rest/resources_v3_1/sites.py, rest-service/manager_rest/storage/models_base.py, rest-service/manager_rest/storage/relationships.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/storage/storage_manager.py, rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py, rest-service/manager_rest/test/endpoints/test_storage_manager.py
This ports #4109 to 7.0.0
* Rewrite storage-manager query building
This essentially rewrites `_get_query`. The new implementation is a bit shorter, because it attempts to do all the query modifications inside of _get_query itself, and the other sub-methods only generate clauses to filter/sort on.
So, we resolve fields only once (including assoc-proxies) and then apply filters on those fields.
The main reason for this was to make assoc-proxy resolving actually correct, which I think it now is, with the aliased-outerjoin-getattr dance in `_resolve_included_fields`. But after that was done, I found that pretty much the whole method had to be rewritten to use those resolved fields.
* don't pass `load_relationships`
This argument is now gone, and it's not needed, because now we're …
=> RND-206 storage_manager._get_query - load correct assoc-proxies

rest-service/migrations/versions/edd6d829a209_6_4_to_7_0.py
This setting is unused, because ldap_ca_cert is used instead. (stored in the certs table)
=> RD-5656 Remove deprecated ldap_ca_path

rest-service/manager_rest/storage/resource_models.py, rest-service/migrations/versions/edd6d829a209_6_4_to_7_0.py
This patch is about the usability of data stored in the audit_log DB table.  Adding ref_identifier field enables storing arbitrary fields used to better identify referenced object.
=> RD-7094 Usable audit_log reference to the original object

rest-service/manager_rest/prometheus_client.py, rest-service/migrations/versions/edd6d829a209_6_4_to_7_0.py
Usually, prometheus exposes just `http://<addr>/api`. But our client tries to query `http://<addr>/monitoring/api`.
This is because in the AIO prometheus, we set
`--web.external-address=http://.../monitoring`.
However, in other deployments, like the cloudify-helm deployment, this url part isn't there.
So we can fix it in two ways:
1. either make the cloudify-helm prometheus expose it under that path,
2. or make the /monitoring part be part of the configuration.
This PR implements 2. I think it's more flexible.
=> RND-178 config.prometheus_url: normalize the base url

rest-service/manager_rest/rest/resources_v3_1/searches.py, rest-service/manager_rest/rest/resources_v3_1/workflows.py
This allows using `/api/v3.1/searches/workflows?_common_only=True` to list only the workflows which are common between the filtered deployments
=> RND-213 Add _common_only flag to searches/workflows

tests/integration_tests/tests/agentless_tests/test_download_blueprint.py
instead of os.system, use subprocess.run
In principle, this use of os.system was vulnerable to injection attacks. Of course, the impact is practically zero, because this function was only called from one test. Still, might as well use the correct approach instead.
=> test_download_blueprint: use subprocess.run

execution-scheduler/execution_scheduler/main.py, rest-service/manager_rest/flask_utils.py, rest-service/manager_rest/server.py
Commonly, the scheduler starts before the restservice does, and in the case of the k8s deployment, even before the restservice is finished inserting rabbitmq address & credentials into the db.
Then, the scheduler fails to run anything, because it started and queried the config before the rabbitmq address was populated there.
Restarting the scheduler would mitigate that, but it's of course not practical to restart the scheduler after every change to the config (including the initial "change" - first inserting it).
So, let's use the same method we use in the restservice, and query last-changed times for the configs. To do that, move the function to the utils module, so that it can be imported into the scheduler service (importing server.py has side-effects, unfortunately...)
=> RND-328 execution-scheduler: update config when it changes

mgmtworker/cloudify_system_workflows/snapshots/snapshot_restore.py, mgmtworker/cloudify_system_workflows/tests/snapshots/partial_snapshot_contents/metadata.json, mgmtworker/cloudify_system_workflows/tests/snapshots/snapshot_contents/metadata.json
* Recognise snapshot flavour by file content and not just snapshot version.
* Upgrade snapshot_version to 7.1.0 in tests
---
This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-manager/pull/4148
=> RND-362 Recognise snapshot flavour by file content

tests/integration_tests/conftest.py, tests/integration_tests/tests/agent_tests/test_snapshots.py, tests/integration_tests/tests/agentless_tests/test_snapshot.py, tests/integration_tests/tests/test_cases.py
- allow_agent is now unnecessary, and it of course breaks k8s tests
- fixup reset_storage usage. I dunno why I missed it in #4153. Whoops.
=> inte-tests: cleanup allow_agent & reset_storage

mgmtworker/cloudify_system_workflows/snapshots/postgres.py, rest-service/migrations/versions/edd6d829a209_6_4_to_7_0.py
* disable auditing triggers while restoring DB tables
* do not create triggered function for usage_collector (it was already removed in 6.4)
=> Fix legacy snapshot restore

mgmtworker/cloudify_system_workflows/blueprint.py, mgmtworker/cloudify_system_workflows/dsl_import_resolver/resolver_with_catalog_support.py
Download the whole blueprint rather than just the main file. The blueprint could import other local yaml files, so in principle, we have to download the whole thing...
=> RND-430 resolver: when parsing imported blueprints, download them

tests/integration_tests/resources/scripts/follow_events.py, tests/integration_tests/tests/agentless_tests/test_manager_status.py
Everyone's favourite way of fixing failing tests: removing asserts and increasing timeouts!
I'm removing the is_remote and extra_info asserts, because this is something we're looking at dropping anyway, and well... is_remote gets blurry in the k8s manager. Is the db remote there? It's a separate container, but the same cluster. Doesn't make sense, really.
As for the sleeps, 20 is just experimentally found to be what makes it reliably always 100% pass
=> Fixups for test_manager_status.py

tests/integration_tests/tests/agent_tests/test_plugin_workdir.py
allow_agent is now unnecessary, and was already removed, but this test was forgotten about. It works fine without it, though.
=> inte-tests: remove nonexistent fixture declaration

tests/integration_tests/tests/agent_tests/test_snapshots.py
This is needed because some of the agent executions are slow on Jenkins
=> Fix test snapshots timeout 700

tests/integration_tests/tests/agent_tests/test_snapshots.py
This is needed because some of the agent executions are slow on Jenkins
=> Increase timeout for _deploy_with_agents exec

mgmtworker/cloudify_system_workflows/snapshots/snapshot_restore.py
7.0 will create new snapshots too, so let's just examine if the metadata file looks like a new or old snapshot, instead of just tying that to the version only
=> _is_legacy_snapshot: examine the metadata file

rest-service/manager_rest/storage/management_models.py, rest-service/migrations/versions/edd6d829a209_6_4_to_7_0.py
It's common - and somewhat expected - that multiple manager (restservice) instances will be sharing the public-ip, when they're behind a single LB/ingress/proxy.
In the future, it'd probably be better if there was only a single entry in the db, perhaps? But anyway, while we do have multiple managers that do indeed all respond behind the same public-ip, that needs to be representable in the db...
=> RND-495 Make managers.public_ip not unique

rest-service/manager_rest/rest/resources_v3_1/blueprints.py
When doing .to_dict(flat=False), all querystring arguments are going to be lists. That's not what we want for essentially all of the parameters available, but most notably, it breaks with visibility (e.g. in the getting-started flow).
Instead, don't use flat=False, but keep the default of flat=True, and get the list in the one and only argument that cares about getting a list: the labels.
=> RD-7154 blueprint upload: handle visibility correctly

amqp-postgres/test-requirements.txt, mgmtworker/cloudify_system_workflows/snapshots/audit_listener.py, mgmtworker/cloudify_system_workflows/snapshots/snapshot_create.py, mgmtworker/cloudify_system_workflows/tests/snapshots/mocks.py, mgmtworker/cloudify_system_workflows/tests/snapshots/test_auditlog_listener.py, mgmtworker/cloudify_system_workflows/tests/snapshots/test_create.py
* include (based on audit_log) changes to the entities which were already in “stage zero snapshot”,
* include executions (and execution_groups) based on deployments already existing in the snapshot.
=> RND-364 Mark related entites for append

rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/test/endpoints/test_deployment_groups.py
In order to follow the progress of deleting the deployments, it'll be useful to receive the execution group id
=> RND-623 Delete dep-group with deployments: return excgroup id

mgmtworker/cloudify_system_workflows/deployment_environment.py, rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/resources_v1/deployments.py, rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/storage/resource_models.py, tests/integration_tests/tests/agentless_tests/test_environments.py
Allow a way to delete deployments recursively, i.e. also delete all contained-in services.
- adjust the checks so that those services are exempt when deleting recursively
- add the deletion code itself to delete-dep-env
- add a test
=> RND-623 Recursive delete for deployments

mgmtworker/cloudify_system_workflows/snapshots/snapshot_create.py, mgmtworker/cloudify_system_workflows/tests/snapshots/mocks.py, mgmtworker/cloudify_system_workflows/tests/snapshots/test_create.py
This adds `latest_timestamp` field to the snapshots in pursue of incremental snapshots (sometime in the future).
Also more tests were added in order to improve test coverage of snapshot_create.py code.
=> RND-620 Store `latest_timestamp` for each entity type

rest-service/manager_rest/dsl_functions.py, rest-service/manager_rest/rest/resources_v3/nodes.py, tests/integration_tests/tests/agentless_tests/scale/test_scale_group.py
This passes through the instance id given in cloudify-cosmo/cloudify-common#1284
Also the test shows exactly the scenario we're looking for.
=> RD-7086 evaluate nodes: pass through the instance id hint

mgmtworker/cloudify_system_workflows/snapshots/agents.py
client.node_instances.dump passes a dict here, not a NodeInstance object. Might as well handle that (which would also handle a NodeInstance as well).
=> snapshot-create agents: accept a dict

mgmtworker/cloudify_system_workflows/snapshots/constants.py, mgmtworker/cloudify_system_workflows/snapshots/snapshot_create.py, mgmtworker/cloudify_system_workflows/snapshots/snapshot_restore.py, mgmtworker/cloudify_system_workflows/tests/snapshots/test_auditlog_listener.py, mgmtworker/cloudify_system_workflows/tests/snapshots/test_create.py, mgmtworker/cloudify_system_workflows/tests/snapshots/utils.py, rest-service/manager_rest/test/endpoints/test_agents.py, rest-service/manager_rest/test/endpoints/test_blueprints.py, rest-service/manager_rest/test/endpoints/test_deployments.py, rest-service/manager_rest/test/endpoints/test_events.py, rest-service/manager_rest/test/endpoints/test_execution_schedules.py
The entities which are related to generated snapshot's content are appended to the snapshot.  This implements happy path for "zero-downtime" snapshots.
=> RND-309 Append altered objects to the snapshot

rest-service/manager_rest/resource_manager.py, tests/integration_tests/resources/dsl/idd/destructive_component.yaml, tests/integration_tests/resources/dsl/idd/destructive_component_parent.yaml, tests/integration_tests/resources/dsl/idd/scripts/fail_once.sh, tests/integration_tests/tests/agentless_tests/component/test_workflows.py
We need to not block a component's uninstall when its component creator is in the middle of an install.
This is for correctly supporting `resume` on the creator's install - which needs to first rollback a botched installation of the component so it can then be installed correctly.
=> Cybl 2036 fix component resume 710

amqp-postgres/test-requirements.txt, rest-service/manager_rest/resource_manager.py, tests/integration_tests/resources/dsl/idd/destructive_component.yaml, tests/integration_tests/resources/dsl/idd/destructive_component_parent.yaml, tests/integration_tests/resources/dsl/idd/scripts/fail_once.sh, tests/integration_tests/tests/agentless_tests/component/test_workflows.py
We need to not block a component's uninstall when its component creator is in the middle of an install.
This is for correctly supporting `resume` on the creator's install - which needs to first rollback a botched installation of the component so it can then be installed correctly.
=> CYBL-2036 Don't block uninstall in components mid-resume

tests/integration_tests/framework/utils.py
No need to limit our own tests! Let's keep them fast. Although the rate-limit mostly doesn't affect the tests, it does affect the benchmarks.
=> RND-584 inte-tests: disable nginx rate-limit

tests/integration_tests/tests/agentless_tests/scale/test_scale_group.py
In a custom workflow, call the scale workflow several times, and check that it did indeed run several times.
This tests the changes from cloudify-cosmo/cloudify-common#1292
=> RND-561 inte-test for multiple scale calls from a custom wf

rest-service/manager_rest/test/endpoints/test_deployment_groups.py
Not only check it model-side, but also fetch the group via restclient (requires cloudify-cosmo/cloudify-common#1293 ), and check there.
Note that running requests do commits, so we'll need to remove the entries we've added in each subtest (not a full cleanup like between tests, but only cleanup enough so that we're not affecting the next subtest)
=> RND-652 Test excgroup status via restclient as well

tests/integration_tests/tests/agent_tests/test_snapshots.py
A better (but slower) approach to fixing agent installation problems: instead of arbitrary sleep between installations, let's execute them sequentially.
=> RND-782 Fix integration test: snapshot with agents

rest-service/manager_rest/test/endpoints/test_maintenance_mode.py, rest-service/manager_rest/test/endpoints/test_usage_collector_triggers.py
Replace .put_blueprint with creating the blueprint object by hand, where possible. This is the first part...
=> RND-696 rest tests: drop .put_blueprint in several tests

service_containers/rabbitmq/config/enabled_plugins
Without this plugin, in k8s, rabbitmq tries to use native DNS discovery, which takes a long time, and ends up often timing out on the liveness probes.
With this, `rabbitmq-diagnostics ping` takes 1 second, without - 10.
=> RND-635 rabbitmq image: add the k8s discovery plugin

rest-service/manager_rest/plugins_update/manager.py, rest-service/manager_rest/resource_manager.py
don't hardcode using the filesystem, go through the storage handler, so that the fileserver can be used, if configured
=> RND-817 plugins update: copy blueprint files using storage handler

rest-service/manager_rest/rest/resources_v1/nodes.py, rest-service/manager_rest/test/endpoints/test_nodes.py, tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_misc.py
This ports #4263 to master
* Node instance update: skip the version check for no-op updates
The point of this commit is, if the update is not actually changing anything, i.e. if the old runtime props are the same as new, skip the version check, so that if many operations at the same tame set the same values, they aren't denied.
Or in cases where runtime-props are "changed" to the same value, which can still happen, and often happens in the case of e.g. the terraform plugin.
* add a test
changing runtime props to the same value, even with the version being older, doesn't actually throw a 409
* add an integration-test
This is actually the scenario from RND-1091, and let's check that no conflict error is thrown
=> RND-1091 node-instance update: skip version check for no-ops

rest-service/manager_rest/rest/resources_v1/nodes.py, rest-service/manager_rest/test/endpoints/test_nodes.py
This partially reverts #4264 - the version check is done always, the
refactor stays...
Turns out, skipping the check doesn't quite work, but it breaks
operations when there's many concurrent runs. It seems that it's
important to keep the node-instances up to date on the workers.
I don't know the exact reason, but skipping this change, does make
operations start to overwrite each others' changes, which makes
the scale inte-tests flaky.
=> RND-1091 node-instance update: keep the version check

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/resources_v3_1/deployments.py
In order to make dep-groups extend not be limited to 1000 items, use `get_all_results=True`. However, for that to be workable, we need some optimizations as well.
=> CYBL-2070 Dep-groups extend: fetch all results

rest-service/manager_rest/persistent_storage.py, rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/server.py, rest-service/manager_rest/test/base_test.py, rest-service/requirements.txt, rest-service/setup.py
Just using requests was nice with a local on-prem server which didn't need authentication, but real s3 does. Let's use boto so that we can use signed requests.
Also, use pre-signed requests for proxying.
Also, fix an unrelated bug: turns out, files were never deleted from fileservers! Heh.
=> RND-1188 Use boto3 for s3 compatibility

rest-service/manager_rest/storage/resource_models.py, tests/integration_tests/tests/agentless_tests/test_blueprint_parsing.py
If inputs have no default, but are still marked as `required=false`, then don't require those inputs, but instead make the default be just None.
Note: we want _explicit_ required=false, not just a missing required field.
Also, add an inte-test to check just this behaviour.
=> RND-1205 create-dep-env: don't require inputs with required=false

rest-service/manager_rest/snapshot_utils.py, rest-service/manager_rest/test/infrastructure/test_snapshot_utils.py
Instead of re-setting the parameters using the ORM, emit direct UPDATE queries (via sqlalchemy core).
This way it will be much faster, but the point is, it'll not fire any setter functions.
In this case, the setter we DON'T want to fire, is execution's parameter re-evaluation (`merge_workflow_parameters`), because that'll run the whole intrinsic function unnecessarily, and that can fail.
Instead, we want to migrate data directly, just set whatever was set before.
=> CYBL-2089 migrate_pickle_to_json: use sqlalchemy core, not ORM

api-service/Dockerfile, execution-scheduler/Dockerfile, mgmtworker/Dockerfile, packaging/cloudify-mgmtworker.spec, packaging/cloudify-rest-service.spec, rest-service/Dockerfile
Because we are running more often in a distributed environment, and /run/cloudify is a common place to keep the "work" files.
=> CYBL-2097 Update snapshot_restoring flag file path

mgmtworker/cloudify_system_workflows/snapshots/snapshot_create.py, mgmtworker/cloudify_system_workflows/snapshots/snapshot_restore.py, rest-service/manager_rest/rest/resources_v2/snapshots.py
The fixup is necessary, especially in case of an installation in a distributed environment, where mgmtworker and "fileserver" do not share the same `/opt/cloudify` volume.  Probably the most common example of such installation is deployment performed with the use of [Cloudify Helm chart](https://github.com/cloudify-cosmo/cloudify-helm).
=> CYBL-2097 Snapshot creation/restore fixup

execution-scheduler/Dockerfile, execution-scheduler/docker/entrypoint.sh, rest-service/setup.py
The execution scheduler needs to know the hash salt so that it can generate rest tokens when sending executions. We declare it the same way we do in the restservice.
Note: currently, this is not configurable in the helm chart, but it should be.
=> NE-6694 execution-scheduler: declare HASH_SALT

rest-service/manager_rest/config.py
When loading config, default the last_updated (if not set in the db, which it won't be after a clean installation) to the current time.
Otherwise, we'll always consider last_updated to be None, which means we'll reload the config every time...
Note: the date needs to be a string for this comparison, hence the isoformat.
=> NE-6713 Avoid reloading config unnecessarily

rest-service/manager_rest/persistent_storage.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/endpoints/test_plugins.py
When trying to fetch a yaml file for a specific version, also give out yamls for older versions, if the requested one is not available (not newer).
=> NE-6712 plugin.yaml_file_path: return the best version available

execution-scheduler/execution_scheduler/main.py
- store the schedule.last_execution
- allow the scheduler to actually run executions that use a blueprint
- make `slip` more lenient, ie. run the schedule if _exactly_ 1 minute has passed, not more (i.e. two minutes)
=> NE-6694 Execution-scheduler fixes

rest-service/manager_rest/storage/resource_models.py, tests/integration_tests/tests/agentless_tests/test_blueprint_parsing.py
If inputs have no default, but are still marked as `required=false`, then don't require those inputs, but instead make the default be just None.
Note: we want _explicit_ required=false, not just a missing required field.
Also, add an inte-test to check just this behaviour.
=> RND-1205 create-dep-env: don't require inputs with required=false 

rest-service/manager_rest/rest/resources_v3/secrets.py, rest-service/manager_rest/rest/resources_v3_1/blueprints.py, rest-service/manager_rest/rest/resources_v3_1/plugins.py, rest-service/manager_rest/test/endpoints/test_blueprints.py, rest-service/manager_rest/test/endpoints/test_deployments.py, rest-service/manager_rest/test/endpoints/test_plugins.py, rest-service/manager_rest/test/endpoints/test_secrets.py
sm.update will try to remove items (if they're not part of the current session cache) if they're duplicating tenant resources, and that includes resources that were just set to global, if their id is duplicated in another tenant.
Long story short, setting visibility to global, not only threw a 4xx in case of conflict, but also deleted your resource. Funny.
Do that under a transaction so that doesn't happen. The resource is considered persisted, and nothing actually happens.
This is the same thing done for all 4 kinds of set-visibility (note, deployments already do run under a transaction for that), and a test for each.
=> NE-6889 set-visibility under a transaction

rest-service/manager_rest/rest/resources_v1/executions.py
Do not attempt to compare `datetime.datetime` with `NoneType` (otherwise we got an exception)
=> CYBL-2097 Execution start/restore fixup

rest-service/manager_rest/resource_manager.py
Deployment delete used to be tied to the filesystem, but now, we also need to delete files from s3.
Let's just use the storage handler, to remove deployment directory from wherever it is actually stored.
=> NE-9865 deployment delete: remove files from s3

mgmtworker/cloudify_system_workflows/dsl_import_resolver/resolver_with_catalog_support.py, mgmtworker/cloudify_system_workflows/tests/blueprint_upload/test_blueprint_upload_autoupload_plugins.py
When fetching a plugin from the marketplace, fetch all the plugin versions, not just the one for the current blueprint. Other blueprints might want to use this blueprint afterwards with other dsl versions.
=> NE-9690 plugin resolver: download all plugin yamls

api-service/docker/entrypoint.sh, rest-service/docker/entrypoint.sh
In the entrypoint, stop hardcoding the postgresql host as `postgresql`. Instead, use the envvar
=> NE-7791 dockerfile: parametrize postgres host in entrypoints

rest-service/manager_rest/configure_manager.py
This is going to be more pleasant to work with. In the k8s deployment we'll be able to use a statefulset, with repeatable hostnames, which will make it so we're not leaking tokens.
On aio, the name is going to be always the same then, which is also going to make it so we're not leaking random tokens
=> NE-7791 configure_manager: use hostname for the admin token

rest-service/docker/prepare_secrets.sh
The environment variable shall be provided, e.g. by helm chart (see https://github.com/cloudify-cosmo/cloudify-helm/pull/126)
=> NE-11514 Use ENCRYPTION_KEY to populate encryption_key security key

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/test/endpoints/test_executions.py
This is important notably for snapshot-restore
=> _validate_execution_update: allow no-op update

mgmtworker/cloudify_system_workflows/snapshot.py, mgmtworker/cloudify_system_workflows/snapshots/snapshot_restore.py, mgmtworker/cloudify_system_workflows/snapshots/utils.py
Using k8s means we can only use the new snapshot, never the 'legacy' form of them.
=> snapshot: only allow 'new' snapshots on k8s

api-service/Dockerfile, execution-scheduler/Dockerfile, mgmtworker/Dockerfile, rest-service/Dockerfile
It's cleaner on vuln scans than the base 3.11-slim
=> Python dockerfiles: use -bookworm for the base image

rest-service/manager_rest/cluster_status_utils.py, rest-service/manager_rest/prometheus_client.py
This is a fix-up which improves mapping of Prometheus' metrics onto Cloudify's cluster stats.  It is now better with reporting status in environments with multiple PostgreSQL instances (HA).
=> NE-6423 Cluster status fixup for beefy deployments

execution-scheduler/docker/entrypoint.sh
Don't use a hardcoded "postgresql" here, users will want to use
different db hostnames.
This was missed in #4340
=>  NE-15504 execution scheduler: parametrize postgres host for dbwait

mgmtworker/Dockerfile, mgmtworker/mgmtworker/worker.py
In this, we keep the default max_workers at 10 for workflows, but now we have a separate amount for operations.
Note that the operations count should be larger than the workflows count in order to avoid deadlocks: notably, with Components, it's common that an operation on component runs a workflow on that component's deployment.
So for example, if we have 10 components, we have 10 operations, each runs a workflow, so 10 workflows, and... none of those workflows can run operations of their own, because there's no operation workers left! So we're stuck waiting forever in a deadlock.
If there's more operation workers than workflow workers, then there's going to be a free slot for those workflows' operations.
Additionally, with this change, all of the mgmtworker command line parameters will …
=> NE-16615 mgmtworker: parametrize wf/op workers separately

rest-service/setup.py
Currently 4.0.6 has an issue where it just doesnt work when called programatically. Let's stick to 4.0.5 for now
=> Constrain flask-migrate to under 4.0.6

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/test/endpoints/test_executions.py
Rather than failing, just queue the executions. System workflows take priority here
=> If system execs are running, defer other execs instead of failing

rest-service/manager_rest/rest/resources_v3_1/deployments.py
We used to delete the deployment if it failed creating / sending the create-dep-env message. Although now we do all this in a transaction, so if this fails, there's nothing to delete, the deployment just doesn't exist.
Attempting to delete here just throws an unreadable SQL error
=> Deployments create: don't attempt to delete nonexistent deps

packaging/cloudify-agents.spec, packaging/cloudify-mgmtworker.spec
Python 3.6 is now deprecated and EOL, and we can drop it.
=> Remove Python 3.6 from the RPMs

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/utils.py
* Get amqp client with its default timout if one was not provided This patch passes `connect_timeout` parameter only in case it is set to a value different than `None` (the default).
* Limit the amount of data retrieved when updating execution's status
---
This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-manager/pull/4425
=> Fix POST executions timeout (nginx's 499 response)

rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/storage/relationships.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/storage/storage_manager.py
The main change here is that in _resolve_included_fields, we now use [db.joinedload](https://docs.sqlalchemy.org/en/20/orm/queryguide/relationships.html#sqlalchemy.orm.joinedload) rather than outerjoin. This populates the assoc-proxy correctly, so that there's no longer 1+N queries when listing deployments including the blueprint_id.
And so, other places that do require the attribute to e.g. sort on it, do need an outerjoin, because assocproxies cant be used for sorting.
Also, rewrite the summarize function. This is the only place that does grouping or with_entities, so let's avoid it polluting the _get_query func
=> NE-31415 storage_manager: use joinedload for associationproxy

rest-service/manager_rest/resource_manager.py, rest-service/manager_rest/rest/resources_v1/executions.py, rest-service/manager_rest/rest/resources_v3_1/deployments.py, rest-service/manager_rest/snapshot_utils.py, rest-service/manager_rest/storage/resource_models.py, rest-service/manager_rest/test/base_test.py, rest-service/manager_rest/test/endpoints/test_deployment_groups.py, rest-service/manager_rest/test/endpoints/test_deployments.py, rest-service/manager_rest/test/endpoints/test_executions.py, rest-service/manager_rest/test/endpoints/test_inter_deployment_dependencies.py, rest-service/manager_rest/test/infrastructure/test_snapshot_utils.py
We need to still return create_execution and latest_execution in a response instead of create_execution_id and latest_execution_id
=> NE-31415 Rename executions related fields

rest-service/manager_rest/rest/resources_v3_1/blueprints.py
Fixes blueprint API (blueprint validate and blueprint upload) so the visibility argument is truly optional when parameters are passed as a form parameters. Additional fix for blueprint validate API endpoint to pass further parameter values as strings (not as one element list of strings which later fails validation).
=> Fix blueprint API - in some cases the visibility parameter is optional
